### ISSUE TITLE
Error While Building Per README.macos.md

### ISSUE THREAD

**Issue by Ccook67357** [BelledonneCommunications/linphone-iphone#10]
Hi, 

I am receiving the following error while attempting to compile Linphone via the 'PKG_CONFIG_PATH=/opt/local/lib/pkgconfig ./configure --prefix=/opt/local --with-srtp=/opt/local --with-gsm=/opt/local --enable-zrtp --disable-strict && make' step in 'linphone-iphone/submodules/linphone/README.macos.md'.

videofilters/videoenc.c:268:14: error: use of undeclared identifier
      'PIX_FMT_YUVJ420P'; did you mean 'AV_PIX_FMT_YUVJ420P'?
                c->pix_fmt=PIX_FMT_YUVJ420P;
                           ^~~~~~~~~~~~~~~~
                           AV_PIX_FMT_YUVJ420P

I am trying to rebuild the entire project from source so that I can have the latest changes incorporating iOS 9 support and whatnot.  Any information or assistance would be greatly appreciated.

**Comment by Ccook67357** [comment]
Let me know if there is any more information I can provide.

**Comment by bagage** [comment]
You are on the wrong repository. Please use [Linphone](https://github.com/BelledonneCommunications/linphone) one instead.
