### ISSUE TITLE
Ringtone on early media incoming call

### ISSUE THREAD

**Issue by reste85** [BelledonneCommunications/linphone-iphone#106]
Using linphone_core_set_ring_during_incoming_early_media before the linphone_core_accept_early_media_with_params method doesn't work. Ringtone is muted (and we've seen that the audioRouteChangeListenerCallback method is called different times during incoming call, changing audio route to "ReceiverAndMicrophone"). When we saw this, we've inserted this piece of code just after the linphone_core_accept_early_media_with_params:

let audioSession = AVAudioSession.sharedInstance()
            try? audioSession.setCategory(AVAudioSessionCategoryPlayAndRecord, withOptions: AVAudioSessionCategoryOptions.DefaultToSpeaker)
            try? audioSession.setActive(true)

After that we saw that the audioRouteChangeListenerCallback method is called, changing audio route to "SpeakerAndMicrophone" but still the ringtone is muted. This doesn't happen with no early media incoming calls.

Thank you very much,
Matteo

**Comment by ReisBenjamin** [comment]
Hello,

Please update to latest commit and re-open if not fixed.

Thanks
