### ISSUE TITLE
Edited contact info after hitting cancel not updated properly (iOS)

### ISSUE THREAD

**Issue by juiced** [BelledonneCommunications/linphone-iphone#108]
Hi, when you, for example, remove a phone number when editing a contact and hit cancel to cancel the removal of this phone number, the contact info is not updated properly. At first sight the phone number seems lost. Only after quiting Linphone (remove from tabs/memory too) and then restarting Linphone will show the contact info before the editing and canceling. This is tested with the latest Linphone version from the Appstore.

**Comment by bagage** [comment]
Confirmed, thanks @juiced. I'll try to fix it for next release.

**Comment by ReisBenjamin** [comment]
Hello,

I believe this issue has been fixed.
I'll close it in a few days if no one reports it again.
