### ISSUE TITLE
wizard.php

### ISSUE THREAD

**Issue by ozmortimer** [BelledonneCommunications/linphone-iphone#109]
Hi,
Does anyone have a copy of wizard.php? obviously I can capture what is being send out - but im stuggling with the returns. I've got as far as being prompted for the 4 digit code, but I cannot confirm it as I do not receive the SMS (ive tried UK and USA).
Any guidance would be appreciated.

**Comment by ReisBenjamin** [comment]
NOt used anymore, try with XMLRPC and re-poen if not fixed
