### ISSUE TITLE
iOS 9 compatibility broken

### ISSUE THREAD

**Issue by h3n1v** [BelledonneCommunications/linphone-iphone#11]
Do you think, this project will be updated to compile with ios9 sdk and xcode 7 ?

regards

**Comment by bagage** [comment]
It already does - what's your issue?

**Comment by h3n1v** [comment]
With the latest SDK i got this:

<pre>
Undefined symbols for architecture arm64:
  "_libmsx264_init", referenced from:
      -[LinphoneManager createLinphoneCore] in LinphoneManager.o
ld: symbol(s) not found for architecture arm64
</pre>

**Comment by bagage** [comment]
How did you build the SDK (./prepare.py options)? Can you try again (`./prepare.py -c` and redo your command).

**Comment by h3n1v** [comment]
got a precompiled SDK here 
http://www.linphone.org/snapshots/ios/

because when i exec prepare, i got this.

$) ./prepare.py -c
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule update --init --recursive

**Comment by bagage** [comment]
Which snapshot did you download? If I use the [latest one](http://www.linphone.org/snapshots/ios/liblinphone-iphone-sdk-2.3-117-g1e764a0.zip), it's working fine here? Are you using linphone iphone?
For your prepare error, is the folder `submodules/cmake-builder/options` present?

**Comment by h3n1v** [comment]
oh got it... it was not the linphone iphone sdk :/
sorry.

btw, submodules/cmake-builder/options not present.

**Comment by bagage** [comment]
Then you must run ` git submodule update --init --recursive` as instructed.

**Comment by h3n1v** [comment]
$git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git

**Comment by bagage** [comment]
Sorry but I cannot help you here - please post on [linphone mailing list](https://lists.nongnu.org/mailman/listinfo/linphone-developers) to get help on this.
This has nothing to do with linphone iphone.

Cheers,
