### ISSUE TITLE
Compiling Error xcode 8

### ISSUE THREAD

**Issue by HugoTheBoss** [BelledonneCommunications/linphone-iphone#110]
get a couple of compile errors in xcode 8;
Unknown type names; implicit declarations, arithmetic on pointer,incomplete definition,...
how can i fix it?

**Comment by juiced** [comment]
Hi, did you try to compile the latest SDK first? It will probably solve at least some of your problems..

**Comment by DeepFriedPotato** [comment]
Sorry, I'm new to this. How do you "compile the latest SDK"?

**Comment by juiced** [comment]
Hi, the README.md file will explain everything.

**Comment by TheEngineerz** [comment]
@juiced I have followed each and every step from Readme file but getting couple of errors.

**Comment by juiced** [comment]
OK.

**Comment by TheEngineerz** [comment]
@HugoTheBoss @DeepFriedPotato were you able to compile Linphone on Xcode 8 ?

**Comment by araby123** [comment]
same issue here .. i follow the step in the re README.md and also same error that 

e_t count = bctbx_list_size(linphone_core_get_proxy_config_list(LC));
? bctbx_list_index(linphone_core_get_proxy_config_list(LC),linphone_core_get_default_proxy_config(LC))

showing this message : 

linphone-iphone-master/Classes/SideMenuTableView.m:105:24: Incompatible pointer types passing 'MSList *' (aka 'struct _MSList *') to parameter of type 'bctbx_list_t *' (aka 'struct _bctbx_list *')

any idea what cause  this error am using xcode 8 on MacOS Serria ?

**Comment by ReisBenjamin** [comment]
Please update to latest commit and re-open if not fixed.

Thanks
