### ISSUE TITLE
How to download linphone-iphone(3.13.9) with submodules?

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#111]
I am downloading linphone-iphone (ver 3.13.9)  from project releases section - [link](https://github.com/BelledonneCommunications/linphone-iphone/releases/tag/3.13.9).

But, its submodule folder is with empty folders; no source code files. So, How can I get submodules released in that linphone-iphone (ver 3.13.9) project release?

I want submodules, not liblinphone-sdk. So, I can build it manually.

Thanks in advance.

**Comment by juiced** [comment]
Hi, did you try "git submodule sync && git submodule update --init --recursive" ?
