### ISSUE TITLE
how to create a fake incoming call log?

### ISSUE THREAD

**Issue by bozog61** [BelledonneCommunications/linphone-iphone#112]

**Comment by juiced** [comment]
It's all SQLite, by writing some queries you can create a log.

**Comment by FarhanAhmad** [comment]
I didn't tested it yet, but you can try something like:

// Pseudo code, If you are referring to native db:
// create content values. with number,type(incoming),date etc
// getContentResolver().insert(CallLog.Calls.ContentURI,values,..);

This should add the log in native db.
