### ISSUE TITLE
How to compile coreapi?

### ISSUE THREAD

**Issue by Spyspyspy** [BelledonneCommunications/linphone-iphone#114]
Hello! I have a question. I need to add some functions in chat.c, address.c. So, how can I rebuild this files so Xcode can use them?

**Comment by juiced** [comment]
Just like how you compiled the SDK the first time.

**Comment by Spyspyspy** [comment]
I writed make in a terminal, and nothing happend, app was using not up to date files. I found core api a sub modules, maybe I need to build submodules? How can I do this? And I have no directory build in submodules.

Thank you for the answer.

**Comment by juiced** [comment]
Can you please show your history of commands and in which directories? What happens if you try the same with a fresh clone of linphone?

**Comment by Spyspyspy** [comment]
Sorry, it was my bad. I cloned fresh copy and it worked. Thanks!
