### ISSUE TITLE
iTerm issue

### ISSUE THREAD

**Issue by veer9002** [BelledonneCommunications/linphone-iphone#115]
When I run  ./prepare.py && make in iTerm. I got following error

ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive

when I run -- $ git submodule sync && git submodule update --init --recursive .. it gives me following error
fatal: Not a git repository (or any of the parent directories): .git

**Comment by juiced** [comment]
From which directory do you execute "git submodule sync && git submodule update --init --recursive" ?

**Comment by manish9002** [comment]
/Users/xyz/LatestWorkingProjects/linphoneIOS/linphone-iphone-master
Then I write ./prepare.py to install all dependencies (everything is in iTerm). But it gives me errors which I mentioned earlier.

**Comment by juiced** [comment]
Try again with the original cloned directory name, so "linphone-iphone" instead of "linphone-iphone-master". If you want you can put linphone-iphone in its own directory called "master".

**Comment by manish9002** [comment]
ERROR: Invalid version of nasm detected. Please make sure that you are NOT using Apple's binary here

**Comment by juiced** [comment]
Try to update nasm and install/update all your other packages and dependencies which will appear in error messages with either macports or homebrew, depending on what package manager you are using on OSX.

**Comment by manish9002** [comment]
I installed - brew install imagemagick doxygen cmake nasm intltool yasm automake coreutils wget optipng autoconf pkg-config.. and run ./prepare.py gives me
 CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/xyz/LatestWorkingProjects/linphoneIOS/linphone-iphone-master/linphone-iphone/WORK/ios-x86_64/cmake/CMakeFiles/CMakeTmp

**Comment by veer9002** [comment]
i have solved it

**Comment by NateMay** [comment]
How did you solve it?

**Comment by Sunarker** [comment]
Why not share your solution?

**Comment by veer9002** [comment]
Just update xcode to latest version and install jdk in your mac

**Comment by rajeshm20** [comment]
Thanks...

**Comment by rvgeerligs** [comment]
same problem is back. latest Xcode 15 and JDK 8xx
