### ISSUE TITLE
Build is failing with LinphoneDialPlan 

### ISSUE THREAD

**Issue by n8glenn** [BelledonneCommunications/linphone-iphone#118]
When I try to build the project, I am getting an error saying that LinphoneDialPlan is an unknown type.

**Comment by juiced** [comment]
Did you update and recompiled the linphone SDK?

**Comment by SexiZhang** [comment]
Do I need to update and recompiled the linphone SDK and replace?

**Comment by juiced** [comment]
Depends on what you want to or need to achieve. It is possible to clone the latest linphone, compile the SDK en copy only the linphone-sdk directory to your project.
