### ISSUE TITLE
when i use the sdks on the iphone4 ,there are 69 warning!

### ISSUE THREAD

**Issue by jok886** [BelledonneCommunications/linphone-iphone#12]
![bb5 4h ccutxu zz opw 9](https://cloud.githubusercontent.com/assets/12808147/10573276/3c81f8ce-7681-11e5-807e-d3f15822ddd1.jpg)
![82401462-be8f-41d6-9e65-5544be3c2e3a](https://cloud.githubusercontent.com/assets/12808147/10573298/586b25f6-7681-11e5-9b67-8cf37d6af8a0.png)

hi, i use xcode7 compile the code, run the real machine（iphone4）,69 issues!
but when i use (./prepare.py i386 && make) in simulators iPhone 4s is ok,
so TARGET_IPHONE_SIMULATOR is ok, in TARGET_OS_IPHONE(armv7)  have  some  issues,
how to fix it ?

6 warning

ld: warning: ARM function not 4-byte aligned: __b_evaluation from /Volumes/data/newmemo/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __a_evaluation from /Volumes/data/newmemo/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __end_b_evaluation2 from /Volumes/data/newmemo/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __a_evaluation2 from /Volumes/data/newmemo/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __end_simple_idct_arm from /Volumes/data/newmemo/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in _avcodec_register_all from /Volumes/data/newmemo/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(allcodecs.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie

63 warning
warning: (armv7)  could not find object file symbol for symbol _ff_add_pixels_clamped_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_get_pixels_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_diff_pixels_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs16_x2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs16_y2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_pix_abs8_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_sse16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_pix_norm1_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_pix_sum_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add_neon
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_dc_add_neon
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add16_neon
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add16intra_neon
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct_add8_neon
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct8_add_neon
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct8_dc_add_neon
warning: (armv7)  could not find object file symbol for symbol _ff_h264_idct8_add4_neon
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_x2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_y2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_xy2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_put_no_rnd_pixels8_xy2_arm
warning: (armv7)  could not find object file symbol for symbol _ff_avg_pixels16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_x2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_y2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_x2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_y2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels16_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_x2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_put_pixels8_y2_no_rnd_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_avg_pixels8_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_scalarproduct_int16_neon
warning: (armv7)  could not find object file symbol for symbol _ff_scalarproduct_and_madd_int16_neon
warning: (armv7)  could not find object file symbol for symbol _ff_j_rev_dct_arm
warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_arm
warning: (armv7)  could not find object file symbol for symbol __row_loop
warning: (armv7)  could not find object file symbol for symbol __b_evaluation
warning: (armv7)  could not find object file symbol for symbol __end_b_evaluation
warning: (armv7)  could not find object file symbol for symbol __a_evaluation
warning: (armv7)  could not find object file symbol for symbol __end_a_evaluation
warning: (armv7)  could not find object file symbol for symbol __almost_empty_row
warning: (armv7)  could not find object file symbol for symbol __end_row_loop
warning: (armv7)  could not find object file symbol for symbol __col_loop
warning: (armv7)  could not find object file symbol for symbol __b_evaluation2
warning: (armv7)  could not find object file symbol for symbol __end_b_evaluation2
warning: (armv7)  could not find object file symbol for symbol __a_evaluation2
warning: (armv7)  could not find object file symbol for symbol __end_a_evaluation2
warning: (armv7)  could not find object file symbol for symbol __end_col_loop
warning: (armv7)  could not find object file symbol for symbol __end_simple_idct_arm
warning: (armv7)  could not find object file symbol for symbol __end_bef_a_evaluation
warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_add_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_put_armv6
warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_put_neon
warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_add_neon
warning: (armv7)  could not find object file symbol for symbol _ff_simple_idct_neon

**Comment by bagage** [comment]
Most of them have been fixed, however there are still some missing symbols for FFMPEG neon files.
