### ISSUE TITLE
cMake Error

### ISSUE THREAD

**Issue by husseinalzand** [BelledonneCommunications/linphone-iphone#123]
hello
iam trying to compile linphone on xcode 8 but have error ./prepare.py like this

 

> CMake Error at configs/config-ios.cmake:60 (message):
>   You need at least CMake version 3.3.20150815 but you are currently using
>   3.3.2.  There is no Cmake release available for it yet, so you must either
>   compile it manually or revert to XCode6 temporary.

how can i solve this problem ?

**Comment by juiced** [comment]
The error says it expects a newer/updated version of CMake, try to update it on your system to the latest version.

**Comment by husseinalzand** [comment]
Thats worked for me thanks
