### ISSUE TITLE
Recommend way to HIDE any field from settings.?

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#127]
For example if I want to hide the proxy and domain field from settings screen what is the recommended way so app functionality is not broken ?

**Comment by JFSene** [comment]
The fields I erase from my custom were all in the Bundle file under my native language.

**Comment by TheEngineerz** [comment]
Sorry can't understand?

**Comment by JFSene** [comment]
@TheEngineerz There is a file called InAppSettings.bundle, you can find it under the Settings folder.
Inside you can find those fields you want to hide.

**Comment by TheEngineerz** [comment]
Thanks @JFSene I have done the same but my concern was just to Hide not Erase..So if i want to show in future how i would be able to do so

**Comment by JFSene** [comment]
@TheEngineerz You can keep a backup file for that, or you can just comment out those lines, and if you ever feel the need to show em again, just uncomment.
