### ISSUE TITLE
Building SDK in Xcode 7.0.1

### ISSUE THREAD

**Issue by steveTW** [BelledonneCommunications/linphone-iphone#13]
Hello all:

I'm trying to use following comand to build SDK:

*./prepare.py -DENABLE_X264=ON all && make*

but it gives me CMake Error:

cmake /Users/Apple/linphone-iphone/submodules/cmake-builder -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/Users/Apple/linphone-iphone/liblinphone-sdk/arm64-apple-darwin.ios -DCMAKE_INSTALL_PREFIX=/Users/Apple/linphone-iphone/liblinphone-sdk/arm64-apple-darwin.ios -DLINPHONE_BUILDER_WORK_DIR=/Users/Apple/linphone-iphone/WORK/ios-arm64 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-ios-arm64.cmake -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-ios-arm64.cmake -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/Users/Apple/linphone-iphone/submodules -DENABLE_X264=ON -G "Unix Makefiles" -DLINPHONE_IOS_DEPLOYMENT_TARGET=6.0 "-DLINPHONE_BUILDER_DUMMY_LIBRARIES=libopenh264 libcunit libavcodec libspeex libpolarssl libswresample libopencore-amrnb libtunnel libopus libbellesip libopencore-amrwb libsrtp libvo-amrwbenc libbzrtp libgsm libmsilbc libmsbcg729 libswscale libvpx libmsamr libbcg729 libspeexdsp liblinphone libx264 libortp libmsopenh264 libmediastreamer_base liblinphonetester libavutil libmssilk libilbcrfc3951 libmediastreamer_voip libmswebrtc libantlr3c libmsx264"
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk
-- Using sdk version: 9.0
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk
-- Using sdk version: 9.0
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Using toolchain file '/Users/Apple/linphone-iphone/submodules/cmake-builder/toolchains/toolchain-ios-arm64.cmake'
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk
-- Using sdk version: 9.0
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk
-- Using sdk version: 9.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Apple/linphone-iphone/WORK/ios-arm64/cmake/Autotools
-- Using configuration file '/Users/Apple/linphone-iphone/submodules/cmake-builder/configs/config-ios-arm64.cmake'
CMake Error at configs/config-ios.cmake:71 (message):
  You need at least CMake version 3.3.20150815 but you are currently using
  3.2.3.  There is no Cmake release available for it yet, so you must either
  compile it manually or revert to XCode6 temporary.
Call Stack (most recent call first):
  configs/config-ios-arm64.cmake:24 (include)
  CMakeLists.txt:70 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/Apple/linphone-iphone/WORK/ios-arm64/cmake/CMakeFiles/CMakeOutput.log".

How do I solve this issue?

**Comment by bagage** [comment]
It's written:

> You need at least CMake version 3.3.20150815 but you are currently using
3.2.3. There is no Cmake release available for it yet, so you must either
compile it manually or revert to XCode6 temporary.

**Comment by LiangyongFShen** [comment]
How did you build that success with the error ： 
You need at least CMake version 3.3.20150815 but you are currently using
3.2.3. There is no Cmake release available for it yet, so you must either
compile it manually or revert to XCode6 temporary.

Can you tell me how to make it work , thanks?
