### ISSUE TITLE
App Crashes on device after launching?

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#130]
![screen shot 2016-11-08 at 1 19 10 am](https://cloud.githubusercontent.com/assets/5149947/20074360/ba9563e0-a551-11e6-9017-82fc936966b3.png)

**Comment by kmiloaguilar** [comment]
Did you build liblinphone in your mac or you let the project download the latest?

**Comment by TheEngineerz** [comment]
@kmiloaguilar  I cloned the repository and build the SDK successfully. I was running ok on simulator but on devices it is crashing. And this is very strange that 7 out of 10 times it crashes and otherwise it works fine.

**Comment by JFSene** [comment]
@TheEngineerz Are you testing it on ur Device or Simulator? Because that happens when you have too many contacts. Might be a good idea to filter contacts while testing.

**Comment by TheEngineerz** [comment]
@JFSene so you mean it will only happens when app is in debug mode. I think it will create issues when it will go live. because we cannot restrict users to have small contact list

**Comment by JFSene** [comment]
@TheEngineerz I mean you can filter those contacts so they will only be added if you need them, and not load eveything when didFinishLoading, or you can write a func that only loads SIP contacts.
