### ISSUE TITLE
background does not work if expire < 600

### ISSUE THREAD

**Issue by vidrik** [BelledonneCommunications/linphone-iphone#131]
hello,

testing the latest linphone on ios 10.1.1, my extension would not re-register with 3600 seconds of expire time

I then tried to put 60, still nothing

searching on the net, I found that an iOS app has a minimum keep alive time of 600 seconds to wake up from background

so I put in 600  et voila, it works !!

so I guess that it would be a good idea to make the expire minimum number to be 600

it is still unclear to me why 3600 would not work

thanks

eric

**Comment by JFSene** [comment]
@vidrik Can you please upload make a pull request so those changes are added to the main project?
