### ISSUE TITLE
Compiling Error with ./prepare.py -DENABLE_NON_FREE_CODECS=ON   -DENABLE_X264=ON & make

### ISSUE THREAD

**Issue by kangzhonghua** [BelledonneCommunications/linphone-iphone#134]
MAC 10.11.6 + XCODE 8.1

 gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$./prepare.py -DENABLE_NON_FREE_CODECS=ON   -DENABLE_X264=ON
$make
.........................
/bin/sh: CMAKE_STRIP-NOTFOUND: command not found
ld: library not found for -lcrt1.3.1.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [x264] Error 1
make[3]: *** [/Users/ABC/Desktop/linphone/linphone-iphone/WORK/ios-armv7/Stamp/EP_x264/EP_x264-build] Error 2
make[2]: *** [CMakeFiles/EP_x264.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

**Comment by JFSene** [comment]
@kangzhonghua did you download or clone the project directly from their github page or did use the command line?

**Comment by kangzhonghua** [comment]
I have clone by command line.

**Comment by kangzhonghua** [comment]
Compile other codes all success except x264.

**Comment by JFSene** [comment]
Update the download repo and try again, or with a new download. also try to build with other options to see if only x264 is broken

**Comment by kangzhonghua** [comment]
Hi JFSene:
     I download repo again via "git clone git://git.linphone.org/linphone-iphone.git --recursive" 
     ./prepare.py -DENABLE_NON_FREE_CODECS=ON   -DENABLE_OPENH264=ON -DENABLE_G729B_CNG=ON -DENABLE_G729=ON -DENABLE_UNIT_TESTS=ON -DENABLE_FFMPEG=ON -DENABLE_X264=ON -DENABLE_GPL_THIRD_PARTIES=ON 
     and make but same error:

/bin/sh: CMAKE_STRIP-NOTFOUND: command not found
clang: warning: argument unused during compilation: '-D PREFIX'
clang: warning: argument unused during compilation: '-D PIC'
clang: warning: argument unused during compilation: '-D STACK_ALIGNMENT=16'
clang: warning: argument unused during compilation: '-D PIC'
clang: warning: argument unused during compilation: '-D HIGH_BIT_DEPTH=0'
clang: warning: argument unused during compilation: '-D BIT_DEPTH=8'
/bin/sh: CMAKE_STRIP-NOTFOUND: command not found
ld: library not found for -lcrt1.3.1.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [x264] Error 1
make[3]: *** [/Users/kang/Desktop/linphone/linphone-iphone/WORK/ios-armv7/Stamp/EP_x264/EP_x264-build] Error 2
make[2]: *** [CMakeFiles/EP_x264.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

**Comment by ReisBenjamin** [comment]
Try latest commit and re-open if not fixed.

Regards
