### ISSUE TITLE
Mismatch in IPs in Via/Contact and RTP when via VPN

### ISSUE THREAD

**Issue by anatoli26** [BelledonneCommunications/linphone-iphone#135]
Hi!

It looks like there's a VPN connectivity issue on iPhone. If I establish an OpenVPN connection to an Asterisk server in the OpenVPN intercept-all-traffic mode (i.e. redirect-gateway directive), then everything works well. Now, if the OpenVPN connection only adds a route to the Asterisk server without intercepting the rest of the traffic, Linphone connects well to the server (sends a correct IP in the `Via` and `Contact` headers), but then, when trying to call, it sends in the `INVITE -> RTP` block its WiFi IP, not the IP of the VPN connection. 

Suppose the phone's WiFi IP is 192.168.0.10, the VPN IP in both modes is 10.0.0.11 and the Asterisk server IP is 10.0.10.1. In both cases Linphone connects to the Asterisk without any problem, but in the intercept-all-traffic mode it sends in the `INVITE -> RTP` packet its correct (VPN) IP, i.e. 10.0.0.11, but when in the single-route mode, it sends its WiFi IP in the `INVITE -> RTP`, i.e. 192.168.0.10: 

```
INVITE sip:100@10.0.10.1 SIP/2.0 
Via: SIP/2.0/TCP 10.0.0.11:54337;branch=z9hG4bK.Jv2auTGwr;rport 
... 
Contact: <sip:777@10.0.0.11:54337;transport=tcp>;+sip.instance="<urn:uuid:xxx>" 
User-Agent: Linphone_iPhone.4S_iOS7.1.2/3.13.9 (belle-sip/1.4.2) 

... 
o=777 2097 2332 IN IP4 192.168.0.10
... 
c=IN IP4 192.168.0.10 
```

What could be the problem? In both cases the IPs of the phone are the same (e.g. when inspecting with System Status Lite/Pro), i.e. there's an IP for a 3g/4g connection, an IP for a WiFi connection and an IP for the VPN connection. The OpenVPN app also reports the same IP (for ifconfig command) in both cases, but Linphone somehow uses different IPs depending on whether it's in the intercept-all-traffic mode (it choses the VPN IP) or in the single-route mode (it choses the WiFi IP). 

It would be understandable to have some issue with IP detection due to the way the gateway/default route is set up, but in any case, the RTP IP should be the same as the Via/Contact IP, shouldn't it?

**Comment by TheEngineerz** [comment]
Yes you are right I faced the same issue and when I disable the video and ICE from settings  then everything was ok. But obviously it's not the solution .

**Comment by anatoli26** [comment]
Actually, I have everything ICE related turned off, as well as video option, just plain voice. Still, having this problem.

**Comment by smorlat** [comment]
Hi,

Have you tried with latest release linphone-iphone 3.15 ? 
This version has a new algorithm for selecting the IP address that goes into the SDP. Instead of choosing the IP address of the interface that has the default route, it chooses the interface that "connects" to the IP address of the SIP server.
This works as long as the client is registered to the SIP server.
Best regards,

Simon

**Comment by anatoli26** [comment]
Thanks Simon, the latest version fixes the problem. Great!

**Comment by BavarvaSajan** [comment]
i can not find linphone-iphone 3.15 in linephone git hub repo so can you plz give correct patch file name and git hub repo branch? 
thanks

**Comment by RajanVindaloo** [comment]
I would like to know in which file the IP address is being set. Please let me know.

**Comment by gonzalezroda** [comment]
I don't know if I'm doing right posting this, but I was facing same error @anatoli26  describes on first post but with Linphone on desktop. Issues between Linphone and Asterisk over OpenVPN, but in my case what finally worked was changing the audio codecs settings. I only have PCMU codec enabled, and that's it. I'm using routed traffic over OpenVPN and Linphone without troubles.
