### ISSUE TITLE
Cannot receive call with Push Notifications turned on

### ISSUE THREAD

**Issue by afriedmanGlacier** [BelledonneCommunications/linphone-iphone#137]
Using the latest released version, 3.15, we are trying to take advantage of the PushKit and VoIP notifications. I assume that means I need to turn on the Push Notifications switch under settings, but when I set that switch to on, Linphone will not receive calls even if the app is currently in the foreground and active. Are there any other settings that need to be changed? 

We are using FreePBX as a server and making VoIP calls over OpenVPN. Its possible this is an issue with lack of push support in FreePBX (we haven't figured out if there is something that needs to be done on the server side), but it seems odd that someone trying to call into Linphone would get a service unavailable message even in Linphone is active and in the foreground.

**Comment by afriedmanGlacier** [comment]
Just realized this is probably a repeat or at least related to #121

**Comment by JFSene** [comment]
@afriedmanGlacier Please close this Issue, since its related to another one thats already open!

**Comment by afriedmanGlacier** [comment]
@JFSene I'm not 100% sure that the questions are the same, but I'll go ahead and close this for now.
