### ISSUE TITLE
Things to consider when launching your app

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#138]
I cloned the linphone-iphone and Build the SDK with default mode. 
I changed the Name of app.
I changed the splash screens and logo with my brand and changed the about page.
I hide some options from settings
I hardcoded my server IP and just login fields are enabled in Sip Account

Now my question is . Can i put it on App Store?

**Comment by JFSene** [comment]
@TheEngineerz 
You cant sell the app, but you can sell support, customization jobs.
Oh and you have to show the the License in the About page.
If a client asks you for the source code, you HAVE to give it to him.

For further information consult the google GNU v2 license

**Comment by TheEngineerz** [comment]
Thank you @JFSene for the reply. ok please correct me if i am wrong . I just have to show the license in about page and change any thing inside app and could upload on app store for free of cost ?

**Comment by JFSene** [comment]
Yep, you got it!
You also have to check the plubins you used, some of them are not free, you have to buy the license, so better check before building the fina project
