### ISSUE TITLE
Issue while creating a new Message.

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#14]
Following code in class ChatRoomViewController.m

LinphoneChatMessage *msg = linphone_chat_room_create_message(chatRoom, [message UTF8String]);

//Below line added by me    
    BOOL outgoing = linphone_chat_message_is_outgoing(msg);
Bool value comes to be FALSE.

It should be true instead, as the message has been created.

Therefore while sending a message from Linphone app, there is a certain jump of cell for message sent.

**Comment by bagage** [comment]
No, it's not outgoing - you simply created a message. See liblinphone API documentation for reference (consider using linphone_chat_room_create_message_2` for instance)
.

**Comment by uditbatra** [comment]
How can i solve this issue. Please check the video.

**Comment by uditbatra** [comment]
![screen shot 2015-10-16 at 2 02 49 pm](https://cloud.githubusercontent.com/assets/3806195/10537326/a88e6644-740e-11e5-8e2a-aaa6a5bf7f88.png)
![screen shot 2015-10-16 at 2 03 00 pm](https://cloud.githubusercontent.com/assets/3806195/10537327/aa255f44-740e-11e5-8c31-7e3af8f66e25.png)

When i type a message there is a transition of message bubble. How can i solve that.

**Comment by bagage** [comment]
See linphone-iphone code for reference, it is pretty straightforward.

**Comment by uditbatra** [comment]
Yes,  i have run the linphone-iphone code. The screen are from the linphone-iphone build.

**Comment by bagage** [comment]
Are you up-to-date with master? Did you recompile liblinphone SDK? This issue should have been fixed a few days back.

**Comment by uditbatra** [comment]
I have compiled this code 15 days back. 

Do i have to recompile the sdk again, or can i get this file from any of the link.
Or there are any simple steps to recompile .

Thanks for your help.

**Comment by bagage** [comment]
Please update linphone-iphone, I updated it to avoid the glitch in application as well. Hence you should not need to recompile the SDK.

**Comment by uditbatra** [comment]
OK Thanks.
