### ISSUE TITLE
Invalid compliance code ? Doesn't match with info.plist

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#140]
when uploading to iTunes store. I am getting issue The compliance code in info.plist doesn't match .Do i have to export my own ? or if there is any document provided already? any quick fix for this solution ?

**Comment by ReisBenjamin** [comment]
take a look a this and re-open if it doesn't work : 
https://stackoverflow.com/questions/35739361/itsappusesnonexemptencryption-export-compliance-while-internal-testing

Thanks
