### ISSUE TITLE
iOS TLS crash app

### ISSUE THREAD

**Issue by openmsk** [BelledonneCommunications/linphone-iphone#143]
iOS application crash when the TLS enable 
debug in attache

[lnphone-debug.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/616518/lnphone-debug.txt)

and to debug are specified DNS server, which I do not!
```

016-11-28 13:04:27:497 MESSAGE Resolver is using DNS server(s):
2016-11-28 13:04:27:497 MESSAGE 	10.77.48.33
2016-11-28 13:04:27:497 MESSAGE 	10.77.48.49
```

**Comment by carras** [comment]
Every time I add an account with TLS configured the app start crashing.

**Comment by ReisBenjamin** [comment]
Please try latest commit and re-open if not fixed.

Thanks
