### ISSUE TITLE
Incoming calls automatically declined

### ISSUE THREAD

**Issue by Flipper1** [BelledonneCommunications/linphone-iphone#144]
New build, new SDK, my application, before was working, now when I receive call, screen goes to decline or answer view and one second later, it is just declined and it goes to missing calls view? Can you check this behaviour? It actually goes to voicemail automatically

EDIT:  I have tried turning off random ports, nothing, on one phone it goes directly to voicemail, second one IncomingCallView juest appear for a second before call is aborted automatically. It says in both cases, when calling from both phones, that User is busy. Both phones are latest iOS 10 versions

EDIT2: Server supports TCP and UDP. When TCP is enabled, I cannot call or receive calls at all, it does nothing. When I switch my phone to UDP, every time it says that User is busy, my screen goes to IncomingCallView for one second before connection is broken and it says "User is busy". On Android, it is working normally. And yes, I am not talking about background modes, we have implemented VOIP push services for iOS 10.

**Comment by ReisBenjamin** [comment]
Try latest build and reopen if not fixed.

Thanks

**Comment by kirti301290** [comment]
@Flipper1  how to solved this issue
facing same issue now
