### ISSUE TITLE
After I invoke linphone_core_pause_call, the linphone_core_get_current_call(theLinphoneCore) will return nil.

### ISSUE THREAD

**Issue by jiangzhibin** [BelledonneCommunications/linphone-iphone#145]
I want linphone_core_resume_call a call which been paused by linphone_core_pause_call.
But I found that linphone_core_get_current_call return nil after invoke linphone_core_pause_call.
Why pause a call would set current call to nil?
What should I do for resuming a call?
It's appreciated for your reply!

**Comment by ReisBenjamin** [comment]
Try this :
LinphoneCall *currentCall = linphone_core_get_current_call(LC);
if (currentCall == nil && linphone_core_get_calls_nb(LC) == 1) {
	currentCall = (LinphoneCall *)linphone_core_get_calls(LC)->data;
}
return currentCall;

**Comment by jiangzhibin** [comment]
@ReisBenjamin  thanks! it works.
