### ISSUE TITLE
Error building new SDK

### ISSUE THREAD

**Issue by Flipper1** [BelledonneCommunications/linphone-iphone#146]
I am trying to build new SDK, I have cloned today's repo and submodules and I am getting this error: 
[ 87%] Built target mediastreamer_voip-static
[ 88%] Linking CXX executable tones.app/tones
Undefined symbols for architecture x86_64:
  "_ms_v4m_cam_desc", referenced from:
      _ms_factory_init_voip in libmediastreamer_voip.a(msvoip.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [tools/tones.app/tones] Error 1
make[5]: *** [tools/CMakeFiles/tones.dir/all] Error 2
make[4]: *** [all] Error 2

**Comment by ReisBenjamin** [comment]
Hello !

The issue should be fixed with commit : 4683bae7b61ea4a47ba8c9c196387b7ea3ee85e7
Regards

**Comment by Flipper1** [comment]
Hello, I've cloned new repo, updated all submodules but it's not working, now this is the error: 

submodules/bzrtp" does not appear to contain CMakeLists.txt.
ios-x86_64/Stamp/EP_bzrtp/EP_bzrtp-configure] Error 1
make[2]: *** [CMakeFiles/EP_bzrtp.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [x86_64-build] Error 2

**Comment by Flipper1** [comment]
Everything is fine now, you can close issue 👍
