### ISSUE TITLE
Video and Conference call icons are disabled

### ISSUE THREAD

**Issue by saurabhs70** [BelledonneCommunications/linphone-iphone#149]
When i make a audio call, then the video and conference icons are disabled for the recipient (they are enabled for the caller only).  I downloaded 9b6194c.
Also i noticed that this works perfect when i download linphone app from appstore.

refer attachment 
![voice-call](https://cloud.githubusercontent.com/assets/17975720/20920090/a57b86cc-bbc4-11e6-9d1b-580f5985f5e9.jpg)

Please advise

**Comment by ReisBenjamin** [comment]
Hello !

Try to rebase on a previous commit, there is an issue in videoToolbox with this commit.
Please let me know if this solve your issue. We're still fixing the problem.

**Comment by saurabhs70** [comment]
Hi @ReisBenjamin ,
I checked that it was due to ICE enabled. When we disabled ICE then it works fine.

**Comment by saurabhs70** [comment]
Thanks a lot!
