### ISSUE TITLE
On Dialer Screen - On Add Contact Click App Crashes.

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#15]
Case:
On Dialer screen when i enter text or number and then press add contact, there is an error.

In Class ContactDetailViewController.m

Following lines there is an error:
- (void)addCurrentContactContactField:(NSString *)address {

	LinphoneAddress *linphoneAddress =
		linphone_address_new([address cStringUsingEncoding:[NSString defaultCStringEncoding]]);

//linphoneAddress is null

	NSString *username = [NSString stringWithUTF8String:linphone_address_get_username(linphoneAddress)];

//error on the above line
.
.
.
.
.
}

![screen shot 2015-10-26 at 6 43 00 pm](https://cloud.githubusercontent.com/assets/3806195/10729754/8518c8d4-7c11-11e5-9337-f40634f43032.png)

**Comment by bagage** [comment]
Indeed, thanks for pinpointing this! It should be fixed now.

**Comment by uditbatra** [comment]
Can you please, help me know what change i have to do in the project. Which file is been updated for that.
On pulling the project, xcode is crashing there for i cant pull the project.

Thanks in advance.

**Comment by bagage** [comment]
See commit 0ec1ecfbea3d4f4a1beb34571821f0c1b61215ad.

**Comment by uditbatra** [comment]
Thanks
