### ISSUE TITLE
Push Notifications and G729 not enabled first time runing app

### ISSUE THREAD

**Issue by Flipper1** [BelledonneCommunications/linphone-iphone#151]
Hi, with previous builds, I was able to enable G729 first time, so users don't have to go to settings and enable it. I can't do that in this latest build, every time I put enabled by default and it is overwritten again in rc, every time is disabled. Same thing with push notifications, I want them to be enabled as default, but when I change settings in plist and rc files, and I use overwrite, push notifications are not enabled. Can you check this?

**Comment by ReisBenjamin** [comment]
Hi,

To enable G729 you need to build the liblinphone SDK with the following option : 
-DENABLE_G729=ON

Go to linphone-iphone repo, enter the following command :
./prepare.py -c && ./prepare.py -DENABLE_G729=ON && make
(You can, of course add other options when executing prepare.py)
Doing this plus your modification in plist and rc should solve the issue. Please let me know if it works for you.
I'm am looking into the push notification problem.

**Comment by Flipper1** [comment]
I have created G729 with SDK and prepare.py and make, I am sorry, I was not clear the first time.

**Comment by ReisBenjamin** [comment]
Okay, so you do see the switch button to allow/disallow G729 in settings ?
What did you do exactly in plist and rc ?
When you modify the rc you have to re-install your app from scratch to apply the changes.

**Comment by ReisBenjamin** [comment]
If you use PushKit push notification preference should be set to NO as the option concerns Legacy push notifications.

**Comment by Flipper1** [comment]
Ok then, thank you for your help :) I have restarted everyhting, deleted app, excode, clean project, G729 is working as default enabled. You can close this

**Comment by ReisBenjamin** [comment]
Glad to hear it !

**Comment by fedesenmartin** [comment]
How did you get push enable by default?

Thanks
