### ISSUE TITLE
ContactsDetailsView does not show all numbers of the contact.

### ISSUE THREAD

**Issue by Spyspyspy** [BelledonneCommunications/linphone-iphone#152]
Hello. When i try to open a contact, which has more than 3 numbers, app shows first 3 and part of the next contact like in picture. But when i open another contact and again open this contact, everything is ok. And then if i open this contact again - i see the same picture like in screens. How can i fix it?

![simulator screen shot 15 2016 10 29 01](https://cloud.githubusercontent.com/assets/22395104/21216837/acec5dd4-c2b1-11e6-9463-c7e82c751b08.png)
![simulator screen shot 15 2016 10 28 55](https://cloud.githubusercontent.com/assets/22395104/21216838/acf08c60-c2b1-11e6-974f-116d50627590.png)

**Comment by ReisBenjamin** [comment]
Hello,
I don't reproduce this issue on my phone... Is you app up to date ?
I think the proble is that the contact avatar and name are hidden on the first picture and thats why you feel that the third phone number is cut bu in fact it should be as on the second picture.

**Comment by Spyspyspy** [comment]
Yeah, i'm using the the app, downloaded few days ago form this repository,
