### ISSUE TITLE
Authentication needed popup on dialing any # with prefix "00" or "+"

### ISSUE THREAD

**Issue by dinnysingh** [BelledonneCommunications/linphone-iphone#153]
Hi @ReisBenjamin,

We love your linphone release.

I just have one open concern, that when we try to call any number from dialpad, with prefix of "+" or "00", then it gives us the authentication error popup. Refer attached.

Can you please tell us why??
![unnamed-8](https://cloud.githubusercontent.com/assets/2306047/21219927/c3001590-c2dc-11e6-830f-d116e716bba5.jpg)

**Comment by ReisBenjamin** [comment]
Hello @dinnysingh,
Thanks for oyur interest in our product and reporting this issue.
I'll look into it and let you know when I find anything.
Could you please tell me if you use a linphone account or a another domain account ?
I you use a linphone account, is it linked to a phone number ?
Thanks !

**Comment by dinnysingh** [comment]
Hi, thanks for this prompt reply.
We are trying with our local sip server, which means that other domain account.
Regards

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin,

any update??

Thanking you in advance.

Regards

**Comment by ReisBenjamin** [comment]
hi @dinnysingh I can't reproduce your issue...
Could you send me logs of when it happens ?

Thanks

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin,

sorry for this late reply, i somehow missed your message.

Ok, I dont know how to get you logs for this (I will try), but you can simply try dialing a number like "+919650452200" from dialpad and it will just pop you up the "authentication needed" popup.

Let me know, if i should try to provide you with some more details, if any.

**Comment by ReisBenjamin** [comment]
Remove this line from linphonec_vtable in LinphoneManager :
.auth_info_requested = linphone_iphone_popup_password_request

The popup shouldn't appear anymore.

**Comment by dinnysingh** [comment]
Now if i remove this line, then i get proxy authentication required alert (however my sip server is able to handle calls with + or 00). please check attachment

![screen shot 2016-12-22 at 2 53 16 pm](https://cloud.githubusercontent.com/assets/2306047/21421008/a862535e-c856-11e6-905e-9c6373f8f0f3.png)

**Comment by ReisBenjamin** [comment]
it means the server refused your register  with a 401 UnAuthorized.
You should check why your server refused the registration.
Did you use a password when you connect to your account ?

**Comment by dinnysingh** [comment]
We do register with a phone# and password to our sip server (from linphone client). (it shows "registered" in the attachment too). 
To give another use case. If we dial with prefix "011" (which means that we are calling outside of USA), then it works without no problem but this problem only comes with "00" or "+" as prefix.

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin 
A very happy new year...

any update to this issue we facing??

Regards
