### ISSUE TITLE
Flexisip call ends up after 32 minutes

### ISSUE THREAD

**Issue by harunates** [BelledonneCommunications/linphone-iphone#155]
Hi,
when we register using Flexisip proxy, call ends up after 32 seconds. We tried both Android and IOS application of LinPhone. But Other sip clients like CSipSimple connects more than 32 seconds and never ends up accidentaly. 

Is there any configuration that can solve this issue? What can you suggest us? I'm waiting for your reply.

Best Regards.

**Comment by ReisBenjamin** [comment]
Hello @harunates,

Linphone automatically ends a call after 32seconds if it didn't receive an ACK.
Could you show logs of a call with your app ?

**Comment by harunates** [comment]
Hi @ReisBenjamin 

I attached the linphone logs. Is there any way that increasing this 32 seconds?

[linphone.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/661410/linphone.txt)

**Comment by ReisBenjamin** [comment]
That's what I thought, you nerver receive an ACK from who called you, that's why the conversation is stopped.

**Comment by Madhuraju** [comment]
Hi @harunates  and @ReisBenjamin,

Currently I am working with Linphone app in iOS app development. Main requirement is we have integrated Linphone code into Video Door Phone iOS application. So, I am also facing same issue after 36 seconds and some times call is ended with after few minutes like 1 or 2 min. 

Please help me on this. Where is the problem occurring and what is the exact issue.  

Best Regards.

**Comment by ReisBenjamin** [comment]
Hello,

Verify in the logs if once the call is accepted (200OK) you receive an ACK after.
I you don't that's why the call is stopped. You need to find why the ACK is not send/received.

**Comment by Madhuraju** [comment]
OK, Thank you so much @ReisBenjamin .

I will check and let you know if need any help.

**Comment by Madhuraju** [comment]
Hi @ReisBenjamin ,

For iPhone or iPad development (iOS) **H263** Codec should work for Linphone. Please help me on this. 

Thanks & Regards,
Madhusudhan G.

**Comment by ReisBenjamin** [comment]
Hello,

This issue has been closed, so please reopen one for future questions.
Try to recompile your SDK with that command ./prepare.py -c && ./prepare.py -DENABLE_H263=ON -DENABLE_H263P=ON -DENABLE_MPEG4=ON -DENABLE_FFMPEG=ON -DENABLE_NON_FREE_CODECS=ON && make
Your app should have H263 supports and H263 available in video settings.

**Comment by cuongitbk** [comment]
> That's what I thought, you never receive an ACK from who called you, that's why the conversation is stopped.

I got same issue, could you let me know how to fix it?
Thanks!

**Comment by cuongitbk** [comment]
@harunates: Pls let me know how you fix this issue, thanks!

**Comment by leelai** [comment]
Hello,

How do you fix this issue?
