### ISSUE TITLE
Unregister to be handled properly for push notifications (on app kill)

### ISSUE THREAD

**Issue by dinnysingh** [BelledonneCommunications/linphone-iphone#156]
Hi @ReisBenjamin ,

In order to get reliable push notifications (when app is terminated), we need the register to expire with expires=0. 
However in some cases, we see that when we kill the app, the unregister with expires=0 is sent but in that another second, the register is sent too with expires=60 (value which is set by us).

So I am wondering that why it happens? (why or in what cases, the register is sent just after the unregister is sent on app kill??)

I have published that same trace below (however have changed IP and other details for security purposes)

##
T 2016/12/16 14:20:40.421040 11.11.11.11:50551 -> 11.11.11.11:5060 [AP]
REGISTER sip:xxxx.com SIP/2.0.
Via: SIP/2.0/TCP 11.11.11.11:50551;alias;branch=sdsdsfdds;rport.
From: <sip:22222@aa.aa.com>;tag=d30-zfdzf4w5.
To: sip:22222@aa.aa.com.
CSeq: 35 REGISTER.
Call-ID: 34dsfsdfsfsdf.
Max-Forwards: 70.
Supported: replaces, outbound.
Accept: application/sdp.
Accept: text/plain.
Accept: application/vnd.gsma.rcs-ft-http+xml.
Contact: <sip:22222@ 11.11.11.11:50551;transport=tcp>;+sip.instance="<urn:uuid:dfsdfdsf-a882-46fb-9af4-fsdfdsf>".
**Expires: 0.**
User-Agent: R_iPhone.4S_iOS9.3.2/sdfsdfdsf (belle-sip/1.5.0).
Content-Length: 0.
Authorization:  Digest realm="aaa.aa.com", nonce="5853f84e000036ed7cf947aad0f10c8e1a69597de8ffdda2", username="22222",  uri="sip:aa.aa.com", response="686923f681dab8923cbe15441d6c6a33".
.

####
T 2016/12/16 14:20:42.982489 11.11.11.11:50551 -> 11.11.11.11:5060 [A]
REGISTER sip:aa.aa.com SIP/2.0.
Via: SIP/2.0/TCP 11.11.11.11:50551;alias;branch=dfsdfdsfdsf3~BwlKs;rport.
From: <sip:22222@aa.aa.com>;tag=F80-nPZbT.
To: sip:22222@aa.aa.com.
CSeq: 34 REGISTER.
Call-ID: 34fsdfsfds.
Max-Forwards: 70.
Supported: replaces, outbound.
Accept: application/sdp.
Accept: text/plain.
Accept: application/vnd.gsma.rcs-ft-http+xml.
Contact: <sip:22222@11.11.11.11:50551;transport=tcp>;+sip.instance="<urn:uuid:324343-a882-46fb-9af4-43432432>".
**Expires: 60.**
User-Agent: R_iPhone.4S_iOS9.3.2/dfsdfdsfs (belle-sip/1.5.0).
Content-Length: 0.
Authorization:  Digest realm="aa.aa.com", nonce="sdfdffdf", username="22222",  uri="sip:aa.aa.com", response="fdsfsfdsfdsfdsfdfdsf34335".

**Comment by ReisBenjamin** [comment]
instead of unregister try to use linphone_core_set_network_reachable(FALSE).

**Comment by dinnysingh** [comment]
Hi,
thanks for this reply.

Basically our server logic is, that once the session unregisters
(expiry=0), then push is sent from the server (to the recipient's device
token). So with this line of code, the session still remains on the server.
So push is never pushed to the client.

**Comment by ReisBenjamin** [comment]
Have you tried to unregister as you did before then call linphone_core_set_network_reachable(FALSE) to not reregister ?

**Comment by dinnysingh** [comment]
This is what our terminate method looks like:

- (void)applicationWillTerminate:(UIApplication *)application {
LOGI(@"%@", NSStringFromSelector(_cmd));

linphone_core_terminate_all_calls(LC);

        linphone_core_set_network_reachable(LC,FALSE);

[LinphoneManager.instance destroyLinphoneCore];


}

**Comment by ReisBenjamin** [comment]
This seems good to me... and you say it doesn't work ?

**Comment by dinnysingh** [comment]
No.

Ok I was testing now again.. so sorry for few mins of delay in my response.

No it doesn't work.

**Comment by dinnysingh** [comment]
Could be a stupid question but good to ask atleast:

Could this be a local network issue?? Can the unregister packets get
blocked in the network??

**Comment by dinnysingh** [comment]
Quick question again:

Is " [LinphoneManager.instance destroyLinphoneCore]; " is the only way to
unregister a user??

**Comment by dinnysingh** [comment]
Is it because we are calling  network reachable "false" before destroy and
it actually is not letting the unregister request (from destroy command) go
to server?


linphone_core_set_network_reachable(LC,FALSE);

[LinphoneManager.instance destroyLinphoneCore];





On Tue, 20 Dec 2016 at 10:03 PM, Jasmeet Singh <dinnysingh@gmail.com> wrote:

Quick question again:

Is " [LinphoneManager.instance destroyLinphoneCore]; " is the only way to
unregister a user??


On Tue, Dec 20, 2016 at 9:44 PM, Jasmeet Singh <dinnysingh@gmail.com> wrote:

Could be a stupid question but good to ask atleast:

Could this be a local network issue?? Can the unregister packets get
blocked in the network??

On Tue, Dec 20, 2016 at 9:28 PM, Jasmeet Singh <dinnysingh@gmail.com> wrote:

No.

Ok I was testing now again.. so sorry for few mins of delay in my response.

No it doesn't work.





On Tue, Dec 20, 2016 at 9:18 PM, ReisBenjamin <notifications@github.com>
wrote:

This seems good to me... and you say it doesn't work ?




—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BelledonneCommunications/linphone-iphone/issues/156#issuecomment-268277514>,
or mute the thread

**Comment by ReisBenjamin** [comment]
It's possible being not reachable prevent from unregistering.

**Comment by dinnysingh** [comment]
Yes it is not sending when i use it with FALSE.

Now the problem is that when we terminate the app, then sometimes the
unregister (with expiry=0) is sent to the server and most of the time it
doesn't go at all.

So why it is inconsistent??

I am using this code now in terminate:


- (void)applicationWillTerminate:(UIApplication *)application {
LOGI(@"%@", NSStringFromSelector(_cmd));

linphone_core_terminate_all_calls(LC);

[LinphoneManager.instance destroyLinphoneCore];


}

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin 

Any update here??

Why "unregister" is not consistent? which means that why unregister hits my server sometimes and why it doesnt.. the other time (on app kill)??

Regards

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin 

Today i was going to this issue again and noticed that when i add " linphone_core_set_network_reachable(LC,YES);
"
then unregister works perfectly fine in iOS9 but it does not work in iOS10.

Any advise for iOS 10??
 

My terminate code is like below now:

- (void)applicationWillTerminate:(UIApplication *)application {
	LOGI(@"%@", NSStringFromSelector(_cmd));

	linphone_core_terminate_all_calls(LC);
    
    linphone_core_set_network_reachable(LC,YES);
    [LinphoneManager.instance destroyLinphoneCore];
}

**Comment by dinnysingh** [comment]
any update @ReisBenjamin ?

**Comment by ReisBenjamin** [comment]
You need to not unregister to get the push notifcation work or else the server won't know to whom sending the push.
