### ISSUE TITLE
Saving push notification values in database?

### ISSUE THREAD

**Issue by saurabhs70** [BelledonneCommunications/linphone-iphone#157]
When we get push notification, then how to save that entry to the database??

I mean that, when i receive push notification for incoming call then i need to show that entry in "recent" (as received or missed call) and when i receive push notification for chat, then i need to show badge increment and show that received message in the chat controller too.

Please advise

**Comment by ReisBenjamin** [comment]
Hi,

Which push notification framework do you use ?
PushKit or another one ?

**Comment by saurabhs70** [comment]
PushKit

**Comment by ReisBenjamin** [comment]
Then you have a Callback in the PushKitRegistryDelegate protocol which is called on every push received.
You can do whatever you want with the notification in the method.
It's called - (void)pushRegistry:(PKPushRegistry *)registry
	didReceiveIncomingPushWithPayload:(PKPushPayload *)payload
							  forType:(NSString *)type {

**Comment by saurabhs70** [comment]
Yes this method is called when the push comes but we looking to find how we store incoming call or chat entries locally (in local app db) from the incoming push data?

**Comment by ReisBenjamin** [comment]
In the payload argument of the method you can access payload.dictionnaryPayload which contains all the information on the notification. And then you can manipulate the info in the method by getting the value from the dictionnary.

**Comment by saurabhs70** [comment]
I am able to retrieve data from the payload however i am not sure how to store that data, so that it can be seen by the user inside the app.
For example:
If user A sends chat to user B with text "123"
Now user B receives push notifications (because his app was killed) with payload data containing the string value "123"
Now when user B clicks open the app, then how can this value "123" be shown in the chat controller for the chat window of user A??
So where to keep this incoming push notification chat message, so that once you open the chat controller, it is shown there.

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin,

Yes even i am interested to know that by how we can insert incoming chat message from push notification to the local chat messages for the sender user.

**Comment by ReisBenjamin** [comment]
Hi,

PushNotification should only be used to wake up the application.
Once the app has woken up it should register and then let the LinphoneManager handle incoming calls and messages.

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin 

But if we won't store the incoming chat message from push notification, then we will never see that message in the chat room of that sender. Isnt it?
Wouldn't that make the chat messages inconsistent for that sender, whenever he sents me the messages (via push notification) when i was offline?

**Comment by ReisBenjamin** [comment]
No,
Because the chat message shouldn't be send in the push notification but in a SIP request by the server.
The push notification has for only purpose to wake the app up so that it registers to the server which will inform the app off messages and calls through SIP request.

Our Push Gateway send empty push notification and all the VoIP signalisation is done with our server's SIP requests.

**Comment by dinnysingh** [comment]
Got it... so we will go with this use case only. We will get push to wake up the call and then send our actual incoming calls or messages after a certain time period (lets say after 2-3 seconds). So this should sort this problem of ours.

**Comment by ReisBenjamin** [comment]
You can do that.
I'd rather suggest to make the server wait for the REGISTER from the app to send the INVITE and MESSAGE requests. You'll be sure to send them as soon as possible.
You just need to store the request in your server.

**Comment by dinnysingh** [comment]
Yes that makes much better sense..

Thanks for always being around to answer to all the concerns and even some stupid questions sometimes 👍  :)

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin

My server provider has denied to change the logic as of now (to what we discussed yesterday). So I am stuck a little.

So now all I can do is that when I receive chat push notification (this will have full chat message) then I store it for the sender and when I open the room then that message from push is displayed there too (with other messages).
Can u help me with this? How can I store push message into our chat messages for a sender room?

**Comment by ReisBenjamin** [comment]
in ChatConversationView you can use [_tableController addChatEntry:chat]; where chat is a LinphoneMessage.
It'll add it to the conversation.
If you store it when you received the push, you can get the message on ViewWillAppear of ChatConversationView and add all the message of the room.

**Comment by dinnysingh** [comment]
Super, I will check it quick. Also how can we do it for incoming calls too? Means if I need to save entry as received or missed call (from push notification)?

**Comment by ReisBenjamin** [comment]
You can call [PhoneMainView.instance displayIncomingCall:call]; from wherever you want in the code where call is a LinphoneCall.
For missed called you should not need pushes as they are handled by the linphone manager.

**Comment by dinnysingh** [comment]
I guess the above you are stating is to handle incoming and missed calls. My concern is that I will receive a push msg like "voice call from xxx". Where xxx is the caller. And I will then make outgoing call to the caller (which will actually be a conference call between me and caller). So now how can I save this incoming and outgoing call entry in the call logs?

Basically to keep it simpler, how can I insert and edit values in the call log? Answer to this will be enough to handle my incoming calls logic.

**Comment by dinnysingh** [comment]
Hi @ReisBenjamin,
We tried "[_tableController addChatEntry:chat];" and it seems that it will add message from me (my side). I would want the sender message to be added to the conversation (so that it comes as received message, not sent message). 

Please advise.

**Comment by ReisBenjamin** [comment]
Instead of addChatEntry, try to launch a kLinphoneMessageReceived notification with the following type of dictionnary as user info :

**Comment by dinnysingh** [comment]
that sounds better... we are checking this now.

I know, i am bothering a little but this last piece is just what i need:
 
how can I insert and edit values in the call log? Answer to this will be enough to handle my incoming calls logic.

**Comment by dinnysingh** [comment]
hi @ReisBenjamin 
We got it resolved by writing method to access db directly.

So all good. thanks

**Comment by saurabhs70** [comment]
Thanks a lot
