### ISSUE TITLE
Flexisip Keepalive

### ISSUE THREAD

**Issue by bozog61** [BelledonneCommunications/linphone-iphone#160]
Hello Everyone,

When we register the flexisip ,we can register sipserver during 10 minutes successfuly. But we want to increasing the 10 minutes. Can flexisip register to sipserver everytime instead of device when app is closed or background mode?
@BelledonneComm  @ReisBenjamin

**Comment by ReisBenjamin** [comment]
When app closed or in background you need to use push notification. It's supported by both linphone and flexisip.

Best regards
