### ISSUE TITLE
App crash in background mode

### ISSUE THREAD

**Issue by tintrung** [BelledonneCommunications/linphone-iphone#162]
I install linphone in iOS and app is crash in background mode.
in background mode, i call from other app to app in iOS and click cancel (make miss call). and after that app in iOS is crash in channel_on_message function (in module provider.c) 
channel_on_message function call --> has_type (crash in this function).

static int has_type(belle_sip_object_t *obj, belle_sip_type_id_t id){
	belle_sip_object_vptr_t *vptr=obj->vptr;

	while(vptr!=NULL){
		if (vptr->id==id) return TRUE;
        if ( (void*)vptr->type_name != NULL)
        {
            vptr=vptr->get_parent();
        }
	}
	return FALSE;
}

crash always in vptr->get_parent() with EXC_BAD_ACCESS.
anybody advice me for this issue
regards

**Comment by carras** [comment]
For me, It crashes instantly since many time ago.

Or maybe when I try to add a SIP account it crashes.

Is it maybe some incompatibility with others apps?

**Comment by ReisBenjamin** [comment]
please try latest build and reopen if not fixed.
