### ISSUE TITLE
why other's presence notification is not calling?

### ISSUE THREAD

**Issue by saurabhs70** [BelledonneCommunications/linphone-iphone#163]
Hi,
as per i think in linphonemanager.m contains 
"linphone_iphone_notify_presence_received_for_uri_or_tel" for showing presence of other but why this not called if other person is going online or offline?

![screen shot 2016-12-30 at 12 41 48 pm](https://cloud.githubusercontent.com/assets/17975720/21561054/61c0db40-ce8d-11e6-8d25-3a9add986408.png)
please help regarding that issue

**Comment by ReisBenjamin** [comment]
Hi,
This function is used for long term presence (which means who uses Linphone in your contact and who doesn't).
It's not used for short term presence (online / offline)

**Comment by saurabhs70** [comment]
Hey!
Thanks for clarify,So do we have short term presence (online / offline) capabilties in linphone??

**Comment by ReisBenjamin** [comment]
Liblinphone does have this capabilities for our desktop version but not for the phones app
