### ISSUE TITLE
how to add incoming text message into database "for  push message "

### ISSUE THREAD

**Issue by saurabhs70** [BelledonneCommunications/linphone-iphone#165]
Hi, 
how to add incoming message in database for my custom push, i'm not discussing about "linphone_iphone_message_received", which is in "linphonemanager.m" this is for notification so i want basically adding incoming push for example
suppose
i found incoming message "hi how are you?"
for sending we have method in linphone "linphone_chat_room_send_chat_message"
NSString *from =@"senderid";
NSString *message =@"hi how are you?";
LinphoneChatRoom *room = linphone_core_get_chat_room_from_uri(LC, [from UTF8String]);
LinphoneChatMessage *msg = linphone_chat_room_create_message(room, message.UTF8String);
linphone_chat_room_send_chat_message(room, msg);
/--- here just message sent! ok-----/
now for recieve ?
please consider asap.
Thanks.
[issue-incoming message.pdf](https://github.com/BelledonneCommunications/linphone-iphone/files/682277/issue-incoming.message.pdf)
![img-incoming](https://cloud.githubusercontent.com/assets/17975720/21609063/4d055fe4-d1e6-11e6-9d08-13b2b04c5c20.png)

**Comment by dinnysingh** [comment]
Hi @saurabhs70 

you can create your own method to do updates directly to chat db. This is the best way out of it.

thanks

**Comment by saurabhs70** [comment]
Thanks a lot

**Comment by S0U1SB4N3** [comment]
did you find a way of connecting push messages into chat database ? 
if so could you share your method ? 
I can not find the chat.db it is linphone-chat.db but only contains call_history table not a chat_history table in the schema ?
