### ISSUE TITLE
Push and receiving call problems

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#166]
Hi!

I have two issues,I compiled the latest version and try it out on the simulator.

When the apps is in foreground ,and someone calls,it doesnt appear any screen for accept or reject the call.

Otherside ,when the app is on background or killed,it doest even ring.I have to configure apple push service for that?

Thanks!

**Comment by ReisBenjamin** [comment]
Hi !
Push notification doesn't work on simulator that' why you don't receive incoming calls when in background.
And since we use CallKit for IOS10 i'm not sure this framework works an a simlator either.
I suggest you try it on an actual device.

**Comment by JFSene** [comment]
@ReisBenjamin is CallKit already implemented or do I need to make any changes ?

**Comment by ReisBenjamin** [comment]
@JFSene hello,
CallKit is already implemented since the release 3.16.1

**Comment by Trushangpatel** [comment]
Hello,

I will resolve this issue with VoIP silent push notification.
if you need help then mail me: trushangpatel3993@gmail.com, add subject: linphone issue

Thanks
