### ISSUE TITLE
Presence info is always online

### ISSUE THREAD

**Issue by Spyspyspy** [BelledonneCommunications/linphone-iphone#170]
Hi! Can you help me. How can i set my presence info, for example online, offline, and get contact's presence info?

**Comment by Spyspyspy** [comment]
So, i've used Basic buddy status notification tutorial and get presence, but it is always online for buddies. I tried to add this code in applicationWillTermitate, and it shows the same - online. What's the problem?
` linphone_core_set_presence_model(lc, linphone_presence_model_new_with_activity(LinphonePresenceActivityOffline, NULL));`

**Comment by ReisBenjamin** [comment]
Hi @Spyspyspy,

The presence used in linphone-iphone is long term presence, which means is the contact reachable by Linphone (does he have a linphone account ?).
Short term presence (Online/Offline) is not implemented in the app because we feel it is not necessary.

**Comment by Spyspyspy** [comment]
@ReisBenjamin  thank you for the answer. 
Will you implement this in the future? And does flexisip support short term presence? 


By the way, 

> The presence used in linphone-iphone is long term presence, which means is the contact reachable by Linphone (does he have a linphone account ?).

I added contact with fake linphone account which does not exist, and there was the image, that he has a linphone account

**Comment by ReisBenjamin** [comment]
Hello,

Yes Flexisip supports short terms presence as it is implemented in our GTK desktop app.
The behavior of linphone is to accept all SIP adresses. You can add a filter to choose a domain or filter if you receive presence as it's done for the phone numbers
