### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by babumoshai-ankush** [BelledonneCommunications/linphone-iphone#176]
Thanks for such a great library. 
I have downloaded the latest SDK. It successfully compiled and running. But I am getting one warning.

**warning: skipping file '/Users/.../liblinphone-sdk/armv7-apple-darwin.ios' (unexpected file type 'folder' in Frameworks & Libraries build phase)**

Kindly help me how I remove this warning.

Thanks in advance.

**Comment by ReisBenjamin** [comment]
Remove armv7-apple-darwin.ios from your project linked binaries

**Comment by babumoshai-ankush** [comment]
Thanks a lot!
