### ISSUE TITLE
AutoLayout issues

### ISSUE THREAD

**Issue by JFSene** [BelledonneCommunications/linphone-iphone#177]
Hello there, 
After some time away from this project, I had to comeback to it since CallKit is finally working.
Altho I'm having some troubles with autolayout.
When testing on A iPhone SE Simulator, the about page broke, and it looks like this now...

any Ideas on how I can fix this? 
![image](https://cloud.githubusercontent.com/assets/17616463/22076912/38fe0280-dd99-11e6-8aad-ae03c6df026a.png)

**Comment by ReisBenjamin** [comment]
Have you try reducing the size of the view in the xib ?

**Comment by ReisBenjamin** [comment]
not answered
