### ISSUE TITLE
H263 Support

### ISSUE THREAD

**Issue by babumoshai-ankush** [BelledonneCommunications/linphone-iphone#178]
Hi,

First of all thanks for distributing such kind of open sorce library. I have some issue kindly go through please.

I have enable H263 codec by -

`$ ./prepare.py -c && ./prepare.py -DENABLE_H263=ON -DENABLE_H263P=ON -DENABLE_MPEG4=ON -DENABLE_FFMPEG=ON -DENABLE_NON_FREE_CODECS=ON && make`

Log showing -

 **H263 , H263 video encoding/decoding support (require license).
  H263p , H263+ video encoding/decoding support (require license).**

H263 codec also not showing in video codec list in app. Kindly help me how to add H263 codec. Its showing **require license** in the terminal log. Where I have to took the license?

**Comment by ReisBenjamin** [comment]
Hello,

You need to purchase a licence to  H263 developper.
We are not H263 developpers you should search for an official website.
