### ISSUE TITLE
Switch the network or Turn on flight mode in calling  crashed

### ISSUE THREAD

**Issue by yk113536** [BelledonneCommunications/linphone-iphone#179]
I Can not find the problem.Always connected wifi or cellular network is no problem.
![b86e375c-00a3-46ba-bd94-681225f698ca](https://cloud.githubusercontent.com/assets/16081425/22180853/2e138d5a-e0b8-11e6-9588-33183e41a4e4.png)

**Comment by ReisBenjamin** [comment]
fixed on master
