### ISSUE TITLE
Custom FFmpeg configuration

### ISSUE THREAD

**Issue by jakubprusa** [BelledonneCommunications/linphone-iphone#18]
Hi,

I am using liblinphone in my project. But also i need FFmpeg for my custom player. FFmpeg that I am using need special configuration that means custom build. Right now I'm combine binary files from my build and from liblinphone build. Somehow it works. But in best way I would like to pass my configuration of FFmpeg to liblinphone. Or just somewhere change it.

 Can you help me where to change the configuration of FFmpeg?

**Comment by bagage** [comment]
All build system is located in `submodules/cmake-builder`. FFMpeg is handled by `submodules/cmake-builder/builders/ffmpeg.cmake`, where you can find our configure and make options.

**Comment by jakubprusa** [comment]
Thanks ! Exactly what I needed
