### ISSUE TITLE
prepare.py throw many errors when executed

### ISSUE THREAD

**Issue by caferlop** [BelledonneCommunications/linphone-iphone#180]
Hello Everybody,

When I run ./prepare.py in the Iterm.app shell, i got the following errors:

Traceback (most recent call last):
  File "./prepare.py", line 45, in <module>
    class IOSTarget(prepare.Target):
  File "./prepare.py", line 53, in IOSTarget
    self.external_source_path = os.path.join(current_path, 'submodules')
NameError: name 'current_path' is not defined

How can I sort this problem? I have followed each step of the readme, with no luck...

**Comment by mmehdi** [comment]
have you sync with submodules after cloning the code? you might have to do the following:
`git submodule sync && git submodule update --init --recursive`

**Comment by ReisBenjamin** [comment]
Try latest build and reopen if not fixed.

Thanks
