### ISSUE TITLE
Getting black image for own video view

### ISSUE THREAD

**Issue by dinnysingh** [BelledonneCommunications/linphone-iphone#181]
Sometimes we see black image inside our own video view. Please refer attachment

![img_1227 jpg](https://cloud.githubusercontent.com/assets/2306047/22199115/8dbd8c0c-e17f-11e6-8f57-90c079ee5aa8.jpg)

**Comment by Spyspyspy** [comment]
Try to change video size to higher, for my case it helped.

**Comment by ReisBenjamin** [comment]
Hello,

This issue happens when you create the camera before having the authorization to do so.
If you restart your app this shouldn't happen

**Comment by ReisBenjamin** [comment]
Fixed in commit : e5c25af5453b3e06817486712b36e79ca211373c
