### ISSUE TITLE
Two calls are created with CallKit for single outgoing call

### ISSUE THREAD

**Issue by hmaracic** [BelledonneCommunications/linphone-iphone#182]
When Linphone is used with a SIP account on iOS 10.2 (iPhone SE) it creates two CallKit calls/sessions for a single outgoing call resulting in the following lock screen:
![img_2613 copy](https://cloud.githubusercontent.com/assets/9732168/22206197/94fa6652-e17a-11e6-980d-08aa9c807be8.png)

Also, even when a call is ended without Linphone ever going to background, after subsequently closing Linphone there is a green double-height in-call bar on the home screen. The only way to remove it is to terminate Linphone which causes a "call failed" native UI screen to appear and the in-call bar disappears.

The SIP proxy is running Asterisk.

After debugging, the cause has been determined as two invocations of the `LinphoneCallOutgoingProgress` case in the switch statement in the `(void)callUpdate:(NSNotification *)notif` of the PhoneMainView.m class.

**Comment by ReisBenjamin** [comment]
Hello,

Does the bug still happen with last commit ?
Thanks
