### ISSUE TITLE
SDK Upgrading Issue

### ISSUE THREAD

**Issue by babumoshai-ankush** [BelledonneCommunications/linphone-iphone#184]
Before me another developer work on my project, but now I checked IPv6 is not supporting by the old SDK. Video call is not establishing in IPv6. I am trying to upgrade the SDK and the rest of the project would be as it is. I have merge with the new version on git and updated submodules by

```
$ git merge master
$ git submodule sync && git submodule update --init --recursive
```
After that when I am tring to buid the SDK by the following commad getting error. -

```
$ ./prepare.py -c

./prepare.py -c
Traceback (most recent call last):
  File "./prepare.py", line 93, in 
    class IOSPreparator(prepare.Preparator):
AttributeError: 'module' object has no attribute 'Preparator'
```

**Comment by ReisBenjamin** [comment]
Try latest build and reopen if not fixed.

Thanks
