### ISSUE TITLE
New SDK XCode build problem

### ISSUE THREAD

**Issue by Flipper1** [BelledonneCommunications/linphone-iphone#185]
I am able to build newest version of SDK, and I am able to build release 3.16.1 SDK version. Every time when I upgrade my SDK in my project, when building projects, errors come up. Can you see what's up with that? Errors:
Undefined symbols for architecture arm64:
  "_tjCompressFromYUVPlanes", referenced from:
      _jpg_process in libmediastreamer_voip.a(turbojpegwriter.c.o)
  "_tjFree", referenced from:
      _jpg_process in libmediastreamer_voip.a(turbojpegwriter.c.o)
  "_tjInitCompress", referenced from:
      _jpg_init in libmediastreamer_voip.a(turbojpegwriter.c.o)
  "_tjInitDecompress", referenced from:
      _jpeg2yuv in libmediastreamer_voip.a(turbojpegnowebcam.c.o)
  "_tjGetErrorStr", referenced from:
      _jpeg2yuv in libmediastreamer_voip.a(turbojpegnowebcam.c.o)
      _jpg_init in libmediastreamer_voip.a(turbojpegwriter.c.o)
      _jpg_process in libmediastreamer_voip.a(turbojpegwriter.c.o)
      _jpg_uninit in libmediastreamer_voip.a(turbojpegwriter.c.o)
  "_tjGetScalingFactors", referenced from:
      _jpeg2yuv in libmediastreamer_voip.a(turbojpegnowebcam.c.o)
  "_tjDecompressToYUVPlanes", referenced from:
      _jpeg2yuv in libmediastreamer_voip.a(turbojpegnowebcam.c.o)
  "_tjDecompressHeader3", referenced from:
      _jpeg2yuv in libmediastreamer_voip.a(turbojpegnowebcam.c.o)
  "_tjDestroy", referenced from:
      _jpeg2yuv in libmediastreamer_voip.a(turbojpegnowebcam.c.o)
      _jpg_uninit in libmediastreamer_voip.a(turbojpegwriter.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ReisBenjamin** [comment]
Please make sure you have libturbojpeg.a in your project linked binaries.
