### ISSUE TITLE
Exact process to have monthly subscription using InAppPurchase 

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#188]
I have successfully build and launch my app now I want to integrate monthly subscription package for my customers.

Please any can just share what will be the exact process so that my customers pay monthly and use the app upto specific minutes .
 
What this is for receipt_validation_url?

**Comment by ReisBenjamin** [comment]
Not related to Linphone.
Please see the Apple concerning API doc.

Regards
