### ISSUE TITLE
"Linphone Audio unavailable" message after terminating a call

### ISSUE THREAD

**Issue by anatoli26** [BelledonneCommunications/linphone-iphone#190]
Almost always, after ending (with the "End call" button) a successful call, I get a screen with the number, the message "Linphone Audio unavailable" and 2 buttons "Cancel" and "Call Back". What could be the problem?

Linphone iOS 3.16.1
Linphone Core 3.10.2-579
iPhone 6S with iOS 10.2.1

![screen](https://cloud.githubusercontent.com/assets/22968420/22623499/abca85a4-eb3b-11e6-919d-ebbaa118e222.png)

**Comment by ReisBenjamin** [comment]
Please update your SDK i believe this issue is already fixed

**Comment by anatoli26** [comment]
This is Linphone from AppStore, the latest version

**Comment by ReisBenjamin** [comment]
Fixed in commit 1bf8383c44b4c1c5702c4f9ab7e518818f006b6d
