### ISSUE TITLE
Linphone replaces first 00 digits of a number with "+"

### ISSUE THREAD

**Issue by anatoli26** [BelledonneCommunications/linphone-iphone#191]
Subj, previous versions were not making this change. The option "Substitute + in phone numbers" is turned off. This is actually a behavior that complicates dialing numbers like 0800 when additional 0 in front (0-0800) is an indication of an outgoing call.

Yes, one could rewrite the dialplan rules, if he/she controls the server, but... could this behavior be made optional?

Linphone iOS 3.16.1
Linphone Core 3.10.2-579
iPhone 6S with iOS 10.2.1

**Comment by ReisBenjamin** [comment]
Fixed in commit 4e738651ca3206be5cbe7b892d38a43234930308
