### ISSUE TITLE
Initial a LinphoneCall from Call Id from VoiP push notification.

### ISSUE THREAD

**Issue by chuquangbao** [BelledonneCommunications/linphone-iphone#192]
When my application is killed, i begin to call to it.
My expect: App will receive a voiP push and retrieve to show new call screen.
But i don't know initial from this call-id after register process is finished.
Please, help me. Thank you.

**Comment by ReisBenjamin** [comment]
Hello,

After the registration you can access the incoming call by using **linphone_core_get_current_call(LC)**
You can also wait the LinphoneManager method onCallStateChanged where you already have the call in a variable.
