### ISSUE TITLE
File Share expansion request

### ISSUE THREAD

**Issue by p5panam** [BelledonneCommunications/linphone-iphone#194]
Hi,
I notice we are only capable of sending a photo from Gallery or by Camera. (very limited nowadays)
Why not expand this option to other file types, as the upload code and structure is already implemented.
(like pdf, doc, xls, zip, rar, etc) 

It will be just a few line of codes, and the improve on chat ecosystem is great.
Keep LIME also compatible with them.

**Comment by ReisBenjamin** [comment]
Hello,

Thanks for reporting this idea, we'll consider it.
Best regards,
Benjamin
