### ISSUE TITLE
Calls not connecting if AUTH is enabled

### ISSUE THREAD

**Issue by dinnysingh** [BelledonneCommunications/linphone-iphone#195]
Use case is:

Server got the INVITE message, Then server asked for Authentication, Client said ACK. But the client is not sending INVITE again
That's why call is failing.

Can you please advise over this issue.

**Comment by ReisBenjamin** [comment]
Hello,

Does the REGISTER works ? Is it also challenged by the server ?

**Comment by dinnysingh** [comment]
Yes registers works and yes it is challenged by the server and that piece
works fine.

**Comment by ReisBenjamin** [comment]
Okay, do you remove or clear auth info in between the REGISTER and the INVITE ?

**Comment by dinnysingh** [comment]
No we are just using your default release from Dec 23 2016.

**Comment by ReisBenjamin** [comment]
Do you use a Linphone Account or a sip none Linphone account ?

**Comment by ReisBenjamin** [comment]
Do you reproduce your problem on the current master branch ?

**Comment by dinnysingh** [comment]
We are using our kamailio sip server

**Comment by dinnysingh** [comment]
Yes we copied latest submodules and liblinphone sdk and the problem still
exists

**Comment by ReisBenjamin** [comment]
In the log do you see a athentication HEADER in your INVITE ?

**Comment by ReisBenjamin** [comment]
Not answered.

Please update to latest commit and re-open if the issue still occurs.

Regards

**Comment by Thucnv** [comment]
Hello,
I have the same issue
[log.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/1406719/log.txt)
![logflow](https://user-images.githubusercontent.com/20784964/31885188-daefadd6-b819-11e7-919e-a3e4ce56b7e6.png)

**Comment by XVincentX** [comment]
@dinnysingh Same here.
