### ISSUE TITLE
Linphone crash at startup on iOS 10.2.1

### ISSUE THREAD

**Issue by Battant** [BelledonneCommunications/linphone-iphone#196]
Hello,

Since I have update my iPhone from iOS 9 to iOS 10.2.1 iPhone look and crack at startup

Step to reproduce :

Tack an iPhone which iOS 9
2. Configure sip account in Linphone 
3. Update iOS to 10.2.1

Actuael result

If you start lineup lit look and crach

Linphone is available at :

Linphone par Belledonne Communications SARL
https://appsto.re/ch/MPIDv.i

Could you help me please to fix this critical bug ?

Thanks for your support 

Best regard

Battant

**Comment by ReisBenjamin** [comment]
Hello do you reproduce this problem on the current version of the master branch ?

**Comment by Battant** [comment]
Hello,

How Cai I download the line phone master branch version on iOS 10.2.1 ?

The last version available is :

Linphone par Belledonne Communications SARL
https://appsto.re/ch/MPIDv.i

Thanks for your support 

Best regards

Battant

**Comment by ReisBenjamin** [comment]
Hello,

The master version of Linphone is not available on the AppStore.
It is available on git following this procedure : https://wiki.linphone.org:8443/xwiki/wiki/public/view/Lib/Getting%20started/iOS/#HBuildingtheSDKmanually
Or you can enter the public beta test of our future release (not the master version but most of the modification are present in the beta) following this procedure : https://wiki.linphone.org:8443/xwiki/wiki/public/view/Linphone/Enter%20the%20public%20beta%20test/

**Comment by Battant** [comment]
Hello,

How could compile linephone master branch and test install and test this version on my iPhone 5 which iOS 10.2.1 not jell break ?

Note the jell break beak the warranty

Could you help me please ?

Thanks for your support 

Best regards

Battant

**Comment by ReisBenjamin** [comment]
Hello,

Do you know how to use XCode to install an app to your device ?

**Comment by Battant** [comment]
Hello,

I have Xcode on my MacBook Pro with Mac OS 10.11.5 

However, I have never use it to install an appliance 

Could you post a link with a step by step procedure to compile and install an application whith Xcode ?

Thanks for your support 

Best regards

Battant

**Comment by ReisBenjamin** [comment]
This might be a little complicated... would you prefer to download our public beta test ?
This is like downloading the app from the store.

**Comment by ReisBenjamin** [comment]
To test our beta please folow our procedure : https://wiki.linphone.org:8443/xwiki/wiki/public/view/Linphone/Enter%20the%20public%20beta%20test/
