### ISSUE TITLE
CallKit - Linphone reports outgoing call state changes from wrong states

### ISSUE THREAD

**Issue by jelenadj** [BelledonneCommunications/linphone-iphone#197]
In the current code, reporting "connecting" and "connected" states for outgoing call happens when linphone call is in Ringing state, which means that after ending the call, in Recents logs from native Phone call application, duration will be longer than it actually is. Also, if you called someone, and this person rejected the call, or didn't answer, duration in Recents will be represent as number of seconds for how long call was between ringing and ended state, instead of to display it as a Canceled call, since call is not established at all.
When I try to use reportOutgoingCallWithUUID:startedConnectingAtDate and reportOutgoingCallWithUUID:connectedAtDate from LinphoneCallConnected and LinphoneCallStreamsRunning states respectively, Linphone changes state call into "paused" from some reason. How to prevent it, and to report outgoing call state properly to the system?

**Comment by ReisBenjamin** [comment]
Hello,
Did you remove the report at StateRinging before adding yours ?

**Comment by jelenadj** [comment]
Yes, I am reporting outgoing call state to the system only on one place, but from some reason linphone call state changes when I try to report "connected" state.

**Comment by ReisBenjamin** [comment]
Are you up to date with master branch ?

**Comment by jelenadj** [comment]
I am using 3.16.1 release, should I switch to master?

**Comment by ReisBenjamin** [comment]
Yes we have fixed some CallKit issues so your modification could work better on the master branch.
I suggest you checkout branch beta_3.16.2.4 which should be stable and include the fixes.

**Comment by jelenadj** [comment]
Thank you, @ReisBenjamin. It works correctly on beta_3.16.2.4 branch.
