### ISSUE TITLE
I

### ISSUE THREAD

**Issue by zziazm** [BelledonneCommunications/linphone-iphone#198]
I have set breakpoint in synchronizeAccounts method, but it does not call after I click login button.I can not find where account login. How can I code to login with my account, password and domain?

**Comment by ReisBenjamin** [comment]
The function of login are in AssistantView.m
Synchronize accounts is a function called by the settings to update the info of the settings.

**Comment by zziazm** [comment]
when I click login button， it does not call synchronizeAccounts method but it shows register。How does it  register successfully？

**Comment by ReisBenjamin** [comment]
Because synchronizeAccounts is not called when a user logs in but only when he changes his account settings in the app settings.
The function called when logging in are in AssistantView.m

**Comment by zziazm** [comment]
when I click login button，how it register sucessfully and what method it calls?

**Comment by ReisBenjamin** [comment]
The account is set up in configureProxyConfig and the register is done on an iteration of the app core.
