### ISSUE TITLE
why video call is not disconnecting?

### ISSUE THREAD

**Issue by saurabhs70** [BelledonneCommunications/linphone-iphone#199]
For example: Alice and bob both have on video for their app from setting  but if alice called up to bob and alice cancel the call but still call did not disconnect to bob end.
![screen shot 2017-03-03 at 10 17 55 am](https://cloud.githubusercontent.com/assets/17975720/23538822/53d44cb0-fffc-11e6-8796-abecf8757647.png)
![videocall](https://cloud.githubusercontent.com/assets/17975720/23538935/53db627e-fffd-11e6-8a09-0414bc84fa9b.png)

Note:even i have tried new app which implemented callkit, even this not working with that too.

**Comment by ReisBenjamin** [comment]
Do you see a CANCEL or a BYE sent by Alice and received by Bob in the log ?

**Comment by saurabhs70** [comment]
No for  video call,no cancel invite has been fired,but in case of audio it works like charm.

**Comment by ReisBenjamin** [comment]
Then you should take a look at what's triggered when you hit the hang-up button to see what's happening. I've tried it on my Linphone and it worked perfectly...

**Comment by saurabhs70** [comment]
But it's also not working with linphone code.

**Comment by ReisBenjamin** [comment]
Are you up to date ? I do not reproduce it on our current version even with automatically start and accept video...

**Comment by saurabhs70** [comment]
yes up to date code,i have no doubt please try at  least twice sometimes it work good but in very rarely,you would be see it.

**Comment by saurabhs70** [comment]
hi ReisBenjamin i'm talking about case,when Bob called Alice but while ongoing call Bob canceled it means  for being time  Alice still did not pick call,before of that call has been disconnected by Bob. so call has been disconnected from Bob's end but Alice's end it's didn't disconnect yet.

**Comment by ReisBenjamin** [comment]
Yes I understand but still I receive the CANCEL all the time... I'll keep trying to reproduce.

**Comment by ReisBenjamin** [comment]
Unable to reproduce.
PLease reopen if stiil happening and provide logs.

Thanks
