### ISSUE TITLE
Experiencing App Crashes 

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#20]
Please see the below log for crashes:

CRASH 1:

Crashed: com.apple.root.default-qos
SIGABRT ABORT 0x0000000196553270
 raw
0	libsystem_kernel.dylib	
__pthread_kill + 8
16	AddressBook	
ABRecordCopyValue + 124
17

FastAddressBook.m line 216
-[FastAddressBook loadData]
18

FastAddressBook.m line 177
__25-[FastAddressBook reload]_block_invoke
19	AddressBook	
__37-[ABTCC accessRequestWithCompletion:]_block_invoke + 48
25	libsystem_pthread.dylib	
start_wqthread + 4

*******************************************************************************************************************

CRASH 2:

12
Crashed: com.apple.root.default-qos
SIGABRT ABORT 0x0000000196553270
 raw
0	libsystem_kernel.dylib	
__pthread_kill + 8
9	CoreFoundation	
-[NSArray componentsJoinedByString:] + 480
10

FastAddressBook.m line 98
+[FastAddressBook normalizeSipURI:]
11

FastAddressBook.m line 202
-[FastAddressBook loadData]
12

FastAddressBook.m line 177
__25-[FastAddressBook reload]_block_invoke
13	AddressBook	
__37-[ABTCC accessRequestWithCompletion:]_block_invoke + 48
19	libsystem_pthread.dylib	
start_wqthread + 4

*******************************************************************************************************************

CRASH 3:

0
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000636125a8
 raw
0	libobjc.A.dylib	
objc_msgSend + 16
3	CoreFoundation	
+[NSArray arrayWithArray:] + 92
4

SettingsViewController.m line 194
-[IASKAppSettingsViewControllerEx settingsReader]
5

IASKAppSettingsViewController.m line 323
-[IASKAppSettingsViewController setHiddenKeys:animated:]
6

SettingsViewController.m line 506
-[SettingsViewController viewWillAppear:]
7	UIKit	
-[UIViewController _setViewAppearState:isAnimating:] + 516
9	UIKit	
-[UIView(Internal) _addSubview:positioned:relativeTo:] + 452
10

UICompositeViewController.m line 334
+[UICompositeViewController addSubView:view:]
11

UICompositeViewController.m line 581
-[UICompositeViewController update:tabBar:stateBar:fullscreen:]
12

UICompositeViewController.m line 595
-[UICompositeViewController changeView:]
13

PhoneMainView.m line 589
-[PhoneMainView _changeCurrentView:transition:force:]
14

PhoneMainView.m line 570
-[PhoneMainView changeCurrentView:push:]
15

UIMainBar.m line 446
-[UIMainBar onSettingsClick:]
16	UIKit	
-[UIApplication sendAction:to:from:forEvent:] + 96
25	UIKit	
UIApplicationMain + 1488
26

main.m line 24
main
27
libdyld.dylib	

*******************************************************************************************************************

CRASH 4:

0
Crashed: com.apple.main-thread
SIGABRT ABORT 0x0000000196553270
 raw
0	libsystem_kernel.dylib	
__pthread_kill + 8
25	UIKit	
-[UIView(Internal) _addSubview:positioned:relativeTo:] + 1792
26

UICompositeViewController.m line 334
+[UICompositeViewController addSubView:view:]
27

UICompositeViewController.m line 583
-[UICompositeViewController update:tabBar:stateBar:fullscreen:]
28

UICompositeViewController.m line 595
-[UICompositeViewController changeView:]
29

PhoneMainView.m line 589
-[PhoneMainView _changeCurrentView:transition:force:]
30

PhoneMainView.m line 570
-[PhoneMainView changeCurrentView:push:]
31

WizardViewController.m line 610
-[WizardViewController registrationUpdate:message:]
32

WizardViewController.m line 1030
-[WizardViewController registrationUpdateEvent:]
33	CoreFoundation	
__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
35	Foundation	
-[NSNotificationCenter postNotificationName:object:userInfo:] + 72
36

LinphoneManager.m line 864
-[LinphoneManager onRegister:cfg:state:message:]
37

linphone_core_notify_registration_state_changed + 1914220
38

linphone_proxy_config_set_state + 1885948
39

register_success + 1732516
40

belle_sip_client_transaction_notify_response + 102536
41

nict_set_completed + 76728
42

belle_sip_provider_dispatch_message + 78940
43

belle_sip_channel_process_stream + 4297519204
44

belle_sip_channel_process_data + 4297510724
45

on_udp_data + 110640
46

belle_sip_main_loop_iterate + 4297476556
47

belle_sip_main_loop_sleep + 4297477036
48

sal_iterate + 1679980
49

linphone_core_iterate + 1815020
50

LinphoneManager.m line 1367
-[LinphoneManager iterate]
51	Foundation	
__NSFireTimer + 92
57	UIKit	
UIApplicationMain + 1488
58

main.m line 24
main
59
libdyld.dylib	
start + 4

**Comment by bagage** [comment]
Hi,

Thanks for reporting these crashes. However row stacktraces are of little help without context nor logs, so we won't be able to process them in current state.

Could you create a separate issue for each issue with:

* what were you doing, what did you expect, what happened
* application logs
* how to reproduce the crash, if possible
* obviously, the provided stacktrace (properly formatted would be better)

Thanks.
