### ISSUE TITLE
Can't dial numbers starting with 000387...

### ISSUE THREAD

**Issue by ralfbergs** [BelledonneCommunications/linphone-iphone#201]
When I try to dial a number starting with `000387` (as used by my SIP provider dus.net, see [here](https://dus.net/de/sip-infos), tab "Service Codes"), Linphone replaces the leading `000` by `+0`, and dialing fails (because my provider doesn't recognize the phone number in this format).

I'm aware that there is a setting in `Settings` -> (My Account) -> `Substitute + in phone numbers`, but changing this doesn't help.

I'm using the current version of Linphone as of today, `3.16.2`.

**Comment by ReisBenjamin** [comment]
Issue has been fixed in commit 4e738651ca3206be5cbe7b892d38a43234930308
It was after the release.

Best regards

**Comment by ralfbergs** [comment]
Thanks a lot.

Any idea when a new build incorporating this fix will be released?
