### ISSUE TITLE
Are there plans to stop using the deprecated linphone_core_new_with_config()?

### ISSUE THREAD

**Issue by nceruchalu** [BelledonneCommunications/linphone-iphone#202]
Hello there,

First of all, thanks so much for this great codebase. It really helps with understanding how linphone core is to be used.

I noticed you've updated the `LinphoneManager` and other classes to stop using deprecated methods for terminating calls. However you still seem to be using `linphone_core_new_with_config()` which is deprecated in favor of `linphone_factory_create_core_with_config()`.

Using this new method requires using a `LinphoneCoreCbs` object to hold callbacks, but it seems there's no method for setting the `global_state_changed` callback on the object and that callback is required as it's currently being used by LinphoneManager to execute `[self finishCoreConfiguration]`

Just wondering if there are any plans around this (really small 😄) issue.

**Comment by jelenadj** [comment]
+1

**Comment by ReisBenjamin** [comment]
done in commit ee9585d722614e948de60b7fabf920854515fc34
