### ISSUE TITLE
H263 Codec enable for Linphone SDK iOS

### ISSUE THREAD

**Issue by Madhuraju** [BelledonneCommunications/linphone-iphone#203]
Hi ReisBenjamin,
As per our previous discussion "**This issue has been closed, so please reopen one for future questions. Try to recompile your SDK with that command ./prepare.py -c && ./prepare.py -DENABLE_H263=ON -DENABLE_H263P=ON -DENABLE_MPEG4=ON -DENABLE_FFMPEG=ON -DENABLE_NON_FREE_CODECS=ON && make Your app should have H263 supports and H263 available in video settings.**"

Can you please assist me how to recompile SDK with suggested command, currently I’m using the version of Linphone is (LINPHONE_IOS_VERSION "2fb5090”). When I searched in online the updated version is showing as ( LINPHONE_IOS_VERSION "b8e1f23”).

Is there any modifications in new version compared to older?
Is H263 Codec available in updated Linphone sdk?

**Comment by ReisBenjamin** [comment]
Hello,

H263 is no longer supported in Linphone Iphone, the liblinphone supports H263 but not the IOS app.
If you want to support it, you'll need to implement it yourself.

**Comment by Madhuraju** [comment]
Hello @ReisBenjamin,
Can you please confirm me H263 Codec doesn't support for iPhone application?, If I need to implement Can you provide the procedure  for liblinphone that supports H263.
