### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ofuron** [BelledonneCommunications/linphone-iphone#207]
I experienced a crash after stopping the linphonecore.

********* Crash dump: **********
Build fingerprint: 'google/sailfish/sailfish:7.1.1/NOF26V/3636322:user/release-keys'
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xa4
Stack frame #00 pc 00399d60  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine emit at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/externals/antlr3/runtime/C/src/antlr3lexer.c:651
Stack frame #01 pc 0039a354  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine nextTokenStr at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/externals/antlr3/runtime/C/src/antlr3lexer.c:292
Stack frame #02 pc 00399b08  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine nextToken at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/externals/antlr3/runtime/C/src/antlr3lexer.c:336
Stack frame #03 pc 0039c7e0  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine fillBuffer at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/externals/antlr3/runtime/C/src/antlr3tokenstream.c:964
Stack frame #04 pc 0039c344  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine tokLT at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/externals/antlr3/runtime/C/src/antlr3tokenstream.c:367
Stack frame #05 pc 0039c6bc  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine _LA at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/externals/antlr3/runtime/C/src/antlr3tokenstream.c:807
Stack frame #06 pc 00397ddc  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (antlr3dfapredict+148): Routine antlr3dfapredict at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/externals/antlr3/runtime/C/src/antlr3cyclicdfa.c:129
Stack frame #07 pc 0016fa14  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine message_raw at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/WORK/android-armv7/Build/bellesip/src/grammars/belle_sip_messageParser.c:166730
Stack frame #08 pc 0013707c  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_message_parse_raw+84): Routine belle_sip_message_parse_raw at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/belle-sip/src/message.c:133
Stack frame #09 pc 0011e0f0  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_channel_parse_stream+1560): Routine belle_sip_channel_parse_stream at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/belle-sip/src/channel.c:579
Stack frame #10 pc 001204a0  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine belle_sip_channel_process_stream at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/belle-sip/src/channel.c:615
Stack frame #11 pc 0011ed7c  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_channel_process_data+364): Routine belle_sip_channel_process_read_data at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/belle-sip/src/channel.c:666
Stack frame #12 pc 00115984  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_main_loop_run+1188): Routine belle_sip_main_loop_iterate at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/belle-sip/src/belle_sip_loop.c:559
Stack frame #13 pc 00115b00  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_main_loop_sleep+64): Routine belle_sip_main_loop_sleep at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/belle-sip/src/belle_sip_loop.c:626
Stack frame #14 pc 000a06c4  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (sal_iterate+12): Routine sal_iterate at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/linphone/coreapi/bellesip_sal/sal_impl.c:838
Stack frame #15 pc 000d4e50  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (sip_config_uninit+276): Routine sip_config_uninit at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/linphone/coreapi/linphonecore.c:5287
Stack frame #16 pc 000d6c68  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so: Routine linphone_core_uninit at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/linphone/coreapi/linphonecore.c:5504
Stack frame #17 pc 001163b8  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (belle_sip_object_delete+228): Routine belle_sip_object_delete at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/belle-sip/src/belle_sip_object.c:232 (discriminator 1)
Stack frame #18 pc 000f6238  /data/app/myapp/lib/arm/liblinphone-armeabi-v7a.so (Java_org_linphone_core_LinphoneCoreImpl_delete+44): Routine Java_org_linphone_core_LinphoneCoreImpl_delete at /Users/ofuron/Documents/VoIP/Benchmark/linphone/linphone-android/submodules/linphone/coreapi/linphonecore_jni.cc:1659
Stack frame #19 pc 01716d07  /data/app/myapp/oat/arm/base.odex (offset 0x1546000)

**Comment by ReisBenjamin** [comment]
Hello,

This is the linphone-iphone repo for Linphone on IOS, you should open an issue on the linphone Android repo : https://github.com/BelledonneCommunications/linphone-android/issues

Regards,
Benjamin
