### ISSUE TITLE
Dial pad is truncating the country code

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#208]
here is an example of what is just did, i dialed 0014420762xxxx2, what is sent to server is +120762xxxx2.  Where 144 is country code.

I Dialed another number of different country. 00923154747xxx but sent to server was +3154747xxx where 92 is country code.

I want to ask is there any settings for truncating the code . Which I can switch on/of. I am using 3.15 version. Or there is any quick fix for this version.

NOTE:    MY ANDROID app is working fine. So there is not any issue with server side.

**Comment by ReisBenjamin** [comment]
Hello,

We have done some fixes around that issue since 3.15 please update your app and tell me if the issue still occurs.

**Comment by TheEngineerz** [comment]
Yes @ReisBenjamin  thanks for the reply I have read all the Ans and you have mentioned that this issue was committed. But as far I can see you have not released the version which includes that's changes.

Should I used the master branch is it stable ?

Or I will suggest you to release the new version so we can access the latest code.wth stability.
In 1-2 days I am plannning to upgrade my exis app.
 Thanks

**Comment by ReisBenjamin** [comment]
Hi,

We have no plan to release a new version in the next few days so I suggest you use our master branch.

**Comment by TheEngineerz** [comment]
Alright thanks @ReisBenjamin  for now i am going to use master branch .again thank yo for the great library
