### ISSUE TITLE
How to activate voicemail access ?

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#209]
I want to have a little button at top of navigation bar right after REGISTERED . Where I can access all of my voice mail. Please let me know if this feature is already implemented or I have to design it my self. 

If I have to design it my self then is there any steps you want to share ? So it would be easy for me to implement keeping the existing functionality as it is?

**Comment by ReisBenjamin** [comment]
Hello, You can access your voicemail by clicking on the "1" button for a long time.
You'll first need to configure your voicemail.

Regards

**Comment by TheEngineerz** [comment]
To configure the Voicemail you mean i must have the Voice mail URI in my settings right? (which in my case is +97)

Ok but i want to create another button on top right navigation bar to get all voicemails . My question is Is there any way I can be notified if there is a new voice mail  available because i just want to change color of that button.

(By the way i am thinking to create a Push notification service for this)

**Comment by ReisBenjamin** [comment]
Yes that's what I meant.

As for your question I think it's possible but I don't know how. You'll have to implement your own signal.
