### ISSUE TITLE
A bug when you try to log in with an external sip address.

### ISSUE THREAD

**Issue by lyuraurora** [BelledonneCommunications/linphone-iphone#21]
If you try to log in with an external sip address, even all the information are right and you fill the proxy already, you will receive a "Registration failure : unauthorized". And after you cancel it and switch to setting view to update the registration, all the things work again.

**Comment by bagage** [comment]
I do not reproduce the problem - without logs I can tell if it is a problem with your SIP provider, in liblinphone, or in linphone iphone application. Could you try again from scratch (uninstall & reinstall) to confirm that you still encounter the problem, grab logs (Settings -> Advanced -> Debug = Yes) and possibly provide me steps to reproduce?

**Comment by bagage** [comment]
Please reopen if still present.
