### ISSUE TITLE
x86_64 build Build Error

### ISSUE THREAD

**Issue by babumoshai-ankush** [BelledonneCommunications/linphone-iphone#211]
Hi,

I am trying compile submodules. I follows the steps found on github. But getting error again and again. Kindly check the terminal log.

```
...
...
...
/Applications/Xcode_8.2.1.app/Contents/Developer/usr/bin/make -C WORK/ios-x86_64/cmake/
Scanning dependencies of target EP_bctoolbox
[  0%] Creating directories for 'EP_bctoolbox'
[  1%] No download step for 'EP_bctoolbox'
[  1%] No patch step for 'EP_bctoolbox'
[  2%] No update step for 'EP_bctoolbox'
[  3%] Performing configure step for 'EP_bctoolbox'
loading initial cache file /Users/admin/Desktop/LINPHONE_RAW/linphone-iphone/WORK/ios-x86_64//tmp/EP_bctoolbox/EP_bctoolbox-cache-Release.cmake
-- Using sysroot path: /Applications/Xcode_8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk
-- Using sdk version: 10.2
-- Using sysroot path: /Applications/Xcode_8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk
-- Using sdk version: 10.2
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode_8.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode_8.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode_8.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode_8.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found suitable version "2.10.1 (Apple Git-78)", minimum required is "1.7.10") 
-- Setting install rpath to /Users/admin/Desktop/LINPHONE_RAW/linphone-iphone/liblinphone-sdk/x86_64-apple-darwin.ios/lib
-- Could NOT find MbedTLS (missing:  MBEDTLS_INCLUDE_DIRS MBEDTLS_LIBRARIES) 
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find PolarSSL (missing: POLARSSL_INCLUDE_DIRS POLARSSL_LIBRARIES
  HAVE_POLARSSL_SSL_H)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPolarSSL.cmake:65 (find_package_handle_standard_args)
  CMakeLists.txt:74 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/admin/Desktop/LINPHONE_RAW/linphone-iphone/WORK/ios-x86_64/Build/bctoolbox/CMakeFiles/CMakeOutput.log".
make[3]: *** [/Users/admin/Desktop/LINPHONE_RAW/linphone-iphone/WORK/ios-x86_64/Stamp/EP_bctoolbox/EP_bctoolbox-configure] Error 1
make[2]: *** [CMakeFiles/EP_bctoolbox.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [x86_64-build] Error 2
Admins-MacBook-Pro:linphone-iphone admin$ 
```

Help me please.

Thanks in advance.

**Comment by ReisBenjamin** [comment]
The error said it couldn't find polarSSL. you need to make sure it's installed on your computer and precise its location in environment variable.

Regards
Benjamin

**Comment by babumoshai-ankush** [comment]
Its solved. Thanks a lot!

**Comment by Rushabh5** [comment]
Hello @ReisBenjamin 

Could you please help with this error.

Rushabh-Mac-mini:build apple$ cmake ..
-- Building LinphoneSDK Version : [4.3.0-alpha.27+d5b0780]
-- Enabled features:
 * Unit tests, Enable unit tests support with BCUnit library.
 * Tools, Enable tools binary compilation.
 * Xml2, Enable bc version of libxml2
 * Sqlite, Enable bc version of sqlite3
 * Zlib, Enable bc version of zlib
 * Mbedtls, Crypto stack implementation based on mbeddtls.
 * GPL third parties, Usage of GPL third-party code (FFmpeg and x264).
 * SRTP, SRTP media encryption support.
 * ZRTP, ZRTP media encryption support.
 * WebRTC AEC, WebRTC echo canceller support.
 * G729, G.729 audio encoding/decoding support.
 * GSM, GSM audio encoding/decoding support.
 * OPUS, OPUS audio encoding/decoding support.
 * Silk, Silk audio encoding/decoding support.
 * Speex, Speex audio encoding/decoding support.
 * BV16, BroadVoice 16 audio encoding/decoding support.
 * Video, Ability to capture and display video.
 * jpeg, JPEG support with libjpeg-turbo.
 * MKV, MKV playing and recording support.
 * VPX, VPX (VP8) video encoding/decoding support.
 * CXX wrapper, Build the C++ wrapper for Liblinphone.
 * LIME X3DH, Enable Linphone IM Encryption version 2 support in  Liblinphone.
 * VCARD, Enable vCard 4 support in Linphone and Liblinphone.
 * Assets, Enable packaging of assets (ringtones) when building the SDK.
 * Advanced IM, Enable advanced instant messaging such as group chat.
 * DB Storage, Enable the database storage.

-- Disabled features:
 * Debug logs, Enable debug level logs in libinphone and mediastreamer2.
 * Doc, Enable documentation generation with Doxygen and Sphinx
 * unmaintained, Allow inclusion of unmaintained code in the build.
 * Soci mysql, Enable mysql support of SOCI
 * Polarssl, Crypto stack implementation based on polarssl.
 * Tunnel, Secure tunnel for SIP/RTP (require license).
 * RTP Map always in SDP, Always include rtpmap in SDP.
 * mDNS, Multicast DNS support
 * Non free codecs, Allow inclusion of non-free codecs in the build.
 * WebRTC AECM, WebRTC echo canceller for mobile support.
 * WASAPI, Windows Audio Session API (WASAPI) sound card support.
 * AMRNB, AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB, AMR wide-band audio encoding/decoding support (require license).
 * Codec2, Codec2 audio encoding/decoding support.
 * G729B CNG, G.729 annex B confort noise generation.
 * G726, G.726 audio encoding/decoding support.
 * iLBC, iLBC audio encoding/decoding support.
 * ISAC, ISAC audio encoding/decoding support.
 * WebRTC VAD, WebRTC voice activation detector support.
 * V4L, Ability to capture and display video using libv4l2 .
 * qrcode, QRCode support with zxing.
 * FFmpeg, Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * H263, H263 video encoding/decoding support (require license).
 * H263p, H263+ video encoding/decoding support (require license).
 * MPEG4, MPEG4 video encoding/decoding support (require license).
 * OpenH264, H.264 video encoding/decoding support with the openh264 library (require license).
 * X264, H.264 video encoding support with the x264 library (require license).
 * AAudio, AAudio Android sound card for Android 8+.
 * Camera2, Android capture filter using Camera2 API for Android 8+
 * PCAP, PCAP support.
 * GTK UI, Enable the GTK user interface of Linphone.
 * CSharp wrapper, Build the C# wrapper from Liblinphone.
 * Swift wrapper, Build the Swift wrapper from Liblinphone.
 * Jazzy doc, Build the Swift doc from Liblinphone.
 * Java wrapper, Build the Java wrapper from Liblinphone.
 * LIME, Enable Linphone IM Encryption support in  Liblinphone.
 * NLS, Enable internationalization of Linphone and Liblinphone.
 * Update Check, Enable update check.
 * Relative prefix, liblinphone and mediastreamer will look for their respective ressources relatively to their location.

CMake Error at cmake/LinphoneSdkUtils.cmake:211 (message):
  'pystache' python module not found
Call Stack (most recent call first):
  cmake/LinphoneSdkCheckBuildToolsCommon.cmake:32 (linphone_sdk_check_python_module_is_installed)
  cmake/LinphoneSdkCheckBuildToolsIOS.cmake:23 (include)
  cmake/LinphoneSdkPlatformIOS.cmake:24 (include)
  CMakeLists.txt:72 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/apple/Desktop/linphone-sdk/build/CMakeFiles/CMakeOutput.log".

Below is the log which CMakeOutput is shown in that file.
**The system is: Darwin - 18.5.0 - x86_64**

Awaiting for your reply!

Thanks
