### ISSUE TITLE
CallKit End and Accept media issue

### ISSUE THREAD

**Issue by Artimuss** [BelledonneCommunications/linphone-iphone#212]
Hi !

We have a media problem on end and accept. When we are in GSM call and we receive a call in our app, if we choose "Hold and accept" it's ok but if we choose "End and accept", we haven't got any media...

EDIT:
@ReisBenjamin We have updated linphone this morning but the problem is still here. We reset the audio session in `didActivateAudioSession` method but it doesn't change anything.
I don't understand why we have media problem when we do a "End and accept" but not when we do a "Hold and accept" ?

**Comment by ReisBenjamin** [comment]
Hello,

What you need to do is only start/accept/resume a call in the didActivateAudioSession Callback.
This is the safe way to be sure that callkit won't stop your media stream by activating the audio session.
This could also happen on a Hold & Accept (and even in an invite) but thanks to timing it doesn't.

Regards,
Benjamin

**Comment by Artimuss** [comment]
Alright but provider's methods are called by CallKit so we can't call them in the `didActivateSessionAudio` and in this method we don't have information about `CXAnswerCallAction` or `CXStartCallAction`

**Comment by ReisBenjamin** [comment]
What we do in Linphone-iphone is set a variable (currentCall) in the startCallAction so that we can access it in the didActivateAudioSession method.
You can see in details how we do it in the source code of ProviderDelegate.m

Regards,
Benjamin

**Comment by Artimuss** [comment]
I used the dev_callkit branch code for ProviderDelegate... With the master code, it works! Thanks a lot.

Regards,
Arthur

**Comment by ReisBenjamin** [comment]
Glad to hear it !
