### ISSUE TITLE
Linphone-iphone is crashes sometimes

### ISSUE THREAD

**Issue by levent2661** [BelledonneCommunications/linphone-iphone#213]
Hello

We have a problem for linphone. App is crashes sometimes. The result of crashes are **belle_sip_object_unref**, **bctbx_list_append** and **belle_sip_channel_queue_message**. What will we do to solve these error. Please hep us.

**Comment by ReisBenjamin** [comment]
Hello,

In which context do the crash happen ?
Which version of Linphone are you using ?

**Comment by levent2661** [comment]
I am using 3.16.1 version. When tapped any button on app. it is sometimes crash such as belle_sip_object_unref, bctbx_list_append and belle_sip_channel_queue_message. I don't understand why is crashes.

**Comment by ReisBenjamin** [comment]
We have fixed issue since 3.16.1 please update to 3.16.2 which is more stable. It can solve your crashes.

**Comment by levent2661** [comment]
Thank you for your response. I have a question. How do I update 3.16.1 to 3.16.2 my changes without affecting.

**Comment by ReisBenjamin** [comment]
It can be tough. If your changes are simple and atomic then you can merge our repo in your project. other wise you have to incorporate our changes manually.

Good luck with that !

**Comment by levent2661** [comment]
Thank you @ReisBenjamin
