### ISSUE TITLE
Android App crashes on pausing call

### ISSUE THREAD

**Issue by shashankkaroo** [BelledonneCommunications/linphone-iphone#214]
My android app crashes when i call 
LinphoneCall call = LinphoneManager.getLc().getCurrentCall();
LinphoneCore lc = LinphoneManager.getLc();
        		if (call != null && call.getState() != State.Paused) {
			lc.pauseCall(call);
		} else if (call != null) {
			if (call.getState() == State.Paused) {
				lc.resumeCall(call);
			}
		}
	}

I am getting a crash which says:

Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68

**Comment by ReisBenjamin** [comment]
Hello you're on the IOS repository.
Please open an issue on the Android one.

Best regards,
Benjamin
