### ISSUE TITLE
Linphone 3.16.2 iOS Xcode 8.2 compile

### ISSUE THREAD

**Issue by mmehdi** [BelledonneCommunications/linphone-iphone#215]
Hi,
I have built the code using prepare.py and make but it's not running in Xcode 8.2. I have built and run previous Linphone iOS versions so I am quite sure I didn't make any errors in Makefile. 
Is there any significant change in 3.16.2? I can see the generated `account_creator.h` doesn't have the enum `LinphoneAccountCreatorStatus`.

**Comment by ReisBenjamin** [comment]
Hello, Please pull latest commit and updtade the submodules this should solve the error.
