### ISSUE TITLE
Pushkit implementation

### ISSUE THREAD

**Issue by mmehdi** [BelledonneCommunications/linphone-iphone#216]
Hi,
I am currently using Linphone SIP accounts and have successfully compiled the Linphone iOS code. The App does not receive push notifications from Linphone server when it's in the background. I have generated my certificates (.pem) file. I can receive push notifications if I do it manually from my own server. Do I have to implement my own server side? even if I am using Linphone SIP accounts? Is there anyway Linphone can use my generated certificate on their server?

Many thanks

**Comment by ReisBenjamin** [comment]
hello,

If you use a Linphone account you just need to implement PushKit and activate push notifications in your account settings to receive push notifications.
If you use another address then you'll have to implement your own SIP service because Flexisip won't send push notification to none Linphone account.

Regards,
Benjamin

**Comment by mmehdi** [comment]
I am compiling Linphone iOS source code and using Linphone SIP account. I have activated push in the account settings but still unable to receive push notifications :(
I don't understand how the Linphone server will send push notification to my app if the code has been compiled on my machine because the server needs the `.pem file` to send push notifications.

**Comment by ReisBenjamin** [comment]
Is the pem file a VoIP services certificate ?
IT it is it should be used on the server to send push notification to a domain associated to your app bundle.
For example FlexiSIP sends push notification to com.linphone.org. If your app has a different bundle ID then you'll need a new pem on your server associated to this bundle ID

**Comment by mmehdi** [comment]
yes it's a VOIP services certificate. I see you mentioned "implement PushKit".. can I setup push notification without `.pem file`? A little bit guide how to do that would be very helpful.

thanks

**Comment by ReisBenjamin** [comment]
Your app doesn't need pem file.
The certificate is used by the SIP server. To see how to implement pushkit you can take example on our AppDelegate class.

**Comment by mmehdi** [comment]
it's not my code, I am using the Linphone iOS source code and it has the Pushkit implementation in the AppDelegate. But still not receiving push notifications.

**Comment by ReisBenjamin** [comment]
did you change the bundle ID of the app ?

**Comment by mmehdi** [comment]
yes I did to compile my code. I cannot add bundle id `com.linphone.org` in my apple developer account.

**Comment by ReisBenjamin** [comment]
In this case it's normal you do not receive push notification since we only send pushes to com.linphone.org. You'll need to implement your own SIP server with a pem file associated to your bundle ID

**Comment by mmehdi** [comment]
hmmmm ok. it would be very helpful if we can add/upload our pem file when using linphone sip service.

thank you
