### ISSUE TITLE
Callkit issue on incoming call

### ISSUE THREAD

**Issue by Artimuss** [BelledonneCommunications/linphone-iphone#217]
Hi there

When we are in a GSM call and a new call is incoming in our app, CallKit offer 3 choices : End & Accept / Decline / Hold & Accept. No problem with that.
But when we are in call with our app and a new GSM call is incoming, CallKit offers only two choices Decline / Accept. It's like CallKit doesn't understand that we have already a call in progress.

Any idea ? Thanks

**Comment by ReisBenjamin** [comment]
Did you create a CXStartCallAction when starting the call ?

**Comment by Artimuss** [comment]
Yes I did

**Comment by ReisBenjamin** [comment]
Did you set the support handling parameter of the CallKit configuration to true ?

**Comment by Artimuss** [comment]
You mean "Holding" ? And yes I did.

 Here my CXProviderConfiguration :
`- (void)config:(NSString *)to {
    LC = [LinphoneManager getLc];
    CXProviderConfiguration* config = [[CXProviderConfiguration alloc] initWithLocalizedName:to];
    config.ringtoneSound = @"ring.caf";
    config.supportsVideo = YES;
    config.iconTemplateImageData = UIImagePNGRepresentation([UIImage imageNamed:@"icon-callkit"]);
    
    NSArray* ar = @[[NSNumber numberWithInt:(int)CXHandleTypeGeneric]];
    NSSet *handleTypes = [[NSSet alloc] initWithArray:ar];
    [config setSupportedHandleTypes:handleTypes];
    config.maximumCallGroups = 2;
    config.maximumCallsPerCallGroup = 1;
    self.provider = [[CXProvider alloc] initWithConfiguration:config];
    [self.provider setDelegate:self queue:dispatch_get_main_queue()];
}`

And my reportIncomingCall method : 
`
- (void) reportIncomingCallwithUUID:(NSUUID*)uuid handle:(NSString*) handle {
    // Create update to describe the incoming call and caller
    CXCallUpdate *update = [[CXCallUpdate alloc] init];
    
    if([handle isEqualToString:@"anonymous"])
    {
        handle = NSLocalizedString(@"MASKED_NUMBER", nil);
        update.localizedCallerName = handle;
    }
    else {
        update.remoteHandle = [[CXHandle alloc] initWithType:CXHandleTypePhoneNumber value:handle];
    }
    
    update.supportsDTMF = TRUE;
    update.supportsHolding = TRUE;
    update.supportsGrouping = TRUE;
    update.supportsUngrouping = TRUE;
    update.hasVideo = NO;
    
    // Report incoming call to system
    LOGD(@"CallKit: report new incoming call");
    [self.provider reportNewIncomingCallWithUUID:uuid
                                          update:update
                                      completion:^(NSError *error) {
                                      }];
}
`

By the way, the situation I explained in my first post is ok for CallKit on Linphone app (3 options on incoming call) but if we wait during the ringtone, the call in progress in Linphone app is killed.

**Comment by Artimuss** [comment]
Nope CallKit has 3 options on GSM incoming call when we are already in call with linphone but sometimes if we do nothing, linphone call is killed

**Comment by ReisBenjamin** [comment]
It's probably a timeout

**Comment by Artimuss** [comment]
Ok

And on the problem with callkit which offers only "Refuse" and "Accept" when we are already in call with our app, any idea ?

**Comment by Starscream27** [comment]
I'm also experiencing the issue where I have only "Refuse" and "Accept". Have you managed to fix it ?
