### ISSUE TITLE
IPv6 compatibility issue with Apple review

### ISSUE THREAD

**Issue by dinnysingh** [BelledonneCommunications/linphone-iphone#218]
Hi there,

We are pushing linphone iOS app for our internal use on AppStore but they are rejecting our app over IPv6 incompatibility (Ofcourse our server only supports IPv4 IP addresses and it works super fine with it). See below:

-----
We discovered one or more bugs in your app when reviewed on iPhone running iOS 10.3 on Wi-Fi connected to an IPv6 network.

Specifically, we were unable to make a call with the provided demo accounts, as the call from the first demo account was never received by the second demo account.

Next Steps

To resolve this issue, please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify any issues, then revise and resubmit your app for review.
-----

Let us know please.

**Comment by Artimuss** [comment]
Hi,

Sometimes it's not ipv6 at all... Apple has rejected our app for the same reason but it was because we use `http` instead of `https` for our api... I don't know if it can help you but it's good to know.

Regards

**Comment by dinnysingh** [comment]
Actually they are testing calls between 2 demo users provided by us. And
ofcourse the calls are not going in IPv6 network because our server doesnt
support it. So thats where we are getting stuck.

On Mon, Apr 10, 2017 at 1:23 PM, Arthur Chambriard <notifications@github.com

**Comment by ReisBenjamin** [comment]
Hello,

It is required taht an application pushed on the App Store supports a full IPv6 network. It's an Apple requirement so even if you don't use IPv6 your app has to support it.
Best regards,
Benjamin

**Comment by dinnysingh** [comment]
The linphone app supports it.. right? We just using your app.

**Comment by ReisBenjamin** [comment]
Yes but if your server doesn't then the communication won't work and therefore the app will be rejected.

**Comment by dinnysingh** [comment]
As far as I am aware. even Whatsapp doesnt support IPv6 right now and its live (Skype does though). So why would that be?

**Comment by chitkosarvesh** [comment]
@ReisBenjamin According to this article https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16
We do not need to support the end-to-end IPv6 network yet, we can test this using a NAT64/DNS64 network. I am trying to resolve this and I've also posted a comment here : https://github.com/BelledonneCommunications/linphone-iphone/issues/220
Waiting for your response. :-)
