### ISSUE TITLE
Set port on Domain

### ISSUE THREAD

**Issue by levent2661** [BelledonneCommunications/linphone-iphone#219]
Hi,

I have a question for sip configuration. When i set sip domain with port on AssistanView such as sip.xxxxxxx.com:PortNumber. The domain with port is set proxy on settingview, but when  i want to set different proxy in my account, it is registration failed. Please help me for this issue.

**Comment by levent2661** [comment]
Will nobody answer?

**Comment by ReisBenjamin** [comment]
please try latest build and reopen if not fixed.

Thanks
