### ISSUE TITLE
Typo in linphone_reason_to_string

### ISSUE THREAD

**Issue by jakubprusa** [BelledonneCommunications/linphone-iphone#22]
Hi,

When i use `linphone_reason_to_string` with reason: `LinphoneReasonDoNotDisturb` answer is `Do not distrub` instead of `Do not disturb`.

**Comment by bagage** [comment]
Indeed, I fixed it in liblinphone (will be available in linphone-iphone in a few days, when upgrading liblinphone submodule). Thanks!
