### ISSUE TITLE
Delete log in History

### ISSUE THREAD

**Issue by levent2661** [BelledonneCommunications/linphone-iphone#221]
Hi

The call log is not deleted when select call log on history to delete. After close app and reopen it . It work correctly and don't see deleting call log.

**Comment by levent2661** [comment]
Hi,

When call number on dialer screen or contactdetail and got to history page, just see last callog on history. If don't call on contact detail and diaper page and go to history page . It is work correctly and see all callog . is this bug ?

**Comment by ReisBenjamin** [comment]
Hello,

Yes this is a bug. We are currently working on it.
Thanks for reporting it. I'll keep you posted when it's solved.

Best regards,
Benjamin

**Comment by ReisBenjamin** [comment]
fixed in commit 9edbaeb98986a1d426e6002bb8405627767006fc of 3.16.x branch
