### ISSUE TITLE
Compilation Errors on Xcode 8.X

### ISSUE THREAD

**Issue by PPPiotr** [BelledonneCommunications/linphone-iphone#222]
Hello

I cloned the repository (branch: master) followed the instructions, from readme and with problems but finally compiled the "liblinphone-sdk". But I got lot of compile errors in different Xcode 8 versions (I tried in  8.3.1, 8.2.1, 8.1). First one is:
`... /linphone-iphone/Classes/Utils/XMLRPCHelper.m:74:61: Incompatible pointer to integer conversion passing 'const char * _Nullable' to parameter of type 'LinphoneXmlRpcArgType' (aka 'enum _LinphoneXmlRpcArgType')`
and
`... /linphone-iphone/Classes/Utils/XMLRPCHelper.m:74:80: Incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *'`

I commented it out and new errors shows up:
`... /linphone-iphone/Classes/SettingsView.m:398:8: Use of undeclared identifier 'LinphoneAccountCreatorOK'`
So I looked for declaration of this enum `LinphoneAccountCreatorOK` and it not exists. I only found `LinphoneAccountCreatorStatus` enum that has `LinphoneAccountCreatorStatusRequestOk` and its generally very similar but not the same. There was much more compilation errors but there is no point showing more of them.

I also tried Xcode 7.3.1 but I got error:
`... /linphone-iphone/Classes/LaunchScreen.xib: The document “(null)” requires Xcode 8.0 or later.`
That tells me that this project is build on Xcode 8.X. But for me it does not compile. 

If tried to compile the "liblinphone-sdk" with command for NO GPL third parties:
`./prepare.py -DENABLE_GPL_THIRD_PARTIES=NO -DENABLE_FFMPEG=NO [other options] && make`
And later with:
`./prepare.py -c && ./prepare.py && make `

But I got the same Xcode compilation errors for both commands.

At end off compiling "liblinphone-sdk" I got this:
`NOTE: the following libraries were STUBBED:
libopenh264
libcunit
libavcodec
libbcunit
libtunnel
libopencore-amrwb
libvo-amrwbenc
libmsbcg729
liblinphonetester
libswscale
libbv16
libswresample
libmsamr
libx264
libmsopenh264
libavutil
libbctoolbox-tester
libopencore-amrnb
libmsx264`
Maybe it will point someone on, what is wrong in my situation.

On other hand I firstly tried to use the downloaded sdk [http://linphone.org/technical-corner/liblinphone/downloads](url) both for branch "master" and "3.16.x" but i got:
`... /linphone-iphone-master/Classes/LinphoneAppDelegate.m:120:6: Implicit declaration of function 'linphone_call_accept' is invalid in C99` 
But `LinphoneAccountCreatorStatus` enum that have `LinphoneAccountCreatorOK` existed. 
So it seems that I have done something wrong when compiling the "liblinphone-sdk". But what?

**Comment by ReisBenjamin** [comment]
Hello,
We are in a middle of a big API change for our account creator.
We suggest not to use our master branch to build SDK but rather use the 3.16.2 tag that corresponds to our latest release.
Regards

**Comment by PPPiotr** [comment]
I checkout this branch, compiled SDK, there was one compilation error in Xcode
`#import "linphoneAppDelegate.h"` in `LinphoneAppDelegate.m`
"linphoneAppDelegate" needed to start with capital letter. I fixed it, it was the only error (except changing development team of course).  It finally compiled and is running. Thanks.
