### ISSUE TITLE
Import static library error!

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#225]
In Xcode I created a static library xcode project name "SipUALibrary" and import only linphonecore to test starting linphonecore with my own class and I build for universal library that support all architecture (armv7 armv7s x86_64 i386 arm64) after that I created a new Xcode single view application project and using my static library. But I got an error "Apple Mach-O Linker Error". I tried to fix this with many solutions but I got the same error.
Please help me. This is my testing project : https://drive.google.com/open?id=0B4gtgiY3w5xyOF9NWFFYMktCSFk

**Comment by ReisBenjamin** [comment]
We changed the build to support frameworks instead of static libs.

PLease try latest commit and reopen if not fixeD.

Regards
