### ISSUE TITLE
Video is not establishing in TCP mode

### ISSUE THREAD

**Issue by babumoshai-ankush** [BelledonneCommunications/linphone-iphone#226]
Hi,
In old SDK (mid 2015) when I set transport to TCP, call coming in foreground & background mode from remote server. But somehow the video is not establishing for both scenario. But when I set transport to UDP, video call establishing perfectly when the app is in foreground mode but didn't get notification in background mode. 
Can you help me please.
Thanks in advance!

Regards,
Ankush

**Comment by ReisBenjamin** [comment]
Hello,

try to update to a more recent SDK and reopen the issue if the problem still occurs.

Thanks
