### ISSUE TITLE
Value Conversion Issue (Compile time Error)

### ISSUE THREAD

**Issue by SoniaKhan** [BelledonneCommunications/linphone-iphone#227]
I have followed all the ReadMe document and compiled sucsessfully the Linphone-SDK.
but as i compiled the linphone project through Xcode as instructred at ReadMe, i got two error 
which is

1) /linphone-iphone/Classes/Utils/XMLRPCHelper.m:74:61: Incompatible pointer to integer conversion passing 'const char * _Nullable' to parameter of type 'LinphoneXmlRpcArgType' (aka 'enum _LinphoneXmlRpcArgType')

2)/linphone-iphone/Classes/Utils/XMLRPCHelper.m:74:80: Incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *'

i am looking for your help or guidence to reslove this issue.

Regards
![linphone error](https://cloud.githubusercontent.com/assets/27810053/25227416/08d8d6d0-25e6-11e7-8116-da5b053eec71.png)

**Comment by ReisBenjamin** [comment]
Hello this has been fixed in commit a522dcc41fbef45aff313ea848e4d568a1dd3599
If you don't want to cherry-pick this commit you can just inverse the arguments of the methods : 
linphone_xml_rpc_new(LinphoneXmlrpcArgString, method.UTF8String);

Best regards,
Benjamin
