### ISSUE TITLE
Can't prepare older version

### ISSUE THREAD

**Issue by f15radar** [BelledonneCommunications/linphone-iphone#228]
I was trying to compile the latest, but I have a lot of issues.  I checked the issues and found out I needed to use the older release.  So I downloaded the zip file of the 3.16.2 and tried to prepare it, however, I get the following error:

./prepare.py 
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive

I suspect just downloading the zip file is not all I need to do.  If I clone the latest, prepare works great, I just get a lot of compile issues in Xcode, so I want to start with 3.16.2.  What am I doing wrong?

**Comment by ReisBenjamin** [comment]
You do not need to prepare the ZIP file it is precompiled. You just need to unzip it and name the folder liblinphone-sdk.

**Comment by f15radar** [comment]
Now I am getting this error

error: /Users/xxxxxxx/Downloads/liblinphone-sdk/liblinphone-sdk/apple-darwin/share/linphone/rootca.pem: No such file or directory

**Comment by ReisBenjamin** [comment]
Okay let's try another  method :
delete the liblinphone-sdk folder. Then do :
git checkout 3.16.x
git pull
git submodule update --init --recursive

./prepare.py -c
./prepare.py
make

This is our stabilization branch for our next release and it builds well.

**Comment by f15radar** [comment]
I'm sorry.  I am new to GitHub.  In the checkout, what do I use for the URL?

**Comment by ReisBenjamin** [comment]
Did you clone the linphone-iphone repo ?

**Comment by f15radar** [comment]
Ok, Thanks for your help.  I finally got it compiled.
