### ISSUE TITLE
Determinate proxy / local network call

### ISSUE THREAD

**Issue by jakubprusa** [BelledonneCommunications/linphone-iphone#23]
Hi, 

I've a question, how to determinate if incoming call is from local network or over connected proxy. I tried to look what is inside LinphoneCall and LinphoneCallParams and I can't find nothing useful for my problem.

**Comment by bagage** [comment]
This is not specific to linphone iphone, so please use developers mailing list instead or ask on [linphone](https://github.com/BelledonneCommunications/linphone/) repository instead. Thanks.
