### ISSUE TITLE
Simultaneous multiple SIP video streams available?

### ISSUE THREAD

**Issue by sree127** [BelledonneCommunications/linphone-iphone#230]
I was wondering if linphone supported multiple video streams from the same controller? 

I have 2 Video Door Phones and would like to stream both the phones simultaneously. Is there a support for that in linphone or which would be the best way to achieve that?

Thanks a lot in advance.

@ReisBenjamin

**Comment by ReisBenjamin** [comment]
Hello,

No the liblinphone doesn't support this for now.
