### ISSUE TITLE
IPv6 on an older version.

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#231]
Hi,

I am using an older Linephone SDK version which was before June 16, 2016. Can you please tell me how can I enable iPV6 on that SDK without upgrading to the latest release.

@bagage Please help me on this.

**Comment by ReisBenjamin** [comment]
Hello,

linphone_core_enable_ipv6(LinphoneCore *lc, bool_t val);
with val at TRUE when you start your application and then never set it to false.

Regards
