### ISSUE TITLE
No video during call

### ISSUE THREAD

**Issue by SoniaKhan** [BelledonneCommunications/linphone-iphone#233]
hi 

I have compiled linphone-sdk then compiled Xcode project.
I have installed application in my iphone and successfully configured it with server. Now when from another iphone I am unable to get video call if the application is running in background.
If I open the application I get the call successfully.
I am not able to figure how to fix this.

**Comment by ReisBenjamin** [comment]
Hello,

Do you use sip.linphone.org or a custom sip service ?

**Comment by SoniaKhan** [comment]
custom server

**Comment by SoniaKhan** [comment]
its working f9 with X-Lite  for audio and video

ReisBenjamin please help me.

**Comment by SoniaKhan** [comment]
i can sleep with u 2night please fix the problem, i ll fix your cock.
