### ISSUE TITLE
./prepare.py won't run

### ISSUE THREAD

**Issue by gabrielvincent** [BelledonneCommunications/linphone-iphone#235]
The error I get is 

```
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive
```

I tried runing `git submodule sync && git submodule update --init --recursive` but still no luck.
I cloned the repository and followed every step, but I can't seem to get it to work.

**Comment by ReisBenjamin** [comment]
do you have a cmake-builder submodule in your submodules directory ?

**Comment by gabrielvincent** [comment]
Yes. I fixed this issue by  cloning the repository again. Turns out I was using `sudo`  carelessly, so a lot of things that should happen wasn't due to permissions. Thanks for the reply!

**Comment by ReisBenjamin** [comment]
Ok then i'll close this issue.
Glad to hear it's solved
