### ISSUE TITLE
--disable-vp9 option brakes make

### ISSUE THREAD

**Issue by gabrielvincent** [BelledonneCommunications/linphone-iphone#236]
`./prepare.py` runs fine, but the `make` command always fails. 

```
Unknown option "--disable-vp9".
See /Users/[my_username]/Projects/linphone-iphone/submodules/externals/libvpx/configure --help for available options.
make[3]: *** [/Users/[my_username]/Projects/linphone-iphone/WORK/ios-x86_64/Stamp/EP_vpx/EP_vpx-configure] Error 1
make[2]: *** [CMakeFiles/EP_vpx.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [x86_64-build] Error 2
```

**Comment by ReisBenjamin** [comment]
Are your submodules up to date with your code ?

**Comment by gabrielvincent** [comment]
How can I check that?

**Comment by ReisBenjamin** [comment]
git submodule update --recursive --init
Did you pass any option to the prepare.py script ?

**Comment by gabrielvincent** [comment]
Yes, I did `git submodule update --recursive --init` multiple times.
I ran `prepare.py` like this:

`./prepare.py -c && ./prepare.py && make`

**Comment by gabrielvincent** [comment]
I don't know what I did, but now it builds. I cloned linphone-iphone all over again and it works now.
