### ISSUE TITLE
Error when archiving

### ISSUE THREAD

**Issue by afriedmanGlacier** [BelledonneCommunications/linphone-iphone#237]
On a fresh version of Linphone cloned from github, I followed the steps to prepare and make the project. I can build it and run it on my phone, but I cannot archive it. I did not have this problem with older versions.

When I try to archive, I receive an "Apple Mach-O linker (Id) Error"

Anyone else seeing this behavior? I don't think I changed anything in my environment since the last time I did this.

**Comment by ReisBenjamin** [comment]
Hello,
try disabling bitcode in your xcode project this should do the trick

**Comment by afriedmanGlacier** [comment]
That worked, thanks @ReisBenjamin
