### ISSUE TITLE
does GPL reject by Apple

### ISSUE THREAD

**Issue by zaferaydn** [BelledonneCommunications/linphone-iphone#238]
Hi there;
Before I start downloading and testing **linphone**, I read some comments in the internet. People says that **linphone** and some other open-source SIP libraries have `GPL` license and Apple is rejecting `GPL` licenced libraries.
Is it true? Can I edit **linphone** project and distribute as my own application in Apple Store for free?
Thanks.

**Comment by demanuel** [comment]
GPL clashes with apple's licensing terms.
Please check: http://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement

I don't know much about licensing, but i hope that can point you in the right direction.
