### ISSUE TITLE
Crash when app is running in background

### ISSUE THREAD

**Issue by AdilSoomro** [BelledonneCommunications/linphone-iphone#24]
We're experiencing a crash when app is in background for few minutes, its frequently reproducible on iOS 8 and 9. Any pointer or help would be appreciated.

We've background mode enabled
we're using tcp transport. 

```
Thread : Crashed: com.apple.main-thread
0  PhoneApp                  0xc86f6c belle_sip_source_uninit + 13135724
1  PhoneApp                  0xc8df59 channel_invoke_state_listener + 13164377
2  PhoneApp                  0xc8ee01 channel_inactive_timeout + 13168129
3  PhoneApp                  0xc8756f belle_sip_main_loop_iterate + 13137263
4  PhoneApp                  0xc876db belle_sip_main_loop_sleep + 13137627
5  PhoneApp                  0xc4d913 sal_iterate + 12900627
6  PhoneApp                  0xc64fd5 linphone_core_iterate + 12996565
7  PhoneApp                  0x885247 -[LinphoneManager iterate] + 8933959
8  Foundation                     0x2513b365 __NSFireTimer + 64
9  CoreFoundation                 0x2432b38f __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 14
10 CoreFoundation                 0x2432afc1 __CFRunLoopDoTimer + 936
11 CoreFoundation                 0x24328e0d __CFRunLoopRun + 1484
12 CoreFoundation                 0x2427c119 CFRunLoopRunSpecific + 520
13 CoreFoundation                 0x2427bf05 CFRunLoopRunInMode + 108
14 GraphicsServices               0x2d402ac9 GSEventRunModal + 160
15 UIKit                          0x284bef15 UIApplicationMain + 144
16 PhoneApp                  0x17d77 main (main.m:17)
17 libdyld.dylib                  0x35f95873 start + 2
```

**Comment by bagage** [comment]
Do you reproduce using linphone iphone? I won't be able to help you otherwise.

**Comment by GrahamBriggs** [comment]
I can confirm that I am experiencing something similar, except I would call it a lockup and not a crash.  
I have observed this with latest Linphone from the iPhone store (December  21 2015).  I have observed the same thing using a version built from the source code pulled two weeks ago.

Here are the symptoms

Using UDP works fine. Except of course it will not answer calls in the background.

Using TCP, usually works fine on startup.  It will register and can make calls.  However, the following steps will reproduce a lockup about 50% of the time:

Place the app in the background, then place a call to the app.  Answer the call from the notification and it will connect and you have two way audio on the call.  However, the call timer will be stuck at either 0:00 or 0:01, and all of the UI is unresponsive.  You have to kill the program and restart it.

Another way to reproduce this lockup (about 1 in 10 trials):  

Start up Linphone (using TCP mode), it registers and you can make a few calls.  Now put linphone in the background for a few minutes.  Now start it up again and try to make a call.  The call will connect and you can hear the conversation, but the call timer is not ticking and all the UI is unresponsive.

I have observed this behavior on iPhone 5c running iOS 8 and 6 plus running iOS 9.

I am new to linphone development, so if you would like me to pull some relevant debug logs, please point me to instructions on how to do so and I will try to reproduce error with logging enabled.
 
Thank you for your attention, and for working on this great project.

**Comment by bagage** [comment]
Thanks for these detailled explanations @GrahamBriggs, it is much appreciated ;-). To be complete could you:

1. record iPhone screen while reproducing this bug, so that I could see if we are doing something different
2. activate logs and send them:
  1. set Settings -> Advanced -> Debug to 'On'
  2. press Clear Logs
  3. reproduce bug
  4. use "Send Logs" to send us the report. Please write something useful in the mail (eg. link to this issue).
I'll update this issue if I find anything useful.

**Comment by GrahamBriggs** [comment]
Thank you for the quick reply.

I have reproduced the lockup behavior with debug logging on.  I also took a video of another instance of the lockup.  In the second instance, I did not even need to go into background mode, it just locked up on making the first call after startup.

Both of these items were sent to you at linphone-iphone@belledonne-communications.com at approximately 10:15 PST on December 21 2015.

Thank you

**Comment by bagage** [comment]
Got them, thanks!

**Comment by bagage** [comment]
Since this is a totally unrelated error, I'll answer to you directly @GrahamBriggs

**Comment by AdilSoomro** [comment]
I tested with latest linphone iOS app and it doesn't seem to be reproducible with latest binaries. I would recommend to close this ticket.

**Comment by bagage** [comment]
Please reopen if needed then, thanks!
