### ISSUE TITLE
How to set Contact URI host part and port?

### ISSUE THREAD

**Issue by bofuliu** [BelledonneCommunications/linphone-iphone#241]
Hi all, 
```
Contact: <sip:Genius123@192.168.2.61:49207;transport=tcp>, 
 Contact URI: Genius123@192.168.2.61:49207;transport=tcp
   Contact URI Host Part: 192.168.2.61:49207
   Contact URI Host Port: 53111
```
With  the registration process, we obtain the "401 Unauthorized" from proxy server. 
In order to make the register success, we need to change the URI host and part. 
Could you help me to do it? 

Thanks a lot 

Ed

**Comment by ReisBenjamin** [comment]
You can set all that in your account settings

**Comment by bofuliu** [comment]
Hi Reis, 

Sorry, I don't understand your suggestion. 
My question is setting Contact URI that was generated by Linpone
Do you mean to set the related information of Contact URI with proxy_config or auth_info?

Thanks you for your kindly help!

ED

**Comment by ReisBenjamin** [comment]
Pl

**Comment by bofuliu** [comment]
The contact URI like "Contact URI: Genius123@192.168.2.61:49207;transport=tcp".
The Contact Host Part is "192.168.2.61:49207",  I want get/set the ip address by manual. 

thanks

**Comment by ReisBenjamin** [comment]
You can't change your ip since it's the ip of your device.
There's no available API for this
