### ISSUE TITLE
Framework errors for liblinphone, bctoolbox, mediastreamer, etc

### ISSUE THREAD

**Issue by eliburke** [BelledonneCommunications/linphone-iphone#242]
I recently merged the latest linphone / liblinphone changes and updated my project to use the liblinphone frameworks instead of static libraries. It builds and runs in the simulator and on my device, but when I attempt to archive and upload a Testflight build, it blows up with numerous validation errors,

My question is: have I missed a step in the integration / merge / build process, or are you still working on the transition from static libraries to frameworks?  

Here is a small sample (for bctoolbox only, but the same errors are repeated for liblinphone, mediastreamer, ortp, mswebrtc, etc. 

````
ERROR ITMS-90081: "This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later."

ERROR ITMS-90087: "Unsupported Architectures. The executable for MyApp.app/Frameworks/bctoolbox.framework contains unsupported architectures '[x86_64]'."

ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "MyApp.app/Frameworks/bctoolbox.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

ERROR ITMS-90360: "Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle MyApp.app/Frameworks/bctoolbox.framework is required."

ERROR ITMS-90057: "The bundle 'Payload/MyApp.app/Frameworks/bctoolbox.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString."

ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'MyApp.app/Frameworks/ortp.framework/ortp' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.\
````

**Comment by ReisBenjamin** [comment]
Hello,

No you didn't miss anythong we're still working on it. You either go back to our latest release tag 3.16.4 or wait for us to finalize this (can take some times...) or use -DENABLE_STATIC_ONLY=On in your prepare options  but you'll also need to put back all the static libs in your xcde project linked binaries

**Comment by amadeu01** [comment]
I'm still having this problem. Was it fixed?

![image](https://user-images.githubusercontent.com/11631092/41256076-f28d8734-6d9e-11e8-84a5-9a469d3f96d3.png)

**Comment by nceruchalu** [comment]
Hi @ReisBenjamin any chance you'll be able to help us out here? Also seeing the linker error about mediastreamer2 not containing bitcode.

**Comment by vaiden** [comment]
Us too. Any luck?

**Comment by m-rayanade** [comment]
Any workaround to this one?
