### ISSUE TITLE
Not build linphone in Xcode 8.3

### ISSUE THREAD

**Issue by alexzh16** [BelledonneCommunications/linphone-iphone#244]
Hello, im downloading last git version to macbook. After that,  
./prepare.py -c
./prepare.py arm64 all armv7 i386 x86_64 simulators devices -DENABLE_GPL_THIRD_PARTIES=NO -DENABLE_FFMPEG=NO
make

alle its ok, but after open in Xcode and build project, i have some error. More in screenshot. Please help.

<img width="1317" alt="snimek obrazovky 2017-06-01 v 15 14 54" src="https://cloud.githubusercontent.com/assets/13469808/26681703/53f2a556-46de-11e7-93e5-5d540c524366.png">
after comment string with this error, and start build, incoming next errors:

<img width="322" alt="snimek obrazovky 2017-06-01 v 15 14 11" src="https://cloud.githubusercontent.com/assets/13469808/26681676/3c1015ae-46de-11e7-8aa1-34c0b5e48d5f.png">

**Comment by alexzh16** [comment]
and one more:
<img width="2018" alt="snimek obrazovky 2017-06-01 v 15 28 29" src="https://cloud.githubusercontent.com/assets/13469808/26681915/05274052-46df-11e7-9ca9-95b5340cdde5.png">

**Comment by alexzh16** [comment]
Deployment target i changed from 8.0 to  8.4, than to 9.3 and 10.3, errors its same.

**Comment by ReisBenjamin** [comment]
Did run git pull then git submodule update --recursive --init before trying to compile the project ?

**Comment by ReisBenjamin** [comment]
You can remove i386 from your command line also since for ios > 8 all simulators are in x86_64

**Comment by alexzh16** [comment]
yes, im make update --recursive --init. Im delete one more all files, than one more make git clone, than git submodule update --recursive --init. and yet compile ok
