### ISSUE TITLE
Help for integration in another App

### ISSUE THREAD

**Issue by shebinkoshy** [BelledonneCommunications/linphone-iphone#245]
Kindly help for https://stackoverflow.com/questions/44253641/convert-c-submodule-included-objective-c-project-linphone-as-a-framework-or

**Comment by ReisBenjamin** [comment]
Please describe your issue here it'll be easier to follow.

Thanks

**Comment by shebinkoshy** [comment]
I solved the issues, Thanks for your support.  I am closing this.
