### ISSUE TITLE
linphone_account_creator_create_proxy_config return NULL

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#247]
I update linphone sdk today from git in my own code and I found some problems when registering a sip account.

const char *uchar = linphone_account_creator_get_username(account_creator);
const char *dchar = linphone_account_creator_get_domain(account_creator);
const char *pchar = linphone_account_creator_get_password(account_creator);

I got correct figures in those three methods but it returns NULL new_config in the last step (configureProxyConfig):
 new_config = linphone_account_creator_create_proxy_config(account_creator); (returns NULL?)

The log says: 
bel/no host found in this uri
lib/Invalid sip identity: "" <sip:>

I double checked the domain, username and the password is correct in account_creator, what did I missed?

**Comment by ReisBenjamin** [comment]
Hi,

You need to call first [self loadAssistantConfig:@"your_file.rc"]; first.
your_first.rc is an xml file with everything to configure a default proxy_config
you can find example of our xml files in our sources :
assistant_linphone_existing.rc
assistant_external_sip.rc
assistant_linphone_create.rc

**Comment by ReisBenjamin** [comment]
I gave you our obj C function but the C function you need to call is linphone_config_load_from_xml_file(LinphoneConfig *lpc, const char *filename);

**Comment by zj299792458** [comment]
@ReisBenjamin Thank you for your response.

I did call [self loadAssistantConfig:@"assistant_external_sip.rc"] in a UIView animate completion handler in the first place, and everything is ok as soon as I roll linphone-sdk back to v3.16.4 (belle sip 1.6.1).

Since you mention this, maybe the new linphone-sdk require something more in *.rc file?  Can I ask what version of SDK are you using?

I will double check it, thanks again for inspiration.

**Comment by ReisBenjamin** [comment]
Any update ?

**Comment by zj299792458** [comment]
@ReisBenjamin Thanks for helping. I don't think linphone_account_creator_create_proxy_config works anymore. I use linphone_core_create_proxy_config instead and manage proxy myself.
