### ISSUE TITLE
Issue with lime messages

### ISSUE THREAD

**Issue by alexzh16** [BelledonneCommunications/linphone-iphone#248]
Hi, im tested linphone 3.16.3-32 chat with enabled Lime encrypt in two iPhones. And if i send message from one to two clients, bekomme message "LIME warning You have received an encrypted....." Im calling to clients with zrtp, confirms codes in both sites, trying one more send message and the same... "LIME warning You have received an encrypted.....". In older versions all its ok.

**Comment by ReisBenjamin** [comment]
Hello I do not reproduce your issue.
Is there a particular scenario where the issue happens ?
Are you logged on several devices ?

**Comment by alexzh16** [comment]
so, im connecting to our sip (freeswitch) server. please see photos
![photo-2017-06-08-10-38-34_0467](https://user-images.githubusercontent.com/13469808/26923898-e1d20406-4c43-11e7-9700-d5bbb1a9ca38.PNG)
![photo-2017-06-08-10-51-10_0468](https://user-images.githubusercontent.com/13469808/26923901-e1f8251e-4c43-11e7-9516-bbefe24dbb9c.PNG)
![photo-2017-06-08-10-51-29_0469](https://user-images.githubusercontent.com/13469808/26923902-e1f81a24-4c43-11e7-905f-1528bf82da63.PNG)
![photo-2017-06-08-10-51-32_0470](https://user-images.githubusercontent.com/13469808/26923899-e1f17b2e-4c43-11e7-9382-63a43341317b.PNG)
![photo-2017-06-08-10-51-44_0471](https://user-images.githubusercontent.com/13469808/26923900-e1f1ea00-4c43-11e7-9f23-a6d697bc54a0.PNG)

**Comment by alexzh16** [comment]
im send message, after that click to buttons "Call", after that confirm one more zrtp words, call ending, send new text message "Test after" and same table with warning. In this case another side not received this message.

**Comment by ReisBenjamin** [comment]
You need to confirm the ZRTP keys on both side

**Comment by alexzh16** [comment]
yes, its confirming on both side. i know this. but, same warning :(. maybe i must flush cache with keys?

**Comment by ReisBenjamin** [comment]
Yes try that

**Comment by alexzh16** [comment]
so. i'm close applications and restart iPhones, after that, message sending without Warning Lime...

**Comment by alexzh16** [comment]
now i'm download from git repos. and running in simulator, and the same Warning in simulator.

<doc><ZID>f9b25200986aec950b4f2050</ZID><msg><pzid>4e8b5a81578054c4f7688c88</pzid><index>37b9edf6</index><text>ByYakewvbmvhZoZBn9+ARw1Kgg==</text><content-type>4ay+ZxM+fLj3JLhlM7hPXz9IkkWZZB1zGAA=</content-type></msg></doc>

<imdn xmlns:linphoneimdn="http://www.linphone.org/xsds/imdn.xsd" xmlns="urn:ietf:params:xml:ns:imdn"><message-id>8d61636e-4d18-11e7-aeea-0d41aec3d219</message-id><datetime>2017-06-09T13:35:50Z</datetime><delivery-notification><status><error/><linphoneimdn:reason code="488">Not acceptable here</linphoneimdn:reason></status></delivery-notification></imdn>

**Comment by alexzh16** [comment]
Hi all,

im have today one more test make and write one video. Please see https://youtu.be/VILNS6XAzXY <https://youtu.be/VILNS6XAzXY>

one site simulator with last git version with last submodules.
another site linphone from testflight 3.16.3-32-gf3ce7ad

all another in the video. Maybe log can help with my problem.

Thank you,

best regards, Alex.

**Comment by alexzh16** [comment]
Hi Benjamin, im found where its Problem. Please check lime.c / lime_im_encryption_engine_process_incoming_message_cb 

selfUri and peerUri

where message encrypted, linphone give selfUri = XXXXXXXX@sip.linphone.org and peerUri  = XXXXXXXX@sip.linphone.org its ok, but, after change to my server or another sip server.  for example selfUri = XXXXXXXX@sip.example.com and peerUri  = XXXXXXXX@ sip.example.com than lime_im_encryption_engine_process_incoming_message_cb selfUri = XXXXXXXX@XXX.XXX.XXX.XXX. Domain change to the ip adress clients. And its not possible unencrypted message.

**Comment by ReisBenjamin** [comment]
Hello,

I didn't understant your last message. When does the domain changes in the callback ?

**Comment by alexzh16** [comment]
if client changed sip server form sip.linphone.org to sip.example.org. Linphone clients not sending Domain Name in the sip uri, but ip address.

**Comment by alexzh16** [comment]
for example: linphone connect to sip.linphone.org. 
Johny call to Benjamin. lime.c incomming johny@sip.linphone.org call to benjamin@sip.linphone.org

after that we change to sip.exmaple.org sip server and 
Johny call to Benjamin. lime.c incomming johny@172.0.0.1 call to benjamin@sip.exmaple.org
in this case, sip.exmaple.org changed to 172.0.0.1 and hash keys not equal.

**Comment by ReisBenjamin** [comment]
We've made some fix concerning Lime, could you try latest commit and tell me if your problem still occurs ? 

Thanks

**Comment by ReisBenjamin** [comment]
Reopen if not solved

**Comment by TheNazzi89** [comment]
Hello @alexzh16 , now I have the same issue between two numbers. Could you tell me how did you fix it?

**Comment by alexzh16** [comment]
Hi,

so… maybe my fix its not will be work in you code. Im fix only by iOs. it must be change in C code lime.c in func ( int lime_im_encryption_engine_process_outgoing_message_cb(LinphoneImEncryptionEngine *engine, LinphoneChatRoom *room, LinphoneChatMessage *msg) )
you must find this part of code:

                        if (zrtp_cache_db == NULL) {
                                ms_warning("Unable to access ZRTP ZID cache to encrypt message");
                                errcode = 488;
                        } else {
                                int retval;
                                uint8_t *crypted_body = NULL;
                                char *selfUri = linphone_address_as_string_uri_only(msg->from);
                                char *peerUri = linphone_address_as_string_uri_only(linphone_chat_room_get_peer_address(room));

                                char *istr;
                                char *selfUri_Change= NULL;
                                char *peerUri_Change= NULL;
                                char *selfUriChange= NULL;
                                char *peerUriChange= NULL;
                                int counts=0;
                                char sep[3]="@";
                                char *realm_name=NULL;
                                selfUri_Change = selfUri;
                                peerUri_Change = peerUri;
                                istr = strtok (peerUri_Change,sep);
                                // for first, we find domain where launch encrypt/decrypt
                                while (istr != NULL)
                               {
                                          if (counts == 1) {
                                                 realm_name = malloc(strlen(istr) + strlen("@") + 1);
                                                if (realm_name) {
                                                        strcpy(realm_name,"@");
                                                        strcat(realm_name,istr);
                                                  }
                                          }
                                          istr = strtok (NULL,sep);
                                          counts++;
                                }

                        peerUriChange = malloc(strlen(peerUri) + strlen(realm_name) + 1);
                                if (peerUriChange) {
                                        strcpy(peerUriChange, peerUri);
                                        strcat(peerUriChange, realm_name);
                                }
                                counts = 0;
                                istr = strtok (selfUri_Change,sep);

                                // now, we change domain of recipients:
                                while (istr != NULL)
                               {
                                          if (counts == 0) {
                                                selfUriChange = malloc(strlen(istr) + strlen(realm_name) + 1);
                                                        if (selfUriChange) {
                                                                strcpy(selfUriChange, istr);
                                                                strcat(selfUriChange, realm_name);
                                                        }
                                          }
                                          istr = strtok (NULL,sep);
                                          counts++;
                                }
				// for the debug uncomment this part
                               // ms_warning("STARTLIME change peerUri: %s\n",peerUri);
                               // ms_warning("STARTLIME change selfUri: %s\n",selfUri);
                               // ms_warning("STARTLIME change selfUriChange: %s\n",selfUriChange);
                               // ms_warning("STARTLIME change selfUriChange: %s\n",peerUriChange);

                                retval = lime_createMultipartMessage(zrtp_cache_db, msg->content_type, (uint8_t *)msg->message, selfUriChange, peerUriChange, &crypted_body);
                                if (retval != 0) { /* fail to encrypt */
                                        ms_warning("Unable to encrypt message for %s : %s", room->peer, lime_error_code_to_string(retval));
                                        if (crypted_body) ms_free(crypted_body);
                                        errcode = 488;
                                } else { /* encryption ok, swap plain text message body by encrypted one */
                                        if (msg->message) {
                                                ms_free(msg->message);
                                        }
                                        msg->message = (char *)crypted_body;
                                        msg->content_type = ms_strdup(new_content_type);
                                }
                                ms_free(peerUri);
                                ms_free(selfUri);
                        }

for me = its working now. you can try. after change, you must make project in command line, for rebuild C code.

--
S pozdravem,

Alexandr Žukovič
