### ISSUE TITLE
linphone_core_new_with_config returning NULL

### ISSUE THREAD

**Issue by shebinkoshy** [BelledonneCommunications/linphone-iphone#249]
class name : LinphoneManager
 method name :  -(void)createLinphoneCore
 Line:  theLinphoneCore = linphone_core_new_with_config(&linphonec_vtable, _configDb, (__bridge void *)(self));
 
theLinphoneCore is NULL, why?

**Comment by ReisBenjamin** [comment]
Are the variables you put in the function correct ?
did you change from our codes ?

**Comment by shebinkoshy** [comment]
i have integrated your entire app into another app, video call and audio call are working perfectly using our own SIP server(UDP). but i dont know why  'theLinphoneCore' variable is NULL.

One more thing i didn't integrate the files under 'submodules' folder. i mean the files that you can see in the below image. What is the use of these files? does i need to integrate in my project? if so, how can i do it?
![screen shot 2017-06-08 at 8 32 20 pm](https://user-images.githubusercontent.com/14162863/26935495-be396fe8-4c89-11e7-88fc-5aa4b3dee501.png)

**Comment by ReisBenjamin** [comment]
Hello all the submodules are our SIP library so yes you'll need them.
The obj-C code is only to call the library and create the UI

**Comment by shebinkoshy** [comment]
Oops. I dont know how audio & video call is working in my app.. Any way, can u tell me why theLinphoneCore is NULL?

**Comment by shebinkoshy** [comment]
https://goo.gl/VmN6tP This is linphone project without submodules. both video call and audio call are working fine. Can you tell me what is the reason for working it without submodules?

**Comment by ReisBenjamin** [comment]
Once the project is compiled you don't need the submodules to run the project

**Comment by shebinkoshy** [comment]
theLinphoneCore is NULL. is that a problem?

**Comment by ReisBenjamin** [comment]
Hi,

Are there any error logs when you try to create the linphone core ?

**Comment by ReisBenjamin** [comment]
Unanswered
