### ISSUE TITLE
Can't build (./prepare.py), following binaries are missing : nasm

### ISSUE THREAD

**Issue by febrian111** [BelledonneCommunications/linphone-iphone#25]
I've followed the steps that exist in the file README.md and has installed all required dependencies via brew including NASM, but when I try to build sdk error message appears an tell me that nasm binary is missing and need to install nasm with brew. I think maybe I need to reinstall nasm but after that It still happen, can't build with the same error message.

**Comment by bagage** [comment]
Which versions of MacOSX, XCode, brew and nasm are you using? What is your $PATH value?

**Comment by GopalPatel1989** [comment]
Hi, i'm having the same issue installing the sdk. It says following binaries missing: nasm.
nasm-2.11.08_1 already installed which is I think newer version. I'm running mac OSX ELCapitan 10.11.1, XCode 6.4. And please tell where to find $PATH?

**Comment by bagage** [comment]
Can you do give me output of the following commands:

```sh
echo $PATH
nasm -v
nasm -f elf32
```

**Comment by GopalPatel1989** [comment]
echo $PATH 
/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

nasm -v
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Oct  5 2015

nasm -f elf32
nasm: fatal: unrecognised output format `elf32' - use -hf for a list
type `nasm -h' for help

**Comment by bagage** [comment]
OK, then your nasm version is incorrect. You have to use brew version, not Apple one which is obsolete.

Something like: `export PATH=/usr/local/bin:$PATH` should do the trick. You should have something like:

> $ nasm -v
> NASM version 2.11.08 compiled on Nov 26 2015
> $ which nasm
> /usr/local/bin/nasm

**Comment by bagage** [comment]
Updated README in ee5e470359cefc9f16287d6ac4288ee7cf56ad27.

**Comment by GopalPatel1989** [comment]
Hey @bagage thanks a lot man, this means a world to me I mean compiling and running the linphone is really much needed finally I got running linphone. Now the question is how do I integrate it into my own project and started working please provide some help. Again thanks for your time.

**Comment by febrian111** [comment]
@bagage thanks for saving my time, I have spent hours to try. Your answer is solving the issue thanks a lot man. Now I'll move forward to run the project and integrate it to my project.
