### ISSUE TITLE
./prepare.py error

### ISSUE THREAD

**Issue by dionisioviei** [BelledonneCommunications/linphone-iphone#250]
When I run prepare.py (Step 4 of Compilation Instructions) the following error appears.
> ERROR:root:Could not find prepare module: module 'prepare' has no attribute 'Target', probably missing submodules/cmake-builder? Try running: 
git submodule sync && git submodule update --init --recursive

I already tried the git command **git submodule sync && git submodule update --init --recursive**, but i get 
the same error, any ideas? _(I already checked the folder cmake-builder and apparently everything is in there)_

**Comment by ReisBenjamin** [comment]
Did you run .prepare.py -c before ?

**Comment by ReisBenjamin** [comment]
./prepare.py -c sorry for the typo

**Comment by dionisioviei** [comment]
i tried now, but i get the same error

**Comment by ReisBenjamin** [comment]
Try a clean clone of our repo maybe there was a problem with the clone

**Comment by dionisioviei** [comment]
Ok i will try, but is there a way to do what prepare.py does manually?

**Comment by ReisBenjamin** [comment]
Yes the prepare.py create a makefile you can read the script and wrote the make file yourself

**Comment by dionisioviei** [comment]
ok, i tried a clean clone repo but i keep getting the same error

**Comment by ReisBenjamin** [comment]
Okay you use linphone-andoird right ?
This repo is only for linphone-iphone on iOS please refer to the correct repo for your questions : 
https://github.com/BelledonneCommunications/linphone-android
I'll close this issue please re-open one on linphone-android.
