### ISSUE TITLE
Directory 'plugins' not found

### ISSUE THREAD

**Issue by Nikiraf** [BelledonneCommunications/linphone-iphone#251]
Hi,

I'm getting error `warning: directory not found for option '-L/Users/aleksandar/linphone-iphone/liblinphone-sdk/apple-darwin/lib/mediastreamer/plugins`

I checked and for some reason I don't have this folder mediastreamer and plugins. I added this folders and I'm getting error `clang: error: linker command failed with exit code 1 (use -v to see invocation)` with no additional explanation. Can someone help me with this.

**Comment by ReisBenjamin** [comment]
Hello,

You either need to build the sdk statically by using -DENABLE_STATIC_ONLY=ON in your prepare options.
Or you need to update your scode project to support frameworks instead of static lib

**Comment by eliburke** [comment]
@ReisBenjamin is the update to support frameworks complete now? (all of the submodule frameworks are correctly versioned and configured and the x86 built stripped out so that it can be submitted to Apple?)

**Comment by ReisBenjamin** [comment]
Hello @eliburke ,

Yes it's correctly working now you can publish the app on itunes connect.
All the modifications have been made in linphone-iphone and you can read the README to see how to incorporate it in your own project.

**Comment by Nikiraf** [comment]
Thanks ReisBenjamin. I will try to build the SDK again. I have found line in `prepare.py` with:
`if '-DENABLE_STATIC_ONLY=ON' in sys.argv or '-DENABLE_STATIC_ONLY=YES' in sys.argv:` and changed it to `if '-DENABLE_STATIC_ONLY=ON' in sys.argv or '-DENABLE_STATIC_ONLY=ON' in sys.argv:`. I will write here if everything goes well.

Thanks

**Comment by Nikiraf** [comment]
I have build SDK with `-DENABLE_STATIC_ONLY=ON` and I get same error
`ld: warning: directory not found for option '-L/Users/aleksandar/Downloads/linphone-iphone/liblinphone-sdk/apple-darwin/lib/mediastreamer/plugins'`

**Comment by ReisBenjamin** [comment]
Please provide with full logs of prepare.py and make

Thanks

**Comment by ReisBenjamin** [comment]
Unanswered
