### ISSUE TITLE
Can I use the latest version yet?

### ISSUE THREAD

**Issue by f15radar** [BelledonneCommunications/linphone-iphone#252]
I had to resort to an earlier release because I couldn't get linphone to compile on Xcode 8.  Another issue said to use an older release which I did.  However I still can't see to get anything that requires https to work under xcode 8 because of the certs.  We are using linphone on a closed network.  I can't get photos to transfer under chat and I cant get remote provisioning to work.  When might I be able to try and compile a newer version.

**Comment by ReisBenjamin** [comment]
Hello,

Linphone compile well on Xcode 8 what are the errors you get ?
make sure to have up-to-date submodule and to have compiled the SDK before compiling the XCode project

**Comment by ReisBenjamin** [comment]
Hello,

Did you solve your problem ?
Can i close the ticket ?

**Comment by f15radar** [comment]
I have been put on another project so no but u can close the ticket
