### ISSUE TITLE
How to play wav in earpiece speaker?

### ISSUE THREAD

**Issue by bofuliu** [BelledonneCommunications/linphone-iphone#253]
Hi @ReisBenjamin, 

I have tested the linphone_core_play_local() API to play .wav file, but the audio is played by speaker.
Could you know to play audio in earpiece speaker?

thanks a lot 

Ed

**Comment by CrabeMan** [comment]
Hello
Have you check about [AudoManager](https://developer.android.com/reference/android/media/AudioManager.html) ?
Try to set the mode to [MODE_IN_CALL](https://developer.android.com/reference/android/media/AudioManager.html#MODE_IN_CALL)
And set the [setSpeakerphoneOn(boolean)](https://developer.android.com/reference/android/media/AudioManager.html#setSpeakerphoneOn(boolean)) method to false

CrabeMan

**Comment by bofuliu** [comment]
HI @CrabeMan, 

It's android implementation.
In iOS, could you give me some hits about it? 

Thanks a lot
ED

**Comment by ReisBenjamin** [comment]
Hi,

you can try to use linphone_core_set_playback_device before calling linphone_core_play_local to choose the earpiece.

**Comment by ReisBenjamin** [comment]
Unanswered, please reopen if not fixed.

Regards
