### ISSUE TITLE
Are there any plans to add Networking QOS for traffic prioritization?

### ISSUE THREAD

**Issue by eliburke** [BelledonneCommunications/linphone-iphone#254]
I realize this is a question I should be asking on the belle-sip repo, but Issues are turned off.

It appears to be very straightforward to enable the feature on UDP sockets: 
https://developer.apple.com/library/content/qa/qa1934/_index.html
https://forums.developer.apple.com/thread/72541

It is possible this is already enabled, but I couldn't find any sign of it in the code.

**Comment by ReisBenjamin** [comment]
Hello,

Thanks for the suggestion but we have no plan for now to do so. Maybe in the future.

Best regards,
Benjamin
