### ISSUE TITLE
What parameters should be send from server (For Push Notifications)

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#255]
I have launched the app successfully.

 the only issue is on the call when the app is in the background. My server developer is asking me what parameters he should send to activate the call kit process?

I don't know what to tell him. Kindly guide? 

[we are using FreePBX ]

**Comment by ReisBenjamin** [comment]
Hello,

The process of push notifications is only used in order to wake the app up.
Once it's awoken, it registers and then receives the INVITE.
You need to add support for push notifications on your server nothing needs to be done in the app.

Regards,
Benjamin

**Comment by TheEngineerz** [comment]
You mean empty payload?

**Comment by ReisBenjamin** [comment]
silent notification

**Comment by ReisBenjamin** [comment]
Did it work ?

**Comment by TheEngineerz** [comment]
@ReisBenjamin actually my server developer is in middle of logic (finding an exact token from the server and send push whenever receive call). I will inform you once done.

**Comment by TheEngineerz** [comment]
@ReisBenjamin everything works great now. Some of my customers facing one issue. 

when App is registered/background/killed they receive the call successfully. but when the network is changed then Push doesn't work until it reregisters again.

What can be the issue here ? it think when network is changed app should be reregister automatically just to send the voip token to server to update it.

Thanks

**Comment by ReisBenjamin** [comment]
Hello,

The problem might be on your server since the push token doesn't change when changing networks. on my side i do not reproduce the issue.
You need to mzke sure you don't unregister when the goes in background.

**Comment by stalley** [comment]
@TheEngineerz What payload did you use to trigger the re-registration?

**Comment by shdaro** [comment]
Hi, 

> 
> 
> Hello,
> 
> The process of push notifications is only used in order to wake the app up.
> Once it's awoken, it registers and then receives the INVITE.
> You need to add support for push notifications on your server nothing needs to be done in the app.
> 
> Regards,
> Benjamin

@ReisBenjamin I have configured the push server successfully and I also get push notification while the app is in background. But the issue is push notification doesn't wake up the app.

**Comment by shdaro** [comment]
@TheEngineerz Could you please share your payload what trigger the apps to wake up?

**Comment by fractalysid** [comment]
Same problem here. Everything correctly set up, but notification doesn't wake up the application.
Any suggestion from developers @ghost on the payload to use?

**Comment by fractalysid** [comment]
Update: with this simple payload, the application wakes up and registers, but only occasionally. It is not consistent. Actually it only works maybe 10% of the times.

'{"aps" : { "content-available" : 1 } }'
