### ISSUE TITLE
ios linphone bcg729 error

### ISSUE THREAD

**Issue by zhangyushneg** [BelledonneCommunications/linphone-iphone#256]
When I compile the linphone static library,Move lib and include to their own project directory and compile, error _libmsbcg729_init
How can i solve it?

**Comment by ReisBenjamin** [comment]
Do you compile the lib corresponding to _libmsbcg729_init ?
You should use our prepare.py / make process this should avoid compile errors

**Comment by ReisBenjamin** [comment]
If you use static library you might need to change the xcode project because now we use frameworks

**Comment by zhangyushneg** [comment]
Thank you, I have solved the problem。
But I met another question about publish, I can not get the server to my publish body content, what can be achieved through the way to publish body content

**Comment by ReisBenjamin** [comment]
Hi,

what do you mean by publish body content ?
