### ISSUE TITLE
Callkit not receiving incomingcall & Audiounit start issue

### ISSUE THREAD

**Issue by saurabhs70** [BelledonneCommunications/linphone-iphone#258]
Hi,
after implementing call callkit with linphone,it's issue that incoming call didn't get pick after accepting call.
**Issue 1:**
it means it didn't change to callview screen.
**Issue 2:**
even if i'hv added callview screen it throws me error of audio-unit didn't start.

**Attachment:**
![img_1909 png](https://user-images.githubusercontent.com/17975720/27691791-c186cbd0-5d02-11e7-95fc-58352d30c981.jpg)
![img_1910 png](https://user-images.githubusercontent.com/17975720/27691801-c6947424-5d02-11e7-8af5-7dfdc292bc99.jpg)

**Source code:**
- (void)provider:(CXProvider *)provider performAnswerCallAction:(CXAnswerCallAction *)action {
	LOGD(@"CallKit : Answering Call");
	
        [self configAudioSession:[AVAudioSession sharedInstance]];
   
	[action fulfill];
	NSUUID *uuid = action.callUUID;

	NSString *callID = [self.calls objectForKey:uuid]; // first, make sure this callid is not already involved in a call
	LinphoneCall *call = [LinphoneManager.instance callByCallId:callID];
	if (call != NULL) {
		BOOL video = (!([UIApplication sharedApplication].applicationState == UIApplicationStateBackground) &&
					  linphone_core_get_video_policy(LC)->automatically_accept &&
		  linphone_call_params_video_enabled(linphone_call_get_remote_params((LinphoneCall *)call)));
		self.pendingCall = call;
		self.pendingCallVideo = video;
      //added callview screen for issue 2 but throwing me error AudioUnit didn't initilized
      PhoneMainView *view = [[PhoneMainView alloc]init];
        [view incomingCallAccepted:call evenWithVideo:YES];
		return;
	};
}

**Comment by ReisBenjamin** [comment]
Hello,

You need to configure the AudioSession when displaying the call, not when answering it.
Plus from the screen view I see that the call is ongoing (the button to pickup became a add button for adding a caller) so this just means that you need to go to the CallView.

Regards

**Comment by saurabhs70** [comment]
Hi
@ReisBenjamin  Thanks for Replying,but i can see in linphone code have configured audio session on "performAnswerCallAction". i have done some R&d over callkit i found some bug in "WWDC" callkit too at first call [](https://developer.apple.com/library/content/samplecode/Speakerbox/Introduction/Intro.html) too this is the same issue which you are explaining but in case if i configure audio session after "AVAudioSessionInterruptionNotification" everything seems fine so why linphone have configured audiosession on "performAnswerCallAction" didn't understand,please explain it.

**Comment by ReisBenjamin** [comment]
My bad, you're right. Could you show me the error you see about audio session ?

**Comment by saurabhs70** [comment]
hello,
sure thanks for helping @ReisBenjamin,

**Error:**
`[Notice] lib/io unit initialized
2017-06-30 18:58:40.354413 linphone[1349:404415] [Notice] lib/I/O unit latency [0.000000], quality [64]
2017-06-30 18:58:40.356854 linphone[1349:404415] [aurioc] 889: failed: 'ent?' (enable 3, outf< 1 ch,  48000 Hz, Int16> inf< 1 ch,  48000 Hz, Int16>)
2017-06-30 18:58:40.357098 linphone[1349:404415] [Error] lib/Cannot start audioUnit because [ent?]
2017-06-30 18:58:40.357330 linphone[1349:404415] [Error] lib/AudioUnit error for (auresult = AudioOutputUnitStart(card->io_unit)): ret=unknown error (1701737535) (/Users/umenit/Desktop/linphone-app/linphone-iphone/submodules/linphone/mediastreamer2/src/audiofilters/msiounit.m:520)
2017-06-30 18:58:40.357514 linphone[1349:404415] [Notice] lib/AudioUnit could not be started, current hw output latency [0.012063] input [0.000625] iobuf[0.011610] hw sample rate [44100.000000]
`
**I have done some changes in code**
here for **performAnswerCallAction** method in **providerdelegate.m** file i have removed  this line of code which i had written 

`PhoneMainView *view = [[PhoneMainView alloc]init];
[view incomingCallAccepted:call evenWithVideo:YES];`
as well i have commented `[self configAudioSession:[AVAudioSession sharedInstance]];` line too and i have called this method from **linphonemanager.m** with method 
`- (void)onCall:(LinphoneCall *)call StateChanged:(LinphoneCallState)state withMessage:(const char *)message`
here it make sense 

please help to resolve this issue.
Thanks.

**Comment by ReisBenjamin** [comment]
Did you try put back [self configAudioSession:[AVAudioSession sharedInstance]]; in performAnswerCallAction ?
I remember having audio issues with callKti and t was calling that function everytime i needed the audio session + waiting for callkit to start audio session before manipulating the call that solved it.

**Comment by saurabhs70** [comment]
yes i tried but still didn't work.

**Comment by ReisBenjamin** [comment]
Did you  wait for the Audio sesion to be started before accepted the call ?

**Comment by saurabhs70** [comment]
yes i found the solution for it,having said that this is still happening with live app of linphone from appstore.
**issue:**
 it shows  auto-pause a call around 1 out of 3-4 calls.it means you need to click  unpause/resume a call to connect again,why is it?

**Comment by ReisBenjamin** [comment]
The push notification only wakes the app, then the app registers and receives the INVITE this what triggers the callkit screen apparition.
You can change this behavior by calling reportIncomingCallwithUUID:(NSUUID *)uuid handle:(NSString *)handle video:(BOOL)video from the method you mentionned but you risk to report it twice

**Comment by saurabhs70** [comment]
yes correct i was supposing this logic too @ReisBenjamin,so after receiving push to **didReceiveIncomingPushWithPayload** how would app  app **registers** i mean what method ?

**Comment by ReisBenjamin** [comment]
These lines 
	[LinphoneManager.instance setupNetworkReachabilityCallback];
	dispatch_async(dispatch_get_main_queue(), ^{
	  [self processRemoteNotification:payload.dictionaryPayload];
	}); in the method make the app registers.

**Comment by saurabhs70** [comment]
but these method are for notification,in case i don't want to use it i just want to register to app so?

**Comment by ReisBenjamin** [comment]
Just call :
**if (!linphone_core_is_network_reachable(LC)) {
        LinphoneManager.instance.connectivity = none; //Force connectivity to be discovered again
        [LinphoneManager.instance setupNetworkReachabilityCallback];
}**

**Comment by saurabhs70** [comment]
this is not working is any other method like for destroy [LinphoneManager.instance destroyLinphoneCore];

**Comment by ReisBenjamin** [comment]
Try : 
**[LinphoneManager.instance setupNetworkReachabilityCallback];
if (!linphone_core_is_network_reachable(LC)) {
LinphoneManager.instance.connectivity = none; //Force connectivity to be discovered again
[LinphoneManager.instance setupNetworkReachabilityCallback];
}**

**Comment by saurabhs70** [comment]
yes i tried and debugging it is there any method which is blocking to do connection in background because i can see it's showing only registration in progress,it's didn't connect

**Comment by iJasonWade** [comment]
What version of iOS are you testing against @saurabhs70? If it is iOS 10 then you MUST use PushKit, check this link: https://developer.apple.com/library/content/qa/qa1938/_index.html

**Comment by saurabhs70** [comment]
In this app we can see A blank video call if we test in on iOS 9,for iOS 10 it is working fine why?

**Comment by ReisBenjamin** [comment]
@saurabhs70 yes you can do that.
I'll close the issue since you solved it :)

Regards
