### ISSUE TITLE
make command is not running

### ISSUE THREAD

**Issue by Aashish09** [BelledonneCommunications/linphone-iphone#26]
First of all, I am android developer but I am unable to create any issue in linphone android page, so I am posting my issue here.
I have installed all specified components on linphone android page but I am unable to run make command. I am working on Ubuntu 14.04 LTS.
I am getting below error after run the make command :

Missing some git submodules. Did you run 'git submodule update --init --recursive'?
Makefile:74: *** commands commence before first target.  Stop.

I tried all specified solution that google gave me but didn't help me.
Please provide me some solution as soon as possible so I can run make command and setup my linphone android project.

Thank you
Aashish Sharma

**Comment by bagage** [comment]
Please post on the developers mailing list instead.
