### ISSUE TITLE
Changing the order of payload type in SDP

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#262]
Hello!
Sorry to bother again. 😅

This time I desire to change the codec list order in offering SDP (such as in INVITE request). 

When multiple codecs match in the first SDP negotiation (INVITE and 200ok), our sip server picks the first codec from matched list by sending a ACK request with the picked codec as a second negotiation .     

In this case I need to choose a preferred codec by rearranging the codec order. 
My current codec list is 0(pcmu) 8(pcma) 18(g729)
And I would like to change it as:
18(g729) 0(pcmu) 8(pcma) in SDP.

Is it possible? I did search the Linphone lib document and the code but I couldn't find anything. 

Appreciate any help, thank you in advance.
Correct me if I post the issue in the wrong place.

**Comment by ReisBenjamin** [comment]
Hello, 

you can do : linphone_core_get_audio_payload_types to get the list of codecs used by Linphone, then re-arrange the order in the list as you wish and do : linphone_core_set_audio_payload_types.

This should do the trick.

Best regards,
Benjamin

**Comment by zj299792458** [comment]
Brilliant!!! That works. 

But it's a little tricky: the codecs from linphone_core_get_audio_payload_types  is a "CONST" list that I can't re-arrange the order directly! It really took me a while to figure that out.  
Re-arranging that kind of list is totally a disaster for me. 😂

Thank you so much.

**Comment by shraddha-patel-1891** [comment]
@zj299792458 

we have used the following code but it gives us bad access

`   bctbx_list_t *new_codec = NULL;
   
    for(int i=0;i<[SharedAppDelegate.arrCodecs count];i++)
    {
        NSMutableDictionary *dict  = SharedAppDelegate.arrCodecs[i];
        NSString *strcodec = [dict valueForKey:@"codec_data"];
        void *data_codec = (void *)CFBridgingRetain(strcodec);
     
        PayloadType *pt = (PayloadType *)data_codec;
       new_codec = bctbx_list_append(new_codec, pt);
       linphone_core_set_audio_payload_types(LC,new_codec)
`
 
can you please pass me code snippet for linphone_core_set_audio_payload_types?

thank you
