### ISSUE TITLE
linphone_core_clear_call_logs does not work

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#264]
Hi 

I intent to clear all call logs by invoking linphone_core_clear_call_logs(). 
But I can still get call logs from linphone_core_get_call_logs() when refreshing the page.

I have to restart the app to make it work.

Did I do something wrong?

Linphone lib version 3.16.4

Thank you.

**Comment by eliburke** [comment]
A while back, i posted a patch to the mailing list to add a setting to liblinphone for this very purpose. Perhaps it will help you:
https://lists.nongnu.org/archive/html/linphone-developers/2015-02/msg00007.html

Apply the patch, then add store_call_logs=0 to the linphonerc

**Comment by zj299792458** [comment]
@eliburke Thanks bro. 

But the patch seems to stop generating call log,  instead of to clean current call log.

**Comment by eliburke** [comment]
Sorry, I misunderstood what you were trying to accomplish. Best of luck

**Comment by zj299792458** [comment]
sorry it's linphone_core_clear_call_logs() not working, not linphone_core_get_call_logs().

The solution is to delete it one by one using linphone_core_remove_call_log(LC, callLog) in a for loop. That does the trick.
