### ISSUE TITLE
ios linphone crash change network status， when onFyCallOutgoingRinging

### ISSUE THREAD

**Issue by zhangyushneg** [BelledonneCommunications/linphone-iphone#265]
bug when LinphoneCallIncomingEarlyMedia not crash

**Comment by zhangyushneg** [comment]
android not crash when  onFyCallOutgoingRinging

**Comment by ReisBenjamin** [comment]
Hello,

Could you be more specific ?
What were you doing ? what happened ? When did the crash happen ?
LinphoneCallIncomingEarlyMedia and  onCallOutgoingRinging are 2 different things ( onFyCallOutgoingRinging does not exist) so are you to comments related ?

Thanks

**Comment by zhangyushneg** [comment]
I started the call, when I received the LinphoneCallOutgoingRinging callback, I started switching the network and got crash

**Comment by ReisBenjamin** [comment]
What do you mean by switching the network ? switching between wifi and data or something code related ?

**Comment by zhangyushneg** [comment]
yes, wifi to data or data to wifi

**Comment by ReisBenjamin** [comment]
I don't reproduce the issue. Is it systematic on your side ?

**Comment by zhangyushneg** [comment]
appstore linphone is crash when  LinphoneCallOutgoingRinging、LinphoneCallOutgoingEarlyMedia ，change change network type

**Comment by ReisBenjamin** [comment]
Please update to latest commit and retry.
Re-open the issue if it still happens

Thanks
