### ISSUE TITLE
Disconnect from bluetooth connection while in call

### ISSUE THREAD

**Issue by futurealecks** [BelledonneCommunications/linphone-iphone#266]
The app works well with bluetooth but I'm unable to switch the audio/microphone back to the handset while in a call.

**Comment by ReisBenjamin** [comment]
Hello,

waht do you mean by handset ?
Could explain step by step what you do, what you expect and what happens ?

Thanks

**Comment by ReisBenjamin** [comment]
Not answered.
Re-open it if you can provide more info.

Thanks
