### ISSUE TITLE
using swift instead of objective-c

### ISSUE THREAD

**Issue by hadidez** [BelledonneCommunications/linphone-iphone#267]
hi, im new in ios. can i use swift instead of objective-c in linphone project ? if no so has BelledonneCommunications any program to jurney to swift ?!
thnaks

**Comment by BrieucV** [comment]
Hi hadidez,
Objective-C and Swift are two distincts language without direct link between it. I don't think there is way to switch without re-implementting the app and this is not in our projects for now.
Hopefully, the whole liblinphone is using C language, so only the UI need to be re-develop.

**Comment by colemancda** [comment]
Here is a working Swift wrapper with unit tests https://github.com/colemancda/LinPhoneSwift

**Comment by ReisBenjamin** [comment]
I'll add that like obj-c, swift can easily import c headers soonly UI should be rework and on top that swift can import obj-c headers so maybe not all the UI is to be remade

can this be closed ?
