### ISSUE TITLE
iOS crash app FastAddressBook.m

### ISSUE THREAD

**Issue by alexzh16** [BelledonneCommunications/linphone-iphone#268]
Hi, its big problem with app. 
1) run app without registration new contact.
2) click to Callpad and choice Chat Icons
3) click to new chat
Crash. please see screenshot exception.

Problem in contact. in module check is Null contacts, but not check if is null address. In this case, address is NULL and linphone_core_find_friend(LC, address) going to crash APP.

if change "if (!contact) {" to "if (!contact && address) { " than working without crash, but next problem will be in Address book.

1) run app and register new account.
2) make call to another account
3) change view to history call
4) click to 3 dots for the logs calls
5) click icons with Add to contacts
6) Click to exist Accounts
7) not save contacts and return to previous menu with click to icons in the left corner (cancel).
Problem - accounts erase with this name. and this another Problem in module FastAddressBook. return contact where contact its NULL.
<img width="1335" alt="snimek obrazovky 2017-07-19 v 16 14 23" src="https://user-images.githubusercontent.com/13469808/28371498-70275304-6c9d-11e7-9fd8-8c8c73eab269.png">
<img width="1623" alt="snimek obrazovky 2017-07-19 v 15 47 17" src="https://user-images.githubusercontent.com/13469808/28371499-7045697a-6c9d-11e7-90da-52f72a67bff4.png">

**Comment by alexzh16** [comment]
im compiled last linphone-iphone from git downloaded source code today.
1) git clone https://github.com/BelledonneCommunications/linphone-iphone.git
2) git submodule update --init --recursive
3) ./prepare.py
4) make

**Comment by ReisBenjamin** [comment]
Does the crash still happen with latest sources ?

Thanks

**Comment by alexzh16** [comment]
yes, last commit c286b234503ed003346e66fc9b34bb59e78e7688
git pull = Already up-to-date.

**Comment by ReisBenjamin** [comment]
Okay,

What do you mean by "Click to exist Accounts" ?
I am trying to reproduce the crash.

**Comment by alexzh16** [comment]
please wait, im make severals screenshot with number. its more situations where apps crashed.

**Comment by alexzh16** [comment]
![chat_blank_crash](https://user-images.githubusercontent.com/13469808/28516697-63ab560c-7062-11e7-9114-1469b580c612.png)

one crash with chat

**Comment by alexzh16** [comment]
![address_book_crash](https://user-images.githubusercontent.com/13469808/28516790-b83b029e-7062-11e7-84a7-d1d03dea80c0.png)

address book crash

**Comment by ReisBenjamin** [comment]
I've pushed a fix in commit bfa84a37fe2c89b3ff02e8a444da219ccea478d2 please try it and tell me if it's still happen.

**Comment by alexzh16** [comment]
![address_book_erase](https://user-images.githubusercontent.com/13469808/28517553-069e6fa0-7065-11e7-80d3-a1bb57e93428.png)

and address book erased situation...

**Comment by ReisBenjamin** [comment]
address book erased situation should be fixed with commit 03ca623e4fc50552fd5b2bc219bd1d033eb60814

**Comment by alexzh16** [comment]
excellent! now its working good.

**Comment by ReisBenjamin** [comment]
Great !
