### ISSUE TITLE
Calls not handled properly - 2 calls w/screen locked and CallKit

### ISSUE THREAD

**Issue by iJasonWade** [BelledonneCommunications/linphone-iphone#269]
We have a custom app that uses the liblinphone sdk and everything is working perfectly, we mimicked the code from this repo. The issue lies when the iPhone screen is locked and a call comes in through CallKit, the first call is answered and works perfectly, however if another VoIP call comes in through CallKit during this scenario and the End & Accept button is pressed the first call is ended successfully but when the second call is being answered there is not any audio and the INVITE is never ACK'ed or responded to by the sip stack. The app thinks it has successfully answered the call but the sip stack never stood up the call. It appears that because of how CallKit works with this scenario where the first call is ended BEFORE the incoming call is answered that there is a brief period where there is not an active call, however there is a pending INVITE. Is there a way to get around this in linphone?

![screen shot 2017-07-20 at 1 52 09 pm](https://user-images.githubusercontent.com/12824479/28435524-fa6f6c2a-6d58-11e7-81f6-b6a967ec35c4.png)

**Comment by ReisBenjamin** [comment]
Does the call come from the same app ?
I do not reproduce this on linphone.

**Comment by iJasonWade** [comment]
Both calls are from other iPhones using the app with lin phone, if I have a call with our app and a cellular call this scenario works fine, the issue only presents itself when there is a call with our app that uses liblinphone and then another call with a phone that uses liblinphone comes in.

**Comment by ReisBenjamin** [comment]
You need to change the behavior of our CallKit callbacks.
Linphone does'nt use Callkit double screen for two linphone calls we have implemented a notification system to do that be cause we were not satisfied with callkit multi call management.
I suggest you do the same or you make your own callkit implementation.

**Comment by ReisBenjamin** [comment]
Nothing's to be done

**Comment by nehalmehta36** [comment]
@iJasonWade were you able to resolve this issue? Or you had to go with the notifications aas mentioned by linphone team?
