### ISSUE TITLE
I encountered when compiling such a mistake GNU assembler not found

### ISSUE THREAD

**Issue by yin329039646** [BelledonneCommunications/linphone-iphone#27]
GNU assembler not found, install/update gas-preprocessor

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
make[3]: *** [../linphone-iphone/WORK/ios-armv7/Stamp/EP_ffmpeg/EP_ffmpeg-configure] Error 1
make[2]: *** [CMakeFiles/EP_ffmpeg.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

**Comment by yin329039646** [comment]
I have solved this problem, I looked at f'f'mpeg of issues, because I saw some old tutorials manually download gas-preprocessor.pl cause, and now I deleted my downloaded gas-preprocessor.pl then compiled got this hint: ERROR: Could not find gas-preprocessor.pl, please install it:
         wget --no-check-certificate https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl && \
         chmod + x gas-preprocessor.pl && \
         sudo mv gas-preprocessor.pl / usr / local / bin /
I follow the prompts, and then compile enough

**Comment by Kondenko** [comment]
Saved my day, thanks!

**Comment by Liujony** [comment]
omg you literaly saved my day! even in 2025!!!

**Comment by gcloudspider** [comment]
omg you literaly saved my day! even in 2025!!!
