### ISSUE TITLE
Outgoing call failed with 408 error will increase the missed call count

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#270]
Hi guys.

To my best understanding I thought linphone_core_get_missed_calls_count(LC) only counts the missed incoming call. But in my test situation outgoing calls with 408 return code also increase the count and 100% reproducible. So I'm wondering is there any special meaning of this?

Thank you for any response.
Best Wishes.

**Comment by ReisBenjamin** [comment]
Hello,
I do not reproduce the issue on Linphone. 408 corresponds to request timeout and i don't see it increasing the badge number anywhere. did you change anything in the code ?

**Comment by zj299792458** [comment]
@ReisBenjamin  
Hello, sorry for the delay reply, I was quite busy last days. 

I'm using the official last Linphone version from App Store, and here is my test result: 
Step 1, initialize an outgoing call
![img_2820](https://user-images.githubusercontent.com/6792825/28761151-33b7809c-75df-11e7-9635-8e0cfae09b21.PNG)

Step2, fail with 408 request timeout, you can see the unread mark on call log tab, it wasn't there before
![img_2821](https://user-images.githubusercontent.com/6792825/28761187-7b455e20-75df-11e7-9503-6e0f9d1ca415.PNG)

Step3, check the call log you can see the log is mark as missed (the latest item)
![img_2822](https://user-images.githubusercontent.com/6792825/28761220-a44ac6fc-75df-11e7-8298-5ebc7d40136f.PNG)

and here is the network capture, 100% reproducible:
![qq20170731-110721](https://user-images.githubusercontent.com/6792825/28761439-347c8ab6-75e1-11e7-9e92-dbdec2387850.png)


Am I doing something wrong?

Thank you for your response!

**Comment by ReisBenjamin** [comment]
It doesn't mean the call is missed, it means it failed and it's the case since you received a 4xx code.
408 is an error code therefore the call must be shown as failed not as declined or cancelled.

**Comment by zj299792458** [comment]
@ReisBenjamin  Like I said I downloaded it from App store without any modification and the version says 3.16.3, did you try it on that? Also I will pull the code from git now and try it on last version. Maybe it was fixed on latter version. 
Thank you anyway. 👍

**Comment by zj299792458** [comment]
@ReisBenjamin 
Confirm: on the latest commit on git (66fac61892908a6e18fa4bcb4d48056b6ee636f7) this issue has been fix and no longer reproducible. 

Maybe you should consider uploading it to App store :)
