### ISSUE TITLE
Crash on Login with empty Domain field (TestFlight, Ad Hoc)

### ISSUE THREAD

**Issue by antongavrilenkov** [BelledonneCommunications/linphone-iphone#272]
It happens only when I test the app via TestFlight or export as Ad Hoc Deployment and install to my phone.

Assistant -> Use SIP Account
Username: random
Password: empty
Domain: empty
Display Name: empty
Transport: UDP

Also it was crashed:
Username: Not Latin symbols (тестёый) 
Password: empty
Domain: sip.linphone.org
Display Name: empty
Transport: UDP

Then press Login and the app will be crashed.

My phone: iPhone 6s Plus, iOS 10.3.3

**Comment by ReisBenjamin** [comment]
Hi,
First crash fixed with commit 1ed7f0a3cbf6fa0caa8ce0c9e7b6d8df81fdc34b
Looking into second one.

Thanks for reporting them !
Benjamin

**Comment by ReisBenjamin** [comment]
Hi again,

The second crash has been fixed in commit ce4421b5f3b3c67ab5588e78bbce428e4d501abe
Now special characters are escaped in the sip address.

I'll close this issue, please reopen it if the fix doesn't work for you.

Cheers
