### ISSUE TITLE
Get an Exception if hide_assistant_custom_account=1

### ISSUE THREAD

**Issue by antongavrilenkov** [BelledonneCommunications/linphone-iphone#273]
I got an exception if set:
hide_assistant_custom_account=1
In linphonerc-factory 
and run it on my phone or an emulator.

**Comment by ReisBenjamin** [comment]
Hello,

Could show me traces and backtrace of the exception ?

thx,
Benjamin

**Comment by antongavrilenkov** [comment]
Sure! 

[backtrace.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/1188577/backtrace.txt)
[traces.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/1188578/traces.txt)

**Comment by ReisBenjamin** [comment]
Thanks for reporting, crash fixed with commit 66fac61892908a6e18fa4bcb4d48056b6ee636f7

Best regards,
Benjamin
