### ISSUE TITLE
Video orientation for local video, before establishing a call

### ISSUE THREAD

**Issue by jelenadj** [BelledonneCommunications/linphone-iphone#274]
When I open Linphone app from the AppStore, and switch to Dialer tab (DialerView) on iPad, it starts showing local video capture, however - it's not correctly oriented in any other orientation except Portrait. Only after establishing a call, video orientation for local capture works properly. Is there a way to make it working before establishing a call too?
It looks like linphone_core_set_device_rotation doesn't have any effect in this case.

**Comment by ReisBenjamin** [comment]
Hi,
I do not reproduce can i have some logs of when it happens ?

Thanks,
Benjamin

**Comment by jelenadj** [comment]
Hi Benjamin. It's reproducible for me every time, so maybe it's something iOS version specific, so you can't reproduce it on your side. I don't need even to make a call, but just to switch Dial tab on iPad, and whenever iPad is in landscape, image is rotated for -90 where it should be 90, and for 90 where it should be -90. Also, what's interesting is, orientation doesn't work only for front camera, while for back camera everything works as expected. Not sure is there anything in debug logs that could be helpful...
I am on iOS 9.3.5 on iPad Pro 9.7".

**Comment by ReisBenjamin** [comment]
Hi please try with the master code of our repo because I can't reproduce it with the latest code, it can be already solved on the current master branch

Thanks

**Comment by jelenadj** [comment]
@ReisBenjamin it works on master branch. Do you have some recommendations where to look for changes (which class or commit) that i can apply on the version of the current AppStore branch, in order to fix this issue? Thanks!

**Comment by ReisBenjamin** [comment]
You can try commit 5987d4a4567f71ff7b3a9a2740cc4ab24c08eaa4 i see nothing else in the history touching the screen orientation

**Comment by ReisBenjamin** [comment]
Please reopen if the commit doesn't fix issue.

Thanks
