### ISSUE TITLE
App cannot resume call because another call is locking the sound resouces - but there is only one call

### ISSUE THREAD

**Issue by bivanov** [BelledonneCommunications/linphone-iphone#275]
I'd like to use following code from liblinphone/linphone-iphone:

```
-(void) holdCurrentCall {
    LinphoneCall *call = [self getCall];
    
    LinphoneCallState state = linphone_call_get_state(call);
    
    bool_t locked = linphone_core_sound_resources_locked(self.lc);
    
    printf("[LH] holdCurrentCall %p with state %d locked %d ", call, state, locked);
    
    if (state == LinphoneCallOutgoingProgress ||
        state == LinphoneCallStreamsRunning) {
        int retVal = linphone_call_pause(call);
        printf("[LH] result is %s\n", retVal == 0 ? "ok" : "fail");
    }
}

-(void) resumeCurrentCall {
    LinphoneCall *call = [self getCall];
    
    LinphoneCallState state = linphone_call_get_state(call);
    
    bool_t locked = linphone_core_sound_resources_locked(self.lc);
    
    printf("[LH] resumeCurrentCall %p with state %d locked %d ", call, state, locked);
    
    if (state == LinphoneCallPaused) {
        int retVal = linphone_call_resume(call);
        printf("[LH] result is %s\n", retVal == 0 ? "ok" : "fail");
    }
}

-(LinphoneCall *) getCall {
    LinphoneCall *currentCall = linphone_core_get_current_call(self.lc);
    if (currentCall == nil && linphone_core_get_calls_nb(self.lc) == 1) {
        currentCall = (LinphoneCall *)linphone_core_get_calls(self.lc)->data;
    }
    return currentCall;
}
```

I can put call on hold and then resume it with no problem, but in case I want to put it on hold and resume second time during a call, I cannot do this due to error mentioned in issue title.
The thing is that I'm not trying to create any other call.

I've filtered logs by [LH] and that's what I've got:

```
// First hold
[LH] holdCurrentCall 0x1508b2600 with state 7 locked 0 Call 0x1508b2600: moving from state LinphoneCallStreamsRunning to LinphoneCallPausing
[LH] result is ok
// First resume
[LH] resumeCurrentCall 0x1508b2600 with state 9 locked 0 ms_filter_unlink: MSFilePlayer:0x174127620,0-->MSDtmfGen:0x174125960,0
[LH] result is ok
// Second hold
[LH] holdCurrentCall 0x1508b2600 with state 7 locked 1 Call 0x1508b2600: moving from state LinphoneCallStreamsRunning to LinphoneCallPausing
[LH] result is ok
// Second resume
[LH] resumeCurrentCall 0x1508b2600 with state 9 locked 1 Cannot resume call 0x1508b2600 because another call is locking the sound resources.
[LH] result is fail
```

So after first resuming sound resources become locked despite I'm referencing to only one call only.
Is there any way to unlock resources manually? Can issue potentially be related not to client code but to SIP cooperation between client and server?

I'm using liblinphone v3.16.4

Regards

P.S. I know that it is more library related question and not client, so I'll appreciate if someone points me to the right place to post it :-)

**Comment by ReisBenjamin** [comment]
Hello,

Why do you need to check if the sound is locked ?
In Linphone we don't do it before pausing resuming a call.
It's possible (if you use CallKit) that CallKit messes with the AudioSession and so the sound locked status ?

Hope it helps,
Benjamin

**Comment by bivanov** [comment]
Hi @ReisBenjamin, thank you for your reply!

I've added additional checks for lock and status just to see where exactly things go wrong. 

And you're absolutely right - without CallKit issue is not present any more, so it is something with AudioSession indeed. Will look into it.

Thanks again!

Regards

**Comment by bivanov** [comment]
OK, so I guess I will reopen it as it appeared that issue is not CallKit-related. I was confused because it appeared that problem is not 100% of times reproducible and my tests without CallKit caught some successful attempts.

I've investigated a bit and found that method that blocks call from being resumed is [ice_in_progress](https://github.com/BelledonneCommunications/linphone/blob/784f2bb8ef17dad5f8abbed2dfd232033343b1bc/coreapi/linphonecall.c#L4338). I've checked source code: it looks for ICE state of current call. It appeared that during first attempt of hold/resume ICE state is IceStateFailed (I guess because I'm not adding any TURN/STUN servers right now), but during second attempt it is IceStateInProgress already for some reason. And with this ICE state it is impossible to resume paused call. 

I was told by telco engineer that in general ICE state should not change during the call itself, or so I understood him. 

So now reason of fail is unclear again. The only way I can control ICE is to set some servers in configuration. Or am I wrong here?

Regards

**Comment by ReisBenjamin** [comment]
You can also disable ICE if you don't want to use (i assume you don't since there's no stun server)

**Comment by bivanov** [comment]
Disabling ICE really helped for now. Though I think I will need ICE soon, so I still have to investigate this issue further.

And sometimes, quiet rarely, I cannot hear other side after resuming, but I guess this is very different story...

Thanks for help!

**Comment by ReisBenjamin** [comment]
When enabling ICE you'll need a STUN server and so the time taken by ice locking th resources may diminish and so the issue might not happen... Let's hope !

As for the sound when resuming you need to be sure callkit reactivated audio session before resuming a call.

**Comment by ReisBenjamin** [comment]
Hello,
Can this be closed ?

**Comment by bivanov** [comment]
Yep, I think so. 

Anyway, it looks like a bug in liblinphone for me when I may get IceStateInProgress even without configured ICE. But it is not client issue, so I close ticket. 

Thank you!
