### ISSUE TITLE
When network is changed in background mode . CallKit doesn't work.

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#277]
My CallKit is working fine .either in background mode or active mode. 

BUT When my app is in background and if I change the network from wifi to 3G or 3G to wifi. It stops receiving calls .I have to launch my app again and then go to background and it starts working. kindly share your thoughts.where can be the issue. 

I am using the latest code which you committed on 22 June 2017

https://github.com/BelledonneCommunications/linphone-iphone/commit/2dd9cfa16fe847827cdd001bfb2a2eeb8384df1e

**Comment by ReisBenjamin** [comment]
Hello,

The iOS 10 background policy forces the app to cut all channel when it goes in background.
Therefore the server cannot be awore of the changes of the IP address when the app changes network that's why it doesn't receive the push.

**Comment by TheEngineerz** [comment]
Ok. But is there any solution for this? as far as i read . Voip token dont change when we change the network. and if Voip device token is not changed then why it dont recieve push?
I mean how the other services like Whatsapp / Imo / viber are handling this.? 

If you think there is any any solution please must share your thoughts becuase it matters a lot Thanks

**Comment by ReisBenjamin** [comment]
After testing on my side I do not reproduce your issue.
I receive the push even after killing the app and switching between data and wifi.
Is your code iup to date ? are you using flexisip or another sip server ?

Thanks

**Comment by TheEngineerz** [comment]
I am using FreePBX. But where can be the issue ? is there any specific way of sending push or any type of flag?

**Comment by ReisBenjamin** [comment]
Hello,

Nothing's changed since this commit about push notification.
Do unregister when going in background ? If you do the server can't know to who send the push.
