### ISSUE TITLE
Own server receiveing username in minus when login

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#278]
I have implemented my owm sip server

Its working fine,but when I do a custom login with sip account ,I always get bad credentials.

I have to skip it and inside the app edit my username with my username in capital letters

Thanks

**Comment by ReisBenjamin** [comment]
Do you use caps when logging ?
It's not standard to have caps in a SIP address

**Comment by fedesenmartin** [comment]
Yes 

Ours username are in caps 

Is there any chance to disable it?Becuase when skip loggin and then change the username to uppercase the login is success

Thanks!

**Comment by ReisBenjamin** [comment]
I've made a change in the login view on last commit of linphone iphone : ce4421b5f3b3c67ab5588e78bbce428e4d501abe

Can you try it and tell me if it works ?

**Comment by fedesenmartin** [comment]
Will take a look and chceck if works!

Thanks

**Comment by fedesenmartin** [comment]
With the new code of the assistanteView

while trying to enter to my custom account i get :


xxxxx@xxx.org NOT configured for push notifications

Also when trying to do it with linphone server
xxxxx@sip.linphone.org NOT configured for push notifications


Im using and old version of the linphone ,Dont know if that may be

Regards

**Comment by ReisBenjamin** [comment]
Hello,

You need to also update the submodule sin sync with the commit indeed.
Please try with up to date submodules and come back to me.

Thanks

**Comment by ReisBenjamin** [comment]
For the sip.linphone.org account did you use **USE LINPHONE ACCOUNT** or **USE SIP ACCOUNT** and precise de sip.linphone.org domain ?

**Comment by ReisBenjamin** [comment]
Push notification or disable by default when using **USE SIP ACCOUNT** procedure.
You can change the default settings in assistant_external_sip.rc : 
Change 
		<entry name="refkey" overwrite="true"></entry>
by
		<entry name="refkey" overwrite="true">push_notification</entry>

**Comment by fedesenmartin** [comment]
Will give it a try!

Thanks

**Comment by fedesenmartin** [comment]
Hi how can I update the submodules without make changes on some modified .m and .h files?

**Comment by ReisBenjamin** [comment]
git submodule update --recursive --init and maybe resolve some merge conflicts.
Or go to each submodule stash your changes checkout master pull and unstash.

Regards
