### ISSUE TITLE
Call fail from native iOS phone book containing "( )"

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#279]
Contacts from native iPhone contact book error out because your system does not strip out the parentheses when dialing. 

so a number (555) 123-1234 errors out attempting to put it in a URL like 1%24555%26%20123%251234@test.linphone.org

instead is needs to say 15551231234@test.linphone.org
![simulator screen shot aug 4 2017 3 32 21 pm](https://user-images.githubusercontent.com/22788570/28986001-c2443f28-792a-11e7-8d80-dadb9924b0b6.png)

this is even so from your own built in contact book. I suggest you make the change on the (id)sender right before the string is sent to the dialer sequence.

**Comment by S0U1SB4N3** [comment]
this is even so from your own built in contact book. I suggest you make the change on the (id)sender right before the string is sent to the dialer sequence.

**Comment by ReisBenjamin** [comment]
Hello,
Did you link your account or create from a phone number ?
Is the field "Country Code" filled in your account settings ?
This is needed in order to normalize the phone number in a sip uri when dialing it.

Thanks

**Comment by S0U1SB4N3** [comment]
no I fixed it when it normalizes it it keeps the () and white spaces 
I modified a version of this :
NSString *originalPhoneNumber = @"(123) 123-456 abc";
NSCharacterSet *numbers = [[NSCharacterSet characterSetWithCharactersInString:@"0123456789"] invertedSet];
NSString *trimmedPhoneNumber = [originalPhoneNumber stringByTrimmingCharactersInSet:numbers];

and corrected it on my downloaded version. it works fine now.

**Comment by ReisBenjamin** [comment]
okay then i'll close this issue
