### ISSUE TITLE
./prepare.py error

### ISSUE THREAD

**Issue by Providnuk** [BelledonneCommunications/linphone-iphone#28]
When I run ./prepare.py I'm getting  next error:
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive
How to solve it?

**Comment by bagage** [comment]
Did you try it?
`git submodule sync && git submodule update --init --recursive`

**Comment by Providnuk** [comment]
Sure. When I run git submodule update --init --recursive, I got 
Cloning into 'submodules/bcg729'...
fatal: repository 'https://git.linphone.org/bcg729/' not found
Clone of 'git://git.linphone.org/bcg729' into submodule path 'submodules/bcg729' failed

**Comment by bagage** [comment]
OK, this is the real error. Can you try:
`cd /tmp/ && git://git.linphone.org/bcg729.git`

Does that work?

**Comment by Providnuk** [comment]
Cloning into 'bcg729'...
fatal: repository 'https://git.linphone.org/bcg729.git/' not found

**Comment by bagage** [comment]
Why URL scheme is `https`? Did you copy/paste my statement? If yes, what's your git version?

**Comment by Providnuk** [comment]
That is a problem. Thank you! Resolved.

**Comment by Providnuk** [comment]
By the way... 
Cloning into 'submodules/bcg729'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Operation timed out

Clone of 'git://git.linphone.org/bcg729' into submodule path 'submodules/bcg729' failed

**Comment by bagage** [comment]
Can you try again cloning the whole thing again please?

**Comment by Providnuk** [comment]
I tried, but got the same:
Ptah$ git submodule sync && git submodule update --init --recursive
Submodule 'Classes/KIF' (https://github.com/kif-framework/KIF) registered for path 'Classes/KIF'
Submodule 'submodules/bcg729' (git://git.linphone.org/bcg729.git) registered for path 'submodules/bcg729'
Submodule 'submodules/belle-sip' (git://git.linphone.org/belle-sip.git) registered for path 'submodules/belle-sip'
Submodule 'submodules/bzrtp' (git://git.linphone.org/bzrtp.git) registered for path 'submodules/bzrtp'
Submodule 'submodules/cmake-builder' (git://git.linphone.org/linphone-cmake-builder.git) registered for path 'submodules/cmake-builder'
Submodule 'submodules/cunit' (git://git.linphone.org/cunit.git) registered for path 'submodules/cunit'
Submodule 'submodules/externals/antlr3' (git://git.linphone.org/antlr3.git) registered for path 'submodules/externals/antlr3'
Submodule 'submodules/externals/ffmpeg' (git://git.linphone.org/ffmpeg.git) registered for path 'submodules/externals/ffmpeg'
Submodule 'submodules/externals/gsm' (git://git.linphone.org/gsm.git) registered for path 'submodules/externals/gsm'
Submodule 'submodules/externals/libvpx' (git://git.linphone.org/libvpx.git) registered for path 'submodules/externals/libvpx'
Submodule 'submodules/externals/libxml2' (git://git.gnome.org/libxml2) registered for path 'submodules/externals/libxml2'
Submodule 'submodules/externals/opencore-amr' (git://git.linphone.org/opencore-amr.git) registered for path 'submodules/externals/opencore-amr'
Submodule 'submodules/externals/openh264' (https://github.com/cisco/openh264) registered for path 'submodules/externals/openh264'
Submodule 'submodules/externals/opus' (git://git.linphone.org/opus.git) registered for path 'submodules/externals/opus'
Submodule 'submodules/externals/polarssl' (git://git.linphone.org/polarssl.git) registered for path 'submodules/externals/polarssl'
Submodule 'submodules/externals/speex' (git://git.linphone.org/speex.git) registered for path 'submodules/externals/speex'
Submodule 'submodules/externals/srtp' (git://git.linphone.org/srtp.git) registered for path 'submodules/externals/srtp'
Submodule 'submodules/externals/vo-amrwbenc' (git://git.linphone.org/vo-amrwbenc.git) registered for path 'submodules/externals/vo-amrwbenc'
Submodule 'submodules/externals/x264' (git://git.linphone.org/x264.git) registered for path 'submodules/externals/x264'
Submodule 'submodules/linphone' (git://git.linphone.org/linphone.git) registered for path 'submodules/linphone'
Submodule 'submodules/msamr' (git://git.linphone.org/msamr.git) registered for path 'submodules/msamr'
Submodule 'submodules/msopenh264' (git://git.linphone.org/msopenh264.git) registered for path 'submodules/msopenh264'
Submodule 'submodules/mssilk' (git://git.linphone.org/mssilk.git) registered for path 'submodules/mssilk'
Submodule 'submodules/mswebrtc' (git://git.linphone.org/mswebrtc.git) registered for path 'submodules/mswebrtc'
Submodule 'submodules/msx264' (git://git.linphone.org/msx264.git) registered for path 'submodules/msx264'
Cloning into 'Classes/KIF'...
remote: Counting objects: 4297, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 4297 (delta 3), reused 0 (delta 0), pack-reused 4288
Receiving objects: 100% (4297/4297), 4.61 MiB | 427.00 KiB/s, done.
Resolving deltas: 100% (2299/2299), done.
Checking connectivity... done.
Submodule path 'Classes/KIF': checked out '2e2e314a44aa9e3949fd54c75baff376af526493'
Cloning into 'submodules/bcg729'...
fatal: unable to connect to git.linphone.org:
git.linphone.org[0: 94.23.19.176]: errno=Operation timed out

Clone of 'git://git.linphone.org/bcg729.git' into submodule path 'submodules/bcg729' failed

**Comment by bagage** [comment]
Strange, I am not sure what's happening there... it seems you are the only one having troubles cloning it I am aware of, so I presume it's an issue on your side (firewall, proxy, etc.). Please try from another network access point?

**Comment by Providnuk** [comment]
You're exactly right! It's because of firewall. Thanks!

**Comment by LiangyongFShen** [comment]
@Providnuk Can you show the ways to solve the problem which happen to you ?
@bagage Had you meet this ?
Here what I meet on step 3 ：
 linphone-iphone hanzimacbook-pro$ git submodule sync && git submodule update --init --recursive
Synchronizing submodule url for 'Classes/KIF'
...
Synchronizing submodule url for 'submodules/msx264'
Cloning into 'Classes/KIF'...
fatal: unable to access 'https://github.com/kif-framework/KIF/': SSLRead() return error -9806
Clone of 'https://github.com/kif-framework/KIF' into submodule path 'Classes/KIF' failed

**Comment by jawnie** [comment]
Hello, 
I'm still getting this error : 
./prepare.py I'm getting next error:
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive

Even after running this: 

git submodule sync && git submodule update --init --recursive

**Comment by dadahua** [comment]
Excuse me, When I run “git submodule update --init --recursive” I'm getting next error:
ERROR:fatal: Needed a single revision
Unable to find current revision in submodule path 'submodules/mswebrtc/webrtc'
Failed to recurse into submodule path 'submodules/mswebrtc'
How to solve it?Please help me!

**Comment by dadahua** [comment]
Excuse me, When I run “git submodule update --init --recursive” I'm getting next error:
ERROR:fatal: Needed a single revision
Unable to find current revision in submodule path 'submodules/mswebrtc/webrtc'
Failed to recurse into submodule path 'submodules/mswebrtc'
How to solve it?Please help me!

**Comment by cgjuliejohn** [comment]
Well I'm getting
**ERROR: The following binaries are missing: android. Please install them.**
after executing ./prepare even after setting my env variables in bashrc

**Comment by whalemare** [comment]
the same error
**ERROR: The following binaries are missing: android. Please install them.**

**Comment by cgjuliejohn** [comment]
I got my issue resolved after setting the android path properly on the terminal. ie, ANDROID_HOME and PATH variables should be correctly specified

**Comment by tahirjilani** [comment]
In my case I noted another reason that caused issue for me. Read my comment at https://github.com/BelledonneCommunications/linphone-iphone/issues/85#issuecomment-360431668

**Comment by jareesh** [comment]
SOLVED!!!
 “git submodule update --init --recursive” I'm getting next error:
switch to public net, or turn of ur firewall
