### ISSUE TITLE
change default settings ?!

### ISSUE THREAD

**Issue by hadidez** [BelledonneCommunications/linphone-iphone#280]
hi all. how can i change default settings ?! for example if i need to change to off some codec, what should i to do !?
i changed default value in .plist but nothing happened.

**Comment by ReisBenjamin** [comment]
Have you try to re-install the app after changing the default settings ?
Thanks

**Comment by hadidez** [comment]
surly yes ...

**Comment by ReisBenjamin** [comment]
Which settings do you want to change ?
Dependings on the settings you might need to change the linphonerc and linphonerc-factory

**Comment by hadidez** [comment]
i need to change default codecs. i want to disable all codecs just opus.

**Comment by ReisBenjamin** [comment]
Try putting in your linphone rc : 
add_missing_audio_codecs=0 in [misc] section and
[audio_codec_0]
mime=opus
rate=48000
channels=2
enabled=1

**Comment by hadidez** [comment]
i did below but nothing happened:
[misc]
file_transfer_server_url=https://www.linphone.org:444/lft.php
max_calls=3
real_early_media=1
speex_16k_preference=0
speex_8k_preference=0
silk_16k_preference=0
[audio_codec_0]
mime=opus
rate=48000
channels=2
enabled=1

**Comment by ReisBenjamin** [comment]
You forgot to add add_missing_audio_codecs=0  in [misc] you should have : 

[misc]
file_transfer_server_url=https://www.linphone.org:444/lft.php
max_calls=3
real_early_media=1
speex_16k_preference=0
speex_8k_preference=0
silk_16k_preference=0
**add_missing_audio_codecs=0**

(...)

[audio_codec_0]
mime=opus
rate=48000
channels=2
enabled=1

You can also make this changes in linphonerc-factory

**Comment by hadidez** [comment]
thanks. it work like a charm ...

**Comment by hadidez** [comment]
hi, where can i get all linphonerc available parameters ? i want to can change settings just by changing linphonerc parameters.
thanks

**Comment by juliancorrea** [comment]
+1

**Comment by bnsy** [comment]
If I want to enable two codecs then what is the process

1. G722
2. G711u

Please suggest @hadidez @ghost @juliancorrea
