### ISSUE TITLE
Wrong CONTACT during REGISTER <> Push

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/linphone-iphone#282]
I'm trying to configure push for the Linphone I just compiled for iOS. However, when it registers it sends something like this (instead of 2 seperate contacts):

Contact: <sip:242683@172.17.106.190:55522;app-id=org.linphone.uz.voip.dev;pn-type=apple;pn-tok=SECRETTOKEN;pn-msg-str=IM_MSG;pn-call-str=IC_MSG;pn-call-snd=notes_of_the_optimistic.caf;pn-msg-snd=msg.caf;pn-timeout=0;pn-silent=1;transport=udp>;+sip.instance="<urn:uuid:d7de811f-b0a8-4e6b-addf-423137603356>"

Also, Asterisk reports an error:

> WARNING[79953]: res_pjsip_registrar.c:457 rx_task_core: Failed to validate contacts in REGISTER request from '242683'

On the FlexiSIP page, I've noticed the following:

> If it is not working, check application code. linphone_proxy_config_set_contact_uri_parameters() should be invoked by application: didRegisterForRemoteNotificationsWithDeviceToken:.

Can someone tell me how to do this? I've found the following in "linphone-iphone/Classes/LinphoneAppDelegate.m":

> 
> - (void)application:(UIApplication *)application
> 	didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
> 	LOGI(@"%@ : %@", NSStringFromSelector(_cmd), deviceToken);
> 	[LinphoneManager.instance setPushNotificationToken:deviceToken];
> }

**Comment by ReisBenjamin** [comment]
Hello,

Why do you want 2 contacts ?
ONe register should only create contact.

**Comment by driesken** [comment]
Thanks. Yeah sorry about that, I took the wrong conclusion.

The Asterisk error (preventing a correct REGISTER) was solved by modifying PJSIP:
/usr/local/src/pjproject-2.4.5/pjsip/include/pjsip/sip_config.h   :  define PJSIP_MAX_URL_SIZE              256
=> increased this to 1024.

However, I'm stuck with the push implementation.

I've compiled an app signed as iOS Developer. I've then generated a certificate using the following tool:
[](https://github.com/fastlane/fastlane/tree/master/pem#readme)

Afterwards, I've connected the iPhone which has the developersversion of Linphone installed and captured the REGISTER which contains the Developer Device Token. I've noticed that the app-id=org.linphone.uz.voip.dev doesn't fully match with the "org.linphone.uz" app id? Is this a problemen?

I've tried to generate a pushalert using the flexisip_pusher, but that throws an error:

`/opt/belledonne-communications/bin/flexisip_pusher --appid org.linphone.uz --pntype apple --pntok PNTOKASINREGISTER --debug`

> Writing logs in : /var/opt/belledonne-communications/log/flexisip/FlexisipLogs_pusher.log
> 2017-08-21 15:50:41:082 flexisip-debug-Searching push notification client on dir [/etc/flexisip/apn]
> 2017-08-21 15:50:41:083 flexisip-debug-Certificate /etc/flexisip/apn/development_org.linphone.uz.pem has a valid expiration: Aug 21 12:12:13 2018 GMT.
> 2017-08-21 15:50:41:083 flexisip-debug-Adding ios push notification client [development_org.linphone.uz]
> 2017-08-21 15:50:41:083 flexisip-debug-Push notification payload is {"aps":{"alert":{"loc-key":"IM_MSG","loc-args":["Pusher"]},"sound":"msg.caf","badge":1},"call-id":"","pn_ttl":2592000}
> **2017-08-21 15:50:41:083 flexisip-error-No push notification client available for push notification request : 0xc8c568**
> Segmentation fault (core dumped)
> 

Could you point me in the right direction?
Yeah sorry about that, I took the wrong conclusion.

The Asterisk error (preventing a correct REGISTER) was solved by modifying PJSIP:
/usr/local/src/pjproject-2.4.5/pjsip/include/pjsip/sip_config.h   :  define PJSIP_MAX_URL_SIZE              256
=> increased this to 1024.

However, I'm stuck with the push implementation.

I've compiled an app signed as iOS Developer. I've then generated a certificate using the following tool:
[](https://github.com/fastlane/fastlane/tree/master/pem#readme)

Afterwards, I've connected the iPhone which has the developersversion of Linphone installed and captured the REGISTER which contains the Developer Device Token. I've noticed that the app-id=org.linphone.uz.voip.dev doesn't fully match with the "org.linphone.uz" app id? Is this a problemen?

I've tried to generate a pushalert using the flexisip_pusher, but that throws an error:

`/opt/belledonne-communications/bin/flexisip_pusher --appid org.linphone.uz --pntype apple --pntok PNTOKASINREGISTER --debug`

> Writing logs in : /var/opt/belledonne-communications/log/flexisip/FlexisipLogs_pusher.log
> 2017-08-21 15:50:41:082 flexisip-debug-Searching push notification client on dir [/etc/flexisip/apn]
> 2017-08-21 15:50:41:083 flexisip-debug-Certificate /etc/flexisip/apn/development_org.linphone.uz.pem has a valid expiration: Aug 21 12:12:13 2018 GMT.
> 2017-08-21 15:50:41:083 flexisip-debug-Adding ios push notification client [development_org.linphone.uz]
> 2017-08-21 15:50:41:083 flexisip-debug-Push notification payload is {"aps":{"alert":{"loc-key":"IM_MSG","loc-args":["Pusher"]},"sound":"msg.caf","badge":1},"call-id":"","pn_ttl":2592000}
> **2017-08-21 15:50:41:083 flexisip-error-No push notification client available for push notification request : 0xc8c568**
> Segmentation fault (core dumped)
> 

Can you point me in the right direction?

**Comment by driesken** [comment]
Hi Benjamin,

Thanks. I've tried your suggestion but it looks like the Device Token doesn't match for some reason?

> 2017-08-21 16:06:38:934 flexisip-debug-PushNotificationClient org.linphone.uz.voip.dev.pem PNR 0x1f1f5d8 running, queue_size=0
> 2017-08-21 16:06:38:935 flexisip-debug-PushNotificationClient org.linphone.uz.voip.dev.pem next, queue_size=1
> 2017-08-21 16:06:39:361 flexisip-debug-PushNotificationClient org.linphone.uz.voip.dev.pem PNR 0x1f1f5d8 sent 163/163 data
> 2017-08-21 16:06:39:361 flexisip-debug-PushNotificationClient org.linphone.uz.voip.dev.pem PNR 0x1f1f5d8 waiting for server response
> 2017-08-21 16:06:39:499 flexisip-debug-PushNotificationClient org.linphone.uz.voip.dev.pem PNR 0x1f1f5d8 read 6 data:
> 2017-08-21 16:06:39:499 flexisip-warning-PushNotificationClient org.linphone.uz.voip.dev.pem PNR 0x1f1f5d8 failed: Invalid server response: PNR 0x1f1f5d8 with identifier 1 failed with error 8 (Invalid token)

The strange thing is that it doesn't seem able to send the push using pushtry.com (even though I'm not receiving it) when Production is selected (even though it's a development certificate?)

**Comment by ReisBenjamin** [comment]
Did you rename your certificate "org.linphone.uz.voip.dev.pem" ?

**Comment by driesken** [comment]
Yes I did:

> 2017-08-21 16:24:39:616 flexisip-debug-Certificate /etc/flexisip/apn/org.linphone.uz.voip.dev.pem has a valid expiration: Aug 21 14:12:00 2018 GMT.

**Comment by ReisBenjamin** [comment]
If you use a development certificate you should not use production, only for a production certificate.

**Comment by driesken** [comment]
Yes, that's the strange thing. I want to sent a push using the (default?) developer gateway (gateway.sandbox.push.apple.com?) in flexisip_pusher, however it isn't working?

**Comment by ReisBenjamin** [comment]
I'm not sure your using the right certificate, i see you use Apple Push services, this is a deprecated service. You need to use VoIP certificate instead.
Can you try with this new certificate ?

Thanks

**Comment by driesken** [comment]
Thanks a lot! The VOIP certificate fixed my issue!

**Comment by ReisBenjamin** [comment]
Great !

I'll close this thread then.

Regards

**Comment by dipenpatel235** [comment]
hello @driesken 
i am also stuck in that.
can u please little help me?

Thanks
