### ISSUE TITLE
Issues with CallKit End & Answer button while screen is locked

### ISSUE THREAD

**Issue by iJasonWade** [BelledonneCommunications/linphone-iphone#283]
So when I have the screen to my iPhone locked with one call through the sip stack active and then receive another call through the sip stack and press end & answer, the call is answering but the audio stream is either lost or never established, I see the following logs:

[Error] belle-sip/bctbx_file_read: Error read Operation not permitted
[Error] lib/linphone_sql_request: statement INSERT INTO call_history VALUES(NULL,'"redacted" <sip:redacted@redacted>','sip: redacted@ redacted',1,20,1502482581,1502482583,0,0,4.980402,'20170811201621046997-bcc453bf77f3c8a9bcf4629e3c8dee0f',NULL); -> error sqlite3_exec(): disk I/O error.
[Error] lib/no such method on filter MSAUWrite, fid=16394 method index=2

**Comment by ReisBenjamin** [comment]
Hello,

i'll need fulllogs to really what's the problem.
Internally in Linphone we decided to managa only one call with callkit and the others via our own app because multicall is badly handled by callkit.
Perhaps you should do the same.
Do you wait for CallKit to go into providerDidActivateAudioSession before accepting a call ?

Thanks

**Comment by iJasonWade** [comment]
So how do you handle multiple calls when the screen is locked? In that scenario they are forced through CallKit so I don't understand how you could handle them in your own app?

**Comment by ReisBenjamin** [comment]
Only one call is going through CallKit UI if there's alreay one call then we use the Linphone UI as before CallKit.

**Comment by iJasonWade** [comment]
I'm not trying to be difficult but that is impossible for you to control if the users device is locked. There is not a way to programmatically unlock their device and launch an app...

**Comment by ReisBenjamin** [comment]
You can try on th elast release, if you receive 2 calls whith phone locked, first one is displayed with Callkit and second one is displayed using a notification and you can either answer or decline the call with the action notifications, as for an incoming message for example.

**Comment by iJasonWade** [comment]
So what about the scenario where a user declined push notifications for Linphone?

**Comment by ReisBenjamin** [comment]
In this case it's indeed impossible not to use CallKit to have call when in background or when the app is killed. You can either allow only one call or use CallKit but as you said it does'nt manage multiple call well and there's nothing you can do.
