### ISSUE TITLE
Need to display caller ID Number not name in Call Kit 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#289]
update.remoteHandle = [[CXHandle alloc] initWithType:CXHandleTypeGeneric value:handle];

this gets the caller ID Name but not the number 
I would like to display "sip:1234567892@sip.linphone.org" instead of 
"John Doe"

when the call comes up.

**Comment by S0U1SB4N3** [comment]
https://camo.githubusercontent.com/64bc01422962917c7b76367eedc01c1140983b9b/687474703a2f2f692e696d6775722e636f6d2f324362494431422e6a7067

**Comment by S0U1SB4N3** [comment]
![687474703a2f2f692e696d6775722e636f6d2f324362494431422e6a7067](https://user-images.githubusercontent.com/22788570/29537302-e13786ec-8686-11e7-9c9b-daa3bb8ff7f8.jpeg)

**Comment by S0U1SB4N3** [comment]
replace "Network Operations" with sip address "sip:1234567891@sip.linphone.org"

**Comment by ReisBenjamin** [comment]
Hello,

Try in LinphoneManager.m method **- (void)onCall:(LinphoneCall \*)call StateChanged:(LinphoneCallState)state withMessage:(const char \*)message** 
Instead of : **NSString \*address = [FastAddressBook displayNameForAddress:addr];**

You can do **NSString \*address = [NSString stringWithUTF8String:linphone_address_get_username(addr)];** that will display **1234567891**

Or : **NSString \*address = [NSString stringWithUTF8String:linphone_address_as_string_uri_only(addr)];** that will display **sip:123456791@sip.linphone.org**

**Comment by S0U1SB4N3** [comment]
is it possible to add both the user name and the sip address to this ? appending a new line and the sip address ? 

your last one let me change from one to the other just fine so that was a good fix :) 

Jon Doe 
1234567891

would be ideal

**Comment by S0U1SB4N3** [comment]
NSString *address1 = [FastAddressBook displayNameForAddress:addr];
    NSString *address2 = [NSString stringWithUTF8String:linphone_address_get_username(addr)];
    NSString *address = [NSString stringWithFormat:@"%@\r%@", address1,address2];

I've tried this but still shows one line

**Comment by S0U1SB4N3** [comment]
ok this is close but not ideal 
results 
John Doe | 1234567891
all on same line using const LinphoneAddress *addr = linphone_call_get_remote_address(call);
	NSString *address1 = [FastAddressBook displayNameForAddress:addr];
    NSString *address2 = [NSString stringWithUTF8String:linphone_address_get_username(addr)];
    NSString *address=[NSString stringWithFormat:@"%@ | %@",address1,address2];

is there a way to put in 2 lines for this ?

**Comment by S0U1SB4N3** [comment]
I've used the ]n but it just goes back to the first line only.

**Comment by ReisBenjamin** [comment]
Hello,

No the CallKit UI only allows one line, you can either choose one of the two info or seperate them as you did by a character.

Can i close this issue ?

Thanks

**Comment by S0U1SB4N3** [comment]
yes thank you :)
ill post here if I find a better solution
