### ISSUE TITLE
Substitute + in phone numbers doesn't work

### ISSUE THREAD

**Issue by antongvrlnkv** [BelledonneCommunications/linphone-iphone#290]
I've switched "Substitute + in phone numbers" to ON, but there is still "+" in packets in Wireshark

<img width="786" alt="screen shot 2017-08-21 at 5 20 17 pm" src="https://user-images.githubusercontent.com/11135741/29538985-1c0b83c2-8696-11e7-9d3f-4f1b3a16bd19.png">

**Comment by ReisBenjamin** [comment]
What does the linphone logs and UA say ?

**Comment by antongavrilenkov** [comment]
"Substitute +" works unclear when I call to different countries:
Russia: +78637253663 -> +78637253663
Ukraine: +3803728904455 -> 003803728904455
USA: +19295758385 -> 01119295758385
Uzbekistan: +998717778833 -> 8998717778833

Also maybe it could be better if the + substitution result will be invisible in "calling history"

[log.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/1242523/log.txt)

**Comment by ReisBenjamin** [comment]
Hello,

I reproduce your issue i'll update you once it's fixed. However the histroy must show the address that has been called so we won't remove the + substitution.

Regards
