### ISSUE TITLE
Call disconnected after 30 sec when I called from iPhone to Android device.

### ISSUE THREAD

**Issue by prasenraj** [BelledonneCommunications/linphone-iphone#292]
Devices are connected to IP address, When I called from iPhone to the Android device after  30 sec call is disconnected automatically but when I call from Android to iPhone device then it is working properly. How to fix this problem?

**Comment by ReisBenjamin** [comment]
Hello,

Did you change your branch ? As said on your pull request the dev_callkit branch doesn't work and has been abandonned and is now erased.
I need logs to see what happens.

Thanks

**Comment by prasenraj** [comment]
Now everything is working fine. thank you
