### ISSUE TITLE
Add new LogOut button, previous data is not clean.

### ISSUE THREAD

**Issue by prasenraj** [BelledonneCommunications/linphone-iphone#293]
I added a new log out button in iPhone when I clicked on that button app is closed but after that when I called from another device on that number, the call is coming. How to fix when I clicked on log out button then previous data and everything will be clear and call is not coming?

**Comment by ReisBenjamin** [comment]
You need to disable push notification in your account settings.

**Comment by prasenraj** [comment]
If I disable push notification, when I press the home button and open a new app, then how to get notification .

**Comment by ReisBenjamin** [comment]
Push notification is only used to wake the app up when it's in background or the app is killed to display an incoming call or message.
Since it's what you want to do i think it's a good solution, no ?

**Comment by prasenraj** [comment]
I want to do exactly When I click on sign out button then everything will be reset, message, call log. if I do not again sign in the apps then no call an message will come. how to do that?

**Comment by ReisBenjamin** [comment]
You'll need manually unregister your account (You can see the code of the unregister button of your account settings).
You'll also need to manyally clear all history and call logs with the functions : 
linphone_core_get_call_logs
linphone_call_log_unref
linphone_core_get_chat_rooms
linphone_chat_room_delete_history
linphone_chat_room_unref

**Comment by prasenraj** [comment]
`-(IBAction)onSignOutClick:(id)sender
{

    [settingsStore removeAccount];
    [self recomputeAccountLabelsAndSync];
    linphone_core_clear_proxy_config(LC);
    [LinphoneManager.instance removeAllAccounts];
   linphone_core_reset_log_collection();
    linphone_core_get_call_logs(LC);
    linphone_core_get_chat_rooms(LC);
    [LinphoneManager.instance destroyLinphoneCore];
   [LinphoneManager.instance resetLinphoneCore];
    const MSList *rooms = linphone_core_get_chat_rooms(LC);
    while (rooms) {
        const MSList *messages = linphone_chat_room_get_history(rooms->data, 0);
        while (messages) {
            LinphoneChatMessage *msg = messages->data;
            if (!linphone_chat_message_is_outgoing(msg)) {
                [LinphoneManager setValueInMessageAppData:nil forKey:@"localimage" inMessage:messages->data];
            }
            messages = messages->next;
        }
        rooms = rooms->next;
    }

    linphone_core_remove_proxy_config(LC, new_config);

       [_settingsController.navigationController popViewControllerAnimated:NO];
      [PhoneMainView.instance changeCurrentView:AssistantView.compositeViewDescription];`




this is my code on sign out button.....when I clicked on the sign out button account is deleted but when someone calling my phone is ringing..How to do unregister account and deleted all the history? please help me .thank you

**Comment by ReisBenjamin** [comment]
for all proxy config : 
	BOOL isDefault = (linphone_core_get_default_proxy_config(LC) == config);

	const LinphoneAuthInfo *ai = linphone_proxy_config_find_auth_info(config);
	linphone_core_remove_proxy_config(LC, config);
	if (ai) {
		linphone_core_remove_auth_info(LC, ai);
	}
	[self setInteger:-1 forKey:@"current_proxy_config_preference"];

	if (isDefault) {
		// if we removed the default proxy config, set another one instead
		if (linphone_core_get_proxy_config_list(LC) != NULL) {
			linphone_core_set_default_proxy_index(LC, 0);
		}
	}
	[self transformLinphoneCoreToKeys];

**Comment by prasenraj** [comment]
LinphoneProxyConfig* config;

[Error] linphone_core_remove_proxy_config: LinphoneProxyConfig [0x0] is not known by LinphoneCore (programming error?)

**Comment by ReisBenjamin** [comment]
You miss an include probably.
You also need to get all proxy config in linphone core

**Comment by prasenraj** [comment]
Thank you, sir
      it's working but problem is that when log out from an account then call is receiving and once login with the different number then its just change the number only not delete message history.
I just show u two snapshot..

https://user-images.githubusercontent.com/25590704/29777518-f49e6c3e-8c29-11e7-9956-8193190ab460.png
https://user-images.
![screen shot 2017-08-28 at 7 43 37 pm](https://user-images.githubusercontent.com/25590704/29777555-205485b6-8c2a-11e7-9ee8-f4a2f9ac99fd.png

**Comment by ReisBenjamin** [comment]
DO you remove all proxy config ?
Do you see unregistration in logs ?
Do you call  linphone_chat_room_delete_history for all chatrooms ?

**Comment by prasenraj** [comment]
please, sir, help me
how to do all those things?
please help me

**Comment by prasenraj** [comment]
`LinphoneProxyConfig *config = bctbx_list_nth_data(linphone_core_get_proxy_config_list(LC),
													  [self integerForKey:@"current_proxy_config_preference"]);

	BOOL isDefault = (linphone_core_get_default_proxy_config(LC) == config);
    

    linphone_proxy_config_edit(config);
    linphone_proxy_config_set_expires(config, 0);
    linphone_proxy_config_done(config);
    linphone_core_terminate_all_calls(LC);
   
   
    [LinphoneManager.instance destroyLinphoneCore];
const LinphoneAuthInfo *ai = linphone_proxy_config_find_auth_info(config);
	linphone_core_remove_proxy_config(LC, config);
    
	if (ai) {
		linphone_core_remove_auth_info(LC, ai);
	}
	[self setInteger:-1 forKey:@"current_proxy_config_preference"];

	if (isDefault) {
		if we removed the default proxy config, set another one instead
		if (linphone_core_get_proxy_config_list(LC) != NULL) {
			linphone_core_set_default_proxy_index(LC, 0);
		}
	}
	[self transformLinphoneCoreToKeys];



`

The account is removed but call and msg coming. How to stop call and message after remove account.Please help me. Thank you.

**Comment by ReisBenjamin** [comment]
Try : 
bctbx_list_t *configs = linphone_core_get_proxy_config_list(LC);
while(configs) {
	linphone_proxy_config_edit(config);
	linphone_proxy_config_set_expires(config, 0);
	linphone_proxy_config_enable_register(config, FALSE);
	linphone_proxy_config_done(config);
	const LinphoneAuthInfo *ai = linphone_proxy_config_find_auth_info(config);
	if (ai) {
		linphone_core_remove_auth_info(LC, ai);
	}
	linphone_core_remove_proxy_config(LC, config);
}
linphone_core_terminate_all_calls(LC);
[LinphoneManager.instance destroyLinphoneCore];

Once you tried that, make sure in the log you see a register with an expire set to 0 for every account you have.

**Comment by prasenraj** [comment]
Thank you 
 It's working fine...

**Comment by ReisBenjamin** [comment]
Great !

I'll close the issue then.
Have fun with Linphone
