### ISSUE TITLE
How to unregister with specific Call-ID?

### ISSUE THREAD

**Issue by bofuliu** [BelledonneCommunications/linphone-iphone#295]
Hi, 
If I have remained 4 Call-ID saved in App, such as 
1.  ~AAAAA
2. ~CCCCC
3. ~BBBBB
4. ~CCCCC

How can I unregister one of them?

**Comment by ReisBenjamin** [comment]
Hello,

Could you be more specific ? Call-ID are not registered they only identify a SIP dialog.
Is it an account you want to unregister ?

Thanks

**Comment by bofuliu** [comment]
Hi ReisBenjamin, 

I have all Call-ID registration information. (e.g all of them contact URI). 
Thank you ReisBenjamin for you every time kindly answer my problem. :)

**Comment by ReisBenjamin** [comment]
Could you tell me with an example what you want to do ? With context and all ?

**Comment by ReisBenjamin** [comment]
Unanswered
Reopen when answered
