### ISSUE TITLE
Linphone Assistant view forces lower case on sip account creation 

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#296]
I have read through some past issues reported and it was stated that it forces the lowercase for new usernames when you signup for a linphone account, however this is not the case. It forces lowercase for all new users even usernames for third party sip accounts. Can you tell me where your code forces the lower case and what we can change it to match case ?

**Comment by S0U1SB4N3** [comment]
example user name on creation page might be: username = sip-UsErNaMe123 when I hit the login button it automatically translates my input to username = sip-username123 
even when I'm using the assistant "use sip account" which is where you can enter non-linphone.org accounts.

**Comment by ReisBenjamin** [comment]
Hi, 

Is your code up to date ?
I do not reproduce your issue, on "use sip account" the higher char are kept this way.
Plus, normally a sip address isn't case sensitive so your server should identify you even if your username is in lower case.

Thanks

**Comment by S0U1SB4N3** [comment]
This is on the native Apple Store release most current and I have to go back into settings to add uppercase as it strips it out on creation 

See screenshots 

![Image](http://i.imgur.com/Ny9HCjF.jpg)

![Image](http://i.imgur.com/jj3xlJ2.jpg)

![Image](http://i.imgur.com/54ltJLg.jpg)

![Image](http://i.imgur.com/k1Gzb6Z.jpg)

![Image](http://i.imgur.com/bqnsMjr.jpg)

![Image](http://i.imgur.com/zKTp3lx.jpg)

![Image](http://i.imgur.com/mAaL5Nm.jpg)

**Comment by S0U1SB4N3** [comment]
Last two screen shots are in reverse order

**Comment by S0U1SB4N3** [comment]
This can be any domain address google.com sip.sip.com Etc... the results for the user name are the same and forced lower case

**Comment by ReisBenjamin** [comment]
Hello,

Cold you try again with the latest code from the master branch ?
As i said before i tried with latest commit and i managed to have high case username in my username so we have probably already fixed it.

Regards

**Comment by S0U1SB4N3** [comment]
This one works as you stated. Debugging a few address issues you can close this issue

**Comment by ReisBenjamin** [comment]
Ok i'll close the issue.

Regards
