### ISSUE TITLE
Unable to edit or modify code for JNI library

### ISSUE THREAD

**Issue by Aashish09** [BelledonneCommunications/linphone-iphone#30]
Hello,
I am using linphone android library for video calling in my application and i have created most of the application but now I am getting an issue over here. In video calling, I need to see captured video over full scrren but that screen showing black strips on top and bottom and I am unable to remove those strips because JNI library including native code which is compiled in .so file and as you know I don't have any control on those files therefore I can not modify or edit that code.
So, please tell me how can I implement the full screen video chat to use similar code or give me any suggetion which help me to complete my application.
Below link provide you the idea that what am i looking for, please look that and provide me the solution.
Link - http://media.wiley.com/Lux/12/411812.image1.jpg
Please reply as soon as possible, I am waiting for help.

Thank you,
Aashish Sharma

**Comment by bagage** [comment]
This is linphone iphone, not linphone android. Please use the mailing list to report bugs on android, thanks.
