### ISSUE TITLE
on logout button I got Error

### ISSUE THREAD

**Issue by prasenraj** [BelledonneCommunications/linphone-iphone#300]
//for Delete all call logs.... 
const MSList *list = linphone_core_get_call_logs(LC);
    LinphoneCallLog *log = (LinphoneCallLog *)list->data;
    linphone_core_remove_call_log(LC, log);

  // for delete all chat history  
    const MSList *rooms = linphone_core_get_chat_rooms(LC);
    const MSList *item = rooms;
    while (item) {
    if(item == NULL)
    {
       
    }
    else{
        LinphoneChatRoom *room = (LinphoneChatRoom *)item->data;
        if (room) {
            
            
            linphone_chat_room_delete_history(room);
         
        }
        item = item->next;
   }
    }
[settingsStore removeAccount];

 [LinphoneManager.instance resetLinphoneCore];

       [_settingsController.navigationController popViewControllerAnimated:NO];
      [PhoneMainView.instance changeCurrentView:AssistantView.compositeViewDescription];

error...
Crash: Linphone core not initialized yet
2017-09-04 16:11:30.486 linphone[7744:177539] Stack Trace: (
	0   CoreFoundation                      0x000000010a17034b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001096e721e objc_exception_throw + 48
	2   linphone                            0x0000000104e329ca +[LinphoneManager getLc] + 106
	3   linphone                            0x0000000104dfa615 -[HistoryListTableView loadData] + 997
	4   linphone                            0x0000000104dfa03a -[HistoryListTableView coreUpdateEvent:] + 58
	5   CoreFoundation                      0x000000010a10e19c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x000000010a10e09b _CFXRegistrationPost + 427
	7   CoreFoundation                      0x000000010a10de02 ___CFXNotificationPost_block_invoke + 50
	8   CoreFoundation                      0x000000010a0d0ea2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
	9   CoreFoundation                      0x000000010a0cff3b _CFXNotificationPost + 667
	10  Foundation                          0x00000001051860ab -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	11  linphone                            0x0000000104e3f1e7 -[LinphoneManager destroyLinphoneCore] + 919
	12  linphone                            0x0000000104e3f36b -[LinphoneManager resetLinphoneCore] + 43
	13  linphone                            0x0000000104dd2495 -[SideMenuView onSignOutClick:] + 485
	14  UIKit                               0x000000010aae85b8 -[UIApplication sendAction:to:from:forEvent:] + 83
	15  UIKit                               0x000000010ac6dedd -[UIControl sendAction:to:forEvent:] + 67
	16  UIKit                               0x000000010ac6e1f6 -[UIControl _sendActionsForEvents:withEvent:] + 444
	17  UIKit                               0x000000010ac6d0f2 -[UIControl touchesEnded:withEvent:] + 668
	18  UIKit                               0x000000010ab55ce1 -[UIWindow _sendTouchesForEvent:] + 2747
	19  UIKit                               0x000000010ab573cf -[UIWindow sendEvent:] + 4011
	20  UIKit                               0x000000010ab0463f -[UIApplication sendEvent:] + 371
	21  UIKit                               0x000000010b2f671d __dispatchPreprocessedEventFromEventQueue + 3248
	22  UIKit                               0x000000010b2ef3c7 __handleEventQueue + 4879
	23  CoreFoundation                      0x000000010a115311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x000000010a0fa59c __CFRunLoopDoSources0 + 556
	25  CoreFoundation                      0x000000010a0f9a86 __CFRunLoopRun + 918
	26  CoreFoundation                      0x000000010a0f9494 CFRunLoopRunSpecific + 420
	27  GraphicsServices                    0x000000010d9dfa6f GSEventRunModal + 161
	28  UIKit                               0x000000010aae6964 UIApplicationMain + 159
	29  linphone                            0x0000000104dbeb2e main + 126
	30  libdyld.dylib                       0x000000010c54968d start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
2017-09-04 16:11:30.488 linphone[7744:177539] *** Terminating app due to uncaught exception 'LinphoneCoreException', reason: 'Linphone core not initialized yet'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a17034b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001096e721e objc_exception_throw + 48
	2   linphone                            0x0000000104e329ca +[LinphoneManager getLc] + 106
	3   linphone                            0x0000000104dfa615 -[HistoryListTableView loadData] + 997
	4   linphone                            0x0000000104dfa03a -[HistoryListTableView coreUpdateEvent:] + 58
	5   CoreFoundation                      0x000000010a10e19c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x000000010a10e09b _CFXRegistrationPost + 427
	7   CoreFoundation                      0x000000010a10de02 ___CFXNotificationPost_block_invoke + 50
	8   CoreFoundation                      0x000000010a0d0ea2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 2018
	9   CoreFoundation                      0x000000010a0cff3b _CFXNotificationPost + 667
	10  Foundation                          0x00000001051860ab -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	11  linphone                            0x0000000104e3f1e7 -[LinphoneManager destroyLinphoneCore] + 919
	12  linphone                            0x0000000104e3f36b -[LinphoneManager resetLinphoneCore] + 43
	13  linphone                            0x0000000104dd2495 -[SideMenuView onSignOutClick:] + 485
	14  UIKit                               0x000000010aae85b8 -[UIApplication sendAction:to:from:forEvent:] + 83
	15  UIKit                               0x000000010ac6dedd -[UIControl sendAction:to:forEvent:] + 67
	16  UIKit                               0x000000010ac6e1f6 -[UIControl _sendActionsForEvents:withEvent:] + 444
	17  UIKit                               0x000000010ac6d0f2 -[UIControl touchesEnded:withEvent:] + 668
	18  UIKit                               0x000000010ab55ce1 -[UIWindow _sendTouchesForEvent:] + 2747
	19  UIKit                               0x000000010ab573cf -[UIWindow sendEvent:] + 4011
	20  UIKit                               0x000000010ab0463f -[UIApplication sendEvent:] + 371
	21  UIKit                               0x000000010b2f671d __dispatchPreprocessedEventFromEventQueue + 3248
	22  UIKit                               0x000000010b2ef3c7 __handleEventQueue + 4879
	23  CoreFoundation                      0x000000010a115311 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x000000010a0fa59c __CFRunLoopDoSources0 + 556
	25  CoreFoundation                      0x000000010a0f9a86 __CFRunLoopRun + 918
	26  CoreFoundation                      0x000000010a0f9494 CFRunLoopRunSpecific + 420
	27  GraphicsServices                    0x000000010d9dfa6f GSEventRunModal + 161
	28  UIKit                               0x000000010aae6964 UIApplicationMain + 159
	29  linphone                            0x0000000104dbeb2e main + 126
	30  libdyld.dylib                       0x000000010c54968d start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ReisBenjamin** [comment]
You should'nt call [LinphoneManager.instance resetLinphoneCore];
But [LinphoneManager.instance destroyLinphoneCore];
And you should call it at the very end of your code.
You don't need this two lines : 
[_settingsController.navigationController popViewControllerAnimated:NO];
 [PhoneMainView.instance changeCurrentView:AssistantView.compositeViewDescription];

**Comment by prasenraj** [comment]
last two used for come back to assistantView when I was clicked on logout button.
First-time log out successfully but once again I want login with different User then getting an error on that line in assistantView 
`LinphoneProxyConfig *config = linphone_core_create_proxy_config(LC)`

 Crash: Linphone core not initialized yet
2017-09-06 13:13:38.733 linphone[2938:2422936] Stack Trace: (
	0   CoreFoundation                      0x2516b933 <redacted> + 150
	1   libobjc.A.dylib                     0x24906e17 objc_exception_throw + 38
	2   linphone                            0x0011e167 +[LinphoneManager getLc] + 140
	3   linphone                            0x0016159b -[AssistantView connectionDidFinishLoading:] + 2346
	4   CFNetwork                           0x257af325 <redacted> + 56
	5   CFNetwork                           0x257af2dd <redacted> + 184
	6   CFNetwork                           0x257af3d1 <redacted> + 36
	7   CFNetwork                           0x25669aff <redacted> + 78
	8   CFNetwork                           0x257288b7 <redacted> + 70
	9   libdispatch.dylib                   0x026c7b6b _dispatch_client_callout + 22
	10  libdispatch.dylib                   0x026cf719 _dispatch_block_invoke + 468
	11  CFNetwork                           0x2565ab07 <redacted> + 18
	12  CoreFoundation                      0x2507ac61 CFArrayApplyFunction + 36
	13  CFNetwork                           0x2565a9ef <redacted> + 182
	14  CFNetwork                           0x2565a8b9 <redacted> + 216
	15  CFNetwork                           0x2565a751 <redacted> + 48
	16  CoreFoundation                      0x2512ddff <redacted> + 14
	17  CoreFoundation                      0x2512d9ed <redacted> + 452
	18  CoreFoundation                      0x2512bd5b <redacted> + 794
	19  CoreFoundation                      0x2507b229 CFRunLoopRunSpecific + 520
	20  CoreFoundation                      0x2507b015 CFRunLoopRunInMode + 108
	21  GraphicsServices                    0x2666bac9 GSEventRunModal + 160
	22  UIKit                               0x2974f189 UIApplicationMain + 144
	23  linphone                            0x000a7f21 main + 124
	24  libdyld.dylib                       0x24d23873 <redacted> + 2
)
2017-09-06 13:13:38.736 linphone[2938:2422936] *** Terminating app due to uncaught exception 'LinphoneCoreException', reason: 'Linphone core not initialized yet'
*** First throw call stack:
(0x2516b91b 0x24906e17 0x11e167 0x16159b 0x257af325 0x257af2dd 0x257af3d1 0x25669aff 0x257288b7 0x26c7b6b 0x26cf719 0x2565ab07 0x2507ac61 0x2565a9ef 0x2565a8b9 0x2565a751 0x2512ddff 0x2512d9ed 0x2512bd5b 0x2507b229 0x2507b015 0x2666bac9 0x2974f189 0xa7f21 0x24d23873)
libc++abi.dylib: terminating with uncaught exception of type NSException.


please help me what should I do?

**Comment by prasenraj** [comment]
I fix this error now it's working fine, thank you very much.

**Comment by ReisBenjamin** [comment]
Glad to hear it, i'll close this issue.

Regards

**Comment by fedesenmartin** [comment]
@prasenraj  how did you solved Linphone core not initialized yet' ?

Regards

**Comment by RONAKSANKHALA** [comment]
Hello, @ReisBenjamin 

i will try to remove all call logs using below code. 
but app will crash at that time below here
 ======> LinphoneCallLog *callLog = (LinphoneCallLog *)logs->data;


    const bctbx_list_t *logs = linphone_core_get_call_logs([LinphoneManager getLc]);
    while (logs != NULL) {
       ======>  LinphoneCallLog *callLog = (LinphoneCallLog *)logs->data;
        linphone_core_remove_call_log(LC, callLog);
        linphone_call_log_unref(callLog);
        logs = logs->next;
        //bctbx_list_next(logs);
    }

but when i use below code then it will remove only one call history.
const MSList *list = linphone_core_get_call_logs(LC);
LinphoneCallLog *log = (LinphoneCallLog *)list->data;
linphone_core_remove_call_log(LC, log);

========================================
i need to remove all call history when user logout.
========================================
**first time inside while loop logs is ======**
(const bctbx_list_t *) logs = 0x00000001c542ae20
**========**
**Second time Inside while loop logs is ========**
Printing description of logs:
-5779727547545862
and crash.
EXC_BAD_ACCESS (code=1, address=0xbadd0bfa921abebd)

How to resolve these issue?
