### ISSUE TITLE
How to display outgoing call with contact name?

### ISSUE THREAD

**Issue by prasenraj** [BelledonneCommunications/linphone-iphone#301]
in the Outgoing call, no name is displayed only showing number, in my sip server I have a number with a name that I save but 
Now make a call from one extension to another extension.
A name is displayed in an incoming call that is okay but not displayed name in outgoing call only display the number.thats not good. how to fix this issue?

**Comment by ReisBenjamin** [comment]
Hello,

When you make the Outgoing call, do you have the number in your contacts?
If not how do you know the name associated to the number ?

**Comment by LAfricain** [comment]
I have the same problem on Android, my brother on Iphone can see the names.

**Comment by ReisBenjamin** [comment]
@LAfricain open an issue on the Android repo

**Comment by LAfricain** [comment]
Oh Yes sorry!

**Comment by simplenetworks** [comment]
I have the same issue, both on Android an iPhone, using a SIP Account on a custom domain. Could it be a server issue? Any advice?
