### ISSUE TITLE
REGISTER SIP message on network change with 2 "Contact" header (TLS)

### ISSUE THREAD

**Issue by Ionik** [BelledonneCommunications/linphone-iphone#304]
Hi,

I have built the last version of linphone-iphone and here is my issue:
The transport is TLS, and 4G is used. There's no problem, the REGISTER is correct and I receive 200 OK.
But when I activate WiFi, the state of registration goes to "LinphoneRegistrationProgress" and here is the REGISTER SIP message:

```
REGISTER sip:sip.foobar.io:1443;transport=tls SIP/2.0
Via: SIP/2.0/TLS 192.168.0.188:49165;alias;branch=z9hG4bK.wdB-7ZIfg;rport
From: <sip:ionik@sip.ringover.io>;tag=13Bms0eZZ
To: sip:ionik@sip.foobar.io
CSeq: 20 REGISTER
Call-ID: v8kn2e2iKK
Max-Forwards: 70
Supported: replaces, outbound
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: <sip:ionik@192.168.0.188:49165;transport=tls>;+sip.instance="<urn:uuid:fe2df60f-4e6e-471a-ac86-c2b3091fb0ac>"
Contact: <sip:ionik@37.172.111.132:11653;transport=tls>;+sip.instance="<urn:uuid:fe2df60f-4e6e-471a-ac86-c2b3091fb0ac>";expires=0
Expires: 3600
User-Agent: Linphone_iPhone9.4_iOS10.3.3/3.16.4-94-g8937a2ca (belle-sip/1.6.3)
Content-Length: 0
```

There are 2 "Contact:" headers, and I think that in REGISTER SIP message, it must have only 1 "Contact:" header. Am I right? Is it a bug? Is there a way to delete 1 Contact header?

Any help would be very appreciated.

Thanks a lot !

Mathieu

**Comment by ReisBenjamin** [comment]
Hello,

It is allowed to to have 2 (and as many as you want) contact headers in a REGISTER.
In your case, the first one has an expire=0 in order to UNREGISTER the old registration and the second one is used to REGISTER your new one.

Everything seems fine to me... Does the server receive your 2nd REGISTER ?

Thanks

**Comment by Ionik** [comment]
Hello,

I didn't know that it was allowed. I use Kamailio as SIP server and I think it doesn't like it... When I send a REGISTER with those 2 Contact headers, Kamailio did receive the message but never responds to it. Maybe it is a configuration problem...
Anyway, now I know that a REGISTER can have several Contact headers, I continue investigating Kamailio side.

Thanks a lot for your time !

Mathieu

**Comment by ReisBenjamin** [comment]
Hello,

I'll close this issue then.

Bes regards
