### ISSUE TITLE
iOS 10, iPhone7 [IOSCapture openDevice] crash

### ISSUE THREAD

**Issue by tuyenntq** [BelledonneCommunications/linphone-iphone#305]
I add fabric to my app, 
I get many crash with [IOSCapture openDevice:]
![screen shot 2017-09-12 at 3 39 16 pm](https://user-images.githubusercontent.com/19769427/30316213-b8baadb0-97d0-11e7-8661-222e0e305642.png)

**Comment by ReisBenjamin** [comment]
Hello,

Do you reproduce this crash ? If so could you provide us with a step by step to reproduce i t?

Thanks

**Comment by AdilSoomro** [comment]
It might be issue with your privacy info string, that needs to be added to your app's info.plist. Please double check it. The string is, `Privacy - Camera Usage Description`

**Comment by tuyenntq** [comment]
Hello Adil & ReisBenjamin

My add has added The string is, Privacy - Camera Usage Description
I have a device with iOS 10, When I test, every things Ok, But Fabric crash report have over 2000 crash with this log.
I use old version of linphone. It’s Ok, right?


Thank and Best Regards,
TuyenLX

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lê Xuân Tuyên
​iOS Developer - NTQ Solution JSC
Mobile: 01655.46.17.39
Skype: tuyen.le@ntq-solution.com.vn
Email: tuyen.le@ntq-solution.com.vn
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ReisBenjamin** [comment]
Humm, you should use an up to date version of linphone since before ios10 release the lib didn't support ios10. you can check for our last release tag 3.16.4 this is a stable version that supports ios10.
Does your app request Video authorization to the user ?

**Comment by tuyenntq** [comment]
Thank you, I will update newest linphone version.
Now, I used 3.9.1. It’s so old version.
Bug is sometime. I don’t think cause is app setting.

Thank and Best Regards,
TuyenLX

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Lê Xuân Tuyên
​iOS Developer - NTQ Solution JSC
Mobile: 01655.46.17.39
Skype: tuyen.le@ntq-solution.com.vn
Email: tuyen.le@ntq-solution.com.vn
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
