### ISSUE TITLE
Sip account validation (invalid)

### ISSUE THREAD

**Issue by arsenx** [BelledonneCommunications/linphone-iphone#31]
I just noticed that the latest build does not have proper validation on the sip configuration page.
1-3 characters is considered invalid, 4 is valid and 4+ is invalid.

Let me know if additional info is required :)

**Comment by bagage** [comment]
What do you mean by "sip configuration page"? Which choice (1 - 4). 
How did you install application? With the AppStore? Did you upgrade a previous version?

What did you enter and in which field to have this error (I think this is the username, but I prefer to ask though).

**Comment by arsenx** [comment]
Hi @bagage, so here's some more details,

It's an app store download (v3.10), haven't had time to compile myself yet :\
So on the new assistant setup page when you go into add existing sip account the username field seems to have validation which prevents any sip username other than 4 chars long to be entered

Hope that helps :)

**Comment by bagage** [comment]
Thanks for details @arsenx. Last question: was it a first installation, or you already had a previous version installed on the device? iPhone or iPad?

**Comment by arsenx** [comment]
It was an update so yes, previous version was in place (Big fan here btw)
One more thing that I can specify, once I entered an invalid 4 char username I was then able to enter my correct username through the settings panel, by accessing my account info

If needed I can uninstall and reinstall to tell you about the results

**Comment by bagage** [comment]
No that's fine, I think I got everything I need thanks :-). I'll try to fix it for next (minor) release.

**Comment by arsenx** [comment]
Wonderful, great work @bagage! You guys have really made by far the best sip client app :smiley:

**Comment by bagage** [comment]
Solved in af64f9977f6e57f12e73597caa0508db664ba905
