### ISSUE TITLE
"The binary you uploaded was invalid"

### ISSUE THREAD

**Issue by TheEngineerz** [BelledonneCommunications/linphone-iphone#310]
I have renewed certificates and profiles. I have also tried Xcode and Application uploader but I am still facing this issue when I upload the app to iTunes store

![screen shot 2017-09-16 at 8 29 11 pm](https://user-images.githubusercontent.com/5149947/30514630-84bf5cf8-9b32-11e7-96cc-b39fec737f0d.png)

**Comment by ReisBenjamin** [comment]
Hello,

Did you compile the SDK in debug mode ?

Thanks

**Comment by ReisBenjamin** [comment]
unanswered
