### ISSUE TITLE
'mediastreamer2/mscommon.h' file not found error in linphone.framework

### ISSUE THREAD

**Issue by powerqian** [BelledonneCommunications/linphone-iphone#311]
Hi Linphone iPhone developer,

I saw the questions has already been asked through the mailing list here http://lists.gnu.org/archive/html/linphone-developers/2017-08/msg00048.html. However the last reply from REIS Benjamin still does not solve the problem. After tried different ways to "add all framworks to your project’s embedded binaries", error still shows.

Based on my understanding, the output of `liblinphone-sdk` changes from static library to dynamic framework now. As a result `#include "mediastreamer2/mscommon.h"` does not really work because
1. Including a header file in other framework should be using `<>`.
2. As mentioned in the mailing list, the framework's name is not `mediastreamer2`, so the file cannot be found anyway.

Maybe my understanding is not correct, but anyway, the error cannot go away...

BTW I'm using Xcode 9 building against iOS 11 SDK.

Any help is appreciated!

**Comment by recoco** [comment]
I encountered the same problem. Xcode 8.2.x/iOS 10 SDK. And try to build with -DENABLE_STATIC_ONLY=ON, but still had the same problem. There is not /mediastreamer/plugins in folder liblinphone-sdk/apple-darwin/lib.

**Comment by ReisBenjamin** [comment]
Commit bd5e82865a703a81c36ee05205cec7d18bfcd19a remove the warning of the missing lib since all needed symbols are in the frameworks.

**Comment by alexvimodev** [comment]
Still I am getting this issue..

@powerqian you resolved this issue ?

**Comment by sakthig** [comment]
@alexvimodev @powerqian guys .. did u resolve this ?

**Comment by powerqian** [comment]
@alexvimodev @sakthig 

I was able to build it by specifying DENABLE_STATIC_ONLY=ON after posting this issue, and haven't tried ever since. Looks like others having the same issue, though...

**Comment by OnurVar** [comment]
I'm also having same problem here

**Comment by StefanBstorm** [comment]
@OnurVar 
I have same problem, you need to include headers in Build Settings

<img width="859" alt="screen shot 2018-04-22 at 14 48 43" src="https://user-images.githubusercontent.com/37397578/39095178-a66c25d8-463c-11e8-9c64-4893bf018d90.png">

**Comment by m-rayanade** [comment]
Im also facing the same issue. Any workaround? Could anyone solve this issue?

**Comment by StefanBstorm** [comment]
@m-rayanade Do you try to include Header Search Paths in Build Settings?

**Comment by arjun011** [comment]
I was try above all thing :( but still same error . Could you please provide step how to configure Linephone Sdk in Xcode 9.3 ?
