### ISSUE TITLE
App hangs on iOS 11 when video ends

### ISSUE THREAD

**Issue by powerqian** [BelledonneCommunications/linphone-iphone#312]
Hi,

The reason is because `VTDecompressionSessionInvalidate` call hangs on iOS 11, and it is called when video ends, e.g. disable video or call ends. In the post on [Apple Developer Forum here](https://forums.developer.apple.com/thread/85678), it covers the details and the work around.

**Comment by fatgue** [comment]
is this problem already fixed?
