### ISSUE TITLE
Enable GSM 

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#314]
Hi 

 I want to enable audio codec gsm from defautl

I noticed that I have to change some settings on linphonerc and linphonerc-factory

Could you help me to configure that?

Thanks

**Comment by ReisBenjamin** [comment]
You need to put he default settings of GSM to true in the Audio.plist file and gsm_preference=1 in both linphonerc and linphonerc-factory, then re-instyall the app from scratch

**Comment by fedesenmartin** [comment]
like this?

[audio_codec_0]
gsm_preference=1

**Comment by ReisBenjamin** [comment]
[audio_codec_0]
mime=GSM
rate=8000
channels=1
enabled=1
