### ISSUE TITLE
Error while building i386

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#315]
I updated the submodules and do ./prepare.py -c && ./prepare.py i386 && make

Get this error after a while building

ld: illegal text-relocation to 'anon' in /Users/user/Documents/liphone_cloned/liblinphone-sdk/i386-apple-darwin.ios/lib/libvpx.a(intrapred_sse2.asm.o) from '_vpx_dc_predictor_4x4_sse' in /Users/user/Documents/liphone_cloned/liblinphone-sdk/i386-apple-darwin.ios/lib/libvpx.a(intrapred_sse2.asm.o) for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Regards

**Comment by ReisBenjamin** [comment]
Hello,

Why do you need to build on i386 ? All recent iOS are built on arm64 armv7 or X86_64 for the simulator.

**Comment by fedesenmartin** [comment]
I need for changing the xcode scheme to release,so I can debug a bug that only produces on release (testflight) builds ,but when I do that xcode errors are for missing archs i386

Regards Reis

**Comment by ReisBenjamin** [comment]
The only available arch on release are arm64 and armv7 since Testflight is only available one IPhone, iPod and iPad
i386 is a deprecated arch to run on simulator (but now it's advised to use x86_64)

**Comment by fedesenmartin** [comment]
I edited the release scheme for debug and this are de xcode error log

<img width="746" alt="captura de pantalla 2017-09-21 a la s 12 38 01" src="https://user-images.githubusercontent.com/17075982/30704693-d301d36a-9ec9-11e7-8e87-be600e2c85c5.png">


Thanks!

**Comment by ReisBenjamin** [comment]
The image is truncated. Is this possible to have the text version ?

**Comment by fedesenmartin** [comment]
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 notices only
Showing first 200 errors only

Thanks

**Comment by ReisBenjamin** [comment]
I need to see which symbols are not found.
Did you add our frameworks in your embedded and linked binaries in XCode ?

**Comment by ReisBenjamin** [comment]
http://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/iOS/#HBuildingtheSDKmanually

**Comment by fedesenmartin** [comment]
I added the frameworks in the embedded and linked binaries 

Also added the run script

Where can I found the missing symbols?

Regards

**Comment by ReisBenjamin** [comment]
After the error you show me, there should be a list of missing symbols. please attach the whole log of the prepare and make procedure.

Thanks

**Comment by fedesenmartin** [comment]
Dont worry about that

The issue is now when I submitted to testflight ,It gives an error when trying to login to custom sip account .

Its rare because the same code works fine while running in xcode directly

Regards Reis

**Comment by ReisBenjamin** [comment]
Can i close the issue and you open a new one for this new problem ?
Thanks
