### ISSUE TITLE
Unable to retrieve custom header in the incoming call

### ISSUE THREAD

**Issue by vijayaa** [BelledonneCommunications/linphone-iphone#317]
i am using the below code to get the custom header. But it is showing as nil

`const LinphoneCallParams *params = linphone_call_get_remote_params(call); 
const char *custom_header = linphone_call_params_get_custom_header(params, [@"Custom_header_key" UTF8String])`

**Comment by vijayaa** [comment]
Sorry i have used wrong method. Below one worked

`linphone_call_params_get_custom_header(params, name);`

**Comment by ReisBenjamin** [comment]
Okay so i'll close the issue.

Best regards
