### ISSUE TITLE
SDK not working on TestFlight 

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#318]
I had made some changes in some classes of the project

And I added some web service calls and Im using a custom flexi sip server.

Its all working ok on testing enviroment.

But when I upload to TestFlight to start testing ,the function ->

ONCLICKBUTTON(Sender, 100, {
            _waitView.hidden = NO;
            NSString *domain = [self findTextField:ViewElement_Domain].text;
            NSString *username = [self findTextField:ViewElement_Username].text;
            NSString *displayName = [self findTextField:ViewElement_DisplayName].text;
            NSString *pwd = [self findTextField:ViewElement_Password].text;
            LinphoneProxyConfig *config = linphone_core_create_proxy_config(LC);
            LinphoneAddress *addr = linphone_address_new(NULL);
            linphone_address_set_username(addr, username.UTF8String);
            linphone_address_set_domain(addr, domain.UTF8String);
            if (displayName && ![displayName isEqualToString:@""]) {
                linphone_address_set_display_name(addr, displayName.UTF8String);
            }
            linphone_proxy_config_set_identity_address(config, addr);
            // set transport
            UISegmentedControl *transports = (UISegmentedControl *)[self findView:ViewElement_Transport
                                                                           inView:self.contentView
                                                                           ofType:UISegmentedControl.class];
            if (transports) {
                NSString *type = [transports titleForSegmentAtIndex:[transports selectedSegmentIndex]];
                linphone_proxy_config_set_route(
                                                config,
                                                [NSString stringWithFormat:@"%s;transport=%s", domain.UTF8String, type.lowercaseString.UTF8String]
                                                .UTF8String);
                linphone_proxy_config_set_server_addr(
                                                      config,
                                                      [NSString stringWithFormat:@"%s;transport=%s", domain.UTF8String, type.lowercaseString.UTF8String]
                                                      .UTF8String);
                
                linphone_proxy_config_set_server_addr(config, proxy);
                
                
                
                
            }
            
            linphone_proxy_config_enable_publish(config, FALSE);
            linphone_proxy_config_enable_register(config, TRUE);
            
            LinphoneAuthInfo *info =
            linphone_auth_info_new(linphone_address_get_username(addr), // username
                                   NULL,								// user id
                                   pwd.UTF8String,						// passwd
                                   NULL,								// ha1
                                   linphone_address_get_domain(addr),   // realm - assumed to be domain
                                   linphone_address_get_domain(addr)	// domain
                                   );
            linphone_core_add_auth_info(LC, info);
            linphone_address_unref(addr);
            
            
            if (config) {
                [[LinphoneManager instance] configurePushTokenForProxyConfig:config];
                if (linphone_core_add_proxy_config(LC, config) != -1) {
                    linphone_core_set_default_proxy_config(LC, config);
                    // reload address book to prepend proxy config domain to contacts' phone number
                    // todo: STOP doing that!
                    [[LinphoneManager.instance fastAddressBook] reload];
                    [PhoneMainView.instance changeCurrentView:DialerView.compositeViewDescription];
                } else {
                    
                    [self displayAssistantConfigurationError];
                }
            } else {
                
                [self displayAssistantConfigurationError];
            }
        });

It enters on the assistant configuration error.
This only accurs in testflight tests

Regards

**Comment by ReisBenjamin** [comment]
Hello,

What is the Assistant error ?
Is it possible to see logs of when it happens ?

Thanks

**Comment by fedesenmartin** [comment]
I cant debug it  in testflight mode

**Comment by ReisBenjamin** [comment]
You have in the advanced option a way to send logs via email.
You can clear the log, reproduce the bug and then send yourself the log to post it here.

What do you mean by "It enters on the assistant configuration error." ?

**Comment by fedesenmartin** [comment]
The issue is like this:

1)I downloaded the latest version of linphone ,compile it ,and run it on xcode,all works like a charm
2) I submitted the app to the app store and testflight
3) when  I open the app from test flight ,when I do a custom sip login it enteres on the asssitant configuration error when ->

 ONCLICKBUTTON(Sender, 100, {
             _waitView.hidden = NO;
             NSString *domain = [self findTextField:ViewElement_Domain].text;
             NSString *username = [self findTextField:ViewElement_Username].text;
             NSString *displayName = [self findTextField:ViewElement_DisplayName].text;
             NSString *pwd = [self findTextField:ViewElement_Password].text;
             LinphoneProxyConfig *config = linphone_core_create_proxy_config(LC);
             LinphoneAddress *addr = linphone_address_new(NULL);
             linphone_address_set_username(addr, username.UTF8String);
             linphone_address_set_domain(addr, domain.UTF8String);
             if (displayName && ![displayName isEqualToString:@""]) {
                 linphone_address_set_display_name(addr, displayName.UTF8String);
             }
             linphone_proxy_config_set_identity_address(config, addr);
             // set transport
             UISegmentedControl *transports = (UISegmentedControl *)[self findView:ViewElement_Transport
                                                                            inView:self.contentView
                                                                            ofType:UISegmentedControl.class];
             if (transports) {
                 NSString *type = [transports titleForSegmentAtIndex:[transports selectedSegmentIndex]];
                 linphone_proxy_config_set_route(
                                                 config,
                                                 [NSString stringWithFormat:@"%s;transport=%s", domain.UTF8String, type.lowercaseString.UTF8String]
                                                 .UTF8String);
                 linphone_proxy_config_set_server_addr(
                                                       config,
                                                       [NSString stringWithFormat:@"%s;transport=%s", domain.UTF8String, type.lowercaseString.UTF8String]
                                                       .UTF8String);
             }
             linphone_proxy_config_set_server_addr(config, proxy);
             
             linphone_proxy_config_enable_publish(config, FALSE);
             linphone_proxy_config_enable_register(config, TRUE);
             
             LinphoneAuthInfo *info =
             linphone_auth_info_new(linphone_address_get_username(addr), // username
                                    NULL,                                // user id
                                    pwd.UTF8String,                        // passwd
                                    NULL,                                // ha1
                                    linphone_address_get_domain(addr),   // realm - assumed to be domain
                                    linphone_address_get_domain(addr)    // domain
                                    );
             linphone_core_add_auth_info(LC, info);
             linphone_address_unref(addr);
             
             if (config) {
                 [[LinphoneManager instance] configurePushTokenForProxyConfig:config];
                 if (linphone_core_add_proxy_config(LC, config) != -1) {
                     linphone_core_set_default_proxy_config(LC, config);
                     // reload address book to prepend proxy config domain to contacts' phone number
                     // todo: STOP doing that!
                     [[LinphoneManager.instance fastAddressBook] reload];
                     [PhoneMainView.instance changeCurrentView:DialerView.compositeViewDescription];
                 } else {
          
                     [self displayAssistantConfigurationError]; --->> HERE ENTERS THE ERROR, ITS LIKE CONFIG IS NULL FOR A REASON.
                 }
             } else {
                 [passwordMG setAlpha:1];

                 [self displayAssistantConfigurationError];
             }
         });
     
     

4) This not happens while running directly from xcode.

**Comment by fedesenmartin** [comment]
any updates?
