### ISSUE TITLE
latest commit can not analyze  domain with ip:port  

### ISSUE THREAD

**Issue by latermonk** [BelledonneCommunications/linphone-iphone#319]
I found the latest commit [commit id 28b2914c0cad1709a9f4a688501821343c326d0a] can not analyze   domain with ip:port  

I use assistant -> use sip account -> domain:

when I  input  some  address like   test.linphone.org ,it's ok ,when I input the IP address 192.168.1.100  it's ok too,but  when I input  **192.168.1.100:1234** ,the App crash .

the crash in the **message.c** file[sdk file],  **belle_sip_request_get_uri** function ,and the error is :  **Thread 1, exec_bad_address(code =1,address=0x50).**

what's the problem  maybe ? 

thanks !

**Comment by ReisBenjamin** [comment]
fixed in commit b2df11512eb53f6e84b418f51fe3da4eea563934
