### ISSUE TITLE
Does anyone have trouble getting the Linphone- ios project run on Xcode 9 and ios 11? It seems to give off a lot of parse errors.

### ISSUE THREAD

**Issue by untamedexplorer** [BelledonneCommunications/linphone-iphone#320]

**Comment by ReisBenjamin** [comment]
Hello,

Current master branch of linphone iphone should compile fine on iOS11/Xcode9.
What errors do you get ?

Thanks

**Comment by untamedexplorer** [comment]
![screen shot 2017-09-26 at 7 14 13 pm](https://user-images.githubusercontent.com/32300004/30863570-fee473f6-a2ee-11e7-93dc-fdfbcb5b9baf.jpg)
Starts with this, but as we try fix each error , new ones creep in. Have not made any change , just cloned the iphone project and dropped in the SDK liblinphone-iphone-sdk-3.16.4.

**Comment by ReisBenjamin** [comment]
the 3.16.4 SDK is no longer compatible with the master branch of linphone.
You need to run git submodule update --recursive --init and then build the SDK manually in order to have a sync between app & SDK

**Comment by untamedexplorer** [comment]
oh. 
Cloned the complete master branch,
ran the git submodule update --recursive --init
and executed ./prepare.py all && make
got this error, SDK folder is created however only two folders are present in it, i386-apple_darwin.ios and x86_x64-apple_darwin.ios

1 warning generated.
[100%] Linking CXX shared library mediastreamer_voip.framework/mediastreamer_voip
ld: illegal text-relocation to 'anon' in /****/*****/*****/*****/*****/linphone-iphone/liblinphone-sdk/i386-apple-darwin.ios/lib/libvpx.a(intrapred_sse2.asm.o) from '_vpx_dc_predictor_4x4_sse' in ****/*****/*****/*****/*****/linphone-iphone/liblinphone-sdk/i386-apple-darwin.ios/lib/libvpx.a(intrapred_sse2.asm.o) for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[6]: *** [src/mediastreamer_voip.framework/mediastreamer_voip] Error 1
make[5]: *** [src/CMakeFiles/mediastreamer_voip.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/****/*****/*****/*****/*****/linphone-iphone/WORK/ios-i386/Stamp/EP_ms2/EP_ms2-build] Error 2
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [i386-build] Error 2

however the SDK folder shows up and once we try to run the project
a lot of linker issues comes up(around 200 of them) mainly highlighting that the frameworks are not of arm64 capability, however i had remade the sdk using "./prepare.py arm64 && make" and tried again still shows the same error.

is it possible to get a pre built SDK that is compatible with the new master branch?

**Comment by ReisBenjamin** [comment]
You need to run : 
./prepare.py -c && ./prepare.py && make

There also is pre-built SDK available here : http://www.linphone.org/snapshots/ios/

**Comment by untamedexplorer** [comment]
Thank You for the timely help. It worked, both the pre-built SDK and the one that i built using the command you mentioned. 
Issue can be closed.
