### ISSUE TITLE
Numbers not replaced by names from address book

### ISSUE THREAD

**Issue by HansBorjes** [BelledonneCommunications/linphone-iphone#321]
Numbers are not always replaced by names from address book in call list.

My address book contains all numbers in international mobile network format.

It seems that Linphone has issues with how region code/mobile network code is embedded in the whole national number.  Please note the leading zero necessary when omitting the country code.

Examples of equivalent notation within Germany:

+49301234567 (address book)
0301234567@sipgate.de (sip message)

+491701234567 (address book)
01701234567@easybell.de

**Comment by bearsh** [comment]
something like [Zoiper's number rewriting](https://www.zoiper.com/en/support/answer/for/android/124/Number_rewriting) would solve this bug...

**Comment by bearsh** [comment]
the corresponding android issue https://github.com/BelledonneCommunications/linphone-android/issues/214
