### ISSUE TITLE
Linphone iterate crashes during call

### ISSUE THREAD

**Issue by reste85** [BelledonneCommunications/linphone-iphone#322]
Hi guys,
We are using Linphone library inside our VoIP app.
We've problems during call (and also outside calls): Linphone crashes during linphone_iterate.
Attached you can find the screenshot of Xcode and the logs (rtf file). 

Linphone version: Linphone [3.10.2-528-g5d73bb8]
Device: iPhone 6, iOS 9.3 (but we have problems also with iOS 10 and iOS 11)

[crash iterate linphone.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/1344414/crash.iterate.linphone.zip)

**Comment by ReisBenjamin** [comment]
I see your linphone version is 3.10.2-528-g5d73bb8, is it the return of your git status command ?
If not can i have the return of this command ?

Thanks

**Comment by reste85** [comment]
That version is the result of linphone_core_get_version() method call. 
I'm trying to run git status command on Linphone directory but I've problems with submodules (“fatal: git status --porcelain failed”)

**Comment by ReisBenjamin** [comment]
Okay,

Your core is outdated, i suggest you run git pull && git submodule update --init --recursive
then recompile your sdk : ./prepare.py -c && ./prepare.py && make

Post here if the crash still happens with an up-to-date version

**Comment by reste85** [comment]
Hi,
I've downloaded the new version of linphone-iphone. I've compiled it and included the new Linphone libraries in my app. When I build I get this error message: linphone.framework/Headers/types.h:25:10: 'mediastreamer2/msinterfaces.h' file not found

how can i solve that?

Thank you!

**Comment by reste85** [comment]
Ok I managed to change the header search paths (there was an error). Now I receive the following error: 

Undefined symbols for architecture arm64:
  "_libmsbcg729_init", referenced from:
      -[LinphoneManager createLinphoneCore] in LinphoneManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ReisBenjamin** [comment]
Did you add all the frameworks of liblinphone in your xcode project linked & embedded binaries ?

**Comment by reste85** [comment]
See attached images: 
Frameworks and embedded binaries, it seems all ok... 
Just to complete the infos, we're using Xcode 7.


![embedded_bin](https://user-images.githubusercontent.com/14905251/31128734-f1492764-a852-11e7-8bac-d2480b462437.png)
![frameworks](https://user-images.githubusercontent.com/14905251/31128696-d5c7bdde-a852-11e7-9f30-3e62c2c04699.png)

**Comment by reste85** [comment]
ld: warning: directory not found for option '-L/Users/kalpa/Documents/Develop/elvox_intercom_ios/Linphone/apple-darwin/lib/mediastreamer/plugins'
Undefined symbols for architecture arm64:
  "_libmsbcg729_init", referenced from:
      -[LinphoneManager createLinphoneCore] in LinphoneManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


If I go to Users/kalpa/Documents/Develop/elvox_intercom_ios/Linphone/apple-darwin/lib I cannot find the directory "mediastreamer"

why???

**Comment by StarTeleLogic** [comment]
I am facing issue in CallKit integration. Actually issue is coming after updating OS version to iOS 11.01.
I have implemented CallKit as per Apple guided in their SpeakerBox example step by step.

Very first time It works fine but in subsequent runs It fails to give voice in earphone. The exact issue is that there is an inconsistency related to audio session means I am not able to use mic to catch voice and the user on other end not able to listen my voice.

All the delegates provided in Provider Class are calling very well. Audio Class instance is also available each time I run. Only issue seems with the creation of Audio session using It's shared instance. I notices that It fires AVAudioSessionRouteChangeNotification frequently and switch-case goes in the case of AVAudioSessionRouteChangeReasonCategoryChange. When I print category type- It gives right selected category named AVAudioSessionCategoryPlayAndRecord.

Let you know that If I put break point in switch-case then It works fine. May be at that point It got enough time to create Audio Session to catch the voice through mic.

Sharing the code where I am setting up audio session:

- (void)setupAudioSession
{
    try {
        // Configure the audio session
        AVAudioSession *sessionInstance = [AVAudioSession sharedInstance];
        // we are going to play and record so we pick that category
        NSError *error = nil;
        [sessionInstance setCategory:AVAudioSessionCategoryPlayAndRecord error:&error];
        XThrowIfError((OSStatus)error.code, "couldn't set session's audio category");

        // set the mode to voice chat
        [sessionInstance setMode:AVAudioSessionModeVoiceChat error:&error];
        XThrowIfError((OSStatus)error.code, "couldn't set session's audio mode");

        // set the buffer duration to 5 ms
        NSTimeInterval bufferDuration = .005;
        [sessionInstance setPreferredIOBufferDuration:bufferDuration error:&error];
        XThrowIfError((OSStatus)error.code, "couldn't set session's I/O buffer duration");

        // set the session's sample rate
        [sessionInstance setPreferredSampleRate:44100 error:&error];
        XThrowIfError((OSStatus)error.code, "couldn't set session's preferred sample rate");

        // add interruption handler
        [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(handleInterruption:)
                                                     name:AVAudioSessionInterruptionNotification
                                                   object:sessionInstance];

        // we don't do anything special in the route change notification
        [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(handleRouteChange:)
                                                     name:AVAudioSessionRouteChangeNotification
                                                   object:sessionInstance];

        // if media services are reset, we need to rebuild our audio chain
        [[NSNotificationCenter defaultCenter]   addObserver:    self
                                                 selector:      @selector(handleMediaServerReset:)
                                                     name:      AVAudioSessionMediaServicesWereResetNotification
                                                   object:      sessionInstance];
    }

    catch (CAXException &e) {
        NSLog(@"Error returned from setupAudioSession: %d: %s", (int)e.mError, e.mOperation);
    }
    catch (...) {
        NSLog(@"Unknown error returned from setupAudioSession");
    }

    return;
}


Below are the method with switch-cases which gets called in case of notification name :AVAudioSessionRouteChangeNotification is fired:

- (void)handleRouteChange:(NSNotification *)notification
{
    UInt8 reasonValue = [[notification.userInfo valueForKey:AVAudioSessionRouteChangeReasonKey] intValue];
    AVAudioSessionRouteDescription *routeDescription = [notification.userInfo valueForKey:AVAudioSessionRouteChangePreviousRouteKey];

    NSLog(@"Route change:");
    switch (reasonValue) {
        case AVAudioSessionRouteChangeReasonNewDeviceAvailable:
            NSLog(@"     NewDeviceAvailable");
            break;
        case AVAudioSessionRouteChangeReasonOldDeviceUnavailable:
            NSLog(@"     OldDeviceUnavailable");
            break;
        case AVAudioSessionRouteChangeReasonCategoryChange:
            NSLog(@"     CategoryChange");
            NSLog(@" New Category: %@", [[AVAudioSession sharedInstance] category]);
            [self setupAudioSession];
            break;
        case AVAudioSessionRouteChangeReasonOverride:
            NSLog(@"     Override");
            break;
        case AVAudioSessionRouteChangeReasonWakeFromSleep:
            NSLog(@"     WakeFromSleep");
            break;
        case AVAudioSessionRouteChangeReasonNoSuitableRouteForCategory:
            NSLog(@"     NoSuitableRouteForCategory");
            break;
        default:
            NSLog(@"     ReasonUnknown");
    }

    NSLog(@"Previous route:\n");
    NSLog(@"%@", routeDescription);
}

PLEASE NOTE THAT EVERY THING WORKS FINE IF I PUT BREAK POINT IN ABOVE METHOD'S CASE- AVAudioSessionRouteChangeReasonCategoryChange !!!

**Comment by afriedmanGlacier** [comment]
@ReisBenjamin I don't know that we are seeing the exact same behavior as above, but at 30-32 seconds with an outgoing call, the call dies. Tracing it, it seems to happen when linphone_iterate is called. Only happens calling out from iOS 11 phone for us.

**Comment by ReisBenjamin** [comment]
Link warning removed in commit bd5e82865a703a81c36ee05205cec7d18bfcd19a

**Comment by arjun011** [comment]
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/Developer/Library/Frameworks'
Undefined symbols for architecture armv7:
  "_libmsx264_init", referenced from:
      -[LinphoneManager createLinphoneCore] in LinphoneManager.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Could you please help me to configure code ? Thanks
