### ISSUE TITLE
Audio Codec priority won't allow for HD quality calls

### ISSUE THREAD

**Issue by w-sky** [BelledonneCommunications/linphone-iphone#323]
Hi there, since the audio codec priority can not simply be changed in the Android version, the only way to use high audio quality seems to be to select **only** the best one audio codec.

In means of audio quality G722 is the best codec of the list which is supported by my provider, but when I also activate any codec above in the list which is supported too, like PCMU, PCMA or GSM, that one will be used.

Should it be like this? If not, then the Android version needs to enable changing the order of the codec list by drag&drop.

**Comment by ReisBenjamin** [comment]
Hello,

You're on the IOS repo, please file an issue on the correct repo.

Thank you.
