### ISSUE TITLE
When app is background then incoming call is not possible?

### ISSUE THREAD

**Issue by prasenraj** [BelledonneCommunications/linphone-iphone#325]
When the app is in the Background state, if I called within 10 sec then incoming call is coming out but after 10 sec incoming calls is not coming? How to fix this error?

**Comment by ReisBenjamin** [comment]
Hello,

Have you allowed push notifications ? Do you use a service that supports push notifications ?

Thanks

**Comment by prasenraj** [comment]
Yes I allowed push notification

**Comment by TheNazzi89** [comment]
Did you disable 'Boot at start' on app Advanced Settings?

**Comment by prasenraj** [comment]
I am not disabled 'boot at start'. Actually, Its working fine on Simulator but in my device (iPhone 4S,9.3.2)after two min it's not working.

**Comment by ReisBenjamin** [comment]
What expire time do you have when you register ?

**Comment by Trushangpatel** [comment]
Hello,

I will resolve this issue from voip silent push notification.
if you need help then mail me: trushangpatel3993@gmail.com, add subject: linphone issue

Thanks
