### ISSUE TITLE
Contact first and last name is not displayed in Contact detail page when add a new contact?

### ISSUE THREAD

**Issue by prasenraj** [BelledonneCommunications/linphone-iphone#326]
Login with valid username and password in IOS device 
Click on contact module 
Click on Add contact button
Enter valid data in all fields and click on submit button
In Contact detail page First name and Last name is not displayed other details is coming like phone number, email id, and sip address. how to fix it?

**Comment by ReisBenjamin** [comment]
Hello,

I do not reproduce your issue.
Does it happen all the time ?

Thanks

**Comment by prasenraj** [comment]
When I add a new contact and when I modify the contact

**Comment by ReisBenjamin** [comment]
Hello,

I've managed to reproduce your issue on our app, it seems the contact synch withthe OS Address book is only done on app restart...
I'll tell you when the bug's fixed. Thanks for reporting it.

Regards

**Comment by prasenraj** [comment]
Is this problem solve? please let me know.

**Comment by ReisBenjamin** [comment]
Fixed at commit 28b403383d745273aeb881c9ecc00ba9338b0e0a.
