### ISSUE TITLE
SelfView Turns ON after changing the screen orientation

### ISSUE THREAD

**Issue by kemotz** [BelledonneCommunications/linphone-iphone#327]
Hi,

On Iphone 6 with ios 11, the Show self view is Off. Starting a video call in landscape or portrait mode without a self view. During the call move phone to another orientation and self view pops up and stays.

Thanks,
Tomek.

**Comment by ReisBenjamin** [comment]
I do not reproduce your issue.
Did you change something in the code concerning the callview ?
