### ISSUE TITLE
Not showing missed call?

### ISSUE THREAD

**Issue by prasenraj** [BelledonneCommunications/linphone-iphone#328]
When I did not receive the call then showing me incoming call whereas it is missed call. otherwise it's working properly.

**Comment by ReisBenjamin** [comment]
Hello,

I need to see logs when it happens.
Is your code up to date ?

Thanks

**Comment by prasenraj** [comment]
When someone calling me and I did not receive the call then this call is incoming call whereas it is a missed call.

yes, this code is up to date.
