### ISSUE TITLE
Linphone(3.16.3) ios app push notification not working when app is killed

### ISSUE THREAD

**Issue by TheNazzi89** [BelledonneCommunications/linphone-iphone#330]
I am using linphone open source app (ver 3.16.3) to make video call in my

application. PushKit is already embeded in this version of linephone app.

So, I get iOS device notifications when app is minimized or running in

the foreground. But, iOS device notifications are not working when I kill

the app. This is working fine for linphone's app which I downloaded from

appstore.

Please help me to solve this problem.

Note : I have created VOIP certificate for this app.

In less words, it's doesn't register when the app is killed. But when the app is in background, it registers e and works fine.

**Comment by ReisBenjamin** [comment]
Did you create a prod or dev certificate ?
You'll need prod for testflight and appstrore and dev for developping your app and testing with Xcode

**Comment by TheNazzi89** [comment]
I created a production certificate. As i said, it works fine in background mode, so the push notifications work. But they don't work when the app is killed(swipping up). They worked fine when on previous build, but not on last build.

I think the problem is that the app is unable to register(wake up) when it receives a voip push notification.

**Comment by TheNazzi89** [comment]
I want to add another note: When I open the app after making a call to(that i didn't receive), the app crashes on linphone_core_start_dtmf_stream(theLinphoneCore) of the function -(void)becomeActive of LinphoneManager.m

**Comment by ReisBenjamin** [comment]
Did you change the code of didBecomeActive ? I do not reproduce any crash and push notification works fine with us.
Can you post logs of when the app receives a push notification and doesn't manage to register ?

Thanks

**Comment by TheNazzi89** [comment]
Yes, @ReisBenjamin. You're right. I edited the didBecomeActive. I forced start_at_boot to NO, because I thought that with push notifications we don't need to boot the app when we switch on the phone. I solved the issue two days ago, but forgot to close it. Thanks anyway!

**Comment by Skkumawat** [comment]
I had successfully setup Linphone library on my machine for the video and audio calling.

I gone through the library and found that PushKit is already embeded in this version of linephone app.

When IOS app is going to background or kill then we don't getting push notification.

I also installed LinPhone app form the Apple store and This is not getting push notification too and not received any call when app kill.

I think the problem is that the app is unable to register or may be some issue in certificate(.pem) file.

Please suggest what is the missing & how we resolve this issue?

**Comment by ReisBenjamin** [comment]
Hello,

Make sure your server supports sending push notification, that push notifications are allowed in your device settings for linphone and that in linphone in your account settings push notifications is turned on.

Thanks

**Comment by luisomar10** [comment]
When you mean: " make sure your server supports" what server do you mean?

Because in my case, im using the Linphone server on the cloud, i dont have the control to set this.

And im getting the same issue when the app is killed.
