### ISSUE TITLE
DTMF Stopped Working

### ISSUE THREAD

**Issue by iJasonWade** [BelledonneCommunications/linphone-iphone#335]
We have a custom implementation of linphone and after pulling in the latest changes from master DTMF stopped working. We rolled back to verify and dtmf was working previously. Also we logged out the result for linphone_call_send_dtmf and it returns a 0.

**Comment by iJasonWade** [comment]
@ReisBenjamin, do you know of a resolution for this issue? I want to upgrade the build we have for linphone to resolve a few issues you have fixed our users have seen but we must have DTMF.

**Comment by zj299792458** [comment]
You should first figure it out what kind of DTMF your server supported.
Use linphone_core_set_use_rfc2833_for_dtmf and linphone_core_set_use_info_for_dtmf to adjust.

**Comment by iJasonWade** [comment]
Ok, so I put the code you suggested in place and DTMF still is not working, it works if I go back to the previous build of the linphone-sdk that we were using without changing my code, that was a build from back around August

**Comment by iJasonWade** [comment]
So I figured out that after I upgraded that sip stack to your latest code it changed my INVITE, a=rtpmap:101 telephone-event/48000, that is wrong and should be a=rtpmap:101 telephone-event/8000, how do I change that? And what caused it to change that?

**Comment by iJasonWade** [comment]
Ok, so here are the pieces of the INVITE that are different:

When DTMF works:
'm=audio 7292 RTP/AVP 96 97 98 99 0 8 18 101 100 102
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 SILK/16000
a=rtpmap:98 speex/16000
a=fmtp:98 vbr=on
a=rtpmap:99 speex/8000
a=fmtp:99 vbr=on
a=fmtp:18 annexb=yes'

When it does not:
'm=audio 7292 RTP/AVP 96 97 98 0 8 18 101 99 100
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 speex/16000
a=fmtp:97 vbr=on
a=rtpmap:98 speex/8000
a=fmtp:98 vbr=on
a=fmtp:18 annexb=yes'

**Comment by iJasonWade** [comment]
When I upgrade the rtpmap is wrong, as a descending list it should be 100, 101, 102 with 8000 as 101, but this is what is sent with the INVITE:
```
a=rtpmap:101 telephone-event/48000
a=rtpmap:99 telephone-event/16000
a=rtpmap:100 telephone-event/8000
```

99 is not valid, RFC2833 defines that the primary payload type should be 101 and that 100+ are adjuncts for possible usage. The correct behavior globally is supposed to be to put 101 as telephone-events/8000
