### ISSUE TITLE
No account counfigured ERROR

### ISSUE THREAD

**Issue by TheNazzi89** [BelledonneCommunications/linphone-iphone#336]
The configured account un-configure for unknown reason. The only thing i'm able to note is that this happened mostly when the iPhone switched off for battery low and then switched on. I think that there are some push notifications due to a call or a message in between(switched off - switched on) that cause an error that un-configure the account when switched on the phone or launched the application.

Could anyone help me to solve this issue, please?

**Comment by ReisBenjamin** [comment]
Could you post logs of when the issue happens ?
Do you use flexisip or another sip service ?

Thanks

**Comment by TheNazzi89** [comment]
It doesn't happen every time. So, now I'm not able to send logs.
I worked around to solve the issue.

Thanks anyway.

**Comment by ReisBenjamin** [comment]
re open when you have logs.

Thank you
