### ISSUE TITLE
Linphone / Liblinphone registration in progress over AT&T/T-Mobile LTE.

### ISSUE THREAD

**Issue by hui-chen** [BelledonneCommunications/linphone-iphone#337]
I have company project based on Liblinphone Andoid library.
It works well till early August.

As I know, AT&T / T-Mobile upgrade their network to fully IPv6 at August, After that, my devices always stay at "Registration In Progress" state when using carrier LTE connection.
For IPv4-based WiFi environment, it works well.

We are connecting to NetSapiens server for SIP service.
The liblinphone code is pulled from master branch at Oct. 17th, 2017.
I tried enableIpv6 true/false and enableIce true/false: the behaviors are same.
I am using AT&T Galaxy S6 and T-Mobile Google Pixel to test.

=============================================

According SIP log, SIP registration fails due to socket connecting timeout:
1. stream_channel_connect() works as expected (bctbx_connect returns -1 with BELLESIP_EINPROGRESS state)
2. in error case, stream_channel_process_data() callback is triggered after one minute with event BELLE_SIP_EVENT_TIMEOUT
3. in working case (IPv4 WiFi environment), stream_channel_process_data is triggered immediately after stream_channel_connect() returns; and state is set to BELLE_SIP_CONTINUE properly.

4. the other potential issue is: when using UDP transport, connection part works fine, but I can only receive the response package for original SIP request: all subscription request cannot get response. The reason looks like after belle_sip_channel_learn_public_ip_port() call, the following SIP request package has different IP address in SIP message header. It works after I commented out this method.

================================================
My questions:
1. For TCP connection issue, is it because of NetSapiens server firewall? If so, why UDP works?
2. If it is not server issue, is it a bug of Liblinphone Android library?

Any information will be very helpful for me.
Thanks!

**Comment by eliburke** [comment]
We have experienced intermittent problems with T-Mobile and AT&T with similar symptoms when connecting to FreeSwitch. (liblinphone for iOS and Android) 

Eventually we determined that the VM hosting our VOIP server did not have IPV6 support compiled into the kernel. Registration would start, but the return address would not match, so it would ultimately fail every time. Your problem may be different, but it’s something you can try to check with your VOIP provider.

**Comment by ReisBenjamin** [comment]
Hello,

It seems to be about Linphone Android, this is the Linphone iOS repo, please open an issue on the correct repo.

Thanks

**Comment by DroidPulkit** [comment]
Did it work on Android?
I also faced the same issue, it's not working on any USA carriers till now
