### ISSUE TITLE
resendChat() not working on iOS 11

### ISSUE THREAD

**Issue by TheNazzi89** [BelledonneCommunications/linphone-iphone#338]
The resend message(white '!' inside red dot) does nothing since I updated the iOS to 11. Hope I'm not the only one who has this problem.

**Comment by ReisBenjamin** [comment]
fixed in commit 5c534def046cf0a0e1d8c2fb332f11e46f11e8e5

**Comment by TheNazzi89** [comment]
Nice! But now on iOS <11 it's not working.

**Comment by TheNazzi89** [comment]
Not working neither on iOS 11. Can't understand what did you fix.
