### ISSUE TITLE
Help compile i dont know why its stop on Ubuntu 16.04 

### ISSUE THREAD

**Issue by zlodij13** [BelledonneCommunications/linphone-iphone#339]
[ 96%] Building C object CMakeFiles/mswebrtc.dir/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c.o
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c: In function ‘mm_pow_ps’:
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:221:1: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
 static __m128 mm_pow_ps(__m128 a, __m128 b) {
 ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c: In function ‘FilterFarSSE2’:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:978:1: error: inlining failed in call to always_inline ‘_mm_storeu_ps’: target specific option mismatch
 _mm_storeu_ps (float *__P, __m128 __A)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:61:7: error: called from here
       _mm_storeu_ps(&yf[1][j], h);
       ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:978:1: error: inlining failed in call to always_inline ‘_mm_storeu_ps’: target specific option mismatch
 _mm_storeu_ps (float *__P, __m128 __A)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:60:7: error: called from here
       _mm_storeu_ps(&yf[0][j], g);
       ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:181:1: error: inlining failed in call to always_inline ‘_mm_add_ps’: target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:59:20: error: called from here
       const __m128 h = _mm_add_ps(yf_im, f);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:181:1: error: inlining failed in call to always_inline ‘_mm_add_ps’: target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:58:20: error: called from here
       const __m128 g = _mm_add_ps(yf_re, e);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:181:1: error: inlining failed in call to always_inline ‘_mm_add_ps’: target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:57:20: error: called from here
       const __m128 f = _mm_add_ps(c, d);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:187:1: error: inlining failed in call to always_inline ‘_mm_sub_ps’: target specific option mismatch
 _mm_sub_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:56:20: error: called from here
       const __m128 e = _mm_sub_ps(a, b);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:55:20: error: called from here
       const __m128 d = _mm_mul_ps(xfBuf_im, wfBuf_re);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:54:20: error: called from here
       const __m128 c = _mm_mul_ps(xfBuf_re, wfBuf_im);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:53:20: error: called from here
       const __m128 b = _mm_mul_ps(xfBuf_im, wfBuf_im);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:52:20: error: called from here
       const __m128 a = _mm_mul_ps(xfBuf_re, wfBuf_re);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:51:20: error: called from here
       const __m128 yf_im = _mm_loadu_ps(&yf[1][j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:50:20: error: called from here
       const __m128 yf_re = _mm_loadu_ps(&yf[0][j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:49:20: error: called from here
       const __m128 wfBuf_im = _mm_loadu_ps(&aec->wfBuf[1][pos + j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:48:20: error: called from here
       const __m128 wfBuf_re = _mm_loadu_ps(&aec->wfBuf[0][pos + j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:47:20: error: called from here
       const __m128 xfBuf_im = _mm_loadu_ps(&aec->xfBuf[1][xPos + j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:46:20: error: called from here
       const __m128 xfBuf_re = _mm_loadu_ps(&aec->xfBuf[0][xPos + j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:978:1: error: inlining failed in call to always_inline ‘_mm_storeu_ps’: target specific option mismatch
 _mm_storeu_ps (float *__P, __m128 __A)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:61:7: error: called from here
       _mm_storeu_ps(&yf[1][j], h);
       ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:978:1: error: inlining failed in call to always_inline ‘_mm_storeu_ps’: target specific option mismatch
 _mm_storeu_ps (float *__P, __m128 __A)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:60:7: error: called from here
       _mm_storeu_ps(&yf[0][j], g);
       ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:181:1: error: inlining failed in call to always_inline ‘_mm_add_ps’: target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:59:20: error: called from here
       const __m128 h = _mm_add_ps(yf_im, f);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:181:1: error: inlining failed in call to always_inline ‘_mm_add_ps’: target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:58:20: error: called from here
       const __m128 g = _mm_add_ps(yf_re, e);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:181:1: error: inlining failed in call to always_inline ‘_mm_add_ps’: target specific option mismatch
 _mm_add_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:57:20: error: called from here
       const __m128 f = _mm_add_ps(c, d);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:187:1: error: inlining failed in call to always_inline ‘_mm_sub_ps’: target specific option mismatch
 _mm_sub_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:56:20: error: called from here
       const __m128 e = _mm_sub_ps(a, b);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:55:20: error: called from here
       const __m128 d = _mm_mul_ps(xfBuf_im, wfBuf_re);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:54:20: error: called from here
       const __m128 c = _mm_mul_ps(xfBuf_re, wfBuf_im);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:53:20: error: called from here
       const __m128 b = _mm_mul_ps(xfBuf_im, wfBuf_im);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:193:1: error: inlining failed in call to always_inline ‘_mm_mul_ps’: target specific option mismatch
 _mm_mul_ps (__m128 __A, __m128 __B)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:52:20: error: called from here
       const __m128 a = _mm_mul_ps(xfBuf_re, wfBuf_re);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:51:20: error: called from here
       const __m128 yf_im = _mm_loadu_ps(&yf[1][j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:50:20: error: called from here
       const __m128 yf_re = _mm_loadu_ps(&yf[0][j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:49:20: error: called from here
       const __m128 wfBuf_im = _mm_loadu_ps(&aec->wfBuf[1][pos + j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:48:20: error: called from here
       const __m128 wfBuf_re = _mm_loadu_ps(&aec->wfBuf[0][pos + j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:47:20: error: called from here
       const __m128 xfBuf_im = _mm_loadu_ps(&aec->xfBuf[1][xPos + j]);
                    ^
In file included from /usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:31:0,
                 from /home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:15:
/usr/lib/gcc/i686-linux-gnu/5/include/xmmintrin.h:929:1: error: inlining failed in call to always_inline ‘_mm_loadu_ps’: target specific option mismatch
 _mm_loadu_ps (float const *__P)
 ^
/home/manager1/linphone-desktop/submodules/mswebrtc/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c:46:20: error: called from here
       const __m128 xfBuf_re = _mm_loadu_ps(&aec->xfBuf[0][xPos + j]);
                    ^
CMakeFiles/mswebrtc.dir/build.make:1238: recipe for target 'CMakeFiles/mswebrtc.dir/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c.o' failed
make[6]: *** [CMakeFiles/mswebrtc.dir/webrtc/webrtc/modules/audio_processing/aec/aec_core_sse2.c.o] Error 1
make[6]: Leaving directory '/home/manager1/linphone-desktop/WORK/desktop/Build/mswebrtc'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mswebrtc.dir/all' failed
make[5]: *** [CMakeFiles/mswebrtc.dir/all] Error 2
make[5]: Leaving directory '/home/manager1/linphone-desktop/WORK/desktop/Build/mswebrtc'
Makefile:149: recipe for target 'all' failed
make[4]: *** [all] Error 2
make[4]: Leaving directory '/home/manager1/linphone-desktop/WORK/desktop/Build/mswebrtc'
CMakeFiles/EP_mswebrtc.dir/build.make:114: recipe for target '/home/manager1/linphone-desktop/WORK/desktop/Stamp/EP_mswebrtc/EP_mswebrtc-build' failed
make[3]: *** [/home/manager1/linphone-desktop/WORK/desktop/Stamp/EP_mswebrtc/EP_mswebrtc-build] Error 2
make[3]: Leaving directory '/home/manager1/linphone-desktop/WORK/desktop/cmake'
CMakeFiles/Makefile2:485: recipe for target 'CMakeFiles/EP_mswebrtc.dir/all' failed
make[2]: *** [CMakeFiles/EP_mswebrtc.dir/all] Error 2
make[2]: Leaving directory '/home/manager1/linphone-desktop/WORK/desktop/cmake'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/manager1/linphone-desktop/WORK/desktop/cmake'
Makefile:14: recipe for target 'desktop-build' failed
make: *** [desktop-build] Error 2

**Comment by ReisBenjamin** [comment]
Hello,

You're on the Linphone iOS repo not linphone-desktop.
Please open an issue on the correct repo.

Thank you
