### ISSUE TITLE
TLS transport with existing SIP account

### ISSUE THREAD

**Issue by fbxcelsior** [BelledonneCommunications/linphone-iphone#34]
Hi,

When I try to connect to connect to an existing SIP account using TLS it seems that UDP is always used. The registration ends up failing after several attempts with an "io error", but if I then press continue go to the account settings and change UDP to TLS in the transport section, it ends up connecting.

This was experienced in the 3.10.9 tag.

Thank you.

Best regards,

Filipe

**Comment by bagage** [comment]
You are right, it was just fixed in 9bd5716371ef1c7d3b3f98e9b6b277050dbfcffc, thanks!
