### ISSUE TITLE
App won't open after remote provision

### ISSUE THREAD

**Issue by bis-nor** [BelledonneCommunications/linphone-iphone#340]
I did a remote provision. It took all the settings and works. After I close the Linphone, I am unable to open Linphone again. It will load the Linphone loading screen but closes after that. 

Is there a way around it, so it can keep the configuration and keep it from automatically closing?

TIA.

**Comment by ReisBenjamin** [comment]
Hello,

can you post the logs and stack trace of when this issue happens ?

Thanks
