### ISSUE TITLE
Enable Push notification default

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#341]
Hi

How can enable push notiication on by default .Its always off at first launch.

Regards

**Comment by hadidez** [comment]
in LinphoneCoreSettingsStore.m in default value section do this:
[self setBool:YES forKey:@"account_pushnotification_preference"];

**Comment by ReisBenjamin** [comment]
Can this be closed ?

**Comment by ThabreshVivid** [comment]
@ReisBenjamin 

I faced one issue while submitting my app (with linphone) to iTunes and i got one error that shown in below. can you please help me to fix this issue.'

"invalid bundle. the bundle linphone.app/frameworks/linphone.framework does not support the minimum os version specified in the info.plist. ios"
