### ISSUE TITLE
Application crashing when declining a call

### ISSUE THREAD

**Issue by lindseyvastola** [BelledonneCommunications/linphone-iphone#342]
My application is crashing and I get this error "You must fill a reason when changing call state" when trying to decline an incoming call with this code:
DispatchQueue.global(qos: .default).async {
			let currentcall = linphone_core_get_current_call(lc)
			if currentcall != nil {
				linphone_core_decline_call(lc, currentcall, LinphoneReasonDeclined)
			} else {
				NSLog("call is nil")
			}
		}

Decline_call does work when my state initially changes but I need to decline when the user selects to, not when the changes.

**Comment by ReisBenjamin** [comment]
linphone_core_decline_call is deprecated, please use linphone_call_decline(call, reason)
What do you mean by "Decline_call does work when my state initially changes but I need to decline when the user selects to, not when the changes." ? can you provide scenario examples ?
Can i see more logs and the crash stack trace ?

Thanks

**Comment by lindseyvastola** [comment]
Sorry for not being clear, the only time I can get decline call to work is when my call state changes. Since I am declining on a user action, I have to be able to do it at a later time.

**Comment by ReisBenjamin** [comment]
Old library is no longer supported, i suggest you update your library.
Can you post the stacktrace of the crash ?
