### ISSUE TITLE
enable_auto_answer_preference aetting doesn't work.

### ISSUE THREAD

**Issue by ProudNoob** [BelledonneCommunications/linphone-iphone#343]
Go to Setings->Advanced->Auto-answer after notification->ON. Press Home button to minimize the app, then call. The notification comes but you still have to tap on it to open the app, no auto-answer.

What is the correct form of linphone push notification, I am using  
`{"aps":{"alert":"Testing.. (26)","badge":1,"sound":"default"}}`

**Comment by ReisBenjamin** [comment]
Hello,

auto_answer allows to answer automatically when linphone is launched. if the app is in background or closed you'll indeed need to tap on the notification to open linphone the the call will be answer.
It's not possible to answer a call automatically if the app is not launched.
