### ISSUE TITLE
Setting Preferred video size not work?

### ISSUE THREAD

**Issue by willylee007** [BelledonneCommunications/linphone-iphone#345]
Hello! I have set preferred video size to HD(960x720) on linphone-demo, details: Setting-->Video-->Preferred video size-->choose HD, then start a video call, but I saw "Sent video resolution: 240x320)". But sometimes , it works really correctly. Why strange things happen?

**Comment by ReisBenjamin** [comment]
Hello,

Depending on the network you can't send HD video, the preferred video size is matched only when the network allows it.

**Comment by willylee007** [comment]
Thanks! I knew that video size is influenced by network after I saw videotoolbox.c's codes. So I modified the following setting in linphonerc:
[net]
download_bw=1000
upload_bw=1000

It works correctly after modify.
