### ISSUE TITLE
VOICE MAIL BUTTON ERROR

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#347]
I guess after the latest iOS update from apple, holding down the 1 button no longer functions for calling your voicemail. When can we see this corrected? I've tested this against your App Store version and im receiving the same failure.

**Comment by S0U1SB4N3** [comment]
I have corrected this on my end with the following line changes. 

DialerView.m

Line 425

- (void)onOneLongClick:(id)sender {
    LinphoneManager *lm = LinphoneManager.instance;
    NSString *voiceMail = [lm lpConfigStringForKey:@"voice_mail_uri"];
 // Strips out all invalid characters the user might type in 
    NSString *condensedPhoneNumber = [[voiceMail componentsSeparatedByCharactersInSet:
                                       [[NSCharacterSet characterSetWithCharactersInString:@"*0123456789"]
                                        invertedSet]]
                                      componentsJoinedByString:@""];
    voiceMail = condensedPhoneNumber;
//END of striping out invalid characters
    LinphoneAddress *addr = [LinphoneUtils normalizeSipOrPhoneAddress:voiceMail];
    
    if (addr) {
        linphone_address_set_display_name(addr, NSLocalizedString(@"Voice mail", nil).UTF8String);
        [lm call:addr];
        linphone_address_destroy(addr);
    } else {
//Hard coding an asterisk default voicemail box Star code if linphone or user has a null value for voicemail and forces the previous address check. 
        NSString *voiceMail = @"*86";
        LinphoneAddress *addr = [LinphoneUtils normalizeSipOrPhoneAddress:voiceMail];
        linphone_address_set_display_name(addr, NSLocalizedString(@"Voice mail", nil).UTF8String);
        [lm call:addr];
        linphone_address_destroy(addr);
        //LOGE(@"Cannot call voice mail because URI not set or invalid!");
    }
    linphone_core_stop_dtmf(LC);
}




if a user doesn't modify the plist and place their own default star code for voicemail or if they leave the voicemail blank this modification will auto dial a *86 voicemail box code, however, if the user places their own code into the voicemail box in the settings within the app, that code overrides my default. the end user will not see or notice any changes however if this is not corrected the enduser will not get a response if a long press of the 1 key, it will just fail and do nothing 


hope this helps out :)

**Comment by ReisBenjamin** [comment]
Hi,

Can this be closed ?

**Comment by S0U1SB4N3** [comment]
yes
but you need to address the null value even your code from app sore gives ever since the latest iOS update.
