### ISSUE TITLE
Sending URI Parameters in SIP request

### ISSUE THREAD

**Issue by mrdavidrees** [BelledonneCommunications/linphone-iphone#348]
I'm trying to add some simple information into the uri parameters to send to the other voip client, these will help identify the user in our database.

So far I have tried to include this information in a few different ways but none of them have been received on the other side.

**Client 1**
    before starting call to address.

    linphone_address_set_header(addr, "TEST", "TEST");
    linphone_address_set_param(addr, "TEST", "TEST");
    linphone_address_set_uri_param(addr, "TEST", "TEST");
    linphone_call_params_add_custom_header(cp, "TEST", "TEST");
    

**Client 2**
    On notification for kLinphoneCallUpdate

    const char *lValue = linphone_address_get_header(cp, "TEST", "TEST");
    const char *lValue = linphone_address_get_param(cp, "TEST", "TEST");
    const char *lValue = linphone_address_get_uri_param(cp, "TEST", "TEST");
    const char *lValue = linphone_call_params_get_custom_header(cp, "TEST", "TEST");

Is this the correct way?, I cannot find any information for this, I've seen some talk around sending information in a contact header but have no idea how to do this on iOS.

**Comment by ReisBenjamin** [comment]
Hello,

I'll need logs from both side to see what happens.

Thanks

**Comment by mrdavidrees** [comment]
Hi,  here are the attached logs.

[recieving.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/1480664/recieving.txt)
[sending.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/1480665/sending.txt)

Calling side.
```

    linphone_address_set_param(copy, "DavidTest1", "DavidTest1Data");
    linphone_address_set_header(copy, "DavidTest2", "DavidTest2Data");
    linphone_address_set_uri_param(copy, "DavidTest3", "DavidTest3Data");

```

Both sides.

```
+ (void)callStatusUpdated:(NSNotification *)notification {
    LinphoneCallState state = [[notification.userInfo objectForKey:@"state"] intValue];
    NSString *message = [notification.userInfo objectForKey:@"message"];
    LinphoneCall *call = [[notification.userInfo objectForKey:@"call"] pointerValue];
    NSLog(@"%@", message);
    
    
    const LinphoneAddress *addr2 = linphone_call_get_remote_address(call);
    const char *test1 = linphone_address_get_param(addr2, "DavidTest1");
    const char *test2 = linphone_address_get_header(addr2, "DavidTest2");
    const char *test3 = linphone_address_get_uri_param(addr2, "DavidTest3");
    
    
    if (test1) {
        NSLog(@"%@",[NSString stringWithUTF8String:test1]);
    }
    if (test2) {
        NSLog(@"%@",[NSString stringWithUTF8String:test2]);
    }
    if (test3) {
        NSLog(@"%@",[NSString stringWithUTF8String:test3]);
    }
}

```

**Comment by ReisBenjamin** [comment]
Hello,

From your logs : You do send correctly your custom info in your INVITE but you do not receives them because you receive another INVITE with another call-id. It means the server you use is not a proxy but a Back 2 Back User Agent and so when it receives your INVITE he recreates one for the calle and as it doesn't understand your custom info it doesn't add them in the INVITE.

I suggest you either change the configuration of your server to support them or your change for a proxy that will only route the INVITE innstead of regenerating them?

Best regards
