### ISSUE TITLE
Unable to compile linphone - Xcode9.1 on Sierra 

### ISSUE THREAD

**Issue by jfalexvijay** [BelledonneCommunications/linphone-iphone#349]
Just a month ago I was able to compile linphone without any issue.

Yesterday I have upgraded xcode and mac OS. After updation I am getting below error:
```
/linphone-iphone/submodules/externals/libmatroska-c/corec/corec/helpers/system/ccsystem_posix.c:47:12: error: 'system' is unavailable: not available on iOS
    return system(Command);
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/usr/include/stdlib.h:195:6: note: 'system' has been explicitly marked
      unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
make[6]: *** [corec/corec/CMakeFiles/corec.dir/helpers/system/ccsystem_posix.c.o] Error 1
make[5]: *** [corec/corec/CMakeFiles/corec.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/linphone-iphone/WORK/ios-arm64/Stamp/EP_matroska2/EP_matroska2-build] Error 2
make[2]: *** [CMakeFiles/EP_matroska2.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2
jfalexvijay:linphone-iphone root#
```
Any idea how to fix it ?

**Comment by ReisBenjamin** [comment]
Hello,

If you update your code to master and your submodule : 
git pull && git submodule update --init --recursive
You should compile fine.
If not make sure that submodules/externals/libmatroska-c is deleted and that submodules/bcmatroska2 is up to date.

**Comment by jfalexvijay** [comment]
Hi @ReisBenjamin,
Above issue is resolved.. 

I am getting this library issue http://lists.gnu.org/archive/html/linphone-developers/2017-08/msg00048.html

Please help me to fix it.

**Comment by ReisBenjamin** [comment]
Does this issue happen on Linphone or your own project ?
On which device are you trying to run it ?

**Comment by jfalexvijay** [comment]
I have added the available linphone frameworks to my project. 

There is a header file called "core.h" in "linphone.framework" which included "mediastreamer2/mscommon.h"

I am getting ["mediastreamer2/mscommon.h" is not found] error while compiling my project.

**Comment by ReisBenjamin** [comment]
Did you add all of our frameworks ?
bctoolbox.framework
linphone.framework
mediastreamer_base.framework
mediastreamer_voip.framework
msamr.framework
mscodec2.framework
msopenh264.framework
mssilk.framework
mswebrtc.framework
msx264.framework
ortp.framework

There needs to be in your project embedded binaries and linked binaries.
And you need to add in your search path their locations

**Comment by jfalexvijay** [comment]
I have added those libraries. But still the same issue. Please check the attached screenshot.

![screen shot 2017-11-22 at 5 00 56 pm](https://user-images.githubusercontent.com/462630/33125552-ef46b51e-cfa6-11e7-80b0-40237eb0f417.png)
![screen shot 2017-11-22 at 5 02 07 pm](https://user-images.githubusercontent.com/462630/33125553-ef8e6ce2-cfa6-11e7-9847-8438de384bdc.png)

**Comment by jfalexvijay** [comment]
Any idea ?

**Comment by S0U1SB4N3** [comment]
mine worked fine sorry can't help

**Comment by sakthig** [comment]
@jfalexvijay did you resolve this ?

@ReisBenjamin which path should i add in search path ? I have srcroot at recursive .. should that not be enough ? and there is no folder called mediastreamer2.

i renamed mediastreamer_base to mediastreamer2.. which makes the error go away. but fails at linker.

**Comment by ReisBenjamin** [comment]
Adding the framework to project is not enough, you need to add them to your linking binaries and to your embedded binaries.

**Comment by OnurVar** [comment]
I'm also having the same problem. You can check out the problem here in this demo project.
[https://github.com/OnurVar/LinphoneRepository](url)

**Comment by sakthig** [comment]
@OnurVar Add the binaries to embedded binaries as @ReisBenjamin said. That works!

**Comment by OnurVar** [comment]
@sakthig Which version of XCode are you using ? And can you please tell the steps of how to add embeded binaries ?

Mine is XCode 9.2 (Mac 10.13.2)

**Comment by sakthig** [comment]
@OnurVar Mine is also 9.2 

Go to General > Embed Frameworks > Click '+' > Select all linphone frameworks > Add

**Comment by OnurVar** [comment]
@sakthig As you can see in screenshots, they are already added but still happening. 

and im using this one http://www.linphone.org/releases/ios/liblinphone-iphone-sdk-latest.zip

**Comment by sakthig** [comment]
sorry i dint see the screenshot. this setup is working for me.

**Comment by jfalexvijay** [comment]
Hi Sakthig,

Why some mediastreamer2 header files are included in <linphone/core.h> file. Please see the attached screenshot for more information.

Am I doing something wrong while compiling linphone source code ?

![screen shot 2018-03-01 at 11 25 00 am](https://user-images.githubusercontent.com/462630/36829114-89cfcd34-1d43-11e8-9d28-631c254f4b75.png)

**Comment by StefanBstorm** [comment]
I have same problem, only solution that i find is
<img width="859" alt="screen shot 2018-04-22 at 14 48 43" src="https://user-images.githubusercontent.com/37397578/39095207-f8874c9e-463c-11e8-92b0-5ae6f98030f3.png">
 you need to include headers in Build Settings

**Comment by cdotindia** [comment]
@jfalexvijay How did you solve this issue?
`error: 'system' is unavailable: not available on iOS`

**Comment by ReisBenjamin** [comment]
@cdotindia 
Update your code and submodules
