### ISSUE TITLE
Issue with lime enabled

### ISSUE THREAD

**Issue by fbxcelsior** [BelledonneCommunications/linphone-iphone#35]
Hi,

I spotted the following:

- with lime enabled (lime=1 in the sip configurations) and using ZRTP encryption, the app crashes when you try to send a message to an account to which you do not trust. This happens when you send a message to an account you never made a call to (and therefore did not establish trust with) or to an account you may have called before but never established trust with or removed trust in the meantime.

This happens in the master version.

Thank you in advance.

Best,

Filipe

**Comment by bagage** [comment]
Hi,

Lime is compiled but not implemented nor tested in iOS version, so indeed crashes may appear. Any patch is welcome however!

**Comment by fbxcelsior** [comment]
Thank you for your reply! Will do, if I managed to find the root cause, I will make a patch.

Any predictions on a stable 3.X version, i.e., one that is good enough for app store release?

Thanks

**Comment by bagage** [comment]
Latest tag is latest stable version, so you should pick tag `3.11.8`.

**Comment by bagage** [comment]
Fixed in 3a8a979
