### ISSUE TITLE
Cannot Send attachment file through Chat

### ISSUE THREAD

**Issue by Skkumawat** [BelledonneCommunications/linphone-iphone#351]
Hey Support Team,
I had successfully setup Linphone library and tried to sending attachment files(Images) through the chat.
Its showing only progress indictor but didn't upload and get to receiver.

**Comment by ReisBenjamin** [comment]
Do you have set up a server where to upload the file ?
Can you post logs of when the issue happens ? Do you try to send file the same way we do on linphone ios ?

**Comment by Skkumawat** [comment]
We didn't set up an own server. I use Linphone server for the Chating. We also downloaded LinPhone IOS app on the IOS device and same issue exist in the Linphone app.

**Comment by Skkumawat** [comment]
Hello Guys,

Any update for us?

**Comment by ReisBenjamin** [comment]
Fixed on the master branch.
Please update your code and retry.
Re-open with logs if the issue still happens.

Thanks

**Comment by mahekkausar** [comment]
I recently have played around with linphone, and I successfully integrate it with my own server for call, and text message, However I am trying to config the sending image and it does not work at all. How I can implement file sharing with my own server

**Comment by navin111** [comment]
I recently have played around with linphone, and I successfully integrate it with my own server for call, and text message, However I am trying to config the sending  file (any type , image , document etc) and it does not work at all. How I can implement file sharing with my own server

 If I use linphone sip, with the same code to send files ; the same attachments are selected, sent and received successfully across devices.
