### ISSUE TITLE
 how to turn off front camera mirror mode

### ISSUE THREAD

**Issue by wlinshicong** [BelledonneCommunications/linphone-iphone#352]
1.When opening the front camera, the screen reversed the left and right, I want to know how to turn off front camera mirror mode and change other video arguments。
2.when i connect to mac linphone ，i click video button，my mac all right，but in ipad，it did not show video which transfer from mac，only show a loading view。 
anyone can help ?

**Comment by ReisBenjamin** [comment]
Hello,

1: We do not modify the video stream of the iOS Camera. You can check the settings og the AVCaptureFoundation frameworks and modify the file ioscapature.m in the meidastreamer2 submodule if you want to change the behavior.

2: we'll need logs to see what went wrong on your video call.

Thank

**Comment by wlinshicong** [comment]
thank for your help！question 1 has solved.question 2 sometiems normal,sometime NO.

**Comment by wlinshicong** [comment]
the  new New question,in my call,the audios is noise and had big noise audios

**Comment by ReisBenjamin** [comment]
Again i'll need logs to see what happens.
Why did you change the rc-factory ?

Thanks

**Comment by ReisBenjamin** [comment]
unanswered.
Reopen when answering.
