### ISSUE TITLE
Delay while dialing a number

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#353]
When introducing Callkit, I know Linphone will wait for didActivateAudioSession to actually invite an address. I assume that is causing the delay of outgoing call window popping out, after user clicks call. (correct me if i'm wrong)

But the strange thing is, when I enter the number on dial pad manually and click call button, the delay is significant like 2-3 secs. If I re-dial this number by click call button again, or from the history list, the delay almost disappears. And if I try re-dial the exact same number once again by manually entering again, delay comes back. I tested it for a hundred times, I feel like I can totally avoid the delay by double click call button or dialing from history list.

I don't see how this factor connected to Callkit, does that mean the delay is totally avoidable programmatically in all circumstances?

**Comment by zj299792458** [comment]
I found the problem.  linphone_core_play_dtmf() will significantly delay the didActivateAudioSession recall for almost 3 seconds. 

In this case, just don't invoke linphone_core_play_dtmf() in UIDigitButton. This eliminates the delay efficiently...

Not sure if this is an issue...

**Comment by ReisBenjamin** [comment]
Hello,

You can make this modification if you want it will only affect the fact that you do no hear the dtmf sound when touching a digit button.
