### ISSUE TITLE
Unable to resume call

### ISSUE THREAD

**Issue by iJasonWade** [BelledonneCommunications/linphone-iphone#356]
When I have an active call and then another call comes in I am calling linphone_call_pause on the active call when the incoming call Answer button is pressed before I call linphone_call_accept for the incoming call, I did this because the documentation says you must call linphone_call_pause before a call can be resumed, however when I try to resume the call that was paused by calling linphone_call_resume that method is returning a -1, if I pause the active call then I can resume either call but this requires our users to do that, how do I get the call on pause to be able to resume in this scenario?

**Comment by araby123** [comment]
there is now a problem with the flexisip are now If you install it via repo in new centos7 not working showing error

**Comment by ReisBenjamin** [comment]
Hello,

Is there any log errors when you resume the call ?

Thanks

**Comment by iJasonWade** [comment]
No, everything works fine after I pause the other call.

**Comment by iJasonWade** [comment]
2017-12-04 09:22:12.093225-0600 ePhoneGO[2003:3187735] [Warning] lib/Cannot resume call 0x15e88ee00 because another call is locking the sound resources.

**Comment by ReisBenjamin** [comment]
You can't have 2 active calls, if you have one active call and one paused call you need to pause the active call before resuming the paused one.

[Warning] lib/Cannot resume call 0x15e88ee00 because another call is locking the sound resources. means that an active call is already using the sound resources

**Comment by iJasonWade** [comment]
Ok, so I tried what you said, when I go to add a second call I iterate through the calls and pause any active call, then send the invite, but the result is the same, once the second call is active I still have to hold it before I can take the first call off of hold, after I do that I can take either call off hold without holding the other one first.

`            const MSList *callsList = linphone_core_get_calls(LC);
            while (callsList) {
                LinphoneCall *call = callsList->data;
                if (linphone_call_get_state(call) == LinphoneCallStreamsRunning) {
                    linphone_call_pause(call);
                }
                callsList = callsList->next;
            }
            linphone_core_invite(LC, [callee UTF8String]);`

**Comment by ReisBenjamin** [comment]
As I said in my previous post, it is impossible to have two active calls in Linphone.
Only one. What exactly do you want to do ?

**Comment by iJasonWade** [comment]
So calling linphone_call_accept() when there is another active call doesn't automatically put that first call on hold? And if it does, which it seems like it does, then shouldn't that mean there is only one active call?

**Comment by ReisBenjamin** [comment]
Can I see logs of when the issue happens ?

Thanks

**Comment by Muhammad-Ahad-Nawaz** [comment]
I am facing same issue, like I can't hold and resume second incoming call. In my case media stream drops audio frame whenever I have an accept call over an active call.

Highly appreciate any help, Thanks

**Comment by Rushabh5** [comment]
Hey @ReisBenjamin 

Would you please help me with that issue.

Awaiting for your reply.

**Comment by varunrevcord** [comment]
Hi Everyone on this thread,

Is this issue resolved because I am facing the same issue in the latest Linphone Source code when compiled and running. Can anyone suggest me something to fix it. 

Thanks and Regards
Varun

**Comment by Shoukat488** [comment]
Hey,
I had the same issue that I was unable to resume the call
I solve this by using the above code in this fashion

`const MSList *callsList = linphone_core_get_calls(LC); 
while (callsList) { 
LinphoneCall *call = callsList->data;  
linphone_call_pause(call); 
callsList = callsList->next; 
}`

Hopefully it will solve your problem

**Comment by varunrevcord** [comment]
Hi Shoukat,

Thanks for replying with help. But I tried the same and it is not working for me. Can you please elaborate or share the complete fix in your code file so that I can try the same and let the community know. 

Thanks and Regards
Varun

**Comment by varunrevcord** [comment]
@BelledonneComm is there any plan to fix this bug up in next release. or anyone who has fixed this please help me to fix it.
