### ISSUE TITLE
disable in app purchase 

### ISSUE THREAD

**Issue by hadidez** [BelledonneCommunications/linphone-iphone#357]
hi, how i can disable in app purchase ? when in disable it from capabilities linker error occur

**Comment by ReisBenjamin** [comment]
What errors ?

**Comment by hadidez** [comment]
Apple Mach-O Linker Error Group
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
  "_OBJC_CLASS_$_SKReceiptRefreshRequest", referenced from:
  "_OBJC_CLASS_$_SKMutablePayment", referenced from:
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hadidez** [comment]
i think its because of some file that are using in app purchase library ...

**Comment by hadidez** [comment]
i just disable in app purchase feature and add store.kit library manually.
