### ISSUE TITLE
is there way to change port in linphone(port : 5060 to other port)?

### ISSUE THREAD

**Issue by chandani412** [BelledonneCommunications/linphone-iphone#358]
is there way to change port in linphone(port : 5060 to other port)?

help me to change port

**Comment by ReisBenjamin** [comment]
Can you elaborate on what you're trying to do ?
You can force a port by using sip:myaddress@domain:port

Thanks

**Comment by usman-kh1** [comment]
The above answer worked for android but tried every possible solution by adding port at the end of domain name, also tired changing port_preference LinphoneCoreSettingsStore. Also changed port in config files but no solution is workable so far. Any help would be appreciable.

**Comment by NFSAWAN** [comment]
The port with url solution worked in android project but not working on ios side. Is there any other way to change the port in ios code

**Comment by moderateepheezy** [comment]
@NFSAWAN Did you figure this out, currently having the same issue.

**Comment by EmilyRRR** [comment]
Does anyone get any idea?

**Comment by nbkhwjm** [comment]
this (using host:port) has worked for me for some time then has stopped now...  both android and IOS...
