### ISSUE TITLE
Close session function

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#359]
Hi 

Im facing troubles trying to implement a logout button in de statusbar.

I created a func like this

- (IBAction)closeSession:(id)sender {
    
    
    [settingsStore removeAccount];
    
     [LinphoneManager.instance destroyLinphoneCore];

    
    [PhoneMainView.instance changeCurrentView:AssistantView.compositeViewDescription];
    
}

But im having a crash trying this

Here is the log->

Linphone core not initialized yet
2017-12-05 17:15:35.235185-0300 linphone[28582:5685551] Stack Trace: (
	0   CoreFoundation                      0x00000001089281ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107d78f41 objc_exception_throw + 48
	2   linphone                            0x0000000100ac876a +[LinphoneManager getLc] + 106
	3   linphone                            0x0000000100aa3a3d -[StatusBarView registrationUpdate:] + 61
	4   linphone                            0x0000000100aa3abe -[StatusBarView globalStateUpdate:] + 62
	5   CoreFoundation                      0x00000001088c3fdc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00000001088c3eda _CFXRegistrationPost + 442
	7   CoreFoundation                      0x00000001088c3c22 ___CFXNotificationPost_block_invoke + 50
	8   CoreFoundation                      0x00000001088858c2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	9   CoreFoundation                      0x0000000108884a3c _CFXNotificationPost + 652
	10  Foundation                          0x00000001042a9852 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	11  linphone                            0x0000000100acc889 __52-[LinphoneManager onGlobalStateChanged:withMessage:]_block_invoke + 105
	12  libdispatch.dylib                   0x00000001093873f7 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x000000010938843c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00000001093936f0 _dispatch_main_queue_callback_4CF + 628
	15  CoreFoundation                      0x00000001088eaee9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00000001088af592 __CFRunLoopRun + 2402
	17  CoreFoundation                      0x00000001088ae9b9 CFRunLoopRunSpecific + 409
	18  GraphicsServices                    0x000000010b4849c6 GSEventRunModal + 62
	19  UIKit                               0x00000001058805e8 UIApplicationMain + 159
	20  linphone                            0x0000000100a5e2be main + 126
	21  libdyld.dylib                       0x0000000109404d81 start + 1
)
2017-12-05 17:15:35.235870-0300 linphone[28582:5685551] *** Terminating app due to uncaught exception 'LinphoneCoreException', reason: 'Linphone core not initialized yet'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001089281ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000107d78f41 objc_exception_throw + 48
	2   linphone                            0x0000000100ac876a +[LinphoneManager getLc] + 106
	3   linphone                            0x0000000100aa3a3d -[StatusBarView registrationUpdate:] + 61
	4   linphone                            0x0000000100aa3abe -[StatusBarView globalStateUpdate:] + 62
	5   CoreFoundation                      0x00000001088c3fdc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00000001088c3eda _CFXRegistrationPost + 442
	7   CoreFoundation                      0x00000001088c3c22 ___CFXNotificationPost_block_invoke + 50
	8   CoreFoundation                      0x00000001088858c2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	9   CoreFoundation                      0x0000000108884a3c _CFXNotificationPost + 652
	10  Foundation                          0x00000001042a9852 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	11  linphone                            0x0000000100acc889 __52-[LinphoneManager onGlobalStateChanged:withMessage:]_block_invoke + 105
	12  libdispatch.dylib                   0x00000001093873f7 _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x000000010938843c _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00000001093936f0 _dispatch_main_queue_callback_4CF + 628
	15  CoreFoundation                      0x00000001088eaee9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00000001088af592 __CFRunLoopRun + 2402
	17  CoreFoundation                      0x00000001088ae9b9 CFRunLoopRunSpecific + 409
	18  GraphicsServices                    0x000000010b4849c6 GSEventRunModal + 62
	19  UIKit                               0x00000001058805e8 UIApplicationMain + 159
	20  linphone                            0x0000000100a5e2be main + 126
	21  libdyld.dylib                       0x0000000109404d81 start + 1

)

Thanks!

**Comment by ReisBenjamin** [comment]
You shouldn't call 

[LinphoneManager.instance destroyLinphoneCore];
unless your killing the app.

**Comment by ReisBenjamin** [comment]
re open if not fixed
