### ISSUE TITLE
UI - Dialpad oversize

### ISSUE THREAD

**Issue by arsenx** [BelledonneCommunications/linphone-iphone#36]
Hi there, I know that this is not a high alert issue but earlier models of the iPhone with 4.7 inch displays have this issue.

When making a call the dialpad is not well placed on the screen thus make the 0 key unusable. I am not an iOS developer and would have loved to contribute if I was.

**Comment by bagage** [comment]
I believe it's fixed in 3.11 release from today. Can you confirm?

**Comment by arsenx** [comment]
Confirming that it's fixed in 3.11

Thank you!
