### ISSUE TITLE
Send DTMF in-band

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#360]
As I know Linphone only has two DTMF options: 
linphone_core_set_use_rfc2833_for_dtmf
linphone_core_set_use_info_for_dtmf

if I understand it correctly, disabling both will block the DTMF sending?
if I enable the 2833 only, can I still handle the incoming sip info message?
What if the sip server only supports in-band DTMF? Does linphone send in-band DTMF by default? 

Appreciate anyone who can explain me any of those, thank you so much.

**Comment by ReisBenjamin** [comment]
Do you use linphone or your own app ?

**Comment by zj299792458** [comment]
@ReisBenjamin use linphone, by changing the figure in settings.

**Comment by ReisBenjamin** [comment]
Thanks for your answer,

The reception of SIP INFO messages will always work even if you disable the DTMFs.
The in band DTMF corresponds to RFC 2833: linphone_core_set_use_rfc2833_for_dtmf.

So to answer your questions : 
- Disabling the two options block DTMF sendings.
- Only enabling RFC 2833 won't prevent you from receiving and processing SIP INFO messages.
- in-band DTMF is RFC 2833.

Best regards
