### ISSUE TITLE
Design support for iPhone X , should just make autolayout in UICompositeView.xib or each xib file ?

### ISSUE THREAD

**Issue by amineghabi** [BelledonneCommunications/linphone-iphone#361]

**Comment by ReisBenjamin** [comment]
UICompositeView.xib should be enough, you can check commits on master : 
6491cce43c5c840940bcd30cbaca7cd3fe9b2e22
506e3b54f9430fddda4282c5f3b53f59df2fda3c

**Comment by amineghabi** [comment]
I tested the master branch but there is always the problem of Autolayout for theTabBar, you notice that it exceeds the safe area below.
<img width="239" alt="tabbar" src="https://user-images.githubusercontent.com/5704129/34387908-1c88fab4-eb31-11e7-8dbf-343a0143cdb3.png">
