### ISSUE TITLE
ERROR: The following binaries are missing: ndk-build.

### ISSUE THREAD

**Issue by chelsea67** [BelledonneCommunications/linphone-iphone#364]
Hi. I'm trying to build this project.
Ive cloned the source.
First I tried prepare.py and in said something about submodules. so I tried git submodule... commands.
Both run successfuly. now when i try prepare,py again it gives this error to me:
ERROR: The following binaries are missing: ndk-build. Please install them.

android ndk 15 is installed and path is set.

So whats going on?

**Comment by ReisBenjamin** [comment]
This is the iOS repo, please open an issue on the correct repo.

Thanks
