### ISSUE TITLE
ios10 or later background can't resign proxy

### ISSUE THREAD

**Issue by ziruozimi** [BelledonneCommunications/linphone-iphone#365]
ios 10 or later, when outgoing call, app enter background, then remote abort call,  I waiting call released invoke "linphone_proxy_config_enable_register" resign proxy, but proxy state never equal LinphoneRegistrationCleared

**Comment by ReisBenjamin** [comment]
LinphoneRegistrationCleared is for the registaration state not he call state.
Are you looking for LinphoneCallStateReleased ?

**Comment by ziruozimi** [comment]
Thank you, I resolved it, In backmodel when remote ended "linphone_core_set_network_reachable" is false, I set it ture, registration cleared.

**Comment by ReisBenjamin** [comment]
Great !
I'll close this issue then.

Best regards
