### ISSUE TITLE
No audio through USB connected audio devices

### ISSUE THREAD

**Issue by dcarrol2** [BelledonneCommunications/linphone-iphone#367]
I am trying to improve audio quality by using a headset connected to a USB audio interface. However, call audio for linphone is not routed to USB audio devices - it continues to use the built-in speaker/mic. I tried using a Shure Mvi and Behringer Xenyx Q502USB connected through Apple's camera connection kit. Neither work with Linphone although they work with other apps. Bug or feature? :)

Linphone iOS 3.16.5 on iOS 11.2.1.

**Comment by ReisBenjamin** [comment]
Hello,

We have fixed somme issues with audio routes in the latest days, could you try with the latest master commit ?

Thanks

**Comment by ReisBenjamin** [comment]
fixed with commit 3d5f8b04474ed6b50c819ca3c8a21b94934ea121
