### ISSUE TITLE
Crash when deleting a contact

### ISSUE THREAD

**Issue by fbxcelsior** [BelledonneCommunications/linphone-iphone#37]
Hi,

Adding a contact and deleting it causes the app to crash. 

This happens in the [ContactsListTableView tableView:commitEditingStyle:forRowAtIndexPath:] method, with the following exception:

NSInternalInconsistencyException

Invalid update: invalid number of sections. The number of sections contained in the table view after the update (1) must be equal to the number of sections contained in the table view before the update (1), plus or minus the number of sections inserted or deleted (0 inserted, 1 deleted).

This was detected in the master version, running on the iPhone 6 iOS 9.2 simulator.

Thank you.

Best regards,

Filipe

**Comment by bagage** [comment]
Can you describe steps to reproduce the bug please?

**Comment by fbxcelsior** [comment]
Off course:

1 - Go to the contacts list
2 - Add a contact
3 - In the list, swipe the newly added contact to show the Delete action
4 - Press Delete

And that is pretty much it.

Thanks

**Comment by bagage** [comment]
OK, you are using swipe to delete! That's the point indeed. I'll provide a fix then, thanks.

**Comment by bagage** [comment]
Fixed in f107715, thanks.
