### ISSUE TITLE
Anyone can guide me how to receive dtmf during call in iOS

### ISSUE THREAD

**Issue by wlinshicong** [BelledonneCommunications/linphone-iphone#370]
Hi,

I am new in linphone. Anyone can guide me how to receive dtmf during call in
iOS. our company server will send some info through by dtmf

**Comment by ReisBenjamin** [comment]
Hello,

What kind of DTMF do you send ? within the thr RTP or as a SIP info message ?

Thanks

**Comment by wlinshicong** [comment]
with the SIP info。thank you.I had konw  how  to send DTMF  .But I can not receive it. I will send  number such as "3"to server.It will send  "4" back to me.i use follow method  to send Dtmf:
linphone_call_send_dtmf(linphone_core_get_current_call(LC),"3")
