### ISSUE TITLE
Configurations by default

### ISSUE THREAD

**Issue by luu-rodriguez** [BelledonneCommunications/linphone-iphone#372]
I have a few doubts about how to set the ipv6 off by default and how to set the country code by default? 

Also, I do not know what the "Repeat notifications" option is. Could you clarify it for me?

Thanks!

**Comment by ReisBenjamin** [comment]
Hello,

You can add a default value in account.plist for country code.
you can edit the default value of ipv6 in network.plist

Repeat notification is used to dispay multiple notifications for a call received in background for IOS < 10 (no calllkit available) so that the phone keeps vibrating

Regards

**Comment by fedesenmartin** [comment]
I eddited the account.plist like this->

		<dict>
			<key>AutocapitalizationType</key>
			<string>None</string>
			<key>AutocorrectionType</key>
			<string>No</string>
			<key>DefaultValue</key>
			<string>54</string>
			<key>IsSecure</key>
			<false/>
			<key>Key</key>
			<string>account_prefix_preference</string>
			<key>Title</key>
			<string>Country code prefix</string>
			<key>Type</key>
			<string>PSTextFieldSpecifier</string>
			<key>IASKTextAlignment</key>
			<string>IASKUITextAlignmentRight</string>
		</dict>


But still nothing changed

Regards

**Comment by ReisBenjamin** [comment]
Remove all call to [self setCString:_<a_value>_ forKey:@"account_prefix_preference"];
So that your default settings si not overwriten

**Comment by ReisBenjamin** [comment]
if youy just want to set a default value that can be changed, then you only need to remove the call to 
[self setCString:"" forKey:@"account_prefix_preference"]; in default section of transformAccountToKeys in LinphoneCoreSettingsStore.m
