### ISSUE TITLE
Invalid bundle from itunes connect

### ISSUE THREAD

**Issue by ThabreshVivid** [BelledonneCommunications/linphone-iphone#373]
Invalid Bundle. The bundle linphone.app/Frameworks/linphone.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by ReisBenjamin** [comment]
Hello,

You're project's min ios requirement should match the linphone framework one so edit it to be the same.

Best regards

**Comment by ThabreshVivid** [comment]
Thanks @ReisBenjamin,

Am using iOS 11. The ipa file should be generating after that am upload ipa to store via application loader then only getting minimum os version error. Actually what version is suitable to generate deployment build. Can you please help me. Am struggling in this waiting to upload the build to store... https://pbs.twimg.com/media/CHO4vdPUYAA_gvf.png

**Comment by ReisBenjamin** [comment]
Dependings on the commit you use you need to set either 8.0 or 9.0 since tag 3.16.5
