### ISSUE TITLE
background and TCP/TLS push service

### ISSUE THREAD

**Issue by cyberevenge** [BelledonneCommunications/linphone-iphone#374]
Hello, 
i have a doubt about the push service, is it required only with UDP because also with TCP and TLS when the app goes in background or the phone in sleep the linphone die as well. 
As far as I know with TCP the app should keep working fine .. unless it is another magic from APPLE to force users to buy other product from them. 
thanks for any help
rob.

**Comment by ReisBenjamin** [comment]
Hello,

Since ios10 it's impossible to keep a TCP socket alive in background (for battery saving reasons according to Apple) so you need push notifications to wake the device up also for TCP/TLS.

Best regards
