### ISSUE TITLE
error when ./prepare.py -c && ./prepare.py && make

### ISSUE THREAD

**Issue by flatworld21** [BelledonneCommunications/linphone-iphone#375]
install log here
http://tech.memoecho.com/java/belledonnecommunications-linphone-iphone-install-log-in-imac/
-------------
CMake Error at /Users/user/Documents/git/ios/linphone-iphone/WORK/ios-x86_64/Build/srtp/CMakeFiles/CMakeTmp/CMakeLists.txt:14 (add_executable):
Cannot find source file:

/Users/user/Documents/git/ios/linphone-iphone/submodules/externals/srtp/test_inline.c

Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx

CMake Error: CMake can not determine linker language for target: cmTC_afc8f
CMake Error: Cannot determine link language for target "cmTC_afc8f".
CMake Error at CMakeLists.txt:134 (try_compile):
Failed to generate test project build system.

-- Configuring incomplete, errors occurred!
See also "/Users/user/Documents/git/ios/linphone-iphone/WORK/ios-x86_64/Build/srtp/CMakeFiles/CMakeOutput.log".
See also "/Users/user/Documents/git/ios/linphone-iphone/WORK/ios-x86_64/Build/srtp/CMakeFiles/CMakeError.log".
make[3]: *** [/Users/user/Documents/git/ios/linphone-iphone/WORK/ios-x86_64/Stamp/EP_srtp/EP_srtp-configure] Error 1
make[2]: *** [CMakeFiles/EP_srtp.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [x86_64-build] Error 2

**Comment by ReisBenjamin** [comment]
Hello,

Did you run 'git submodule update --init --recursive' before trying to build the SDK ?
