### ISSUE TITLE
IOS Linphone Clear call history problem

### ISSUE THREAD

**Issue by RONAKSANKHALA** [BelledonneCommunications/linphone-iphone#376]
Hello, @ReisBenjamin 

i will try to remove all call logs using below code. 
but app will crash at that time below here
 ======> LinphoneCallLog *callLog = (LinphoneCallLog *)logs->data;

    const bctbx_list_t *logs = linphone_core_get_call_logs([LinphoneManager getLc]);
    while (logs != NULL) {
       ======>  LinphoneCallLog *callLog = (LinphoneCallLog *)logs->data;
        linphone_core_remove_call_log(LC, callLog);
        linphone_call_log_unref(callLog);
        logs = logs->next;
        //bctbx_list_next(logs);
    }

but when i use below code then it will remove only one call history.
const MSList *list = linphone_core_get_call_logs(LC);
LinphoneCallLog *log = (LinphoneCallLog *)list->data;
linphone_core_remove_call_log(LC, log);

========================================
i need to remove all call history when user logout.
========================================
**first time inside while loop logs is ======**
(const bctbx_list_t *) logs = 0x00000001c542ae20
**========**
**Second time Inside while loop logs is ========**
Printing description of logs:
-5779727547545862
and crash.
EXC_BAD_ACCESS (code=1, address=0xbadd0bfa921abebd)

How to resolve these issue?

**Comment by ReisBenjamin** [comment]
What's the crash on your first methods ?

**Comment by RONAKSANKHALA** [comment]
EXC_BAD_ACCESS (code=1, address=0xbadd0bfa921abebd)

**Comment by ReisBenjamin** [comment]
Try your first method without calling linphone_call_log_unref(callLog);
And send the stack trace of the crash please

**Comment by hamzaozturk** [comment]
Objective-c version:

```
const bctbx_list_t *logs = linphone_core_get_call_logs(LC);

while (logs != NULL) {
	LinphoneCallLog *log = (LinphoneCallLog *)logs->data;

	logs = bctbx_list_next(logs);

	linphone_core_remove_call_log(LC, log);
	linphone_call_log_unref(log);
}
```

Swift version:

```
var logs = linphone_core_get_call_logs(LinphoneManager.getLc())

while logs != nil {
    if let log = OpaquePointer(logs?.pointee.data) {
        
        logs = UnsafePointer(bctbx_list_next(logs))
        linphone_core_remove_call_log(LinphoneManager.getLc(), log)
        linphone_call_log_unref(log)
    }
}
```

**Comment by RONAKSANKHALA** [comment]
Thanks @hamzaozturk  and @ReisBenjamin for your support.
its work now.

and @ReisBenjamin we like your Linphone Library to work on that.

Thanks again.
