### ISSUE TITLE
Not able to back up the user data. Please enable feature to backup to the cloud

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#377]
When I changed from iOS 10 to iOS 11 all my user data was gone when I updated the app, this only happened on a few of my friends devices, however, we would like to have it back up to any ftp server we choose can you please add this feature.

**Comment by ReisBenjamin** [comment]
Hello,

What do you mean by your user data ?
Did you uninstall linphone ?

Thanks

**Comment by S0U1SB4N3** [comment]
I mean like the user account information and login credentials so that I don't have to re-program the information if something were to happen to my installed app. 

for instance if I brick my phone and have to re-load the program n such. 
I was stating enduser data entry. such and sip login and settings that the enduser enters to make their account work, regardless if they use linphone account or a google sip account. I want to save all the data the end user has to enter so that if the program crashes and a re-load is necessary they can just import from a file they saved to an FTP server or cloud server like amazon aws

**Comment by ReisBenjamin** [comment]
As long as the app is not uninstalled the accounts settings are locally saved.
So if you quit the app or it crashes or restart the phone etc... all the settings should be saved and reloaded, is it the case ?

There's also a 'Fetch Remote Configuration' option in the account assistant that you can use as long as you've saved your configuration.

**Comment by S0U1SB4N3** [comment]
How do I save the config to a remote server ?

**Comment by S0U1SB4N3** [comment]
I see the fetch but no save ?

**Comment by S0U1SB4N3** [comment]
@ReisBenjamin where do I select to save my credentials to a remote server ? 
I see the fetch however I am not able to locate the save settings ? please assist

**Comment by ReisBenjamin** [comment]
We offer no service to save a configuration. You'll have to do it on your own.
We only fetch it

**Comment by S0U1SB4N3** [comment]
can you show me an example of a saved configuration so that I can use it as a template ?

**Comment by S0U1SB4N3** [comment]
""There's also a 'Fetch Remote Configuration' option in the account assistant that you can use as long as you've saved your configuration."" how do I save my own config, im just not understanding what the saved config looks like. is there somewhere I can copy a generic one ?

**Comment by S0U1SB4N3** [comment]
or does it look like the linphoneRC file ? 
im sorry to bother you im just a hands on visual learner.... 
so any example I can modify, I just need a base to work off of please.

**Comment by S0U1SB4N3** [comment]
even a basic one that shows a username, password, transport and sip server would be a good start

**Comment by ReisBenjamin** [comment]
Here's an example on our wiki : https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Remote%20Provisioning/

**Comment by S0U1SB4N3** [comment]
Your documentation is inconclusive to what I needed is does not show the auth protocols but I did some digging and here is the basic needs 
auth_info_1, 2, 3, etc for multiple accounts and just match the proxy_0,1,2,3etc accordingly. 

linphonerc:
[auth_info_0]
username=USERNAMEHERE
passwd=YourPassword
realm=1.2.3.4
domain=1.2.3.4

[proxy_0]
reg_proxy=<sip:1.2.3.4;transport=tcp> ///tcp,udp,tls, etc for the transport type. 
reg_route=sip:1.2.3.4;transport=tcp
reg_identity=sip:USERNAMEHERE@1.2.3.4
quality_reporting_enabled=0
quality_reporting_interval=0
reg_expires=3600
reg_sendregister=1
publish=0
avpf=-1
avpf_rr_interval=5
dial_escape_plus=0
privacy=32768
publish_expires=-1


XML remote file example:
<config xmlns="http://www.linphone.org/xsds/lpconfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.linphone.org/xsds/lpconfig.xsd lpconfig.xsd">

 <section name="auth_info_0">
    <entry name="username">USERNAMEHERE</entry>
    <entry name="passwd">YourPassword</entry>
    <entry name="realm">1.2.3.4</entry>
    <entry name="domain">1.2.3.4</entry>
</section>
<section name="proxy_0">
    <entry name="reg_proxy">sip:1.2.3.4;transport=tcp</entry>
    <entry name="reg_route">sip:1.2.3.4;transport=tcp</entry>
    <entry name="reg_identity">sip:USERNAMEHERE@1.2.3.4</entry>
    <entry name="quality_reporting_enabled">0</entry>
    <entry name="quality_reporting_interval">0</entry>
    <entry name="reg_expires">3600</entry>
    <entry name="reg_sendregister">1</entry>
    <entry name="publish">0</entry>
    <entry name="avpf">-1</entry>
    <entry name="avpf_rr_interval">5</entry>
    <entry name="dial_escape_plus">1</entry>
    <entry name="privacy">32768</entry>
    <entry name="publish_expires">-1</entry>
</section>

I think is what I was needing...

**Comment by S0U1SB4N3** [comment]
ok its because tog the tags containing the "<>"

**Comment by ReisBenjamin** [comment]
If you manage to create you xml, can I close the issue ?

**Comment by S0U1SB4N3** [comment]
Yes
