### ISSUE TITLE
Linphone SIP service allows long passwords but Linphone 4.0 client does not!

### ISSUE THREAD

**Issue by WPFilmmaker** [BelledonneCommunications/linphone-iphone#378]
Hi, 

Linphone SIP service allows the user to register with very long passwords, however Linphone client allows the user to enter only 34 characters. If the password is longer it throws an error "too long!(max 34 char.)".

Either reduce the character limit on your SIP registration service (IMHO bad) or allow Linphone to deal with passwords longer than 34 characters (IMHO better). 

Right now an user can register with an unusable password which is not cool.

I am using Linphone Desktop 4.0 Core 3.11.2-158-g4c291e2

Thanks a lot for the software and the SIP registration you provide!

**Comment by ReisBenjamin** [comment]
Hello this is the iOS repo.
Please open an issue on the correct repo : linphone-desktop.

Thanks
