### ISSUE TITLE
Decline All incoming calls

### ISSUE THREAD

**Issue by fedesenmartin** [BelledonneCommunications/linphone-iphone#379]
Hi

Im makin a "dont disturb" mode.

Is there a way to decline all incoming call?

I reach to avoid de outgoing calls with   linphone_core_set_sip_network_reachable(LC,FALSE);

But I want to make the phone not reacheable ; I tried  with

    LinphoneProxyConfig *cfg = linphone_core_get_default_proxy_config(LC);
    linphone_proxy_config_edit(cfg);
    linphone_proxy_config_set_expires(cfg,0);
    linphone_proxy_config_done(cfg);

But incoming calls are still ringing .

Thanks!

**Comment by fedesenmartin** [comment]
@ReisBenjamin  news?

**Comment by ReisBenjamin** [comment]
Hello,

You can use the function linphone_call_decline(call, reason) on every received call, this is the easiest thing to do.

Regards
