### ISSUE TITLE
Issue while FastAddressBook Class

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#38]
Hi, 

I am using an older version nearly 2-3 months older. I am having an issue that as soon as i click on Contacts App crashes.

Please see attachment. Mainly issue is in class FastAddressBook.
I cannot use the updated version, as if i pull the changes, it will discard all my changes and i have to make many changes as there are manny commit have been made after that.
Please help. 

Thanks for understanding.

![screen shot 2016-02-17 at 5 11 51 pm](https://cloud.githubusercontent.com/assets/3806195/13108606/1ccffbde-d59a-11e5-842e-67e6c1b2d183.png)

**Comment by uditbatra** [comment]
Same Code  if working good for some devices, and giving crash for some devices.

**Comment by bagage** [comment]
Sorry I don't see any obvious reason here, but there was a lot of refactoring in FastAddressBook class to avoid such crashes so you should definitively use latest version.
