### ISSUE TITLE
rtp packets of incoming cumulative lost is NEGATIVE

### ISSUE THREAD

**Issue by lucifer662607004** [BelledonneCommunications/linphone-iphone#381]
In the RTP STATISTICS from Linphone log I accidentally found the incoming cumulative lost can be negative as above:

> 2018-01-30 15:37:31:528 MESSAGE ms_ticker_set_time_func: ticker's time method updated.
> 2018-01-30 15:37:31:529 MESSAGE ===========================================================
> 2018-01-30 15:37:31:529 MESSAGE              AUDIO SESSION'S RTP STATISTICS                
> 2018-01-30 15:37:31:529 MESSAGE -----------------------------------------------------------
> 2018-01-30 15:37:31:529 MESSAGE sent                                       4661 packets
> 2018-01-30 15:37:31:530 MESSAGE                                               0 duplicated packets
> 2018-01-30 15:37:31:530 MESSAGE                                          149152 bytes  
> 2018-01-30 15:37:31:530 MESSAGE received                                   3548 packets
> 2018-01-30 15:37:31:530 MESSAGE                                               5 duplicated packets
> 2018-01-30 15:37:31:530 MESSAGE                                          113536 bytes  
> 2018-01-30 15:37:31:531 MESSAGE incoming delivered to the app             95136 bytes  
> 2018-01-30 15:37:31:531 MESSAGE incoming cumulative lost                    -17 packets
> 2018-01-30 15:37:31:531 MESSAGE incoming received too late                  466 packets
> 2018-01-30 15:37:31:531 MESSAGE incoming bad formatted                       17 packets
> 2018-01-30 15:37:31:532 MESSAGE incoming discarded (queue overflow)         104 packets
> 2018-01-30 15:37:31:532 MESSAGE sent rtcp                                    20 packets
> 2018-01-30 15:37:31:532 MESSAGE received rtcp                                 0 packets
> 2018-01-30 15:37:31:532 MESSAGE ===========================================================

How am I supposed to understand this figure? thx.

**Comment by ReisBenjamin** [comment]
Hello,

Do you reproduce this with the latest version of liblinphone ?

Thanks
