### ISSUE TITLE
Linphone issues with doorbell stations and iphone

### ISSUE THREAD

**Issue by luisomar10** [BelledonneCommunications/linphone-iphone#382]
Hello.

I got some problems with the linphone app, using an iphone.  In the past i used the linphone and i dont get any problems with our doorstation.
Now that i update the version of the linphone, i got problems with the video on my voip calls. 

I dont know how could someone could help me found out this, because i dont know what other steps, settings, or configuration could we try to solve this.

Also, when i used the linphone accounts into a android based device (phone or tablet) i could get video and the communication is fine.

HELP!!!

**Comment by ReisBenjamin** [comment]
Hello, what kind of problem in your video calls ?
Could you post logs of a video call here ?

Thanks

**Comment by luisomar10** [comment]
Hi, This is a log that i made with a sip call between a door station (192.168.1.215) and the iphone (192.168.1.52)
[packet-h (iphone).pdf](https://github.com/BelledonneCommunications/linphone-iphone/files/1697591/packet-h.iphone.pdf)

**Comment by luisomar10** [comment]
Just a follow up, with this post.
Any update?
Thanks in advance.

**Comment by ReisBenjamin** [comment]
Hello,

What i need are the app logs, not the network capture : you can either get them by pluging a device in the XCode software to have the logs in XCode's console or go to the linphone settings and search for 'Send logs', then send the logs to your address and post them here.

Best regards

**Comment by luisomar10** [comment]
Hello.

Here are the logs:
[linphone_log.gz](https://github.com/BelledonneCommunications/linphone-iphone/files/1707876/linphone_log.gz)

Please let me know is there is something we need to set in the iphone or in the router of the customer.

Thanks.

**Comment by luisomar10** [comment]
Good Morning.

Do you have any updates for this case?

Thanks in advance.

**Comment by ReisBenjamin** [comment]
Hello,

There's nothing in the logs you provided.
I need to get logs of a call from the initiating INVITE to the ending BYE so that i can see why there's no video.

Did you make sure to enable video in your settings ?

Thanks

**Comment by luisomar10** [comment]
Here is the Wireshark Log that we did in the last test.

[iphone Teste 2.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/1783150/iphone.Teste.2.zip)

**Comment by luisomar10** [comment]
And i have the Enable Video Set up.

With the last log, we found that the doorstation starts the call with the .VP8 codec, and in some point it doesnt "converts" or starts the call in the H.264.  So that is why this doorstation works fine for android base phone, than the Iphones.  We try to unable the VP8 codec in the Linphone App of the Iphone, try to disable the H.264 but neither one or the other works fine.  Also disable the audio codecs, just leave the PCMU, but still no video for iphones.

**Comment by luisomar10** [comment]
Here is a log that i made with my door station and iphone
the call was made on 2018-03-06 around 09:26.
Hopefully this will be useful for analyze from you.
[linphone_log Cleared Log 3618.gz](https://github.com/BelledonneCommunications/linphone-iphone/files/1786001/linphone_log.Cleared.Log.3618.gz)

**Comment by luisomar10** [comment]
Could you please reply. I dont heard from you since a long time ago.
