### ISSUE TITLE
Linphone iphone 3.16.6 crashes when taking address book

### ISSUE THREAD

**Issue by hamzamon** [BelledonneCommunications/linphone-iphone#383]
Hi All, I am tired with crashing linphone iphone 3.16.6 when loading address book, I have build the latest changes in [Linphone-iphone](https://github.com/BelledonneCommunications/linphone-iphone) but still not resolved my issue. Reproduce method : Run Linphone iPhone in any device and take dialer view then click address book (I tested without and with register sip server)

**Please find error log**
2018-02-05 17:15:33.399158+0530 linphone[11727:4812599] *** Terminating app due to uncaught exception 'CNPropertyNotFetchedException', reason: 'A property was not requested when contact was fetched.'
*** First throw call stack:
(0x183fd2364 0x183218528 0x183fd22ac 0x18ee13b48 0x1048f1608 0x10491897c 0x1049199b8 0x104913580 0x104912ce0 0x18d588ae8 0x18d5886c0 0x1049678b0 0x104967e34 0x10496b300 0x104908574 0x104908154 0x10490cf7c 0x18d5bd6b4 0x18d5bd634 0x18d5a81dc 0x18d5bcf28 0x18d5bca48 0x18d5b7f60 0x18d588f64 0x18dede31c 0x18dee08a8 0x18ded97c0 0x183f7a97c 0x183f7a8fc 0x183f7a184 0x183f77d5c 0x183e97e58 0x185d44f84 0x18d5ec67c 0x1048d63b4 0x1839b456c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Please help me to resolve it.

**Comment by ReisBenjamin** [comment]
Hello,

When you crash on address book fetch, could you type 'bt' in your lldb console so that we can see which methods causes the crash ?

Thanks

**Comment by ReisBenjamin** [comment]
Fixed with commit ae3f843f21518726986796b8463dc868bbf80f3d
