### ISSUE TITLE
Getting LinphoneCallPausedByRemote state by callee when callee hold call then unhold call.

### ISSUE THREAD

**Issue by Jaimin-Hodusoft** [BelledonneCommunications/linphone-iphone#384]
Hi,
 I am facing an issue is some what like this

Caller A calls to callee B at that time its working properly but when Callee B holds call at that time caller A get hold tone and after some time callee B unholds call at that time in this method 
**- (void)callUpdate:(LinphoneCall *)call state:(LinphoneCallState)state animated:(BOOL)animated**
 callee B gets LinphoneCallState as  **LinphoneCallPausedByRemote** this should not happen. 
now because its showing a message saying "You are paused by remote" and user has to close the call because there is no option to un hold (From caller A).

![Screen From Callee B : Caller A called to callee B and callee B hold the call ](https://user-images.githubusercontent.com/19401778/35974495-598e2da4-0cff-11e8-9550-7eb0ac0b32e5.PNG)
![Screen From Callee B : Callee B un hold call with Caller A](https://user-images.githubusercontent.com/19401778/35974496-59cd455c-0cff-11e8-80c1-67ed600e01ff.PNG)

Its working good when caller A do same thing like Caller A holds call at that time callee B get hold tone and after some time caller A unholds call that time Callee B gets unholds.

**Comment by ReisBenjamin** [comment]
Hello,
i'm not sure i understand the problem, could you detail a scenario ?
Explain the problematic behaviour what was the behaviour you expected ?

Thanks

**Comment by Jaimin-Hodusoft** [comment]
Take a scenario and follow steps

1.  You are calling me 
2. Now On going call i am puts our call to hold state. Now You should get hold tone
3. Now after some time i am going to un hold our on going call. Now as expected your hold tone will stop and our call should continue....
 But its not happening like that and my screen is going to be stuck on that above message after i press un hold (and the hold button is also disabled).

**Comment by Jaimin-Hodusoft** [comment]
Actually i have tested with App Store build and Android Play Store build in both i am getting same issue. So then i have downloaded latest master commit  for iOS (commit b61c5f8a432985c80ff65ffe55eebf33b84c2a0a
Author: Benjamin Reis <benjamin.reis@belledonne-communications.com>
Date:   Thu Jan 4 12:04:11 2018 +0100
)

 from git. and i have found this issue occurs in both android and iOS.

let me try to provide you logs. Can you please tell me what kind of log you will actually need?

**Comment by ReisBenjamin** [comment]
The full logs of a call where the problem occurs, from the initaiting INVITE to the BYE.

Thanks

**Comment by Jaimin-Hodusoft** [comment]
Ok thanks, @ReisBenjamin 

 I am sharing you LOG for INVITE to BYE.

Caller is 103 and Callee is 105.

Now as per our discussion caller 103 established call with 105. Now 105 is putting call on Hold and then un holds after some time. Then 105 on going call is getting issue.


[INVITE_TO_BYE(Caller 103 , Callee 105).docx](https://github.com/BelledonneCommunications/linphone-iphone/files/1715397/INVITE_TO_BYE.Caller.103.Callee.105.docx)

**Comment by ReisBenjamin** [comment]
Hello,

nothing's wrong in the logs,
could you send me the the logs of the other device ? the one who is called ?

Thanks

**Comment by Jaimin-Hodusoft** [comment]
Hello,
     Are you asking me to send you log of caller? (currently here is 103 is caller). I have sent you logs for Callee (105).

**Comment by ReisBenjamin** [comment]
This is a known issue.
We're working on it.
I'll post here once it's solved
