### ISSUE TITLE
IOS CallHold Button Disable in Outgoing Call.

### ISSUE THREAD

**Issue by RONAKSANKHALA** [BelledonneCommunications/linphone-iphone#385]
IOS CallHold Button Disable in Outgoing Call.

When i try to outgoing call from one sip user to another sip user UICallPauseButton will be enable.
How to enable UICallPause Button in Linphone 3.16.4 SDK.

but it will works fine in Incoming call.
UICallPauseButton will enable in Incoming Call.
How to solve this problem @ReisBenjamin .

**Comment by ReisBenjamin** [comment]
Hello,

Please post logs of a call where the pause button is not enabled to see if something goes wrong

thanks

**Comment by RONAKSANKHALA** [comment]
Hello, @ReisBenjamin 
Thanks you for update.

now CallPause Button Working Fine.

i have one more problem in OutGoing Call.
when i try to outgoing call and call will be running and i am trying to hold or Pause call from my side then **CallPausedTableView** not display but  it display only **NoActiveCallView** in Call view
 i need to display **CallPausedTableView** when i tap on pause button but its display only **NoActiveCallView** 

it will be working fine in Incoming call.
when i pickup an incoming and call are in running state and i tap on pause button then display **CallPausedTableView** and **NoActiveCallView**.


Please Find Attached ScreenShot for InComing and OutGoing Call.

**OUTGOING CALL SCREENSHOT**
![screen shot 2018-02-13 at 11 35 41](https://user-images.githubusercontent.com/35218259/36135755-16fe5290-10b3-11e8-86d7-d2deee1d4008.png)
![screen shot 2018-02-13 at 11 35 51](https://user-images.githubusercontent.com/35218259/36135758-1c6eae8c-10b3-11e8-9804-426420f350d0.png)

**INCOMING CALL SCREENSHOT**
![screen shot 2018-02-13 at 11 32 21](https://user-images.githubusercontent.com/35218259/36135917-e1784ad0-10b3-11e8-9a1c-21534b5ceec0.png)
![screen shot 2018-02-13 at 11 32 28](https://user-images.githubusercontent.com/35218259/36135920-e5dd46ac-10b3-11e8-9a66-74290c26f1e3.png)

Please check and Update what can i do for this issue.

Please Find Below Log .

Thanks

[Logs.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/1719033/Logs.zip)

**Comment by ReisBenjamin** [comment]
This is a known issue.
We're working on it.
I'll post here once it's solved

**Comment by Rushabh5** [comment]
Hey @ReisBenjamin 

Would you please update this issue so we can do it.

Awaiting for your reply!

Thanks
