### ISSUE TITLE
linphone -imx6

### ISSUE THREAD

**Issue by MValishetra** [BelledonneCommunications/linphone-iphone#386]
Hello I am working on VOIP and I tried building linphone lib on imx6 . I am able to build it but facing issues when run basic call C aplication. Can not connect call often. some times it connects and some times its not. I dont know what is the exact issue. Can any one please help with this.

**Comment by ReisBenjamin** [comment]
This is the IOS repo, no iOS device run on imx6.
I'll close this issue.

Please reopen one on the correct repo
