### ISSUE TITLE
Can't use linphone_call_defer_update

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#387]
Hi. I would like to ask about linphone_call_defer_update() function. I want to show a popup to enable a video like an original linphone project but when i use this function before show a popup it tell me

> [Error] linphone_call_defer_update() not done in state LinphoneCallUpdatedByRemote

But i call this function in LinphoneCallUpdatedByRemote state. I don't know why. Please can someone help me.

Here. How i call the function

```
// MARK: Call Updated by remote
else if callState == LinphoneCallUpdatedByRemote {
// Testing
// Remote want to update with video
     if sipUAManager.isRemoteVideoEnabled(call: call) && !sipUAManager.isVideoEnabled(call: call) {
          if SipVideoManager.getVideoAutoAccept() {
               os_log("CallingView : Video auto accept is allow : Update call", log: log_app_debug, type: .debug)
               // Accept call update from remote call
               sipUAManager.acceptCallUpdate()
          } else {
               os_log("CallingView : Video auto accept is not allow : Asking to allow", log: log_app_debug, type: .debug)
               linphone_call_defer_update(call)
               showAskingVideoCallPopup()
          }
     // Remote want to update others
     } else {
          // Accept call update from remote call
          sipUAManager.acceptCallUpdate()
     }         
 }
```

**Comment by ReisBenjamin** [comment]
Hello 
Could you post the logs please ?

Thanks

**Comment by SarunyuPrasert** [comment]
Hello @ReisBenjamin 

Here is log file
https://drive.google.com/open?id=1wO89wCjmy4-cgNcVsgKp4UqEbzhGHv33

Thank you

**Comment by ReisBenjamin** [comment]
Hello,

Why do you want to call linphone_call_defer_update ?
It is not called in Linphone iphone only the accept method

**Comment by SarunyuPrasert** [comment]
Because I want to show popup and asking user before accept video enable.If user accept then view will change from audio call to video call.

**Comment by ReisBenjamin** [comment]
Yes, it's what's done in Linphone iphone, you can check our code.
The defer is made to report on a long time the answer for the update not to just wait for a user interaction

**Comment by SarunyuPrasert** [comment]
Yes, I understand i've already check but I would like to know why i call linphone_call_defer_update in app part It doesn't work i have to call it in 
my framework as i explain above.
