### ISSUE TITLE
Issue on call resume with TURN/ICE

### ISSUE THREAD

**Issue by VincentPerez** [BelledonneCommunications/linphone-iphone#388]
When using TURN and ICE in a simple outgoing call, if I call the function linphone_call_pause() everything seems to go as planned but when the function linphone_call_resume() is called it doesn't execute properly, stating 'Cannot resume call "..." because another call is locking the sound resources.'. The other party is kept on hold and the media is not reestablished poperly. This issue is linked to the TURN/ICE because otherwise with a standard call without it the pause/resume functions are flawless.

**Comment by ReisBenjamin** [comment]
Does the re-Invite was received on both side before pausing the call ?
There are known issues with ice so maybe disable it for now

Thanks

**Comment by VincentPerez** [comment]
OK so it seems that the issue is coming from somewhere else, I will close this one and write a more specific one in the linphone repo.
