### ISSUE TITLE
I Want to update firmware name in linphone app 

### ISSUE THREAD

**Issue by nareshkmr058** [BelledonneCommunications/linphone-iphone#389]
Hai,

I want to update linphone firmware version (belle-sip/1.6.3) as like xxxxxx and model version. If Any one knows please assist me.

**Comment by ReisBenjamin** [comment]
I'm not sure to understand waht you want.
Could you elaborate ?

Thanks

**Comment by nareshkmr058** [comment]
lin phone's User-Agent name will shows like devicename+model_number+vendor name(belle-sip).
For example : demo_simulator.64bits_iOS11.2/3.16.5-46-324141 (belle-sip/1.6.3). 
I want to change that belle-sip name.
