### ISSUE TITLE
Updating and enabling video preview and video streaming direction not working during call

### ISSUE THREAD

**Issue by tryingtoprogram** [BelledonneCommunications/linphone-iphone#391]
I was able to get both audio and video streaming working and disabling video streaming works during a call. However, re-enabling it doesn't work.

Here's how im turning off video during a call
`let call_params = linphone_call_params_copy(linphone_call_get_current_params(call));
linphone_call_params_enable_video(call_params, 0);
linphone_call_params_set_video_direction(call_params, LinphoneMediaDirectionInactive)
linphone_call_update(call, call_params)`

And here's how i'm re-enabling it
`let call_params = linphone_call_params_copy(linphone_call_get_current_params(call));
linphone_call_params_enable_video(call_params, 1);
linphone_call_params_set_video_direction(call_params, LinphoneMediaDirectionRecvOnly)
linphone_call_update(call, call_params)`

Also, for some reason, setting the direction to `LinphoneMediaDirectionRecvOnly` when calling on `linphone_call_params_set_video_direction` actually enables uploading rather than downloading when observing what is passed back from `linphone_call_get_video_stats` and logging both `download_bandwidth` and `upload_bandwidth` property.

**Comment by ReisBenjamin** [comment]
You should call linphone_call_params_enable_video(call, true/false) to change the video enalbement in a call.
Not linphone_call_params_set_video_direction
