### ISSUE TITLE
Error while running ./prepare.py

### ISSUE THREAD

**Issue by moohhoom** [BelledonneCommunications/linphone-iphone#392]
Hi,
i am receiving the below when i am running the script any suggestions ??

_`ERROR: iOS SDK not found, please install Xcode from AppStore or equivalent.`_

Xcode ver 9.2 (9C40b)
mac OS ver10.13 (17A365)

thank you

**Comment by leechul** [comment]
please install Xcode from AppStore or equivalent.

**Comment by moohhoom** [comment]
Hi,
that’s what exactly what i did  from app store ??
any other suggestions??

**Comment by psx88** [comment]
Try "sudo xcode-select --switch /Applications/Xcode.app"

**Comment by leechul** [comment]
Chuls-MacBook-Pro:submodules leechul$ xcodebuild -showsdks
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
Chuls-MacBook-Pro:submodules leechul$ ls /Applications/Xcode.app/
Contents
Chuls-MacBook-Pro:submodules leechul$ sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/
Password:
Chuls-MacBook-Pro:submodules leechul$ xcrun --sdk iphoneos --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk

**Comment by leechul** [comment]
need to switch to your Xcode path in my case is "sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/"

**Comment by moohhoom** [comment]
Perfect its working fine now, thank you both @psx88 @leechul
