### ISSUE TITLE
Can't hold in outgoing call in IOS

### ISSUE THREAD

**Issue by krupaIOS** [BelledonneCommunications/linphone-iphone#393]
When i try to perform outgoing call from one sip user to another sip user, Call hold button stays disabled. However it works perfectly fine with Incoming call. I'm using Linphone sdk 3.16.4.

I'm facing same issue with 3.16.5 also.

I have downloaded an application from Appstore in IOS devices. Same issue occurs in the latest application which is available in Appstore.

I have attached screenshot and logs of caller and receiver for reference.

[caller.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/1761998/caller.zip)
[Receiver.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/1762001/Receiver.zip)

Looking forward to positive response. Please Help me.

**Comment by ReisBenjamin** [comment]
This is a known issue.
We're working on it.
I'll post here once it's solved

**Comment by shraddha-patel-1891** [comment]
any update?
