### ISSUE TITLE
Is there a similar method to linphone_call_set_next_video_frame_decoded_callback but for audio?

### ISSUE THREAD

**Issue by tryingtoprogram** [BelledonneCommunications/linphone-iphone#394]
Is there a way to know when audio is ready for playback? I've got a feature for audio only calls, would like to keep a load indicator up until any audible sound can be heard.

**Comment by ReisBenjamin** [comment]
Hello,

There's no such callback in our liblinphone.
You might want to wait the the LinphoneCallStateStreamsrunning ?

**Comment by tryingtoprogram** [comment]
Thanks @ReisBenjamin for the response. 

We're currently waiting for `LinphoneCallStateStreamsrunning`, however, it's not a clear indication that audio is in fact ready to be played back. Often times, `LinphoneCallStateStreamsrunning` would be set as a status and audio can be heard a couple of seconds after.

**Comment by ReisBenjamin** [comment]
Then there is no other way in liblinphone.

Sorry
