### ISSUE TITLE
Linphone-iOS called MicroSip, MicroSip click hold then unhold, linphone-iOS was stuck.

### ISSUE THREAD

**Issue by willylee007** [BelledonneCommunications/linphone-iphone#395]
Hello!
Linphone-iOS(latest version) called MicroSip(latest windows version), MicroSip click hold then unhold, linphone-iOS was stuck but not crashed.But MicroSip called Linphone-iOS, MicroSip click hold then unhold, everything is OK;
So I used bugly to find where place caused stucks, then reported these stacks:

> 

3 mediastreamer_base | ms_ticker_get_last_late_tick + 68
-- | --
4 mediastreamer_voip | video_stream_track_fps_changes + 152
5 mediastreamer_voip | video_stream_iterate + 32
6 linphone | linphone_call_handle_stream_events(_LinphoneCall*, int) + 248
7 linphone | linphone_call_background_tasks + 472
8 linphone | linphone_core_iterate + 1284

Can you help me to find what's wrong with it ?
Thx!

**Comment by ReisBenjamin** [comment]
This is a known issue.
We're working on it.
I'll post here once it's solved

**Comment by willylee007** [comment]
Thx for your working!
