### ISSUE TITLE
Export .ipa Error

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#396]
Hi. I get this error when i try to export archives file to .ipa using xcode with Ad Hoc or Development option. I have my framework that using linphone library and I use my framework in my application. I set Enable Bitcode to YES in my framework and my application.

> Failed to verify bitcode in bctoolbox.framework/bctoolbox:
error: Cannot extract bundle from /var/folders/2r/nr_yw84n5gx4706j83xm1kz40000gn/T/XcodeDistPipeline.HP9/Root/Payload/SipUADemo.app/Frameworks/bctoolbox.framework/bctoolbox (x86_64)

I don't know how to fix this error and I don't know what i miss. Because I can export completely with the linphone original project. But if i set Enable Bitcode to NO in my framework and my application. I can export. Please help me.

Thank you.

**Comment by ReisBenjamin** [comment]
It means bitcode wasn't embedded in the bctoolbox framework.
Do you reproduce with latest commit of bctoolbox ?

**Comment by SarunyuPrasert** [comment]
@ReisBenjamin Now I can export it. Thank you.

**Comment by basisty-evgeny** [comment]
hi, I got same problems.
how did you fix it?

**Comment by basisty-evgeny** [comment]
@SarunyuPrasert
