### ISSUE TITLE
Domain name value will set defaultly

### ISSUE THREAD

**Issue by nareshkmr058** [BelledonneCommunications/linphone-iphone#397]
In linphone app SIP Account creating time Domain name value will set default value. For example domain name value defaulty shows xxxxx@com. I changed this one in assistant.m page. but once app uploaded in app store this value automatically removed.

**Comment by ReisBenjamin** [comment]
Hello,

I didn't understand your issue.
Could you elaborate and explain what you're trying to do ?

Thanks
