### ISSUE TITLE
There is no video in IOS app, in device

### ISSUE THREAD

**Issue by xav13er** [BelledonneCommunications/linphone-iphone#4]
I have successfully installed Linphone on my Iphone 6 device, through this very helpful source (https://github.com/BelledonneCommunications/linphone-iphone). The app is deployed in my device, I’ve configured it to use “ostel.co” voip server online, and works like a charm. I can place calls and send messages. I cannot, however, place video calls. There is no video, whether I start an audio call and initiate video feed, or if I start a video call from the start. It doesn’t work.  I am using linphone on Iphone, and a 3rd party app in the desktop. If I use linphone also on the desktop, the video call gets established but with POOR quality (another problem to solve later on). I wan't to use linphone with 3rd party software, what needs to be done?

Can you please help me solve the issue? I’ve configured my liblinphone-sdk for non third party, as there is a chance for commercial licensing later on. Linphone sdk has the following configuration, and I am surprised video does not work at all:

-- Debug:
 -- Including builder antlr3c
 -- Including builder polarssl
 -- Including builder cunit
 -- Including builder bellesip
 -- Including builder ortp
 -- Including builder gsm
 -- Including builder opus
 -- Including builder speex
 -- Including builder vpx
 -- Including builder srtp
 -- Including builder bzrtp
 -- Including builder ms2
 -- Including builder libilbcrfc3951
 -- Including builder msilbc
 -- Including builder mswebrtc
 -- Including builder mssilk
 -- Including builder linphone
 
 -- Enabled Features:
 * Unit tests , Build unit tests programs for belle-sip, mediastreamer2 and linphone.
 * Documentation , Enable documentation generation with Doxygen.
 * SRTP , SRTP media encryption support.
 * ZRTP , ZRTP media encryption support.
 * DTLS , DTLS media encryption support.
 * GSM , GSM audio encoding/decoding support.
 * iLBC , iLBC audio encoding/decoding support.
 * ISAC , ISAC audio encoding/decoding support.
 * OPUS , OPUS audio encoding/decoding support.
 * Silk , Silk audio encoding/decoding support.
 * Speex , Speex audio encoding/decoding support.
 * Video , Ability to capture and display video.
 * VPX , VPX (VP8) video encoding/decoding support.
 
 
 
 -- Disabled features:
  * Tunnel , Secure tunnel for SIP/RTP (require license).
  * RTP MAP , Always include rtpmap in SDP.
  * GPL third parties , Usage of GPL third-party code (FFmpeg and x264).
  * Non free codecs , Allow inclusion of non-free codecs in the build.
  * AMR-NB , AMR narrow-band audio encoding/decoding support (require license).
  * AMR-WB , AMR wide-band audio encoding/decoding support (require license).
  * G.729 , G.729 audio encoding/decoding support (require license).
  * WASAPI , Windows Audio Session API (WASAPI) sound card support.
  * WebRTC AEC , WebRTC echo canceller support.
  * FFmpeg , Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
  * H263 , H263 video encoding/decoding support (require license).
  * H263+ , H263+ video encoding/decoding support (require license).
  * MPEG4 , MPEG4 video encoding/decoding support (require license).
  * OpenH264 , H.264 video encoding/decoding support with the openh264 library (require license).
  * X264 , H.264 video encoding support with the x264 library (require license).
  * V4L , V4L camera driver.
  * MKV , MKV playing and recording support.

**Comment by bagage** [comment]
Does it work with App Store version? If not, please grab logs from within linphone.

**Comment by xav13er** [comment]
No, it does not work with the app store application as well. I will post the logs of the source code.

BTW:  Jitsi was the 3rd party application used in the desktop. 
Video Codecs: H.264, H.263-1998 / H.263+, (VP8 coming soon…)

**Comment by bagage** [comment]
In the mean time please use users mailing list instead of github issues tracking ([see FAQ](https://wiki.linphone.org/wiki/index.php/Faq#I_have_a_problem._How_to_get_logs.2Ftools.2Fcontacts_to_troubleshoot_the_issue.3F)), since this is more of an incompatibility issue than a bug in linphone-iphone. I am closing this for now.

Thanks,
