### ISSUE TITLE
KIF/KIF.h file not found

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#40]
Hello. 
I did exactly as the README says and in the last step when I press "⌘R" it gives me a "KIF/KIF.h file not found" error in LinphoneTestCase.h in Target linphoneTests. But I was running the main target named "linphone", i don't know how those two relate each other. I found the KIF.h under a subproject KIF, but how can I import it? Am I doing anything wrong? 

Sorry if I'm asking something stupid...

(also i tried to compile linphoneTesters and click run all tests but it crashes at 
2016-02-19 10:23:47:737 ortp-fatal-Account for "Super Marie" <sip:marie_iykQI@sip.example.org> could not be created on server.)

**Comment by bagage** [comment]
Hi @zj299792458,

Indeed sometime I got this error too but I do not have an explanation for it yet, I can only confirm it for now. Temporary you can remove `linphoneTests` target to build the application.

For your `ortp-fatal` error, liblinphone requires some accounts in order to test the library. They are created dynamically at execution, but sometime it can fail (server under maintenance, invalid network connectivity, etc.) and in this case it abort everything and crash since it wont be able to pass the tests. You might want to try again later.

**Comment by zj299792458** [comment]
@bagage Thanks a lot. I did remove it at the first time but I feel bad about it :(

Also I encountered another issue: as long as i try to compile it with default settings "./prepare.py -c && ./prepare.py && make" it will return a EP_ffmpeg error as below.

I have to avoid armv7 compilation with  "./prepare.py -c && ./prepare.py x86_64 arm64 && make", which means it's only supports iPhone5s and latter devices. Am I the only one who has this problem?


[ 47%] Forcing build for 'EP_vpx'
[ 48%] Performing build step for 'EP_vpx'
    [CREATE] vpx_scale_rtcd.h
    [CREATE] vp8_rtcd.h
ar: creating archive libvpx_g.a
a - vpx/src/vpx_decoder.c.o
a - vpx/src/vpx_encoder.c.o
a - vpx/src/vpx_codec.c.o
a - vpx/src/vpx_image.c.o
a - vpx/src/vpx_psnr.c.o
a - vpx_mem/vpx_mem.c.o
a - vpx_scale/generic/vpx_scale.c.o
a - vpx_scale/generic/yv12config.c.o
a - vpx_scale/generic/yv12extend.c.o
a - vpx_scale/generic/gen_scalers.c.o
a - vpx_scale/vpx_scale_rtcd.c.o
a - vpx_ports/arm_cpudetect.c.o
a - vp8/common/alloccommon.c.o
a - vp8/common/blockd.c.o
a - vp8/common/debugmodes.c.o
a - vp8/common/dequantize.c.o
a - vp8/common/entropy.c.o
a - vp8/common/entropymode.c.o
a - vp8/common/entropymv.c.o
a - vp8/common/extend.c.o
a - vp8/common/filter.c.o
a - vp8/common/findnearmv.c.o
a - vp8/common/generic/systemdependent.c.o
a - vp8/common/idct_blk.c.o
a - vp8/common/idctllm.c.o
a - vp8/common/rtcd.c.o
a - vp8/common/loopfilter.c.o
a - vp8/common/loopfilter_filters.c.o
a - vp8/common/mbpitch.c.o
a - vp8/common/modecont.c.o
a - vp8/common/quant_common.c.o
a - vp8/common/reconinter.c.o
a - vp8/common/reconintra.c.o
a - vp8/common/reconintra4x4.c.o
a - vp8/common/sad_c.c.o
a - vp8/common/setupintrarecon.c.o
a - vp8/common/swapyv12buffer.c.o
a - vp8/common/variance_c.c.o
a - vp8/common/treecoder.c.o
a - vp8/common/arm/filter_arm.c.o
a - vp8/common/arm/loopfilter_arm.c.o
a - vp8/common/arm/dequantize_arm.c.o
a - vp8/common/arm/variance_arm.c.o
a - vp8/common/arm/neon/bilinearpredict_neon.c.o
a - vp8/common/arm/neon/copymem_neon.c.o
a - vp8/common/arm/neon/dc_only_idct_add_neon.c.o
a - vp8/common/arm/neon/dequant_idct_neon.c.o
a - vp8/common/arm/neon/dequantizeb_neon.c.o
a - vp8/common/arm/neon/idct_blk_neon.c.o
a - vp8/common/arm/neon/idct_dequant_0_2x_neon.c.o
a - vp8/common/arm/neon/idct_dequant_full_2x_neon.c.o
a - vp8/common/arm/neon/iwalsh_neon.c.o
a - vp8/common/arm/neon/loopfilter_neon.c.o
a - vp8/common/arm/neon/loopfiltersimplehorizontaledge_neon.c.o
a - vp8/common/arm/neon/loopfiltersimpleverticaledge_neon.c.o
a - vp8/common/arm/neon/mbloopfilter_neon.c.o
a - vp8/common/arm/neon/reconintra_neon.c.o
a - vp8/common/arm/neon/sad_neon.c.o
a - vp8/common/arm/neon/shortidct4x4llm_neon.c.o
a - vp8/common/arm/neon/sixtappredict_neon.c.o
a - vp8/common/arm/neon/variance_neon.c.o
a - vp8/common/arm/neon/vp8_subpixelvariance_neon.c.o
a - vp8/encoder/arm/dct_arm.c.o
a - vp8/encoder/arm/neon/denoising_neon.c.o
a - vp8/encoder/arm/neon/fastquantizeb_neon.c.o
a - vp8/encoder/arm/neon/shortfdct_neon.c.o
a - vp8/encoder/arm/neon/subtract_neon.c.o
a - vp8/encoder/arm/neon/vp8_mse16x16_neon.c.o
a - vp8/encoder/arm/neon/vp8_shortwalsh4x4_neon.c.o
a - vp8/vp8_cx_iface.c.o
a - vp8/encoder/bitstream.c.o
a - vp8/encoder/boolhuff.c.o
a - vp8/encoder/dct.c.o
a - vp8/encoder/encodeframe.c.o
a - vp8/encoder/encodeintra.c.o
a - vp8/encoder/encodemb.c.o
a - vp8/encoder/encodemv.c.o
a - vp8/encoder/ethreading.c.o
a - vp8/encoder/denoising.c.o
a - vp8/encoder/lookahead.c.o
a - vp8/encoder/mcomp.c.o
a - vp8/encoder/modecosts.c.o
a - vp8/encoder/onyx_if.c.o
a - vp8/encoder/pickinter.c.o
a - vp8/encoder/picklpf.c.o
a - vp8/encoder/quantize.c.o
a - vp8/encoder/ratectrl.c.o
a - vp8/encoder/rdopt.c.o
a - vp8/encoder/segmentation.c.o
a - vp8/encoder/tokenize.c.o
a - vp8/encoder/treewriter.c.o
a - vp8/vp8_dx_iface.c.o
a - vp8/decoder/dboolhuff.c.o
a - vp8/decoder/decodemv.c.o
a - vp8/decoder/decodeframe.c.o
a - vp8/decoder/detokenize.c.o
a - vp8/decoder/error_concealment.c.o
a - vp8/decoder/onyxd_if.c.o
a - vp8/decoder/threading.c.o
a - vpx_config.c.o
    [CREATE] vpx.pc
[ 49%] Performing install step for 'EP_vpx'
[ 50%] Completed 'EP_vpx'
[ 50%] Built target EP_vpx
Scanning dependencies of target EP_ffmpeg
[ 51%] Creating directories for 'EP_ffmpeg'
[ 52%] No download step for 'EP_ffmpeg'
[ 53%] No patch step for 'EP_ffmpeg'
[ 54%] No update step for 'EP_ffmpeg'
[ 55%] Performing configure step for 'EP_ffmpeg'
GNU assembler not found, install/update gas-preprocessor

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
make[3]: *** [/Users/Steven/GitProjects/LinphoneIPhone/WORK/ios-armv7/Stamp/EP_ffmpeg/EP_ffmpeg-configure] Error 1
make[2]: *** [CMakeFiles/EP_ffmpeg.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

**Comment by bagage** [comment]
You should update your gas-preprocessor perl script. Several people hit this problem, but I did not find a proper way to check the script version... anyway you should run:

```
        wget --no-check-certificate https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl && \
        chmod +x gas-preprocessor.pl && \
        sudo mv gas-preprocessor.pl $(which gas-preprocessor.pl)
```

**Comment by zj299792458** [comment]
@bagage Reeeeeally appreciate it man!!! Sorry about low lvl question...
