### ISSUE TITLE
crash when contacts clicked

### ISSUE THREAD

**Issue by sameer4** [BelledonneCommunications/linphone-iphone#400]
2018-03-11 21:08:39.928902+0500 linphone[16309:203409] Crash: A property was not requested when contact was fetched.
2018-03-11 21:08:39.929254+0500 linphone[16309:203409] Stack Trace: (
0 CoreFoundation 0x000000010a02312b __exceptionPreprocess + 171
1 libobjc.A.dylib 0x00000001096b7f41 objc_exception_throw + 48
2 CoreFoundation 0x000000010a098245 +[NSException raise:format:] + 197
3 Contacts 0x0000000102b2eeaa -[CNContact organizationName] + 184
4 linphone 0x00000001022f9d8a -[Contact displayName] + 378
5 linphone 0x000000010231f79d -[ContactsListTableView displayNameForContact:] + 61
6 linphone 0x00000001023208c2 -[ContactsListTableView loadData] + 3090
7 linphone 0x000000010231a649 -[ContactsListView changeView:] + 521
8 linphone 0x0000000102319e2d -[ContactsListView viewDidLoad] + 173

exception on line NSString *lOrganization = _person.organizationName; in -[Contact displayName]

**Comment by ReisBenjamin** [comment]
Hello,

Do you use latest master of linphone-iphone ?
This issue has been fixed recently in commit 422d5d91a2ecabaaaf9db7aed39f2c7eb980867e

Thanks
