### ISSUE TITLE
Linphone unreachable after missed call

### ISSUE THREAD

**Issue by psx88** [BelledonneCommunications/linphone-iphone#401]
Affecting current master:

Issue:
App is closed -> Incoming call triggered through push notification -> Don’t answer & hang up on caller side -> Missed call notification is shown -> App doesn’t respond to incoming calls anymore unless you open the app.

Solution:
After a missed call there are two lines in LinphoneManager.m which are causing this error:

878: linphone_core_set_network_reachable(LC, FALSE);
879: LinphoneManager.instance.connectivity = none;

I’m not sure why this is in there, makes no sense to me. After removing this, the app is working fine again!

**Comment by ReisBenjamin** [comment]
Hello,

these 2 lines are used to force linphone to refresh it's registraton in the case iOs has broken its voip sockets.
Removing risk that when the app is awoken by a push notification, it won't register and therefore won't receive th ecall/message.

**Comment by psx88** [comment]
I understand that this is done to refresh the registration. But unfortunately this prevention seems to be a part of the problem.
Have you tried the exact scenario? It fails every time, after a missed call linphone is unreachable.
Seems that the code that should prevent this error is causing this error!?

**Comment by psx88** [comment]
Hello ReisBenjamin,
first of all, thank for your contributions to this project!

As I see this code is also in the 3.16.5 branch. Maybe the issue lies behind the 2 lines of code.
Unfortunately I see no easy way to trace this issue. Have to use my own flexisip instance because of the push notifications and I have to attach Xcode to the process to catch the startup of the app (app has to be closed to reproduce this issue) But logging on attached processes isn't working at all. So the only option left would be to look at the log files which didn't help in this particular case either.

I also can't see any context in flexisip configuration which would cause the client to stop processing incoming notifications after the first missed call (working fine in any other scenario!). Is there any way you can think of how I could drill down the issue? Any other helpful command to debug flexisip / show registered users & data?

Simplest solution would be to remove the two lines in my own checkout, as it solves my current problem. But I opened this issue to draw attention to a possible problem. It would help if someone could test the scenario posted in the first post to check if this is affecting at least another person.

Regards

**Comment by ReisBenjamin** [comment]
Hello,

I've tried to reproduce on my side and everything went fine for me.
Are up to date witj our latest master ?

Thanks

**Comment by psx88** [comment]
Hello @ReisBenjamin,

Yes, I'm up-to-date with the latest linphone-iphone from master and flexisip via apt.

> everything went fine for me

Ok, perfect! I't would be much worse if this affecting everbody!

The big question is why is this happening after "linphone_core_set_network_reachable(LC, FALSE);". Because this code is also executed on exit of the app. And for the first call after app exit this is no issue at all! So why after a missed call?

I was playing around and searched for other calls of "LinphoneManager.instance.connectivity = none;" which is called directly after the line which causes the issue and found it in LinphoneAppDelegate where it was followed by "[LinphoneManager.instance setupNetworkReachabilityCallback];"

I added the line above directly after the two lines:

879: linphone_core_set_network_reachable(LC, FALSE);
880: LinphoneManager.instance.connectivity = none;
881: [LinphoneManager.instance setupNetworkReachabilityCallback];   //NEW

And it's working. It seems that something in "setupNetworkReachabilityCallback" is required to solve my issue.

Do you have any idea why this fixing the problem???
