### ISSUE TITLE
iOS 10 and above: Not able to connect Linphone when the app got killed or in background for more then 3 minutes

### ISSUE THREAD

**Issue by GauravKabra03** [BelledonneCommunications/linphone-iphone#407]
Here the the steps I have implemented:
1. I have used Linphone Manager.h and .m with Linphone library.
2. When app is in foreground I am able to receive proper Linphone call from socket.
3. When app got terminate I am calling methods:
  - linphone_core_terminate_all_calls(LinphoneManager.linphoneCore())
 - LinphoneManager.instance().destroyLinphoneCore()
4. When app is in background for more than 3 minutes the connection got lost, here we used PushTry Notification to wake up the app. So when app goes in BG I called " LinphoneManager.instance().enterBackgroundMode()" but when app receive push notification from server in "didReceiveIncomingPushWith" delegate I have called following methods: 
- LinphoneManager.instance().connectivity = none; 
- LinphoneManager.instance().setupNetworkReachabilityCallback()  
- LinphoneManager.instance().refreshRegisters()
- LinphoneManager.instance().startLinphoneCore()
- LinphoneManager.instance().becomeActive() 
let currentCall = linphone_core_get_current_call(LinphoneManager.linphoneCore())
 if currentCall != nil {
                      var callContext = LinphoneManager.instance().currentCallContextBeforeGoingBackground
                    if currentCall == callContext.call {
                        if linphone_call_params_video_enabled(linphone_call_get_current_params(currentCall)) == 1 {
                            linphone_call_enable_camera(currentCall, 0)
                        }

                        callContext.call = OpaquePointer(bitPattern: 0)
                    }
                }

So I am not getting nil in "currentCall" all the time when my app woke up from background after 3 mins and after killed.
So please help in me in finding why I am not receiving object in "currentCall"

I have spent lot of time in this but no success as I am not getting object from "linphone_core_get_current_call"

Please find the attached file for the reference. Appreciate if you will respond asap.

[Code_Snnipet.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/1856190/Code_Snnipet.zip)

**Comment by ReisBenjamin** [comment]
Hello,

As long as the device is not ringing there's no current call in the core.
you can't answer the call in LinphoneManager.instance().becomeActive() you'll have to wait for the call back of state change of a linphone call

Regards

**Comment by GamexStudio** [comment]
hi @GauravKabra03 , did you find any solution for this? I am facing the same issue at my end.

**Comment by luisomar10** [comment]
Same thing in my tests with iPhone or iPad.
What would be the solution for this?
