### ISSUE TITLE
i have enabled apple pay,in-app purchase in project but shop option is still not showing in sidemenu

### ISSUE THREAD

**Issue by sameer4** [BelledonneCommunications/linphone-iphone#408]
[https://ibb.co/mbCRen](https://ibb.co/mbCRen)

link to project setting image

can you please help me what am i missing?

**Comment by sameer4** [comment]
sorry my mistake.had to enable inapp purchase from config file

**Comment by chandani412** [comment]
i also enable in app purchase from config
still can't see shop menu

what is producer to enable in app purchase for linphone?
