### ISSUE TITLE
Can't Add More Ringtones

### ISSUE THREAD

**Issue by iJasonWade** [BelledonneCommunications/linphone-iphone#409]
I am attempting to add more ringtones to the project but when I go to set them I get the following message:
`[Warning] liblinphone/'Mid_steady.wav' ring file does not exist`
I added the ringtone files to submodules/linphone/share, and I also tried adding them to Resources/sounds and them adding them through Xcode, nothing works.

**Comment by ReisBenjamin** [comment]
You need to also add them into the xcode project so that there are embedded in the binaries resources
