### ISSUE TITLE
How to update linphone-sdk in IOS

### ISSUE THREAD

**Issue by RONAKSANKHALA** [BelledonneCommunications/linphone-iphone#410]
Hello @ReisBenjamin.
i have tried to update **linphone-sdk** in my old project but i am not able to update **linphone-sdk**.

i am using below steps to update my l**inphone-sdk** please check once and let me know if the below steps are required or not. if not then how to update **SDK** in linphone..?

i have tried below steps to update **SDK**.

1. **sudo ./prepare.py**
2. **sudo git submodule sync && git submodule update — init — recursive**
3. **sudo ‘./prepare.py -c && ./prepare.py && make`**
4. **sudo ‘./prepare.py -G Xcode -g && make’**

i am await for your positive response.

Thanks.

**Comment by zj299792458** [comment]
you should firstly "git pull" so that the submodules can be updated.
Or there is an easy way, download the linphone-sdk from Linphone website and copy it to your project fold.

**Comment by ReisBenjamin** [comment]
Hello,

indeed try 
git pull 
git submodule update — init — recursive
./prepare.py -c
/prepare.py -G Xcode -g && make

It's not advised to compile in sudo however
