### ISSUE TITLE
The proximity monitor impacts voice badly during a call

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#414]
Hi, I have been testing the audio quality of linphone, and I accidentally found the proximity sensor on iPhone has a tremendous impact on Linphone's audio quality (the sensor that will dim your screen when you put your iPhone close to ear). And I know it sounds crazy.

All the tests are performed under ideal network environment. The RTP jitter is controlled under <1ms and the package loss is strictly 0%. 

When I perform my first voice call, I can hear the voice clear and loud as it should be. As soon as I start to put my iPhone on my ear and put it down repeatedly, the voice is getting worse and worse that I can barely recognize it. I also test another software named Bria, it does not have this issue. 

It will be much obvious when I play a fixed tone sound track from the other endpoint to Linphone  during a Call:

![voice_test](https://user-images.githubusercontent.com/6792825/38969000-a4593700-43c0-11e8-8958-1bd8b51bc5ec.png)

Also here is a tip, I can see Linphone is setting the proximity sensor manually on CallView.m and LinphoneManager.m with:
'[[UIDevice currentDevice] setProximityMonitoringEnabled:FALSE];'
The fact is, when you are using callkit the proximity sensor will be automatically enable when the call starts, and it will be automatically disable when you switch the audio session to speaker or bluetooth. You don't need any of this code at all if you would like to try it out.

I did a little search and I found this on stackoverflow:
https://stackoverflow.com/questions/18967664/proximity-sensor-affects-thread-that-plays-audio
I'm not sure if it is the same issue, I hope we can share some information of this problem and solve it together. Because I'm a big fan of Linphone. 

Thank you for reading.

**Comment by zj299792458** [comment]
I think I found the cause of the issue.
I roughly went through the code, in linphone for iOS, voice processing model is like:

Remote RTP------>jitter buffer------>codec------>flow control bufferizer ------>Audio Unit API
(correct me if i'm wrong)

The flow control bufferizer has default 40ms capacity to store extra audio data that haven't been pushed to Audio Unit. And it will drop left over audio data that exceeds 40ms in every 5000ms.

In the case of G711u 8000Hz audio format, the flow control bufferizer is offering 16000Hz Linear PCM data to Audio Unit, by waiting for Audio Unit's render callback. 

Normally the Audio Unit will ask for 256 frames each time, in case of 16000Hz audio,  it triggers render callback every 16ms. But when I cover iPhone's proximity sensor and the screen go dark, Audio Unit asks for 1024 frame instead! And it will cause a gap (about 180ms) that it does not ask for anything! This 180ms audio data will be left over in flow control bufferizer and be dropped eventually. When I repeat this action the flow control bufferizer keeps dropping audio data over and over again. 

Here is 3750 samples that render callback is triggered by Audio Unit (sampled in submodules/mediastreamer2/src/audiofilters/msiounit.m)

![3aa0bf78-87ce-4a02-aa2c-7546af512d5e](https://user-images.githubusercontent.com/6792825/39753541-c6447b96-52f1-11e8-80e4-33a4a189e8ac.png)

I download Apple Office Audio Example from 
'https://developer.apple.com/library/content/samplecode/Speakerbox/Introduction/Intro.html'

And I found the proximity sensor **DOES NOT** affect frame number of each render callback in this official example! Their render callback from Audio Unit persists dealing 256 frame each time no matter how I trigger the proximity sensor. 

I'm not sure why Linphone's audio unit is different from Apple official one. I'm still studying it.

**Comment by zj299792458** [comment]
Problem solved. 

Limit the audio session's hardware buffer so that Audio Unit won't ask for too much frames when proximity sensor is triggered.

in static void au_write_preprocess(MSFilter *f) {} add:
'
    Float32 bufferSizeInSec = 0.02f;
    if (AudioSessionSetProperty(kAudioSessionProperty_PreferredHardwareIOBufferDuration, 
    sizeof(Float32), &bufferSizeInSec) == noErr) {
		    ms_message("setting hardware buffer duration: %f", bufferSizeInSec);
    }
'
No side affect found for now.
@ReisBenjamin will you merge this alter to '/submodules/mediastreamer2/src/audiofilters/msiounit.m' ?

**Comment by ReisBenjamin** [comment]
Hello @zj299792458 

Thanks a lot for your fix proposal.
I've adapted it to use [AVSession setPreferredIOBufferDuration] method.

Best regards and thanks again

**Comment by khaliddd** [comment]
Hello Guys!
@lucifer662607004 
can someone help me please to fix this issue ?

**Comment by khaliddd** [comment]
As suggestion i am using this code when call connects: 
[session setPreferredIOBufferDuration:0.02f];

and it's still not working, I am stuck on it from previous 2 days, I'll be really thankful for any kind of help.
