### ISSUE TITLE
On receiving VOIP push notification it takes time to establish call. Register with SIP some what late.

### ISSUE THREAD

**Issue by Jaimin-Hodusoft** [BelledonneCommunications/linphone-iphone#415]
Hi @ReisBenjamin ,

I have implemented Linphone in my app. its working all fine and  i am also receiving VOIP calls perfectly using call kit. But some time when my app is killed and i get VOIP push notification (which is instant). At that time Push notification processed instantly and its also going to register with SIP server instantly and call is established. 

But some time its not going to register with SIP server within 5 seconds. Although i get VOIP push notification instantly. And Push notification processed instantly but its not going to register with SIP server. So its not going to establish call.

I mean some time its going to register within 2 seconds and some time its not going to take 5 seconds or more than that seconds to register. 

I have attached log for that please go through it. and let me know whats wrong with it.

This log has taken more than 25 seconds to establish call **Linphone_Call_Instant_Issue_Behind_25Sec.docx**

[Please see link](https://notepad.pw/r0vq1pyu) . 

[LinphoneCall_Instant_Issue.docx](https://github.com/BelledonneCommunications/linphone-iphone/files/1931472/LinphoneCall_Instant.docx)

[Linphone_Call_Instant_Working.docx](https://github.com/BelledonneCommunications/linphone-iphone/files/1931574/Linphone_Call_Instant_Working.copy.docx)

[Linphone_Call_Instant_Issue_Behind_25Sec.docx](https://github.com/BelledonneCommunications/linphone-iphone/files/1931593/Linphone_Call_Instant_Issue_Behind_25Sec.docx)

**Comment by Jaimin-Hodusoft** [comment]
@ReisBenjamin Can you please look at this issue?

I have googled but didn't get whats actually happening here. Can you please help me to short out this issue?

https://forums.developer.apple.com/thread/28019

https://stackoverflow.com/questions/48236673/how-much-runtime-does-an-app-get-when-it-receives-a-pushkit-voip-push

https://stackoverflow.com/questions/33503666/background-running-time-with-pushkit-voip-notifications

**Comment by phanindhra7** [comment]
Hi @Jaimin-Hodusoft 
Same problem here, did you get any solution bro?

**Comment by bnsy** [comment]
Hello @Jaimin-Hodusoft @phanindhra7 @Gui13 @jehandelalune @smorlat 

We are also facing the same issue, App is not able to connect to the SIP server on the first VOIP Push when an app is in terminated/killed state.

Any help would be appreciated.

Thanks
Shubham

**Comment by bnsy** [comment]
Did anyone has the solution?
