### ISSUE TITLE
Hi, i got some issues that '[x86_64-build]' when I was building './prepare.py -c && ./prepare.py && make'

### ISSUE THREAD

**Issue by yuehengwu** [BelledonneCommunications/linphone-iphone#416]
These are the details below : 

[ 36%] Building C object src/CMakeFiles/mediastreamer_voip.dir/crypto/zrtp.c.o
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/src/crypto/zrtp.c:71:8: error: 
      use of undeclared identifier 'ZRTP_KEYAGREEMENT_X255'; did you mean
      'MS_ZRTP_KEY_AGREEMENT_X255'?
                case(ZRTP_KEYAGREEMENT_X255): return "ECDH-255";
                     ^~~~~~~~~~~~~~~~~~~~~~
                     MS_ZRTP_KEY_AGREEMENT_X255
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/include/mediastreamer2/zrtp.h:83:2: note: 
      'MS_ZRTP_KEY_AGREEMENT_X255' declared here
        MS_ZRTP_KEY_AGREEMENT_X255,
        ^
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/src/crypto/zrtp.c:72:8: error: 
      use of undeclared identifier 'ZRTP_KEYAGREEMENT_X448'; did you mean
      'MS_ZRTP_KEY_AGREEMENT_X448'?
                case(ZRTP_KEYAGREEMENT_X448): return "ECDH-448";
                     ^~~~~~~~~~~~~~~~~~~~~~
                     MS_ZRTP_KEY_AGREEMENT_X448
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/include/mediastreamer2/zrtp.h:84:2: note: 
      'MS_ZRTP_KEY_AGREEMENT_X448' declared here
        MS_ZRTP_KEY_AGREEMENT_X448
        ^
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/src/crypto/zrtp.c:550:75: error: 
      use of undeclared identifier 'ZRTP_KEYAGREEMENT_X255'; did you mean
      'MS_ZRTP_KEY_AGREEMENT_X255'?
  ...bzrtpKeyAgreements[bzrtpCount++] = ZRTP_KEYAGREEMENT_X255; break;
                                        ^~~~~~~~~~~~~~~~~~~~~~
                                        MS_ZRTP_KEY_AGREEMENT_X255
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/include/mediastreamer2/zrtp.h:83:2: note: 
      'MS_ZRTP_KEY_AGREEMENT_X255' declared here
        MS_ZRTP_KEY_AGREEMENT_X255,
        ^
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/src/crypto/zrtp.c:551:75: error: 
      use of undeclared identifier 'ZRTP_KEYAGREEMENT_X448'; did you mean
      'MS_ZRTP_KEY_AGREEMENT_X448'?
  ...bzrtpKeyAgreements[bzrtpCount++] = ZRTP_KEYAGREEMENT_X448; break;
                                        ^~~~~~~~~~~~~~~~~~~~~~
                                        MS_ZRTP_KEY_AGREEMENT_X448
/Users/test/Desktop/linphone-iphone1/submodules/mediastreamer2/include/mediastreamer2/zrtp.h:84:2: note: 
      'MS_ZRTP_KEY_AGREEMENT_X448' declared here
        MS_ZRTP_KEY_AGREEMENT_X448
        ^
4 errors generated.
make[6]: *** [src/CMakeFiles/mediastreamer_voip.dir/crypto/zrtp.c.o] Error 1
make[5]: *** [src/CMakeFiles/mediastreamer_voip.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/test/Desktop/linphone-iphone1/WORK/ios-x86_64/Stamp/EP_ms2/EP_ms2-build] Error 2
make[2]: *** [CMakeFiles/EP_ms2.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [x86_64-build] Error 2

Can you give me some help about this issue?

**Comment by ReisBenjamin** [comment]
Hi,

You need to run git submodule update --recursive --init to be sure you submodules are well synced

Regards

**Comment by XiaoWuTongZhi** [comment]
Thx for your help, i fixed this issue after I updated submodule.
