### ISSUE TITLE
Getting error integrating swift

### ISSUE THREAD

**Issue by alimirshad** [BelledonneCommunications/linphone-iphone#417]
I have followed the steps showed on GIT. I am getting the following output when building sdk.

[100%] Completed 'EP_dummy_libraries'
[100%] Built target EP_dummy_libraries
Done
/Users/alienbrainz-2/Downloads/Xcode.app/Contents/Developer/usr/bin/make sdk
[x86_64 arm64 armv7] Mixing bctoolbox.framework in liblinphone-sdk/apple-darwin/Frameworks/bctoolbox.framework
[x86_64 arm64 armv7] Mixing linphone.framework in liblinphone-sdk/apple-darwin/Frameworks/linphone.framework
[x86_64 arm64 armv7] Mixing linphonetester.framework in liblinphone-sdk/apple-darwin/Frameworks/linphonetester.framework
[x86_64 arm64 armv7] Mixing mediastreamer_base.framework in liblinphone-sdk/apple-darwin/Frameworks/mediastreamer_base.framework
[x86_64 arm64 armv7] Mixing mediastreamer_voip.framework in liblinphone-sdk/apple-darwin/Frameworks/mediastreamer_voip.framework
[x86_64 arm64 armv7] Mixing msamr.framework in liblinphone-sdk/apple-darwin/Frameworks/msamr.framework
[x86_64 arm64 armv7] Mixing mscodec2.framework in liblinphone-sdk/apple-darwin/Frameworks/mscodec2.framework
[x86_64 arm64 armv7] Mixing msopenh264.framework in liblinphone-sdk/apple-darwin/Frameworks/msopenh264.framework
[x86_64 arm64 armv7] Mixing mssilk.framework in liblinphone-sdk/apple-darwin/Frameworks/mssilk.framework
[x86_64 arm64 armv7] Mixing mswebrtc.framework in liblinphone-sdk/apple-darwin/Frameworks/mswebrtc.framework
[x86_64 arm64 armv7] Mixing msx264.framework in liblinphone-sdk/apple-darwin/Frameworks/msx264.framework
[x86_64 arm64 armv7] Mixing ortp.framework in liblinphone-sdk/apple-darwin/Frameworks/ortp.framework
NOTE: the following libraries were STUBBED:
msopenh264
mssilk
linphonetester
mscodec2
msx264
msamr

The project builds and when I Try to run the build it shows me following error

dyld: Library not loaded: @rpath/msopenh264.framework/msopenh264
  Referenced from: /var/containers/Bundle/Application/87021C0D-71BA-4C77-B8CC-578105890742/LinPhoneDemo.app/LinPhoneDemo
  Reason: image not found

**Comment by aly-irshad** [comment]
@bagage please have a look.

**Comment by ReisBenjamin** [comment]
Hello,

You need to add all the framework genereated by the build of the SDK to your XCode project embedded and linked binaries as explained the the README.

Regards

**Comment by aly-irshad** [comment]
@ReisBenjamin I have already added all frameworks from **liblinphone-sdk/apple-darwin/Frameworks**

![screen shot 2018-04-27 at 6 38 47 pm](https://user-images.githubusercontent.com/20099371/39364124-78442fea-4a4a-11e8-81c4-a0073b1d9132.png)

**Comment by phamminhvu** [comment]
Hi everyone,

any news here?

**Comment by aly-irshad** [comment]
@phamminhvu try this, It worked for me. 

https://github.com/cwliu/linphone-swift-demo
