### ISSUE TITLE
Change the contact header

### ISSUE THREAD

**Issue by Arslan007** [BelledonneCommunications/linphone-iphone#418]
Hi 
I am using linphone-iPhone, linphone-android and Flexisip and its working fine so far.
There is only one thing I want to do this change the contact header.

Linphone-iPhone sents the private ip in contact header when its registered first time with server then after next register packet contact header have it private IP of that device.

But as a comparison to that Android app sends SIP domain in contact header and the same I want for iOS version aswell. How I can change this in linphone-iPhone version and send this specific contact header and device address. 

<img width="1221" alt="screen shot 2018-04-24 at 1 35 37 am" src="https://user-images.githubusercontent.com/1511567/39295669-416433d2-493f-11e8-985f-afc985ddf406.png">

Thanks!

**Comment by Arslan007** [comment]
@Gui13 @Viish Can you please comment on this. Thanks

**Comment by Arslan007** [comment]
@ReisBenjamin Can you please have a look. Its been like 5 days and I am still struggling to get answer

**Comment by ReisBenjamin** [comment]
Hello,

As you know Linphone is an open source & free project. Therefore our help to our user is based on a best effort basis and we also rely on the rest of the linphone community to help one another.

What you're asking is not to fix a bug, therefore if you want to have a quick answer I invite you to contact info@belledonne-communications.com that will propose you different support solutions.

**Comment by Arslan007** [comment]
Hello @ReisBenjamin 

Thanks for your reply and I understand what you are saying. 
Just to clear I am not using linphone for any commercial usage so far and the option you are giving is for paid support that in my case doesnot make in sense right now. And YES if I will be using linphone for commercial usage and getting any revnue then I should be going for paid support.

However I really appreciate if you can answer about my query and it will help all other opensource community users as well. 

Thanks
