### ISSUE TITLE
-DENABLE_GPL_THIRD_PARTIES=NO error

### ISSUE THREAD

**Issue by fbxcelsior** [BelledonneCommunications/linphone-iphone#42]
Hi,

In the master version, when executing "./prepare.py -DENABLE_GPL_THIRD_PARTIES=NO" the following error is thrown:

CMake Error at options/ms2.cmake:41 (message):
  Trying to enable FFmpeg but GPL third parties not enabled
  (ENABLE_GPL_THIRD_PARTIES).

I am assuming that -DENABLE_FFMPEG=NO must also be used, correct?

Thank you.

Best regards.

**Comment by bagage** [comment]
Yes, this is correct and expected.
