### ISSUE TITLE
Remove Callkit for China?

### ISSUE THREAD

**Issue by lucifer662607004** [BelledonneCommunications/linphone-iphone#423]
Did you receive the letter from apple? The rumour overruns across the internet: 

Dear Developer,
The Chinese Ministry of Industry and Information Technology (MIIT) http://www.miit.gov.cn/n1146285/ ... n3057713/index.html requested that CallKit functionality be deactivated in all apps available on the China App Store.
Since your app currently includes CallKit and is available for sale on the China App Store, you will need to submit an update that removes CallKit functionality in China.
VOIP call functionality continues to be allowed but can no longer take advantage of CallKit ’ s intuitive look and feel. CallKit can continue to be used in apps outside of China.
If you have questions or do not believe your app is subject to this update, please contact MIIT.
Best regards,
App Store Review

**Comment by Daniele-Tentoni** [comment]
So how did it end? We have to publish an application that has been rejected by appstoreconnect, do we have to remove China among the distribution regions?

**Comment by zj299792458** [comment]
> So how did it end? We have to publish an application that has been rejected by appstoreconnect, do we have to remove China among the distribution regions?

Just add some mechanism to make sure callkit will not be activated in China area and explain it to App Store review. And you are welcome to China.
