### ISSUE TITLE
Linphone library starting drop entire frame.

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#424]
Hi. 
I use a linphone library and i implement an CallKit to my project. The problem is while A and B talking C call to B then B show CallKit native ui with 3 options (end&answer, decline, hold&answer). If i choose end&answer or hold&answer the action from CallKit provider work as it should be but liblinphone start showing this and no any sound.

> Log domain : mediastreamer
[Warning] Flow controlled bufferizer of max 40 ms is filled with 9980 ms at the end of the 5000 ms interval, asking to drop 4970 ms
Log domain : mediastreamer
[Warning] Too much buffered audio signal, throwing out 4970 ms
Log domain : mediastreamer
[Warning] Too many samples to drop, dropping entire frame.

- In case i tab end&answer.
- This is how i handle end call action for provider.
![screen shot 2561-05-17 at 00 40 28](https://user-images.githubusercontent.com/18572139/40133784-ef0ea306-596a-11e8-8505-416a96b79097.png)
- The end call reason is nil (It's from native ui) and it terminate a linphone call.

- And then answer call in provider is called.
![screen shot 2561-05-17 at 00 38 41](https://user-images.githubusercontent.com/18572139/40133688-b144cabe-596a-11e8-89b5-855bcef754e3.png)

- And config audio session is called.
![screen shot 2561-05-17 at 00 37 44](https://user-images.githubusercontent.com/18572139/40133625-8a684bbe-596a-11e8-8a21-7e06d74d042a.png)

- And did active audio session is called.
![screen shot 2561-05-17 at 00 45 43](https://user-images.githubusercontent.com/18572139/40134157-ce677a96-596b-11e8-944b-a72abae82969.png)
- It enter an LinphoneCallIncomingReceived case and i've checked that i answer a correct call.

Could someone help me? Please.

**Comment by zj299792458** [comment]
I have exactly same issue. Try pause and resume the C call, will it be normal?
If so I suggest reset the AVAudioSession when the C call's audio is activated.

**Comment by lindseyvastola** [comment]
Did anyone find an answer to this problem? I tried pausing and resuming the call and setting AVAudioSession active on resume but it doesn't work.

**Comment by SarunyuPrasert** [comment]
I'v solved a problem. I edited my code following to linphone project. Don't use CallKit to report incoming call multiple times. Use it to active only 1 call. If in case overlap incoming call (2 incoming call come or while outgoing call and there is incoming call), Use user notification to show notification with  action on another call instead or show app incoming view if app is in foreground and if call that active with CallKit is ended by remote or user terminate just find a left call (even in paused state) to active call with CallKit immediately.

**Comment by zj299792458** [comment]
> I'v solved a problem. I edited my code following to linphone project. Don't use CallKit to report incoming call multiple times. Use it to active only 1 call. If in case overlap incoming call (2 incoming call come or while outgoing call and there is incoming call), Use user notification to show notification with action on another call instead or show app incoming view if app is in foreground and if call that active with CallKit is ended by remote or user terminate just find a left call (even in paused state) to active call with CallKit immediately.

It's not an elegant solution. The call history is incomplete in iOS recent list. And you can't switch between calls with CallKit on lock screen. And other associated functions won't work neither. Rejecting the second incoming call with busy tone is enough to avoid this problem.

**Comment by SarunyuPrasert** [comment]
So there is no one can help me about this and I email to a sell team about this problem and they tell me to do following the linphone project.

**Comment by Li-coder** [comment]
i had likely problem print "mediastreamer-warning-AudioUnit playback discontinuity detected". i tried three days  still can't fix this problem  does anyone konw thank u
