### ISSUE TITLE
Push notification not adding message in chat history 

### ISSUE THREAD

**Issue by parmarkaushik** [BelledonneCommunications/linphone-iphone#428]
We have implemented custom push notification module with freeswitch server and we are sending push notification to devices when status of SIP registration is offline. Below are format of Push notification of Android and iOS push notification

iOS : 

`{"aps":{"alert":{"loc-key":"IM_MSG","loc-args":["919848"],"loc-data":{"msg":"hi","from":"919848","time":"2018-05-26 10:26:11"}},"sound":"msg.caf","badge":"1"},"call-id":"","pn_ttl":"2592000"}
`
Android : 

`{"body":{"msg":"hello","from":"919848","time":"2018-05-26 10:28:40"},"title":"Chat message 919848","sound":"default","color":"#D34B21"}
`
In both the cases we are able to receive push notification in application but it is not adding message to Linphone chat history. Can any one help with the format of push notification which can automatically add push notification chat message to Linphone Chat history database?

Thanks,
Kaushik Parmar

**Comment by tjramoliya** [comment]
@ReisBenjamin 

So how to add new incoming message in chat history? it's not reflecting in chat history if we get notification. it's not updating in list.

We have added method that if we get msg notification, we tap on that and open screen we are checking register state. if device is registered then we are fetching data.
