### ISSUE TITLE
Unable to use G729 codec

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#43]
I am able to build linphone-sdk successfully. However, I am not able to use G729 audio codec in project. It is always disabled. I have tried many different build options as suggested in README.md file. But, nothing helped me.

I have tried with following different commands on linphone-iphone project root directory:
(1) **./prepare.py -c && ./prepare.py -DENABLE_GPL_THIRD_PARTIES=ON && make**
(2) **./prepare.py -c && ./prepare.py -DENABLE_G729=ON && make**
(3) **./prepare.py -c && ./prepare.py --build-all-codecs && make**

I want to use G 729 codec in project and to display G 729 codec in Settings>Audio>Codecs list. Please, suggest me, what can I do for this.

Also, PFA output log of building process:
[Terminal Saved Output 23:02:2016 0837.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/144702/Terminal.Saved.Output.23.02.2016.0837.txt)

**Comment by bagage** [comment]
`./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_G729=ON`

**Comment by nitesh-borad** [comment]
Still G 729 codec is disabled.

I tried your suggestion as follows:

(1) **./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_G729=ON** (only preparing)
(2) **./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_G729=ON && make** (preparing and making)

But, it didn't help me. 
It always says, 
"NOTE: the following libraries were STUBBED:
libopenh264
libopencore-amrwb
libvo-amrwbenc
libtunnel
libmsbcg729
libmsamr
libbcg729
libx264
libmsopenh264
libopencore-amrnb
libmsx264"
Do I need to do anything else?

Also, PFA output log of building process:
[Terminal Saved Output 25022016.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/146092/Terminal.Saved.Output.25022016.txt)

**Comment by bagage** [comment]
Please run first: 

`git pull && git submodule update --init --recursive && ./prepare.py -c` and try again. I tried there and everything works as expected.

**Comment by nitesh-borad** [comment]
Thanks. It's worked. Now I am able to use G 729.

**Comment by zziazm** [comment]
I have run ./prepare.py -c && ./prepare.py -DENABLE_NON_FREE_CODECS=ON -DENABLE_G729=ON
it shows:
WARNING: 
***************************************************************************
***************************************************************************
***** CAUTION, this liblinphone SDK is built using 3rd party GPL code *****
***** Even if you acquired a proprietary license from Belledonne      *****
***** Communications, this SDK is GPL and GPL only.                   *****
***** To disable 3rd party gpl code, please use:                      *****
***** $ ./prepare.py -DENABLE_GPL_THIRD_PARTIES=NO                    *****
***************************************************************************
***************************************************************************
it does not  display G 729 codec in Settings>Audio>Codecs list

**Comment by eunalp** [comment]
Hi, I am also trying to enable G729 however it doesn't appear on the list after successfully build. Is there any config step to do after enabling it through prepare.py?

**Comment by chrice** [comment]
I only find: Media Attribute (a): fmtp:18 annexb=yes, but I can not find " a=rtpmap:18 G729/8000/1", does any on know the reason?
other words, does linphone only support G729B , can not support G729A ?

**Comment by shraddha-patel-1891** [comment]
@niteshborad 
how to add g729 in linphone framework means 4.1?
anyone have solution then please help me.

**Comment by Rushabh5** [comment]
> Please run first:
> 
> `git pull && git submodule update --init --recursive && ./prepare.py -c` and try again. I tried there and everything works as expected.

@bagage Getting error like this.
fatal: not a git repository (or any of the parent directories): .git
