### ISSUE TITLE
Parameters for Push Header and Payload 

### ISSUE THREAD

**Issue by wmukhtar** [BelledonneCommunications/linphone-iphone#430]
Please share sample of Header and Payload should be sent from our HTTP/2 server to Apple Push Server (not flexisip)

Please share samples for Incoming Calls and Messages in "json format".

i found following but not sure if it is outdated and it seems like it is only for incoming messages: 
{“aps":{"alert":{"loc-key":"IM_MSG","loc-args":["Pusher"]},"sound":"msg.caf","badge":1},"call-id":"","pn_ttl”:60}

I couldn't find complete header and payload sample anywhere on the web.

**Comment by ReisBenjamin** [comment]
This is not outdated
