### ISSUE TITLE
AddressBook sync take too much time

### ISSUE THREAD

**Issue by chandani412** [BelledonneCommunications/linphone-iphone#431]
hello,
i am developing app using linphone with tunnel and without tunnel

without tunnel -->> it is working fine if i have more then 1000 contacts

but with tunnel -->> it take  about 4 to 5 minits to copy all contacts from addressbook and it loads every time when i kill the app and launch it again

is there any way to save it locally(in my app)?

temporary i found solution -> contacts loading proccess put in to background using dispatch_queue

but main issue is that why every time it is copy all contacts from addressbook?

i am stuck with this issue from one week..
thanks.

**Comment by ReisBenjamin** [comment]
It's the intended behavior in order not to loose sync with native contacts.
