### ISSUE TITLE
ios12 no longer has libstdc++.6.tbd

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#433]
Can't compile on Xcode beta...any ideas?

**Comment by fedesenmartin** [comment]
Same here

**Comment by zj299792458** [comment]
@fedesenmartin indeed it works...

**Comment by SamboVisal** [comment]
I removed that library and add libc++ instead and then it throws me another error
I have asked this question in stackoverflow but no one reply me yet. Please help me  [https://stackoverflow.com/questions/52659593/linphone-ld-symbols-not-found-for-architecture-x86-64-xcode-10](url) 
please copy and paste it to your web browser. Thank in advance.
