### ISSUE TITLE
Implementing deprecated method at ios 11 and xcode 9.4

### ISSUE THREAD

**Issue by shdaro** [BelledonneCommunications/linphone-iphone#434]
I was compiling linphone through xcode. Last time I uploaded to appstore too. There was no problem at all. Now I want to make the same app for other. 
Then I upgraded the xcode version to 9.4 and changed the target ios version 11 sdk as per new [requirements](https://developer.apple.com/ios/submit/) of appstore.

In my current development there is no code change. Just colors and icons.All the code is as same as my previous app. But I am getting the error when build. I have added the screenshoot for your information.

Current Configuration: macOS High Sierra 10.13.5, Xcode 9.4, ios development target 11

When I try to build ... the build became unsuccessfull with the following error
 
"Implementing deprecated method" at following code
location: approotfolder>classes>DialerView.m
 

- (void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation  
  
                                         duration:(NSTimeInterval)duration {  

And the avobe error was indicating to this error
location: ios 11.4>frameworks>UIkit>headers>UiViewController.h>UiViewController(UiViewController)
 
- (void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration NS_DEPRECATED_IOS(3_0,8_0, "Implement viewWillTransitionToSize:withTransitionCoordinator: instead") __TVOS_PROHIBITED;  
 
 
 
Note: Please Find the screenshots for details understanding
I am new here If the posting format is wrong please forgive me. And let me know if you need more information.
 
https://drive.google.com/file/d/1twT61DH67Epz-iV8umwnDw3UrfnN0CSZ/view
 
https://drive.google.com/file/d/1cllESBPmxOFCxOf0jTvUWIi3wTNOmUQ3/view
 
https://drive.google.com/file/d/1mg4ooBZ5RFoSva1rhCZmD2OiFHZXJ7qA/view

**Comment by ReisBenjamin** [comment]
It means you should stop using method void)willAnimateRotationToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration because it has been deprecated

**Comment by ReisBenjamin** [comment]
you should use viewWillTransitionToSize:withTransitionCoordinator

**Comment by ronydatta** [comment]
Thank you so much @ReisBenjamin 
since I am not an app developer I need to wait for the changes in latest linphone-iphone repository. I just can compile.
May I know when will you release the next version... I think everyone facing the same problem.

**Comment by Daniele-Tentoni** [comment]
Yes, it's a very big problem not having the latest version updated with undeprecated methods.
