### ISSUE TITLE
When Server not receiving register packet from iOS app when we set account expire time is 60.

### ISSUE THREAD

**Issue by mounikakrify** [BelledonneCommunications/linphone-iphone#435]
we are making some SIP calls from A to B in several app condition (foreground, background, telephone locked for more than 60 seconds, app closed): but we experienced that, sometimes, the iOS app does not send the expected REGISTER packet to the SIP server (or at least the server do not receive the packet).

**Comment by ReisBenjamin** [comment]
I'll need logs of when it happens.

Thanks
