### ISSUE TITLE
Architecture error when upload to TestFlight 

### ISSUE THREAD

**Issue by beraylik** [BelledonneCommunications/linphone-iphone#437]
Hello everyone, when I'm trying to upload my project to the test flight I get a lot of errors about unsupported architecture x86_64
![2018-06-13 17 32 01](https://user-images.githubusercontent.com/22113339/41396796-b1d33158-6fba-11e8-8360-8a314feae133.png)

I did install everything as it says in the docs. 
Everything works fine both on simulator and on a real device.

So I can't send the app to the TestFlight.
How to fix this issue?

**Comment by ReisBenjamin** [comment]
There's a need  of a script called deploy.sh in Tools

Take a look at the README.md

**Comment by beraylik** [comment]
I fixed this problem, I just have implemented this script wrong way. And now I have new problem, after I uploaded the app to the test flight I can't open it anymore, it just instantly crashes. it only happens when I download it from TestFlight. when debugging everything is ok, why would this happen?

**Comment by jelenadj** [comment]
@beraylik how did you solve the issue with TestFlight build?
