### ISSUE TITLE
Push notification not configured

### ISSUE THREAD

**Issue by chandani412** [BelledonneCommunications/linphone-iphone#439]
when i am register using **mydomain.com:5070** with enable notification with function " linphone_proxy_config_set_ref_key(config, "push_notification"); " then i will goes into registration in progress and failed registration

when i disable push notification **(comment this line: linphone_proxy_config_set_ref_key(config, "push_notification");)** registration working fine.

can not identify what is going wrong with enable push notification

thanks

**Comment by ReisBenjamin** [comment]
Please post logs when attemption to regiter when it doesn't work.

Thanks

**Comment by alexmatute** [comment]
I have the same error in an Iphone 8 with IOS 12
when i am register using my sip account, with enable notification with function " linphone_proxy_config_set_ref_key(config, "push_notification"); " then i will goes into registration in progress and failed registration

when i disable push notification (comment this line: linphone_proxy_config_set_ref_key(config, "push_notification");) registration working fine.

can not identify what is going wrong with enable push notification

thanks!
