### ISSUE TITLE
Question: How does work the flow of receiving a call?

### ISSUE THREAD

**Issue by amadeu01** [BelledonneCommunications/linphone-iphone#441]
I know that a push notification will wake the phone to establish a call.
However, I cannot see which methods are called, and how the flow of receiving a call works.
For instance, 

```
Method A is first called when the push notifications are received, then Method B takes the payload of the notification and establishes a call between the two sip accounts.
```

**Comment by ReisBenjamin** [comment]
Hello,

When receiving a push the app wakes.
Then the app registers to the SIP service
Once Registered the app should receive the INVITE to start the call

Is that clear ?

**Comment by amadeu01** [comment]
@ReisBenjamin  Actually, I was looking up for some trace of methods that end up on the call being established.

Isn't the push notification itself one INVITE?

**Comment by ReisBenjamin** [comment]
Hello,

NO the push notification only wakes the app up.
Then it has to register (triggered in th eprocessRemoteNotifcation method of LinphoneAppDelegate)

The invite is later received in the onCallStateChanged... method of LinphoneManager.

the push notification is not an invite nor a message
