### ISSUE TITLE
RTSP via Linphone

### ISSUE THREAD

**Issue by beraylik** [BelledonneCommunications/linphone-iphone#443]
Is it possible to use Linphone SDK to fetch RTSP Stream?

**Comment by pergolafabio** [comment]
Did you found the solution?

**Comment by pergolafabio** [comment]
completed? is it a new function ?

**Comment by benoit-martins** [comment]
Hi,

We have closed all open tickets as the upcoming release of Linphone 6.0 is a complete redesign of the app. 
This new version will address existing issues with a fresh approach, so we encourage you to explore the updated app when it's available.

Thank you for your understanding and support!

Best regards

**Comment by pergolafabio** [comment]
ah, so rtsp is also part of the 6.0 ?

**Comment by benoit-martins** [comment]
Unfortunately, RTSP isn't included in version 6.0.
If you need streaming protocols, you might need to consider an alternative solution or wait, but its integration isn't planned for now.
