### ISSUE TITLE
core initialization crashes if VCARD support is disabled

### ISSUE THREAD

**Issue by eliburke** [BelledonneCommunications/linphone-iphone#445]
I'm not sure if this issue belongs here or in the liblinphone submodule; it's an SDK problem. 

If liblinphone-iphone-sdk is compiled with VCARD support OFF, it crashes when IosPlatformHelpers() is initialized:
`std::string vcardPath = directoryForResource(CFSTR("org.linphone.belcard"), CFSTR("vcard_grammar"));`

IosPlatformHelpers::directoryForResource does not check to see if CFBundleCopyResourceURL returns a value:  
```
std::string IosPlatformHelpers::directoryForResource (CFStringRef framework, CFStringRef resource) {
	CFBundleRef bundle = CFBundleGetBundleWithIdentifier(framework);
	CFURLRef grammarUrl = CFBundleCopyResourceURL(bundle, resource, nullptr, nullptr);
	CFURLRef grammarUrlDirectory = CFURLCreateCopyDeletingLastPathComponent(nullptr, grammarUrl);

```

**Comment by ReisBenjamin** [comment]
fixed with commit df14dc66dc26cb7c9ea52df2743ce421906f6820
