### ISSUE TITLE
Creating core using linphone_factory_create_core_with_config_3

### ISSUE THREAD

**Issue by jelenadj** [BelledonneCommunications/linphone-iphone#446]
I am trying to replace deprecated linphone_factory_create_core_with_config from createLinphoneCore with linphone_factory_create_core_with_config_3, but having troubles with triggering callbacks (like linphone_iphone_configuring_status_changed) when creating a core with the new method.
Are you planing to upgrade it in LinphoneManager soon?

**Comment by ReisBenjamin** [comment]
done in commit 33b57bd9ac67649fe56a66428215d20fdf48b451
