### ISSUE TITLE
Unable to made calls with WiFi

### ISSUE THREAD

**Issue by mbonnafon** [BelledonneCommunications/linphone-iphone#447]
Good afternoon,

I have an issue with Linphone client on iOS. I'am not able to made outbound calls by using WiFi.
You can find logs enclosed.

###### Steps done during logs record:

I turned only data on, it registered well, I done an outbound call. It worked fine.
I turned off data, I turned on WiFi, it registered well but when I tried to made outbound call (same number as the previous one), I had no tone and it never rang.

Another user with same iOS version and Linphone core tried same manipulations(with others SIP credentials), he had the same issue. He wasn't in the same LAN as me.
To rule out network issue I downloaded Linphone on my Linux workstation, I used the Wizard to configure SIP line. It worked well.

If you need further information, I will be happy to provide it to you.

###### Informations:

Linphone iOS 4.0
Linphone core 3.12.0-2403-gc448d2e00
iOS version: 11.2

###### Logs:
[linphone_log.gz](https://github.com/BelledonneCommunications/linphone-iphone/files/2137019/linphone_log.gz)

**Comment by ReisBenjamin** [comment]
2018-06-26 12:11:36:245 [belle-sip] ERROR - no DNS servers available - resolution aborted.

It seems you wiki network doesn't have DNS resolver

**Comment by kodols34** [comment]
Thanks for your reply, my wifi have a DNS resolver. 
I did the test with a web browser, it resolved well domain name.
Does it is possible that another error either in question.

**Comment by alexzh16** [comment]
Dear Benjamin, i have same problem, and its not working in ipv6 networks. issues #429. please see email communications. This problem with IPNAT6. i sending weblink from apple support. where apple tested last commit, than have same problem, linphone not working in ipv6 networks.

**Comment by alexzh16** [comment]
commit linphone from Fenbruar 2018 work fine, but after this commit, i cannot yet build linchpin with Xcode, because submodules have deprecated functions. i tested commit 836f7c93e919685aa1c9e8c6518cb217ddde020b - this not working too.
