### ISSUE TITLE
OutgoingCall not transitioning to EarlyMedia, Connected, StreamsRunning

### ISSUE THREAD

**Issue by mrdavidrees** [BelledonneCommunications/linphone-iphone#448]
When calling the another client, it connects though properly, the other client will receive the call, start ringing, accept and connect. However the other client doesn't ever connect one the outgoing call is accepted. instead it logs this error:

[Error] Unexpected method [BYE] for dialog state BELLE_SIP_DIALOG_EARLY

I have just updated to the current master revision at the date of this issue but the issue persists.

I have attached the logs to aid in the resolution of this issue.

[receiving-client.log](https://github.com/BelledonneCommunications/linphone-iphone/files/2139568/receiving-client.log)
[calling-client.log](https://github.com/BelledonneCommunications/linphone-iphone/files/2139569/calling-client.log)

**Comment by ReisBenjamin** [comment]
You never received the 200Ok therefore de call is never accepted on the caller's side.
In the callee the 200OK is sent therefore it might an issue with your proxy server that lost it.

**Comment by mrdavidrees** [comment]
Okay thankyou, I'll talk to the server administrator about this.
