### ISSUE TITLE
How can I read server info from response header in 200 ok

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#45]
Hello everyone.
I'm trying to collect server info in Objective C level, which means I need to retrieve the server field in registration response message such as 200 OK for each session. I'm wondering is it possible without modifying the liblinphone?
I roughly went through the linphonecore.h api and didn't find a clue. 
Could someone give me a hint plz??

**Comment by bagage** [comment]
For such questions that are not really linphone-iphone, please use the [dev mailing list](https://lists.nongnu.org/mailman/listinfo/linphone-developers) instead where you should have more help.
