### ISSUE TITLE
how can i enable in app purchse in linpnone ios?

### ISSUE THREAD

**Issue by chandani412** [BelledonneCommunications/linphone-iphone#450]
i also enable=1 from config file "linphonerc"

**Comment by alexzh16** [comment]
[in_app_purchase]
#set to 1 if in-app purchases are to be shown in the application
enabled=1

#specify here the id of the sip account in-app purchase service to be shown in the shop section of the app
paid_account_id=yourBundleName.Purchase

#the url of the inapp/account management server, for submitting the receipt and validating the account.
receipt_validation_url=https://yourserver

#for future use, to specify the full list of paying services to show in the shop view
products_list=yourPurchaseList

#minimum period of time between notifications to the user about his expiring/expired account, in seconds.
expiry_check_period=30

#period of time before account expiry, to start notifying the user about expiration arriving, in seconds.
warn_before_expiry_period=160

#for test only, simulate an account expiry after the specified number of seconds
expiry_time_test=180

#save temporarily the receipt for any purchase in case of XMLRPC server error
save_tmp_receipt=0
