### ISSUE TITLE
Duplication of text messages

### ISSUE THREAD

**Issue by Dsonigara52** [BelledonneCommunications/linphone-iphone#454]
**Algorithm for error occurrence** :

**First device** : chat--new chat--enter recipient id--write message-send button
**Second device** : answer to this message
**First device** : 2 chat with same contact

**Comment by ReisBenjamin** [comment]
Hello,

I do not reproduce this issue, do you communicate with 2 Linphone iOS?
Do you use sip.linphone.org accounts?

**Comment by Dsonigara52** [comment]
Hello,

So here is the main issue I am facing with is that when i send message using **DID** which is without any prefix for example **4567892134** and when the receiver text me back it makes duplicate entry that is with prefix for example **(1)4567892134** so now there is two entry for same contact with and without prefix and using extension its working fine.

**Comment by basitmashwani** [comment]
@Dsonigara52 Have you find any solution to this problem?

**Comment by dsonigara** [comment]
@basitmashwani not now
