### ISSUE TITLE
I am receiving local notification when application is killed But I could not get call.

### ISSUE THREAD

**Issue by vyasdarshan** [BelledonneCommunications/linphone-iphone#455]
I am receiving local notification in PushKit's delegate method "- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion", However, in this same method "processPush" method is called which handles call related stuff but that is not working at app terminated state. Please help me in it. I am struggling from many days.

**Comment by 1inq** [comment]
Hello @ReisBenjamin ,

I would glad to hear your advice. Do you have any ideas, why refresh registers doesn't work when app was terminated? I receive remote push and try to restore default proxy registration by use this code:

```
if (linphone_core_get_default_proxy_config(self.lc)) {
	linphone_core_refresh_registers(self.lc);
	linphone_core_iterate(self.lc);
}
LinphoneProxyConfig* proxyConfig = linphone_core_get_default_proxy_config(self.lc);
if (proxyConfig) {
	linphone_proxy_config_edit(proxyConfig);
	linphone_proxy_config_enable_register(proxyConfig, true);
	linphone_proxy_config_enable_publish(proxyConfig, true);
	linphone_proxy_config_done(proxyConfig);
	linphone_proxy_config_refresh_register(proxyConfig);
	linphone_core_iterate(self.lc);
}
```
Is there any specific options that I should do to restore registration with this method?

**Comment by sky1987a** [comment]
@GamexStudio  Did you do anything for app, i can't receive any notification when app in background or killed

**Comment by ronydatta** [comment]
Hi all,

Any solution? I am also facing this issue. I can get the push notification for call but it doesn't wake up the app from background. Any possible solution for this?

**Comment by bnsy** [comment]
I am also facing the same issue, please let us know did anyone found the solution @shdaro @1inq @GamexStudio
