### ISSUE TITLE
Cannot compile liblinphone-sdk static library

### ISSUE THREAD

**Issue by metin9527** [BelledonneCommunications/linphone-iphone#458]
./prepare -c && ./prepare -DENABLE_STATIC_ONLY=ON && make
You will see the error.

**Comment by ReisBenjamin** [comment]
DENABLE_STATIC_ONLY is no longer supported

**Comment by metin9527** [comment]
But on #442, you said can use ENABLE_STATIC_ONLY=ON.
Can you tell me why no longer supported?
Thanks!
