### ISSUE TITLE
*.linphone.org unreachable from VPS providers since ~ early July 

### ISSUE THREAD

**Issue by oneacl** [BelledonneCommunications/linphone-iphone#459]
Hi,
Since a few weeks ago (give or take) anything linphone.org related (including the website) is unreachable from VPS providers (tried GCP, Linode, Vultr) - however, it works just fine from a residential IP.
My asterisk box is on a VPS (for high availability, can't host it at home) and can no longer use my Linphone account to receive incoming calls on iOS.

Is this a firewall gone wrong or some sort of blanked DDOS protection? Is there any way to whitelist an IP?

Thank you.

**Comment by ReisBenjamin** [comment]
Unrelated to linphone-iphone
