### ISSUE TITLE
Video cannot disconnect using Asterisk

### ISSUE THREAD

**Issue by mrdavidrees** [BelledonneCommunications/linphone-iphone#463]
Hey.
I've been investigating this issue for about a week now- My Video just wont turn off. In fact it still broadcasts to the other person even after I have switched it off.

I've gone over the code that turns video off and on and looked at every bit of code in the linphone-iPhone library that relates to this and I guarantee that I turn video on and off the same way linphone-iPhone does.

I had some suspicions that the server was the issue, however when I used the Bria app with the same phones and sip accounts, the video call worked perfectly.
The most confusing part was that when I downloaded the linphone-iPhone app and ran it, the video would not disconnect just as I was experiencing in our app.

Since the Bria app works fine with the asterisk server, is there anything that could be done to get the video working?

I've included the logs to show that it is error-ing when updating the call state and turning the video off.

[linphone_video_disconnection_error.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/2289323/linphone_video_disconnection_error.txt)

Thanks, David.

**Comment by githupchenqiang** [comment]
I met the same problem, could you tell me how do you solve, hope you can give me some advice, thank you

**Comment by mrdavidrees** [comment]
@ReisBenjamin is there any knowledge or direction you can provide? Any assistance would be very appreciated as we are trying to release our app to production.
