### ISSUE TITLE
App crash while making call

### ISSUE THREAD

**Issue by Spyspyspy** [BelledonneCommunications/linphone-iphone#466]
I've get latest source and when i try to make call in iPad Air iOs 9.3, or other device with iOs 9 app is crashing.

2018-08-17 10:27:03.342 linphone[1057:22159] [Message] CallSession [0x158ad9248] New ICE state: audio: [IceStateInProgress]    video: [IceStateNotActivated]    text: [IceStateNotActivated]
2018-08-17 10:27:03.342 linphone[1057:22159] [Message] ms_filter_link: MSRtpRecv:0x158cc3470,0-->MSAUWrite:0x158cc68b0,0
2018-08-17 10:27:03.343 linphone[1057:22159] [Message] Configuring audio session for playback/record
2018-08-17 10:27:03.344 linphone[1057:22159] -[AVAudioSession setCategory:mode:options:error:]: unrecognized selector sent to instance 0x15612c8b0
2018-08-17 10:27:03.348 linphone[1057:22159] Crash: -[AVAudioSession setCategory:mode:options:error:]: unrecognized selector sent to instance 0x15612c8b0
2018-08-17 10:27:03.373 linphone[1057:22159] Stack Trace: (
	0   CoreFoundation                      0x0000000182e9cf74 <redacted> + 148
	1   libobjc.A.dylib                     0x000000019794bf80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182ea3c6c <redacted> + 0
	3   CoreFoundation                      0x0000000182ea0c14 <redacted> + 872
	4   CoreFoundation                      0x0000000182da4dcc _CF_forwarding_prep_0 + 92
	5   mediastreamer_voip                  0x0000000100597f74 configure_audio_session + 464
	6   mediastreamer_voip                  0x0000000100596a50 au_write_preprocess + 84
	7   mediastreamer_base                  0x00000001011f3e14 ms_ticker_attach_multiple + 180
	8   mediastreamer_base                  0x00000001011f3d50 ms_ticker_attach + 20
	9   mediastreamer_voip                  0x0000000100553800 audio_stream_prepare_sound + 264
	10  linphone                            0x0000000101311e30 _ZN15LinphonePrivate12MediaSession11startInviteEPKNS_7AddressERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEPKNS_7ContentE + 976
	11  linphone                            0x0000000101307c1c _ZN15LinphonePrivate19MediaSessionPrivate15handleIceEventsEP4msgb + 996
	12  linphone                            0x000000010130866c _ZN15LinphonePrivate19MediaSessionPrivate18handleStreamEventsEi + 824
	13  linphone                            0x000000010130de74 _ZN15LinphonePrivate19MediaSessionPrivate22executeBackgroundTasksEb + 288
	14  linphone                            0x0000000101311584 _ZN15LinphonePrivate12MediaSession7iterateElb + 40
	15  linphone                            0x00000001012750f0 _ZN15LinphonePrivate11CallPrivate7iterateElb + 64
	16  linphone                            0x000000010131c4d4 _ZNK15LinphonePrivate11CorePrivate12iterateCallsElb + 248
	17  linphone                            0x0000000101422d0c linphone_core_iterate + 1208
	18  linphone                            0x000000010008cd44 -[LinphoneManager iterate] + 184
	19  Foundation                          0x0000000183ddc324 __NSFireTimer + 88
	20  CoreFoundation                      0x0000000182e54c9c <redacted> + 28
	21  CoreFoundation                      0x0000000182e54940 <redacted> + 884
	22  CoreFoundation                      0x0000000182e52054 <redacted> + 1520
	23  CoreFoundation                      0x0000000182d80dc0 CFRunLoopRunSpecific + 384
	24  GraphicsServices                    0x000000018dd10088 GSEventRunModal + 180
	25  UIKit                               0x000000018845af44 UIApplicationMain + 204
	26  linphone                            0x00000001000092cc main + 144
	27  libdyld.dylib                       0x000000019816a8b8 <redacted> + 4
)
2018-08-17 10:27:03.373 linphone[1057:22159] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AVAudioSession setCategory:mode:options:error:]: unrecognized selector sent to instance 0x15612c8b0'
*** First throw call stack:
(0x182e9cf5c 0x19794bf80 0x182ea3c6c 0x182ea0c14 0x182da4dcc 0x100597f74 0x100596a50 0x1011f3e14 0x1011f3d50 0x100553800 0x101311e30 0x101307c1c 0x10130866c 0x10130de74 0x101311584 0x1012750f0 0x10131c4d4 0x101422d0c 0x10008cd44 0x183ddc324 0x182e54c9c 0x182e54940 0x182e52054 0x182d80dc0 0x18dd10088 0x18845af44 0x1000092cc 0x19816a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by chuquangbao** [comment]
I have that same problem too!

**Comment by Phaptlq** [comment]
i have this issue.
