### ISSUE TITLE
How can I configure Linphone to always ring when a call is received?

### ISSUE THREAD

**Issue by Daguerre101** [BelledonneCommunications/linphone-iphone#467]
Hi,
We have been testing Linphone for the last few weeks and all is OK with one exception: If Linphone is in background or if the Iphone is on standby, incoming calls does not ring at all. I can see that Linphone unregisters itself while not "in front".

How can I configure Linphone so that it could always ring for incoming calls?

Thanks in advance for your help

Have a great day
Dag

**Comment by oallanmendes** [comment]
Hi @Daguerre101 ! Did you find out how to solve this problem?

**Comment by Daguerre101** [comment]
We do not use Linphone anymore.

You can close this thread if you want to.

Thank you!

De : oallanmendes <notifications@github.com>
Envoyé : 18 avril 2019 13:09
À : BelledonneCommunications/linphone-iphone <linphone-iphone@noreply.github.com>
Cc : Frédéric Giguère <fgiguere@groupeedifio.com>; Mention <mention@noreply.github.com>
Objet : Re: [BelledonneCommunications/linphone-iphone] How can I configure Linphone to always ring when a call is received? (#467)


Hi @Daguerre101<https://github.com/Daguerre101> ! Did you find out how to solve this problem?

**Comment by oallanmendes** [comment]
Whats are you using now?

**Comment by oallanmendes** [comment]
What application are you using now?

**Comment by Daguerre101** [comment]
IP phones. Spectralink.

De : oallanmendes <notifications@github.com>
Envoyé : 18 avril 2019 13:20
À : BelledonneCommunications/linphone-iphone <linphone-iphone@noreply.github.com>
Cc : Frédéric Giguère <fgiguere@groupeedifio.com>; Mention <mention@noreply.github.com>
Objet : Re: [BelledonneCommunications/linphone-iphone] How can I configure Linphone to always ring when a call is received? (#467)


Whats are you using now?

**Comment by Daguerre101** [comment]
None we are using Ipphones instead.

De : oallanmendes <notifications@github.com>
Envoyé : 18 avril 2019 13:21
À : BelledonneCommunications/linphone-iphone <linphone-iphone@noreply.github.com>
Cc : Frédéric Giguère <fgiguere@groupeedifio.com>; Mention <mention@noreply.github.com>
Objet : Re: [BelledonneCommunications/linphone-iphone] How can I configure Linphone to always ring when a call is received? (#467)


What application are you using now?

**Comment by oallanmendes** [comment]
ok! ):
Thaaanks!!!
