### ISSUE TITLE
I really shouldn't git pull

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#47]
after git pull & git submodule update --recursive --init, I couldn't even compile it.

/Users/Steven/GitProjects/LinphoneIOS/submodules/externals/gsm/src/code.c:95:8: error: 
      implicitly declaring library function 'memcpy' with type 'void *(void *,
      const void *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
        (void)memcpy( (char *)S->dp0, (char *)(S->dp0 + 160),
              ^
/Users/Steven/GitProjects/LinphoneIOS/submodules/externals/gsm/src/code.c:95:8: note: 
      include the header <string.h> or explicitly provide a declaration for
      'memcpy'
1 error generated.
make[6]: *** [CMakeFiles/gsm.dir/src/code.c.o] Error 1
make[5]: *** [CMakeFiles/gsm.dir/all] Error 2
make[4]: *** [all] Error 2
make[3]: *** [/Users/Steven/GitProjects/LinphoneIOS/WORK/ios-arm64/Stamp/EP_gsm/EP_gsm-build] Error 2
make[2]: *** [CMakeFiles/EP_gsm.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [arm64-build] Error 2

**Comment by bagage** [comment]
Both travis and jenkins are compiling fine (as well as mine obviously). Furthermore last update of gsm was 2015-07-03, so I am not sure why are you complaining here.

Check your setup.

**Comment by zj299792458** [comment]
This is what i tried in root directory:
git reset --hard HEAD
git checkout
git clean -fdx
git pull
git submodule update --recursive
git submodule update --recursive --init
./prepare.py -c
./prepare.py
make

The last git version works just fine and I didn't touch anything since then, Could you please tell me where i did wrong? Thank you ...

@bagage

**Comment by bagage** [comment]
Fixed in master. For your information, your problem was not due to linphone but your upgrade of Xcode to 7.3. Next time please ensure you are blaming the proper tool ;-).

**Comment by zj299792458** [comment]
@bagage appreciate it!
