### ISSUE TITLE
When app enter in bacground, app can't receive any incalling, 

### ISSUE THREAD

**Issue by sky1987a** [BelledonneCommunications/linphone-iphone#471]
When app enter in background, it's can't receive any incalling and response

**Comment by saeed-rz** [comment]
same problem

**Comment by djkskqyr3** [comment]
same problem
I got VOIP push from server, but seems that SIP register does not working.

`belle-sip-error-udp_listening_point: recvfrom() failed on [sip:0.0.0.0:63057;transport=UDP], : [Socket is not connected] reopening server socket`

**Comment by saeed-rz** [comment]
I tried test pushkit, send sample push with pusher application before the call, and it works. now I try to implement push on server application for real test

**Comment by sky1987a** [comment]
I also used the same method, but I still try to receive incalling without push notification, it's pooible?

**Comment by ReisBenjamin** [comment]
No it's not.
Since ios 10 PushKit is the only way to receive calls and messages when app goes in background
