### ISSUE TITLE
Can't receivce calls when device lock screen

### ISSUE THREAD

**Issue by sky1987a** [BelledonneCommunications/linphone-iphone#472]
When device lock scrren , it can recevice push notification, but can't recevice incalling. Has anyone encountered this problem?

2018-09-18 15:28:34.607647+0800 linphone[9959:4390887] [Message] Activity started
2018-09-18 15:28:34.609241+0800 linphone[9959:4390887] [Message] channel [0x110f20000]: starting recv background task with id=[1b].
2018-09-18 15:28:34.609392+0800 linphone[9959:4390887] [Message] Socket is not connected because of IOS10 background policy
2018-09-18 15:28:34.609528+0800 linphone[9959:4390887] [Message] channel 0x110f20000: state DISCONNECTED
2018-09-18 15:28:34.609651+0800 linphone[9959:4390887] [Message] channel [0x110f20000]: ending recv background task with id=[1b].
2018-09-18 15:28:34.609731+0800 linphone[9959:4390887] [Message] Activity ended

**Comment by sky1987a** [comment]
solved

**Comment by AllenEllis** [comment]
How did you solve it? I'm not receiving calls on my lock screen either (iOS 12)

**Comment by krishnastvSMSC** [comment]
Hello, 
How the issue is resolved, we enable push notification at setting tab under more options. Where we can set our .p8 file at server side. Any response will appreciate.

Thanks

**Comment by sky1987a** [comment]
Maybe u should study how to build apn server

**Comment by krishnastvSMSC** [comment]
We know how to develop APNS push notifications, but in Linphone Application source code already PusherKit is integrated, for sending push notification we need to give our VOIP certificate at server end. we cannot it at server side.

**Comment by sky1987a** [comment]
Sorry,my bad. It wasn't apns server. You must to use pushkit server and send message with pushkit token. Hope it will help u

**Comment by krishnastvSMSC** [comment]
Linphone already did every thing at client application side (PushKit and VOIP notifications and callkit). But at server side where we have to do that

**Comment by sky1987a** [comment]
Maybe u can send me more information about  u r server side, and i will try to help you.
Email: sky1987a@gmail.com

**Comment by Trushangpatel** [comment]
Hello,

I will resolve this issue from voip silent push notification.
if you need help then mail me: trushangpatel3993@gmail.com, add subject: linphone issue

Thanks

**Comment by leelai** [comment]
We have an issue regarding to push notification on linphone.linphone couldn't receive push notification from our sip server(flixisip) sometimes not always, especially when we test it on next day in the morning(put the phone aside all night and do nothing), it usually couldn't get the first notification, but the second time it will work normally.
Do you how to solve this?
