### ISSUE TITLE
VPX library won't build for iOS 12

### ISSUE THREAD

**Issue by GlacierSecurityInc** [BelledonneCommunications/linphone-iphone#475]
After upgrading Xcode to the latest version (10) for use with iOS 12 on my Mac, I had problems building due to some deprecated code. I decided to start from scratch and pull the latest from github, but I was not able to build the libraries.

It turns out that libstdc++ is fully deprecated in iOS 12, but clang++ is still trying to build and/or link with it. After some fiddling, I added the following lines in cmake-builder/configs/config-ios.cmake under the vpx section and it solved that particular problem (the first line was already there and is just for context):

lcb_builder_linking_type(vpx "--enable-static" "--disable-shared")
lcb_builder_extra_cxxflags(vpx "-stdlib=libc++")
lcb_builder_extra_ldflags(vpx "-stdlib=libc++")

Not sure if this is something that others will find or if I need to fix something else in my development environment, but wanted to document it here just in case. Also, maybe this would be better under the cmake specific prject, but since it broke my linphone build I put it here. Feel free to move it and close it if its better suited under cmake-builder.

**Comment by S0U1SB4N3** [comment]
I am getting this same error on all builds past and present

**Comment by S0U1SB4N3** [comment]
=== BUILD AGGREGATE TARGET EP_vpx OF PROJECT Project WITH THE DEFAULT CONFIGURATION (Debug) ===

Check dependencies

PhaseScriptExecution CMake\ Rules /Users/S0U1SB4N3/LinTest/test/linphone-iphone/WORK/ios-arm64/cmake/Project.build/Debug-iphoneos/EP_vpx.build/Script-7B23D8B98E04420C82FF95BE.sh
    cd /Users/S0U1SB4N3/LinTest/test/linphone-iphone/submodules/cmake-builder
    /bin/sh -c /Users/S0U1SB4N3/LinTest/test/linphone-iphone/WORK/ios-arm64/cmake/Project.build/Debug-iphoneos/EP_vpx.build/Script-7B23D8B98E04420C82FF95BE.sh
echo "Performing configure step for 'EP_vpx'"
Performing configure step for 'EP_vpx'
cd /Users/S0U1SB4N3/LinTest/test/linphone-iphone/WORK/ios-arm64/Build/vpx && /Users/S0U1SB4N3/LinTest/test/linphone-iphone/WORK/ios-arm64/cmake/EP_vpx_configure.sh
  disabling shared
  enabling error_concealment
  enabling realtime_only
  enabling vp8
  disabling vp9
  disabling install_docs
  disabling debug_libs
  disabling examples
  disabling unit_tests
Configuring selected codecs
Configuring for target 'arm64-darwin-gcc'
  enabling arm64
  enabling neon
Toolchain is unable to link executables

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
make[1]: *** [/Users/S0U1SB4N3/LinTest/test/linphone-iphone/WORK/ios-arm64/Stamp/EP_vpx/Debug-iphoneos/EP_vpx-configure] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution CMake\ Rules /Users/S0U1SB4N3/LinTest/test/linphone-iphone/WORK/ios-arm64/cmake/Project.build/Debug-iphoneos/EP_vpx.build/Script-7B23D8B98E04420C82FF95BE.sh
(1 failure)
make: *** [arm64-build] Error 65

**Comment by saeed-rz** [comment]
update EP_vpx submodule from git
then run 
./prepare.py -c
./prepare.py
make
