### ISSUE TITLE
Build Failed while try to build new Linphone For Iphone

### ISSUE THREAD

**Issue by RONAKSANKHALA** [BelledonneCommunications/linphone-iphone#476]
Hello @ReisBenjamin , 

I am working on Linphone project from last 6 to 7 months. currently I am working on  linphone 3.14.0 and it's working fine and i had no issue at the time of download this version, but from last 3 day I am trying to download Linphone 4.0.1 in my system but I am not able to download latest version of Linphone. I am getting make[3]: *** **### ~/linphone-iphone/WORK/ios-x86_64/Stamp/EP_vpx/EP_vpx-configure] Error 1**.

- **Please find below steps for download Latest Linphone and please check this all steps are correct or not.**

**Step 1:**  **Clone project using below HTTPS URL**

            -  git clone https://github.com/BelledonneCommunications/linphone-iphone.git

**Step 2:**  **Update submodule** 

            -  git submodule sync && git submodule update --init --recursive

**Step 3:** **Build SDK**
**I tried below all option for build Linphone using Different Option of Make and Prepare.py** 

             - ./prepare.py -c && ./prepare.py && make
                                       OR
             - ./prepare.py -c && ./prepare.py [all] && make  
                                       OR
             - ./prepare.py -c && ./prepare.py [all] && make  -j1
                                       OR
             - ./prepare.py -c && ./prepare.py  && make -j1

**but above all option are not working for me. when i try to build Linphone after update submodule at that time i am facing bellow ERROR**

**ERROR While build Latest Linphone in Mac High Sierra **

             Configuration failed. This could reflect a misconfiguration of your
             toolchains, improper options selected, or another problem. If you
             don't see any useful error messages above, the next step is to look
             at the configure error log file (config.log) to determine what
             configure was trying to do when it died.
             make[3]: *** [/Users/ronaksankhala/Documents/RONAK/NewLinphone/Linphone/linphone- 
             iphone/WORK/ios-x86_64/Stamp/EP_vpx/EP_vpx-configure] Error 1
             make[2]: *** [CMakeFiles/EP_vpx.dir/all] Error 2
             make[1]: *** [all] Error 2
             make: *** [x86_64-build] Error 2

**Please Help me to solve above Issue**
Thanks.

**Comment by S0U1SB4N3** [comment]
My build on xCode 10 macOSHigh Sierra 10.13 stable 
fails to build with the same errors

**Comment by saeed-rz** [comment]
same error after update xCode 10

**Comment by saeed-rz** [comment]
I have clone manually "EP_vpx" submodule and its work.
