### ISSUE TITLE
Send Emoji in messages is not working

### ISSUE THREAD

**Issue by vetrek** [BelledonneCommunications/linphone-iphone#477]
The linphone_chat_room_create_message function called from 'sendMessage' in ChatConversationView is not working when there is an emoji inside the message.

`LinphoneChatMessage *msg = linphone_chat_room_create_message(_chatRoom, [message UTF8String]);`
Gives the error:
**Error while converting a string from 'locale' to 'UTF-8': Illegal byte sequence**

![screen shot 2018-10-01 at 11 51 37 am](https://user-images.githubusercontent.com/8821449/46281938-77b28f80-c570-11e8-82ed-92534a227595.png)

**Comment by Valerio69** [comment]
I forgot to mention that my iOS version is 12.
The problematic line seems to be this one:
`ret = iconv(cd, &in_buf, &in_left, &out_buf, &out_left);`
inside the file charconv.cc

**Comment by kenfemus** [comment]
I found this problem on my device too (simulator not found this problem). I think it cause from bctoolbox.framework. I try to download liblinphone-ios-sdk-4.0.2 from http://www.linphone.org/technical-corner/liblinphone/downloads and replace bctoolbox.framework in project. It work for me.
