### ISSUE TITLE
push notifications not working in iOS 12 with Xcode 10

### ISSUE THREAD

**Issue by razin097** [BelledonneCommunications/linphone-iphone#478]
Hello, I have built an app using Xcode 9 for IOS 11. After updating to versions 10 and 12 respectively push notifications in the app stopped working. Nothing have been changed except deleting libstdc++6 in IOKit.framework. I suppose Xcode 10 builds the app incorrectly because pushes work for all others in my team who use ios 12 but haven't rebuilt the app using Xcode 10. App version is 4.0.1. 
What can it be?
Also linphone crashes in iOS 12 while calling on iPhone which is in mute mode.

**Comment by sivachirravuri** [comment]
Facing similar problem with xcode10 and ios 12. After terminating the application,   Registration is successful  after receiving PUSH  but not responding to INVITE sent from server. Application is not triggering registration when it is in background mode even after receiving PUSH.

**Comment by sivachirravuri** [comment]
HI 
Xcode: 10
IOS:12
APP:  Linphone iOS 4.0.1-102-g397e8d11
          Linphone Core 3.12.0-gf319f5cf1

Attached is the log when the app is moved to background and push notification is received by the app.
Registration is not triggerered..


[log1.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/2449857/log1.txt)

Observation:  
1. linphone_core_is_network_reachable is returning 1 in background mode.


Please help

**Comment by sivachirravuri** [comment]
HI Everyuone..
 Any Update on this??
Please  post if anyone else has faced this issue?? Or Did I miss something or Did a mistake in running my app???

**Comment by chiragagrawal** [comment]
Hi Everyone,

We are also facing the same issue. After upgrading the xCode version to 10, the push notification service stopped working in iOS 12. Additionally, we are using FCM for sending notification and ionic as the framework.

Till the time Apple fixes the issue, can anybody help us with any possible workaround.

Thanks

**Comment by razin097** [comment]
Hello, Push notifications works is 4.0.2 version. Try: Settings -> Sip Account -> <Your username> -> more options -> push notifications. Notification Switch sets to "OFF" after account configuring.

**Comment by chiragagrawal** [comment]
I appreciate the quick response. I tried finding the above options and I am unable to find any such option. I am a novice, I might sound like a dumb but I tried finding it in iOS and xCode but could not find any such option. The notifications are turned on in Xcode.

**Comment by razin097** [comment]
I mean the settings in the app. Open Linphone on your iphone -> Side menu -> Settings -> Sip Account -> "your username" -> more options -> push notifications

**Comment by sivachirravuri** [comment]
Hi
 Tested this with 4.0.2 version . APP is killed and phone is locked.  Registration is received in the server(I am using Kamailio)  after receiving the push notification. But there is no  answer for the SIP INVITE received there after. Kamailio is sending SIP INVITE to the proper port received in the new Registration.

One more thing is, the same app is not responding even for the regular Invite that is sent when it is in foregound.  Same app works in this scenario when the Push notification is turned off in settings. 

Please help..
Siva

**Comment by bhrugumehta** [comment]
May be you should check with LinphoneCore

**Comment by shdaro** [comment]
> HI
> Xcode: 10
> IOS:12
> APP: Linphone iOS 4.0.1-102-g397e8d11
> Linphone Core 3.12.0-gf319f5cf1
> 
> Attached is the log when the app is moved to background and push notification is received by the app.
> Registration is not triggerered..
> 
> [log1.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/2449857/log1.txt)
> 
> Observation:
> 
>     1. linphone_core_is_network_reachable is returning 1 in background mode.
> 
> 
> Please help

Did you able to solve the issue? If so could you please share the solution?

**Comment by Trushangpatel** [comment]
Hello,

I will resolve this issue from voip silent push notification.
if you need help then mail me: trushangpatel3993@gmail.com, add subject: linphone issue

Thanks
