### ISSUE TITLE
iPhone 7 and 8 Crash on incoming call about 3 seconds into the 1st ring

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#479]
On iPhone 7 or 8 updated to iOS 12 --- I have noticed the app drops the incoming call on the first ring, however this app works on iPhone X and 6s plus 

it also reads iPhone 9 in the debug logs 
please assist

**Comment by S0U1SB4N3** [comment]
this crash occurs when the hardware switch silent is turned on.

**Comment by ReisBenjamin** [comment]
Can you post the stack trace ?
Crash during calls has been fixed recently.

Thanks

**Comment by S0U1SB4N3** [comment]
ill see what I can get as its a friends phone who's having the issue

**Comment by S0U1SB4N3** [comment]
okay my friend downloaded your app thats in the app store currently ands an iPhone 7s plus  on iOS12 (the switch on the side of the phone by the up volume key is switched ON) the call flashes on the screen then closes the the app stays loaded but the call is dropped as if it just skips the call. 
the switch is in the OFF position the call rings the phone no problem 

you should be able to replicate this as it happened on the iPhone 8 as well , I have the iPhone 6 s plus and a iPhone X for testing and they both work just fine.

**Comment by llemtt** [comment]
I can confirm that it happens also on my freshly updated iPhone 5s

**Comment by llemtt** [comment]
4.0.2 fixed for me!

**Comment by S0U1SB4N3** [comment]
PLEASE CLOSE THIS

**Comment by dmpanch** [comment]
Same issue on iPhone 6s iOS 12.1.3 when volume key is switches OFF.
