### ISSUE TITLE
Getting Started Step 3

### ISSUE THREAD

**Issue by adamooo777** [BelledonneCommunications/linphone-iphone#48]
Hi Guys,
I got stucked once trying to install the prepare.py. The following error message occurs. Can you please help? :) 
Happy Easter!

ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running: git submodule sync && git submodule update --init --recursive

**Comment by bagage** [comment]
Did you try it? Running:

`git submodule sync && git submodule update --init --recursive`

**Comment by adamooo777** [comment]
I think I passed STEP 3 and now I a stucked with STEP 5.

I get the same error. This time that command line didn't work out. Any other suggestion to build the SDK?

"ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive"

**Comment by bagage** [comment]
How did you get the project?

Can you run `ls` and `ls submodules/cmake-builder/`?

**Comment by bagage** [comment]
Please reopen if still needed.

**Comment by babumoshai-ankush** [comment]
I am also getting error -
Before me another developer work on my project, but now I checked IPv6 is not supporting the previous SDK. Video call is not establishing in IPv6. I am trying to upgrade the SDK and the rest of the project would be as it is. I have merge with the new version on git and updated submodules by 

```
$ git merge master
$ git submodule sync && git submodule update --init --recursive
```

After that when I am tring to buid the SDK by the following commad getting error. -
```
$ ./prepare.py -c

./prepare.py -c
Traceback (most recent call last):
  File "./prepare.py", line 93, in 
    class IOSPreparator(prepare.Preparator):
AttributeError: 'module' object has no attribute 'Preparator'

```
