### ISSUE TITLE
Problem with xcode 10 

### ISSUE THREAD

**Issue by sambo-visal** [BelledonneCommunications/linphone-iphone#480]
I was trying to run the app which it throws me error

Undefined symbols for architecture x86_64:
"std::_List_node_base::unhook()", referenced from:
  std::list<Linphone::Conference::Participant, 
std::allocator<Linphone::Conference::Participant> 
liblinphone.a(conference.cc.o)
"std::_List_node_base::hook(std::_List_node_base*)", referenced from:
  Linphone::Conference::addParticipant(_LinphoneCall*) in 
liblinphone.a(conference.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can someone solve this problem?
Xcode 10 removed support for -lstdc++
Then i i just removed that library and added new library libc++ instead and then this error occur.

**Comment by erlaha95** [comment]
Try this https://github.com/Kila2/libstdc-.6.0.9.tbd
Really helped me

**Comment by SamboVisal** [comment]
@erlaha95  Don't you mind guide me the step please?

**Comment by SamboVisal** [comment]
@erlaha95  i have followed all the step. But it still return me that error. Is there any solution?

**Comment by SamboVisal** [comment]
I just removed lstdc++ and then i followed all the step that you just provided me link and still return me error. After i have copied to all those directory and i just relaunched my project and cleaned my project for several times, but still it return me error...

**Comment by erlaha95** [comment]
@SamboVisal have you tried to clean the DerivedData folder?

**Comment by SamboVisal** [comment]
@erlaha95  Yes sir! I also clean everything in that folder as well

**Comment by S0U1SB4N3** [comment]
what version of nasm and python is linphone 4 built on ? im getting script errors now and I believe its something related to using newer versions of nasm or python.

**Comment by mhisham** [comment]
> I just removed lstdc++

If you removed it from the project  (Link Binary with Libraries) please add it again you don't need to remove anything.

Just follow the instructions as @erlaha95 said from https://github.com/Kila2/libstdc-.6.0.9.tbd
and it will compile without any issues

**Comment by SamboVisal** [comment]
If i don't remove that library and still it throws me this error
`ld: library not found for -lstdc++.6
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

NOTE: I also have followed [https://github.com/Kila2/libstdc-.6.0.9.tbd](https://github.com/Kila2/libstdc-.6.0.9.tbd)

**Comment by SamboVisal** [comment]
Only thing that can solve my problem, i deleted Xcode 10. and re-download Xcode 9.4. ;(
