### ISSUE TITLE
How to deregister sip registration and prevent auto registration on app restart?

### ISSUE THREAD

**Issue by gauravlnx** [BelledonneCommunications/linphone-iphone#482]
Hi,

I am working on an App which has a user login functionality. Users can perform VoIP call after they log in. After the user logs out, I want to unregister the sip registration. I am able to unregister the sip but after app restart, I am calling `[[LinphoneManager instance] startLinphoneCore]` which causes the sip registration again. This is an issue I am facing because in this case SIP registration is happening even if the user is not logged in.

The basic flow of the app is:
1. The app starts and calls `[[LinphoneManager instance] startLinphoneCore]`
2. After user logs in, I get the SIP details like domain, username, and password which is then used to configure linphone.
3. On app restart linphone performs sip registration
4. On logout, sip is unregistered

The code I am using to unregister on logout is:
```
// Get the default proxyCfg in Linphone
    LinphoneProxyConfig* proxyCfg = linphone_core_get_default_proxy_config([LinphoneManager getLc]);
    
    // To unregister from SIP
    linphone_proxy_config_edit(proxyCfg);
    linphone_proxy_config_enable_register(proxyCfg, FALSE);
    linphone_proxy_config_done(proxyCfg);
    
    while(linphone_proxy_config_get_state(proxyCfg) !=  LinphoneRegistrationCleared){
        linphone_core_iterate([LinphoneManager getLc]); /*to make sure we receive call backs before shutting down*/
        ms_usleep(50000);
    }
```

I believe I have to clear out the sip configuration so that linphone cannot register again unless a new configuration is provided. But I don't know how to do that. I am new to Linphone and SIPs.

Any help will be appreciated. Thanks

**Comment by eliburke** [comment]
Last time I looked closely at the SDK it was "helpfully" writing the proxy and auth info into its RC file. Enable/disable registration is not saved; it's a run time property. Here is my connect and disconnect code, as an alternate example to what Linphone-iphone provides. It is Swift (I assume you are using objective C) but you should be able to follow along:

    func connectAccount(voiceNumber: String, password: String, domain: String, server: String) -> Bool {

        guard !voiceNumber.isEmpty, !password.isEmpty, !domain.isEmpty, !server.isEmpty else {
            DDLogError("connectAccount: bad parameter")
            return false
        }
        
        guard let localAuthInfo = linphone_auth_info_new(voiceNumber, nil, password, nil, domain, server) else {
            DDLogError("connectAccount: Can't create authInfo: \(voiceNumber)@\(domain) -> \(server)")
            return false
        }
        
        guard let localProxyCfg = linphone_core_create_proxy_config(linphoneCore) else {
            DDLogError("connectAccount: Can't create proxy config: \(voiceNumber)@\(domain) -> \(server)")
            return false
        }

        // set a header indicating that ZRTP is supported
        linphone_proxy_config_set_custom_header(localProxyCfg, "X-ZRTP", "1")
        
        let addr = linphone_address_new(nil)
        linphone_address_set_username(addr, voiceNumber)
        linphone_address_set_domain(addr, domain)
        linphone_proxy_config_set_identity_address(localProxyCfg, addr)
        linphone_address_unref(addr)
        
        // Set transport
        var transports = LinphoneSipTransports()
        linphone_core_get_sip_transports(linphoneCore, &transports)
        let components = server.components(separatedBy: ":")
        let serverAddr = "sip:\(components[0])"
        guard let lpAddress = linphone_address_new(serverAddr) else {
            DDLogError("Can't create linphone_address: \(serverAddr)")
            return false
        }

        if transports.udp_port > 0 {
            linphone_address_set_transport(lpAddress, LinphoneTransportUdp)
        } else if transports.tcp_port > 0 {
            linphone_address_set_transport(lpAddress, LinphoneTransportTcp)
        } else if transports.dtls_port > 0 {
            linphone_address_set_transport(lpAddress, LinphoneTransportDtls)
        } else {
            linphone_address_set_transport(lpAddress, LinphoneTransportTls)
        }
        
        let serverAndRoute = linphone_address_as_string_uri_only(lpAddress)
        linphone_proxy_config_set_server_addr(localProxyCfg, serverAndRoute)
        linphone_proxy_config_set_route(localProxyCfg, serverAndRoute)
        ortp_free(serverAndRoute)
        linphone_address_unref(lpAddress)
        
        let regExpire = UserDefaults.standard.integer(forKey: AppDefaults.registrationExpireTimeout.rawValue)
        if regExpire > 0 {
            linphone_proxy_config_set_expires(localProxyCfg, Int32(regExpire))
        } else {
            linphone_proxy_config_set_expires(localProxyCfg, Int32(LINPHONE_DEFAULT_REG_EXPIRE))
        }
                
        linphone_core_add_auth_info(linphoneCore, localAuthInfo)
        linphone_core_add_proxy_config(linphoneCore, localProxyCfg)
        linphone_core_set_default_proxy_config(linphoneCore, localProxyCfg)
        
        // start registering. note that this is automatically undone by linphone_core_remove_proxy_config
        linphone_proxy_config_enable_register(localProxyCfg, 1)
        
        authInfo = localAuthInfo
        proxyCfg = localProxyCfg

        return true
    }
    
    // deactivate registered account
    func disconnectAccount() {
        if let proxyCfg = proxyCfg {
            linphone_core_remove_proxy_config(linphoneCore, proxyCfg)
            self.proxyCfg = nil
        }
        if let authInfo = authInfo {
            linphone_core_remove_auth_info(linphoneCore, authInfo)
            self.authInfo = nil
        }
    }
