### ISSUE TITLE
Voice Audibility Issue after 6 Seconds in the call while using 3.16.5 Linphone-iPhone

### ISSUE THREAD

**Issue by mounikakrify** [BelledonneCommunications/linphone-iphone#484]
Dialler wasn’t able to hear the voice from the receiver after 6 sec until the receiver keeps the call on hold for a sec (Dialler needs to hear the call on hold ringtone) and unhold

1. Suppose a Person B receives a audio call from Person A
2. Person B answers the call and able to hear the voice of Person A for 6 secs. 
3. Person A was not able to hear anything after that until Person B puts the call on hold for a sec and uphold the call  (Person A needs to hear the waiting ringtone while he was kept on hold)

But when I'm using version 4.0.1 for both Dailer and Receiver can able to seek more than 6 seconds with out voice issue. Can you please explain me where is the issue.

**Comment by mhisham** [comment]
I have the same issue,

I think it's related to xcode 10
because I tried to build old linphone project was working fine, but when I build it on xcode 10 the issue happen

and as u said I have to pause and resume the call again to make it work fine.

**Comment by mounikakrify** [comment]
Hi Mhisham,
Thanks for the reply.
We are facing this audio issue when we compile the linphone 3.16.5 version in xcode 9. 

What is the version you are referring to when you said that " old project was working fine" ?

Are you able to execute 3.16.5 Linphone-iphone code in Xcode10 ?

**Comment by mhisham** [comment]
Hi Mounika,
Thank you for supporting me and make me feel I'm not alone in that issue 🔢 
Actually, I'm using Cocoapod version 3.16.5 and upgrading now to 3.99.7 to check if the same issue exists or not.

in the old project it's 3.12.0-222-g145b05ee8

Yes, I executed 3.16.5 Linphone-iphone code in XCode 10, I found 1 issue and solved it.

**Comment by mounikakrify** [comment]
Hi Mhisham,

in Xcode10 which issue you were faced and how do you solved it?

**Comment by mhisham** [comment]
that issue #480

**Comment by mhisham** [comment]
BTW I tried 4.0.1 but issue still exist i have to hold the call and un-hold again in incoming call
