### ISSUE TITLE
receive calls to ios 12

### ISSUE THREAD

**Issue by IpHuu** [BelledonneCommunications/linphone-iphone#487]
I do not receive calls to ios 12, how to fix the error?

**Comment by GlacierSecurityInc** [comment]
probably same issue as #488 and could be related to: https://forums.developer.apple.com/thread/108785

**Comment by GlacierSecurityInc** [comment]
Looks like this was fixed Sept 29 and released in 4.0.2. Just update. This ticket should probably be marked as closed.
