### ISSUE TITLE
Register to a specify server port?

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#49]
Hi.

Because our servers do not use 5060 port for some reasons, I have to modify the default proxy port. But in assistant view if I add a port following domain Linphone will crash immediately on:
linphone_account_creator_configure(account_creator);

is it meant to be like that?

Thank you.

**Comment by bagage** [comment]
No it's not, thanks for sharing this out. I'll provide a fix and let you know when it's done.

**Comment by bagage** [comment]
Fixed in commit 7e57f2f4cf2ff76590529294261196a86f7b39bf
