### ISSUE TITLE
Error while denable FFMPEG

### ISSUE THREAD

**Issue by minkwon14** [BelledonneCommunications/linphone-iphone#496]
Hi,
I was trying to enable FFMPEG but ended up with error. I have clone from latest git and I could successfully build without enabling FFMPEG.

**I used command following:**
./prepare.py -c  && ./prepare.py -DENABLE_GPL_THIRD_PARTIES=YES -DENABLE_FFMPEG=YES && make

**I got error as followings:**
License: LGPL version 2.1 or later
Creating config.mak, config.h, and doc/config.texi...

WARNING: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/../../usr/bin/pkg-config not found, library detection may fail.
[ 16%] Forcing build for 'EP_ffmpeg'
[ 17%] Performing build step for 'EP_ffmpeg'
/Users/enguser/Desktop/LinGit/linphone-iphone/submodules/externals/ffmpeg/libavutil/arm/asm.S:44:9: error: unknown directive
        .arch armv7-a
        ^
/Users/enguser/Desktop/LinGit/linphone-iphone/submodules/externals/ffmpeg/libavutil/arm/asm.S:57:9: error: unknown directive
        .fpu neon
        ^
make[4]: *** [libavcodec/arm/blockdsp_neon.o] Error 1
make[3]: *** [/Users/enguser/Desktop/LinGit/linphone-iphone/WORK/ios-armv7/Stamp/EP_ffmpeg/EP_ffmpeg-build] Error 2
make[2]: *** [CMakeFiles/EP_ffmpeg.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [armv7-build] Error 2

Let me know what I can do.
Thank you,

**Comment by AdilSoomro** [comment]
@minkwon14 Did you find the solution to this?

**Comment by minkwon14** [comment]
@AdilSoomro Yes, this is what I did.
1. Go to your project folder -> WORK -> ios-armv7 -> cmake
2. Open 'EP_ffmpeg_configure.sh'
3. Add "--disable-asm" at the bottom chunk of code

Now try to build again. It worked for me.

**Comment by AdilSoomro** [comment]
Okay, that's a considerable option. I've read that disabling asm may effect its performance ie  losing the assembly optimizations.

I'm going to try with Xcode 9.2, as suggested in similar issue thread for ffmpeg if that didn't workout, I'll try disabling the asm.

**Comment by AdilSoomro** [comment]
Just to update you. I tried with Xcode 9.2. It compiled fine.

1. Download Xcode 9.2 from apple downloads.
2. Select Xcode path for command line. ie `sudo xcode-select -s /Applications/Xcode_9.app/Contents/Developer/`
3. Do a clean `./prepare.py -c`.
4. Recompile including ffmpeg ie `./prepare.py arm64 armv7 x86_64 -DENABLE_NON_FREE_CODECS=ON -DENABLE_FFMPEG=ON`
5. Success.
