### ISSUE TITLE
Can't Send image through Chat

### ISSUE THREAD

**Issue by Dsonigara52** [BelledonneCommunications/linphone-iphone#498]
Hey Support Team,
I had tried to sending attachment files(Images) through the chat.
Its showing only progress indicator and failed showing resend option.
We set up an own server, i receiving attachment file(Image) but can't send.

**Comment by mahekkausar** [comment]
I recently have played around with linphone, and I successfully integrate it with my own server for call, and text message, However I am trying to config the sending image and it does not work at all.  how can I implement with my own server?
