### ISSUE TITLE
Compilation Error on Xcode 7

### ISSUE THREAD

**Issue by GuyKahlon** [BelledonneCommunications/linphone-iphone#5]
Hi, 

I try to launch Linphone for iPhone, I have download the last master branch version.
During the build process I get an error:

1. Install Xcode 7.0 from AppStore.
2. Install HomeBrew, a package manager for OS X.
3. Build SDK : ./prepare.py -c && ./prepare.py && make
An error occurred:

Guys-MacBook-Pro-2:LinPhoneiOS guykahlon$ ./prepare.py -c && ./prepare.py && make
 cmake /Users/guykahlon/Developer/LinPhoneiOS/submodules/cmake-builder -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/Users/guykahlon/Developer/LinPhoneiOS/liblinphone-sdk/x86_64-apple-darwin.ios -DCMAKE_INSTALL_PREFIX=/Users/guykahlon/Developer/LinPhoneiOS/liblinphone-sdk/x86_64-apple-darwin.ios -DLINPHONE_BUILDER_WORK_DIR=/Users/guykahlon/Developer/LinPhoneiOS/WORK/ios-x86_64 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-ios-x86_64.cmake -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-ios-x86_64.cmake -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/Users/guykahlon/Developer/LinPhoneiOS/submodules -G "Unix Makefiles"
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Using toolchain file '/Users/guykahlon/Developer/LinPhoneiOS/submodules/cmake-builder/toolchains/toolchain-ios-x86_64.cmake'
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/guykahlon/Developer/LinPhoneiOS/WORK/ios-x86_64/cmake/Autotools
-- Using configuration file '/Users/guykahlon/Developer/LinPhoneiOS/submodules/cmake-builder/configs/config-ios-x86_64.cmake'
CMake Error at configs/config-ios.cmake:78 (message):
  You need at least CMake version 3.3.20150815 but you are currently using
  3.3.2
Call Stack (most recent call first):
  configs/config-ios-x86_64.cmake:24 (include)
  CMakeLists.txt:69 (include)

-- Configuring incomplete, errors occurred!
See also "/Users/guykahlon/Developer/LinPhoneiOS/WORK/ios-x86_64/cmake/CMakeFiles/CMakeOutput.log".
Guys-MacBook-Pro-2:LinPhoneiOS guykahlon$ 

Can you assist please?

Thanks,
Guy

**Comment by bagage** [comment]
See the error:
> 
> You need at least CMake version 3.3.20150815 but you are currently using
> 3.3.2

You MUST have Cmake 3.3.20150815 or more to properly build linphone ios. CMake has no 3.4 release yet, so either you have to install it from sources, or wait for a new release to be available.

Cheers,

Gautier Pelloux-Prayer
Software Engineer @ Belledonne Communications

**Comment by GuyKahlon** [comment]
Hi,

Thanks for the help.

I have updated the Cmake, but now I have another problem:

fc3951ConfigVersion.cmake
[ 45%] Completed 'EP_libilbcrfc3951'
[ 45%] Built target EP_libilbcrfc3951
Scanning dependencies of target EP_vpx
[ 46%] Creating directories for 'EP_vpx'
[ 47%] No download step for 'EP_vpx'
[ 48%] No patch step for 'EP_vpx'
[ 48%] No update step for 'EP_vpx'
[ 49%] Performing configure step for 'EP_vpx'
  disabling shared
  enabling error_concealment
  enabling realtime_only
  enabling vp8
  disabling vp9
  disabling install_docs
  disabling debug_libs
  disabling examples
  disabling unit_tests
Configuring selected codecs
Configuring for target 'arm64-darwin-gcc'
  enabling arm64
  enabling neon
Toolchain is unable to link executables

Configuration failed. This could reflect a misconfiguration of your
toolchains, improper options selected, or another problem. If you
don't see any useful error messages above, the next step is to look
at the configure error log file (config.log) to determine what
configure was trying to do when it died.
make[3]: *** [/Users/guykahlon/Developer/LinPhoneiOS/WORK/ios-arm64/Stamp/EP_vpx/EP_vpx-configure] Error 1
make[2]: *** [CMakeFiles/EP_vpx.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all-arm64] Error 2



Thanks,
Guy

**Comment by bagage** [comment]
See http://lists.nongnu.org/archive/html/linphone-developers/2015-09/msg00029.html
Gautier Pelloux-Prayer
Software Engineer @ Belledonne Communications
