### ISSUE TITLE
Issue with lime

### ISSUE THREAD

**Issue by fbxcelsior** [BelledonneCommunications/linphone-iphone#50]
Hi,

There was a previous issue regarding lime where a device with lime enabled would crash when sending a message to another device. That is now fixed, but now I am unable to send messages between two devices with lime enabled. The "composing" notice appears, but the messages are not sent. 

This happens with the latest version. To replicate it is enough to set lime=1 and try to send a message.

Thank you.

Best regards,

Filipe

**Comment by bagage** [comment]
Did you do a secure call between them first? Then need to share ZRTP secrets first to have Lime working, otherwise they won't be able to decrypt messages.

**Comment by fbxcelsior** [comment]
That was it! Totally forgot that!

Thank you!
