### ISSUE TITLE
linphone sometimes crashes on destroyLinphoneCore 

### ISSUE THREAD

**Issue by surabhi20** [BelledonneCommunications/linphone-iphone#503]
I am unable to reproduce this issue, but this is what I am getting in logs. Can someone suggest what this crash log indicates?

0   linphone                        0x0000000102da2ac8 0x102c4c000 + 1403592 (LinphonePrivate::CallPrivate::onCallSessionSetTerminated(std::__1::shared_ptr const&) + 560)
1   linphone                        0x0000000102da2ac4 0x102c4c000 + 1403588 (LinphonePrivate::CallPrivate::onCallSessionSetTerminated(std::__1::shared_ptr const&) + 556)
2   linphone                        0x0000000102e28db0 0x102c4c000 + 1953200 (LinphonePrivate::CallSessionPrivate::setTerminated() + 100)
3   linphone                        0x0000000102e27b54 0x102c4c000 + 1948500 (LinphonePrivate::CallSessionPrivate::setState(LinphonePrivate::CallSession::State, std::__1::basic_string, std::__1::allocator > const&) + 1552)
4   linphone                        0x0000000102e3e1a4 0x102c4c000 + 2040228 (LinphonePrivate::MediaSessionPrivate::setState(LinphonePrivate::CallSession::State, std::__1::basic_string, std::__1::allocator > const&) + 124)
5   linphone                        0x0000000102e29048 0x102c4c000 + 1953864 (LinphonePrivate::CallSessionPrivate::terminate() + 132)
6   linphone                        0x0000000102e3feb0 0x102c4c000 + 2047664 (LinphonePrivate::MediaSessionPrivate::terminate() + 120)
7   linphone                        0x0000000102de7b28 0x102c4c000 + 1686312 (LinphonePrivate::CallSession::terminate(_LinphoneErrorInfo const*) + 816)
8   linphone                        0x0000000102de76c4 0x102c4c000 + 1685188 (LinphonePrivate::Call::terminate(_LinphoneErrorInfo const*) + 52)
9   linphone                        0x0000000102da5c2c 0x102c4c000 + 1416236 (LinphonePrivate::CorePrivate::uninit() + 76)
10  linphone                        0x0000000102da574c 0x102c4c000 + 1414988 (_linphone_core_uninit + 108)
11  linphone                        0x0000000102da56cc 0x102c4c000 + 1414860 (_linphone_Core_uninit(_LinphoneCore*) + 44)
12  linphone                        0x0000000102c542fc 0x102c4c000 + 33532 (belle_sip_object_delete + 232)
13  ChatSecureCore                  0x000000010175a840 0x10145c000 + 3139648 (-[LinphoneManager destroyLinphoneCore] + 384)
14  ChatSecureCore                  0x0000000101476df0 0x10145c000 + 110064 (-[ProviderDelegate provider:performEndCallAction:] + 1308)

**Comment by astuter** [comment]
I am having this issue as well for latest version of linphone and its reproducible every time.

**Comment by astuter** [comment]
Hi @ReisBenjamin ,

Following are the stacktrace of crash. Can you please look into this? 

```
#0	0x000000010672180c in has_type [inlined] at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/belle-sip/src/belle_sip_object.c:29
#1	0x0000000106721804 in belle_sip_object_cast [inlined] at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/belle-sip/src/belle_sip_object.c:471
#2	0x0000000106721800 in belle_sip_object_unref_2 at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/belle-sip/src/belle_sip_object.c:135
#3	0x00000001010326d8 in bctbx_list_free_with_data ()
#4	0x00000001066deba8 in _linphone_core_stop(_LinphoneCore*) at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/linphone/coreapi/linphonecore.c:6421
#5	0x00000001066defbc in ::_linphone_core_uninit(LinphoneCore *) at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/linphone/coreapi/linphonecore.c:6521
#6	0x00000001065138f4 in _linphone_core_destructor(_LinphoneCore*) [inlined] at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/linphone/src/c-wrapper/api/c-core.cpp:51
#7	0x00000001065138d8 in _linphone_Core_uninit(_LinphoneCore*) at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/linphone/src/c-wrapper/api/c-core.cpp:38
#8	0x0000000106721e20 in belle_sip_object_uninit at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/belle-sip/src/belle_sip_object.c:260
#9	0x0000000106721a00 in belle_sip_object_delete [inlined] at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/belle-sip/src/belle_sip_object.c:275
#10	0x00000001067219f8 in belle_sip_object_unref_2 at /Users/aniruddh/Documents/Linphone/4-1/linphone-sdk/belle-sip/src/belle_sip_object.c:166
#11	0x00000001004789c0 in -[LinphoneManager destroyLinphoneCore] at /Users/aniruddh/Documents/Linphone/linphone-iphone/Classes/LinphoneManager.m:2157
#12	0x0000000100478cb0 in -[LinphoneManager resetLinphoneCore] at /Users/aniruddh/Documents/Linphone/linphone-iphone/Classes/LinphoneManager.m:2178
#13	0x000000010049f9c8 in -[AssistantView resetLiblinphone:] at /Users/aniruddh/Documents/Linphone/linphone-iphone/Classes/AssistantView.m:158
#14	0x00000001004afa30 in __51-[AssistantView onRemoteProvisioningDownloadClick:]_block_invoke at /Users/aniruddh/Documents/Linphone/linphone-iphone/Classes/AssistantView.m:1597
#15	0x0000000197108688 in __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke ()
#16	0x000000019711c220 in __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke ()
#17	0x0000000197598f68 in __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ ()
#18	0x00000001974a5420 in -[NSBlockOperation main] ()
#19	0x00000001974a4908 in -[__NSOperationInternal _start:] ()
#20	0x000000019759acec in __NSOQSchedule_f ()
#21	0x00000001180d6e90 in _dispatch_block_async_invoke2 ()
#22	0x00000001180c8c74 in _dispatch_client_callout ()
#23	0x00000001180d66fc in _dispatch_main_queue_callback_4CF ()
#24	0x0000000196ac5ec0 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#25	0x0000000196ac0df8 in __CFRunLoopRun ()
#26	0x0000000196ac0354 in CFRunLoopRunSpecific ()
#27	0x0000000198cc079c in GSEventRunModal ()
#28	0x00000001c2f33b68 in UIApplicationMain ()
#29	0x00000001003e3da0 in main at /Users/aniruddh/Documents/Linphone/linphone-iphone/main.m:39
#30	0x00000001965868e0 in start ()
```
