### ISSUE TITLE
No Voice Communication when call is accepted using CallKit

### ISSUE THREAD

**Issue by SamboVisal** [BelledonneCommunications/linphone-iphone#509]
I was trying to make a call from extension 100(Linphone App) to 102(My application). The extension 102 has shown the incoming call screen and then clicked accept button and then, extension 100 starts to talk to extension 102 but extension 102 unable to hear anything from 100 and also extension 100 unable to hear from 102 as well.

I think the problem because of app. But i don't know what is wrong with my application.

     `  let callKitManager = CallKitCallInit(uuid: UUID(), handle: "")
    
    lazy var providerDelegate: ProviderDelegate = ProviderDelegate(callKitManager: self.callKitManager)
    
    
    func displayIncomingCall(uuid: UUID, handle: String, completion: ((NSError?) -> Void)?) {
        providerDelegate.reportIncomingCall(uuid: uuid, handle: handle, completion: completion)
    }`

These function above i declared in appdelegate in order to handle incoming call.

extension ProviderDelegate: CXProviderDelegate {
    
    func providerDidReset(_ provider: CXProvider) {
        print("Stop Audio ==STOP-AUDIO==")
        
        for call in callKitManager.calls {
            call.end(uuid: UUID())
        }
        
        callKitManager.removeAllCalls()
    }
    
    func provider(_ provider: CXProvider, perform action: CXAnswerCallAction) {
        // 1.
        guard let call = callKitManager.callWithUUID(uuid: action.callUUID) else {
            action.fail()
            return
        }
        // 2.
        configureAudioSession()
        // 3.
        call.answer()
        // 4.
        if #available(iOS 11, *) {
            print ("vKclub")
        } else {
            
            action.fulfill()
        }
        
    }
    
    func provider(_ provider: CXProvider, perform action: CXEndCallAction) {
        // 1.
        guard let call = callKitManager.callWithUUID(uuid: action.callUUID) else {
            action.fail()
            return
        }
        
        // 2.
        print("Stop audio ==STOP-AUDIO==")
        configureAudioSession()
        // 3.
        call.end(uuid: action.callUUID)
        // 4.
        if #available(iOS 11, *) {
            print("Our vKclube")
        } else {
            action.fulfill()
        }
        
        // 5.
        callKitManager.remove(call: call)
    }
    
    // 5.
    func provider(_ provider: CXProvider, didActivate audioSession: AVAudioSession) {
        print("Starting audio ==STARTING-AUDIO==")
    }
    
    
    func provider(_ provider: CXProvider, didDeactivate audioSession: AVAudioSession) {
        print("Received \(#function)")
    }
    
    func configureAudioSession() {
        let session = AVAudioSession.sharedInstance()
        do {
            try? session.setCategory(AVAudioSessionCategoryPlayAndRecord)
            try? session.setMode(AVAudioSessionModeVoiceChat)
            try? session.setPreferredSampleRate(44100.0)
            try? session.setPreferredIOBufferDuration(0.005)
            try? session.setActive(true)
        } 
        
    }
}

class ProviderDelegate: NSObject {
    // 1.
    fileprivate let callKitManager: CallKitCallInit
    fileprivate let provider: CXProvider
    
    init(callKitManager: CallKitCallInit) {
        self.callKitManager = callKitManager
        // 2.
        provider = CXProvider(configuration: type(of: self).providerConfiguration)
        
        super.init()
        // 3.
        provider.setDelegate(self, queue: nil)
    
    }
    
    // 4.
    static var providerConfiguration: CXProviderConfiguration {
        let providerConfiguration = CXProviderConfiguration(localizedName: "vKclub")
        
        providerConfiguration.supportsVideo = false
        providerConfiguration.maximumCallsPerCallGroup = 1
        providerConfiguration.supportedHandleTypes = [.phoneNumber]
        return providerConfiguration
    }
    
    func reportIncomingCall(uuid: UUID, handle: String, hasVideo: Bool = false, completion: ((NSError?) -> Void)?) {
        // 1.
        print("This is UUID === ", uuid)
        configureAudioSession()
        let update = CXCallUpdate()
        update.remoteHandle = CXHandle(type: .phoneNumber, value: handle)
        update.hasVideo = hasVideo
        
//        // 2.
        provider.reportNewIncomingCall(with: uuid, update: update) { error in
            
            
            if error == nil {
                // 3.
                self.configureAudioSession()
                let call = CallKitCallInit(uuid: uuid, handle: handle)
                self.callKitManager.add(call: call)
                lastCallUUID = uuid
                print("UUID === ", uuid)
            } else {
                
            }
            
            // 4.
            completion?(error as NSError?)
        }
        
        
    }
    
    
    
    
   
    

   
    

    
    
}

**Comment by phamhung159** [comment]
you can set if (![audioSession setActive:NO error:&err] && err) {  in startLinphoneCore() from NO To YES to solve this problem

**Comment by SamboVisal** [comment]
It works fine @phamhung159 . Thank you :D

**Comment by piyush-ebizz** [comment]
@SamboVisal , @phamhung159 . I am not using the Obj-C code. and not using startLinphoneCore() method. And getting this issue. Do you have any solution for this?
PS: when I mute and unmute after that the audio is audible to both parties.

**Comment by iOS38moon** [comment]
@piyush-ebizz :- I have same issue. Did you find any solution? Please reply me
