### ISSUE TITLE
BackGroundMode

### ISSUE THREAD

**Issue by bozog61** [BelledonneCommunications/linphone-iphone#51]
Hi guys

The Linphone code is work when background mode in simulator .We can see local push notification and received call but not working in real device . Why did not work real device?.

**Comment by bagage** [comment]
What's not working? Did you allowed push notifications?

**Comment by bozog61** [comment]
Yes allowed push notification in network where settings but real devices is not working.

**Comment by bozog61** [comment]
Yes allowed push notification in network where settings but real devices is not working. when app is background mode we cannot see any call notification .

**Comment by juiced** [comment]
Try using TCP, you are probably using UDP, which is not supported by Apple/iOS for use in background applications.

**Comment by bagage** [comment]
Closing since no response for a long time. Please reopen if needed.
