### ISSUE TITLE
Permission denied when cloning submodules branch 3.16.5.x

### ISSUE THREAD

**Issue by tdnguyen1006** [BelledonneCommunications/linphone-iphone#510]
Hi, I tried to clone branch 3.16.5.x with this command **git clone -b 3.16.5.x git://git.linphone.org/linphone-iphone.git --recursive**. However, some submodules cannot be cloned due to permission denied. I already tried **git submodule sync && git submodule update --init --recursive** but it didn't work. How can I clone these submodules for branch 3.16.5.x?

Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/Classes/KIF'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bcg729'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bcmatroska2'...
fatal: remote error: access denied or repository not exported: /bcmatroska2.git
fatal: clone of 'git://git.linphone.org/bcmatroska2.git' into submodule path '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bcmatroska2' failed
Failed to clone 'submodules/bcmatroska2'. Retry scheduled
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bctoolbox'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bcunit'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/belcard'...
remote: warning: unable to access 'info/attributes': Permission denied        
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/belle-sip'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/belr'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bzrtp'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/cmake-builder'...
fatal: remote error: access denied or repository not exported: /linphone-cmake-builder.git
fatal: clone of 'git://git.linphone.org/linphone-cmake-builder.git' into submodule path '/Users/tdnguyen/Desktop/linphone-iphone/submodules/cmake-builder' failed
Failed to clone 'submodules/cmake-builder'. Retry scheduled
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/antlr3'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/bv16-floatingpoint'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/codec2'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/ffmpeg'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/gsm'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/libjpeg-turbo'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/libvpx'...
remote: warning: unable to access 'info/attributes': Permission denied        
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/libxml2'...
fatal: unable to connect to git.gnome.org:
git.gnome.org[0: 209.132.180.180]: errno=Connection refused
git.gnome.org[1: 209.132.180.168]: errno=Connection refused

fatal: clone of 'git://git.gnome.org/libxml2' into submodule path '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/libxml2' failed
Failed to clone 'submodules/externals/libxml2'. Retry scheduled
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/mbedtls'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/opencore-amr'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/openh264'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/opus'...
remote: warning: unable to access 'info/attributes': Permission denied        
	Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/speex'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/srtp'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/vo-amrwbenc'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/externals/x264'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/linphone'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/mediastreamer2'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/msamr'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/mscodec2'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/msopenh264'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/mssilk'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/mswebrtc'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/msx264'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/ortp'...
Cloning into '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bcmatroska2'...
fatal: remote error: access denied or repository not exported: /bcmatroska2.git
fatal: clone of 'git://git.linphone.org/bcmatroska2.git' into submodule path '/Users/tdnguyen/Desktop/linphone-iphone/submodules/bcmatroska2' failed
Failed to clone 'submodules/bcmatroska2' a second time, aborting

**Comment by aquacode** [comment]
I am having this same issue after checking out 3.4.x branch and commit hash 9dc4f33605c82fd148ff57f27270deab3e68e7fe
This worked for me some months ago and I would like to generate a new AAR using the same exact code but only replacing the NDK version.
Could someone assist in fixing this `git submodule` issue or point to the correct branch/commit that can be used that has a fix?
