### ISSUE TITLE
Not receive voice 

### ISSUE THREAD

**Issue by Bhadresh4488** [BelledonneCommunications/linphone-iphone#521]
Not receive voice in iphone at call incoming & outgoing  
voice success out 

My Code implement:
if let ptG729 = linphone_core_find_payload_type(theLinphone.lc, "g729", 8000, -1) {
            linphone_core_enable_payload_type(theLinphone.lc, ptG729, 1);
        }
        if let ptGSM = linphone_core_find_payload_type(theLinphone.lc, "GSM", 8000, -1) {
            linphone_core_enable_payload_type(theLinphone.lc, ptGSM, 1);
        }
        if let ptPCMA = linphone_core_find_payload_type(theLinphone.lc, "PCMA", 8000, -1) {
            linphone_core_enable_payload_type(theLinphone.lc, ptPCMA, 1);
        }
        if let ptPCMU = linphone_core_find_payload_type(theLinphone.lc, "PCMU", 8000, -1) {
            linphone_core_enable_payload_type(theLinphone.lc, ptPCMU, 1);
        }
        if let ptH263 = linphone_core_find_payload_type(theLinphone.lc, "h263", 90000, 1) {
            linphone_core_enable_payload_type(theLinphone.lc, ptH263, 1);
        }

**Comment by AhmedShmmala** [comment]
@Bhadresh4488  did you able to resolve it ?
