### ISSUE TITLE
Force to use TURN only

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#530]
Can i force a linphone library to use TURN only? 
I see an options in network settings but after I set ICE off and set TURN on and also add username, password then make a new outgoing call. I still get a candidate type in as host only, no relay in INVITE.

**Comment by SarunyuPrasert** [comment]
@ReisBenjamin Can you guide me how to force using it?

**Comment by Muhammad-Ahad-Nawaz** [comment]
I am also facing issue with Turn media relay posted issue [here](https://github.com/BelledonneCommunications/linphone-iphone/issues/531)

**Comment by SarunyuPrasert** [comment]
@Viish Do you know how to force using it?

**Comment by krishnastvSMSC** [comment]
I am also facing the same issue.
Disable the TURN and STUN at settings, stil getting ice candidates in the SDP packets. How to resolve this.

Thanks

**Comment by basncy** [comment]
linphone doe NOT send turn request, according to my turnserver log.
while I can get turn relay log on server side with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/


#sed '/^#/d' turnserver.conf |grep -vE "^[[:blank:]]*$"
relay-device=eth0
min-port=10000
max-port=19999
fingerprint
lt-cred-mech
user=myuser:mypass
no-tcp
no-tls
no-dtls
log-file=/var/log/turnserver/turn.log
pidfile=/run/turnserver/turnserver.pid
