### ISSUE TITLE
Set DNS

### ISSUE THREAD

**Issue by demchenko2018** [BelledonneCommunications/linphone-iphone#539]
Hi

I can't understand how I can set DNS on swift 4-5.x syntaxes.

I want to set DNS is 8.8.8.8

linphone_core_set_dns_servers(theLinphone.lc, ...)

I need to help. How I can make this argm `bctbx_list_t *servers`

**Comment by showgoodjiang** [comment]
//Set DNS
    bctbx_list_t *dnsList = NULL;
    const char *dns1 = "8.8.8.8";
    const char *dns2 = "223.5.5.5";
    dnsList = bctbx_list_append(dnsList, (void*)dns1);
    dnsList = bctbx_list_append(dnsList, (void*)dns2);
    
    linphone_core_set_dns_servers(LC, dnsList);

**Comment by ShlomieRottenberg** [comment]
In Swift.
```
let server1 = UnsafeMutablePointer<Int8>(mutating: ("8.8.8.8" as NSString).utf8String)
let server2 = UnsafeMutablePointer<Int8>(mutating: ("223.5.5.5" as NSString).utf8String)
// Add more servers here.

var dnsList = bctbx_list_new(server1)
dnsList = bctbx_list_append(servers, server2)
// Repeat line above for all the servers you want

linphone_core_set_dns_servers(theLinphone.lc, dnsList)
```
