### ISSUE TITLE
Getting a lot of decoder errors on the caller side for the first 5-10 seconds of OpenH264 video

### ISSUE THREAD

**Issue by clawoo** [BelledonneCommunications/linphone-iphone#54]
I recently upgraded to the latest git version of linphone-iphone (f35ab9e) and noticed a significant amount of missing frames when beginning an OpenH264 video call on the caller side, sometimes 4, other times up to 10-15 seconds. I don't recall having this issue about two months ago when I last tested.

I noticed this behavior when initiating the call from a 4S or a 5S, but did not notice it when initiating the call from a 6S so maybe hardware has a part to play in it?

This is what OpenH264 is initialized with on the caller side:

> I/lib/[OpenH264] this = 0x0x138d441c0, Info:CWelsH264SVCEncoder::InitEncoder(), openh264 codec version = f35ab9e+M
>
> I/lib/[OpenH264] this = 0x0x138d441c0, Info:iUsageType = 0,iPicWidth= 480;iPicHeight= 640;iTargetBitrate= 1062100;iMaxBitrate= 1118000;iRCMode= 1;iPaddingFlag= 0;iTemporalLayerNum= 1;iSpatialLayerNum= 1;fFrameRate= 30.000000f;uiIntraPeriod= 300;eSpsPpsIdStrategy = 0;bPrefixNalAddingCtrl = 0;bSimulcastAVC=0;bEnableDenoise= 0;bEnableBackgroundDetection= 1;bEnableSceneChangeDetect = 0;bEnableAdaptiveQuant= 0;bEnableFrameSkip= 1;bEnableLongTermReference= 0;iLtrMarkPeriod= 30;iComplexityMode = 1;iNumRefFrame = 1;iEntropyCodingModeFlag = 0;uiMaxNalSize = 1240;iLTRRefNum = 0;iMultipleThreadIdc = 2;iLoopFilterDisableIdc = 0 (offset(alpha/beta): 0,0;iMaxQp = 51;iMinQp = 0)
>
> I/lib/[OpenH264] this = 0x0x138d441c0, Info:sSpatialLayers[0]: .iVideoWidth= 480; .iVideoHeight= 640; .fFrameRate= 30.000000f; .iSpatialBitrate= 1062100; .iMaxSpatialBitrate= 1118000; .sSliceArgument.uiSliceMode= 3; .sSliceArgument.iSliceNum= 0; .sSliceArgument.uiSliceSizeConstraint= 1240;uiProfileIdc = 66;uiLevelIdc = 0
>
> I/lib/[OpenH264] this = 0x0x138d441c0, Warning:ParamValidationExt(), slice mode = SM_SIZELIMITED_SLICE, uiSliceSizeConstraint = 1240 ,uiMaxNalsize = 1240, will take uiMaxNalsize!
>
> I/lib/[OpenH264] this = 0x0x138d441c0, Info:WelsInitEncoderExt() exit, overall memory usage: 9003079 bytes

And then I see a lot of these in the log:
> E/lib/OpenH264 decoder: DecodeFrame2 failed: 0x10
> I/lib/Request sending of PLI on videostream [0x138d05630]

Eventually this:
> E/lib/OpenH264 decoder: DecodeFrame2 failed: 0x24
> I/lib/Request sending of PLI on videostream [0x138d05630]
> E/lib/OpenH264 decoder: DecodeFrame2 failed: 0x20
> I/lib/Request sending of PLI on videostream [0x138d05630]

And then finally:
> I/lib/First video frame decoded successfully

Is anyone else experiencing this behavior? I can produce full logs from both sides of the convo if needed. Thanks!

**Comment by bagage** [comment]
Hi @clawoo, I'll experience with it on my side before next release, there may be regressions because we are now using latest version of openh264 (eg. git master version) to fix some builds issues (cf  #19). I'll update this issue on update.

**Comment by bagage** [comment]
We upgraded openH264 + added hardware accelerated h264; openh264 is not maintained anymore but please reopen if still subject to errors.
