### ISSUE TITLE
+390xxx is replaced with +39xxxx removing the zero and making an non valid numer

### ISSUE THREAD

**Issue by AnthillSudoku** [BelledonneCommunications/linphone-iphone#541]
Linphone 4.0.1 from f-droid
Android Kitkat 4.4.2

If I calling a number that has a zero after the international code, the zero is removed (tested only with +39)

+3904xx become +394xx that will be an non valid numer in Italy
same if I try 003904xx

calling the number 04xx without the international code works fine

Sincerely
Luca

**Comment by laris** [comment]
ditto

iOS 4.1 automatically remove 1, weird.
