### ISSUE TITLE
Linphone setup objetive C code  

### ISSUE THREAD

**Issue by viv578ek** [BelledonneCommunications/linphone-iphone#542]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AudioHelper", referenced from:
      objc-class-ref in LinphoneManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by viv578ek** [comment]
I have new setup to existing app  integrate linphone. I am setup to all process  off linphone manage but getting error when compile  


Undefined symbols for architecture x86_64:
"OBJC_CLASS$_AudioHelper", referenced from:
objc-class-ref in LinphoneManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hamzaozturk** [comment]
How did you integrate the linphone into your project? Using pods or manually?
