### ISSUE TITLE
How to Integrate linphone-sdk to my swift project 

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#547]
I cloned a linphone sdk project using this command.

"git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive"

Then I followed  a guide in readme to build linphone-sdk after enable some feature and using command 'cmake --build .' but after it done I can't find any .framework file.

In the previous method was using ./prepare.py to enable feature and build sdk but now I can't use it because of some error missing.

"fatal: No url found for submodule path 'Classes/KIF' in .gitmodules"

Could someone guide me how to build it. 
Thank you.

**Comment by bruce107** [comment]
how to slove it ? can you tell me, thank you

**Comment by SarunyuPrasert** [comment]
They use cmake to build a library. You can read a “README” in project to build it

**Comment by Rushabh5** [comment]
Hello @SarunyuPrasert,

There is no information in the README file so can you please explain?

Awaiting for your reply!

Thanks

**Comment by SarunyuPrasert** [comment]
After clone a project following this command 
"git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive"
Then "cd linphone-sdk" to go to a project path.
Then "mkdir build && cd build" to create folder and get in.
Then "cmake .. -DLINPHONESDK_PLATFORM=IOS" to config a building as iOS platform.
Using "ccmake .." to enable or disable an building option.
Then "cmake --build ." to build an sdk.

**Comment by Rushabh5** [comment]
> After clone a project following this command
> "git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive"
> Then "cd linphone-sdk" to go to a project path.
> Then "mkdir build && cd build" to create folder and get in.
> Then "cmake .. -DLINPHONESDK_PLATFORM=IOS" to config a building as iOS platform.
> Using "ccmake .." to enable or disable an building option.
> Then "cmake --build ." to build an sdk.

Thank you so much @SarunyuPrasert It's working fine but I am stuck at last command can you please show the attached log file.

In that getting error while I am using the last command.
[log.docx](https://github.com/BelledonneCommunications/linphone-iphone/files/3807790/log.docx)

**Comment by SarunyuPrasert** [comment]
I haven't tested on a latest update. It might be a feature that you enable. Have you tried to build it with the original settings?

**Comment by Rushabh5** [comment]
Yes, @SarunyuPrasert I have checked with original settings.

**Comment by SarunyuPrasert** [comment]
Have yo tried to clone a project on a release/4.2 branch and build it?

**Comment by Rushabh5** [comment]
Yes, I have downloaded 4.2 build.

**Comment by Rushabh5** [comment]
Which file will be generated after all steps can you please tell me?

**Comment by jacobdeepak10** [comment]
After cmake --build . 
What to do to run the sample ios project if i run i get .h fill missing error
