### ISSUE TITLE
Build error, targeted OS version does not support

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#553]
I clone a project using
"git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive"

Then I followed a guide in readme file to build my local linphone sdk
1. mkdir build && cd build
2. cmake .. -DLINPHONESDK_PLATFORM=iOS
3. cmake --build . 

And i get this error

ld: targeted OS version does not support use of thread local variables in _linphone_logging_service_get_current_callbacks for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[8]: *** [src/linphone.framework/linphone] Error 1
make[7]: *** [src/CMakeFiles/linphone.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS/linphone-sdk/build/WORK/ios-x86_64/Stamp/EP_linphone/EP_linphone-build] Error 2
make[4]: *** [CMakeFiles/EP_linphone.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ios-x86_64-prefix/src/ios-x86_64-stamp/ios-x86_64-build] Error 2
make[1]: *** [CMakeFiles/ios-x86_64.dir/all] Error 2
make: *** [all] Error 2

How can i fix it without disable build option for x86_64 architecture.
Thank you.

**Comment by SarunyuPrasert** [comment]
@Viish Do you know how to fix it?

**Comment by Viish** [comment]
What version of XCode are you using ? Which iOS version do you target ?
We build every night the SDK for iOS (even for x86_64) and it compiles.

**Comment by SarunyuPrasert** [comment]
My XCode version is 10.2.1
I don't know an iOS version target i've just followed a step in a README guide to build sdk.

**Comment by SarunyuPrasert** [comment]
Now. I can build it. I have to put -b release/4.2 when using git clone
