### ISSUE TITLE
Can't compile the linhpone-iphone using local sdk

### ISSUE THREAD

**Issue by chathu123adi** [BelledonneCommunications/linphone-iphone#555]
I have built the local sdk according to readme file in it. This is how i build the local sdk

- git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive

- inside the cloned folder i have make a folder called build.

- inside that build folder i have executed this command, And it built with no error
     cmake .. -DLINPHONESDK_PLATFORM=IOS -DENABLE_G729=ON -DENABLE_SILK=ON

But after that when i download the linphone-iphone code and run this command to build the project using local sdk,

PODFILE_PATH=/Users/macuser/Desktop/kani/Vinota\ Latest\ -\ 2019-06-20/linphone-iphone pod install

error saying,
[!] No podspec found for `linphone-sdk` in `/Users/macuser/Desktop/kani/Linphone Local SDK/linphone-sdk`

can some one give the proper guid for this.

**Comment by ChenDanmei** [comment]
Hi, 

Can you find the file linphone-sdk.podspec in your build folder ?
PODFILE_PATH means the reporsitory of your build folder, which includes the linphone-sdk and podspec file.

**Comment by Rushabh5** [comment]
Hey @ChenDanmei,

Can you please explain in detail i have successfully completed the below step for configuring linphone-SDK but after that what will be doing i don't understand.

After clone a project following this command
"git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive"
Then "cd linphone-sdk" to go to a project path.
Then "mkdir build && cd build" to create folder and get in.
Then "cmake .. -DLINPHONESDK_PLATFORM=IOS" to config a building as iOS platform.
Using "ccmake .." to enable or disable an building option.
Then "cmake --build ." to build an sdk.

Your early reply is highly appreciated.

Thanks

**Comment by alekyaios** [comment]
Hi @Rushabh5 ,

I'm stuck with the same issue.Did you find any workarounds?
