### ISSUE TITLE
Version 4.1.1 no Audio Codec G729

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-iphone#557]
Hi , i have used the source of linphone android version 4.1.1 but i cannot find audio codec G729 all over internet are the methods at compile time command execution but new source of 4.1.1 download the library while in android studio . 

in this scenario how will i be able to enable Audio Codec G729 in linphone-android 4.1.1

Thanks

**Comment by shraddha-patel-1891** [comment]
@Adnan-addi 
have you got any solution? I have the same problem.

**Comment by Adnan-addi** [comment]
No ! , I have moved back to old version where codec G729 is by default enabled .
if you Really want to enable G729 in Latest version of linphone than you have to manually add it in the library and use it , 
but i am afraid that will cause a problem in other functionalities . :-)

**Comment by shraddha-patel-1891** [comment]
@Adnan-addi
Does it mean G729 is not a free codec?Right

**Comment by Adnan-addi** [comment]
its free 
https://stackoverflow.com/questions/14972124/how-to-enable-g729-in-linphone-android
you have to rebuild the project . i was not successful in this , so revert back to old version 3.3.2 and its working fine over there :-)

**Comment by shraddha-patel-1891** [comment]
@Adnan-addi 
ok, thank you i will try with an old version.

**Comment by Adnan-addi** [comment]
Your Welcome
All The Best...!

**Comment by shraddha-patel-1891** [comment]
@Adnan-addi 

we have tried to enable g729 in new version of linphone but it give me following error :
**Codec G729/8000 fmtp=[annexb=yes] number=18, default enablement: 16) added to the list of possible codecs.
Codec G729/8000 read from conf is not supported by mediastreamer2, ignored.**

so can you please help me related to g729?
Thank you

**Comment by Mukesh2310** [comment]
@Adnan-addi

Can you please help me out, How to enable G729 audio codec in linphone 4.3.0 SDK
please i am in trouble from a couple of days your help must need hope you understand?

**Comment by Adnan-addi** [comment]
@Mukesh2310  Your need to build local sdk read their readme.md file and it all there , 
you need to build local sdk and than use it in the android or ios app

**Comment by Mukesh2310** [comment]
*Linphone 4.4.0 build steps as per below mention*

Build dependencies Need to required setup in Linux
------------------------------------------------------------------
Common to all target platforms
The following tools must be installed on the build machine:

cmake >= 3.6
python = 2.7 (python 3.7 if C# wrapper generation is disabled)
pip
yasm
nasm
doxygen
Pystache (use pip install pystache)
six (use pip install six)

- Download the latest linphone-sdk
$ git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git -- recursive

- Successfully Android SDK download after below mention command execute
$ mkdir build
$ cd build

$ export ANDROID_HOME=$HOME/Android/Sdk && export PATH=$PATH:$ANDROID_HOME/tools && export PATH=$PATH:/opt/android-sdk/ndk-bundle

$ cmake .. -DLINPHONESDK_PLATFORM:STRING=Android -DLINPHONESDK_ANDROID_ARCHS="arm64, armv7, x86_64, x86" -DENABLE_G729=YES -DENABLE_G729B_CNG=YES -DENABLE_VCARD=OFF -DENABLE_ILBC=OFF -DENABLE_SILK=OFF -DENABLE_ISAC=OFF -DENABLE_MKV=OFF -DENABLE_GSM=OFF -DENABLE_DOC=OFF -DENABLE_UNIT_TESTS=OFF -DENABLE_LIME=OFF -DENABLE_GPL_THIRD_PARTIES=OFF -DENABLE_NON_FREE_CODECS=OFF

$ cmake --build .

- Successfully build generate after go to linphone-sdk/build/maven_repository/org/linphone/linphone-sdk-android/4.4.0-alpha.221+1d24dfa/linphone-sdk-android-4.4.0-alpha.221+1d24dfa.aar

- linphone-sdk-android-4.4.0-alpha.221+1d24dfa.aar this file import in android-studio and sync the project as per below mention steps

1)File -> New -> New Module -> Import .jar/.aar and import your .aar.

2)Then in your project’s build.gradle (the one under ‘app’) add the following:

dependencies {
compile project(':linphone-sdk-android-4.4.0-alpha.221+1d24dfa.aar')
}

3)Clean Build after all the above steps.

**Comment by vadherjitu** [comment]
Super brother its helps me lot ..thanks for save mine and others time thanks you so much....

**Comment by shraddha-patel-1891** [comment]
@Mukesh2310 
Please help me for ios i want to build linphone for ios using mac.

Thank you.

**Comment by Mukesh2310** [comment]
@shraddha-patel-1891 

wait for few days one of my friend doing same once he done i will let u know the steps for sure

**Comment by RaviMalviya** [comment]
Use [this](https://stackoverflow.com/questions/29361502/integrate-linphone-in-own-ios-project/63938650#63938650) link explain linphone sdk compile process with codec g729.
