### ISSUE TITLE
Linphone Call State changed

### ISSUE THREAD

**Issue by ibrahimdn** [BelledonneCommunications/linphone-iphone#563]
`let callStateChanged: LinphoneCoreCallStateChangedCb = {
    (lc: Optional<OpaquePointer>, call: Optional<OpaquePointer>, callSate: LinphoneCallState,  message: Optional<UnsafePointer<Int8>>) in
    
    switch callSate{
    case LinphoneCallStateIncomingReceived: /**<This is a new incoming call */
        NSLog("callStateChanged: LinphoneCallIncomingReceived")
        
        if answerCall{
            ms_usleep(3 * 1000 * 1000); // Wait 3 seconds to pickup
            linphone_core_accept_call(lc, call)

        }
        
    case LinphoneCallStateStreamsRunning: /**<The media streams are established and running*/
        NSLog("callStateChanged: LinphoneCallStreamsRunning")
        
    case LinphoneCallStateError: /**<The call encountered an error*/
        NSLog("callStateChanged: LinphoneCallError")
        
    default:
        NSLog("Default call state")
    }
}`

Ihi, I want to show you whether the user is talking on the phone.

**Comment by hamzaozturk** [comment]
```

**Comment by hamzaozturk** [comment]
You can check the current call. Just write the code below where you want to show whether the user is talking on the phone or not.
```
if let currentCall = linphone_core_get_current_call(lc) {
      // There is an ongoing call so you can access it.
} else {
     // There is no call
}
```
