### ISSUE TITLE
Unable to checkout 'cb264a3ee7790edad4e9927a547a87a7886491eb' in submodule path 'submodules/bcg729'

### ISSUE THREAD

**Issue by ericeche** [BelledonneCommunications/linphone-iphone#57]
Submodule path 'submodules/mssilk': checked out '2af360002ccf2a0e30c48aec9498b2bfd23fcd2c'
Cloning into 'submodules/mswebrtc'...
remote: Counting objects: 324, done.
remote: Compressing objects: 100% (285/285), done.
remote: Total 324 (delta 167), reused 0 (delta 0)
Receiving objects: 100% (324/324), 74.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (167/167), done.
Checking connectivity... done.
fatal: reference is not a tree: 4cbe59460ebcd5293b6ee5a205d20c8b6e46d868
Cloning into 'submodules/msx264'...
remote: Counting objects: 319, done.
remote: Compressing objects: 100% (244/244), done.
remote: Total 319 (delta 162), reused 142 (delta 69)
Receiving objects: 100% (319/319), 64.93 KiB | 0 bytes/s, done.
Resolving deltas: 100% (162/162), done.
Checking connectivity... done.
Submodule path 'submodules/msx264': checked out 'e9e6b60172291a705c9f3be0b72a46686099ffbc'
Unable to checkout 'cb264a3ee7790edad4e9927a547a87a7886491eb' in submodule path 'submodules/bcg729'
Unable to checkout 'e330dbd9812005eb418f53ac5e5f9e29726eae42' in submodule path 'submodules/bzrtp'
Unable to checkout '7b6bf08ea8c45dbc10b27a78dbcde919ef88cfd0' in submodule path 'submodules/linphone'
Unable to checkout 'c41e7bf746575d060245785231c151243537d486' in submodule path 'submodules/msilbc'
Unable to checkout 'c622597e45dc7885bb82afbeee6f70da50d7e6f1' in submodule path 'submodules/msopenh264'
Unable to checkout '4cbe59460ebcd5293b6ee5a205d20c8b6e46d868' in submodule path 'submodules/mswebrtc'

Any help will be greatly appreciated

**Comment by ericeche** [comment]
Dildorf:eloquence-communicator ericecheverri$ git submodule update --init --recursive
fatal: reference is not a tree: cb264a3ee7790edad4e9927a547a87a7886491eb
fatal: reference is not a tree: e330dbd9812005eb418f53ac5e5f9e29726eae42
fatal: reference is not a tree: 7b6bf08ea8c45dbc10b27a78dbcde919ef88cfd0
fatal: reference is not a tree: c41e7bf746575d060245785231c151243537d486
fatal: reference is not a tree: c622597e45dc7885bb82afbeee6f70da50d7e6f1
fatal: reference is not a tree: 4cbe59460ebcd5293b6ee5a205d20c8b6e46d868
Unable to checkout 'cb264a3ee7790edad4e9927a547a87a7886491eb' in submodule path 'submodules/bcg729'
Unable to checkout 'e330dbd9812005eb418f53ac5e5f9e29726eae42' in submodule path 'submodules/bzrtp'
Unable to checkout '7b6bf08ea8c45dbc10b27a78dbcde919ef88cfd0' in submodule path 'submodules/linphone'
Unable to checkout 'c41e7bf746575d060245785231c151243537d486' in submodule path 'submodules/msilbc'
Unable to checkout 'c622597e45dc7885bb82afbeee6f70da50d7e6f1' in submodule path 'submodules/msopenh264'
Unable to checkout '4cbe59460ebcd5293b6ee5a205d20c8b6e46d868' in submodule path 'submodules/mswebrtc'

**Comment by ericeche** [comment]
Any help will be appreciated

**Comment by ericeche** [comment]
I need to point out that this branch is an old branch and I need to use this old branch from linphone

Thanks

**Comment by bagage** [comment]
Then you might run `git submodule sync && git submodule update --init --recursive`. But since some submodules are dead (libvpx, opus and such), you might not be able to retrieve them. Good luck!
