### ISSUE TITLE
Push notification not adding message in chat history 

### ISSUE THREAD

**Issue by tjramoliya** [BelledonneCommunications/linphone-iphone#571]
Hello,

I got notification for chat but when i tap on notification, it's redirect to chat history but i didn't get last message which i got in notification.

So can you guide me how to add in history or how to update chat history with all messages.

**Comment by benedictcontawe** [comment]
Hi me too I have the same problem as well

**Comment by AhmedShmmala** [comment]
@benedictcontawe 
@tjramoliya 
do you able to solve this ?
