### ISSUE TITLE
linphone_core_ensure_registered

### ISSUE THREAD

**Issue by TERMIK** [BelledonneCommunications/linphone-iphone#572]
I tried to compile the application, but I'm getting the error
<img width="758" alt="Screenshot 2019-09-02 at 18 36 23" src="https://user-images.githubusercontent.com/5457854/64124877-e4519200-cdb0-11e9-86db-718af6af873b.png">

**Comment by driesken** [comment]
I'm having the same issue.

**Comment by TERMIK** [comment]
Hm... I think, I've solved it.
I've downloaded last version of the linphone-sdk-ios here https://www.linphone.org/snapshots/ios/ , in my case it was the file linphone-sdk-ios-4.2-121-gd40eb09.zip
After I've replaced all files in the directory /Users/.../linphone-iphone-master/Pods/linphone-sdk/linphone-sdk/apple-darwin/Frameworks on files in "Frameworks" directory of the downloaded repository.
Now everything is fine.
