### ISSUE TITLE
Can't play dtmf

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#573]
I've create a swift project and using a linphone library then i created this function to play a dtmf
![Screen Shot 2562-09-13 at 15 46 21](https://user-images.githubusercontent.com/18572139/64849501-b59fab00-d63d-11e9-9c3f-b3daaba172a1.png)
By passing a parameter "3" for digit and -1 for durations and when i call this function it shows me this 

"[Warning] Not a dtmf key." 

I can't here any dtmf sound.
Can anyone guide me to solve this?
Thank you.

**Comment by moderateepheezy** [comment]
Have you been able to fix this @SarunyuPrasert

**Comment by SarunyuPrasert** [comment]
@moderateepheezy  No. I've no idea how to fix it

**Comment by SarunyuPrasert** [comment]
It also happened with function "linphone_call_send_dtmf"

**Comment by Viish** [comment]
"3" isn't a DTMF key. '3' is.
I guess your problem is a String/Char type issue.

**Comment by SarunyuPrasert** [comment]
@moderateepheezy I can fix it by using CChar. It an Int8 in swift. 
Change to this and pass a String to CChar like this "5".cString(using: .utf8)![0]

![Screen Shot 2562-09-18 at 14 25 50](https://user-images.githubusercontent.com/18572139/65125914-81066780-da20-11e9-97c0-9a55bd53d89f.png)
![Screen Shot 2562-09-18 at 14 26 33](https://user-images.githubusercontent.com/18572139/65125916-81066780-da20-11e9-8db6-8935614950b4.png)
