### ISSUE TITLE
linphone_iphone_popup_password_request don't retrieve auth_info

### ISSUE THREAD

**Issue by Daniele-Tentoni** [BelledonneCommunications/linphone-iphone#576]
Hi all,
this method `static void linphone_iphone_popup_password_request(LinphoneCore *lc, LinphoneAuthInfo *auth_info, LinphoneAuthMethod method)`, that manage the password request, i think after an user disconnect, can't retrieve the username, domain and realm with those methods from auth_info: `linphone_auth_info_get_username(auth_info)`, `linphone_auth_info_get_realm(auth_info)` and `linphone_auth_info_get_domain`.

Seems that auth_info too doesn't contain anything. Anyone can help me?

PS: This issue can be related to #574 .

**Comment by Daniele-Tentoni** [comment]
This is a problem in linphone-dk project? I need to open an issue here?

**Comment by divyeshvora2007** [comment]
@Daniele-Tentoni  Any solution you can get ?

**Comment by Daniele-Tentoni** [comment]
Sadly no, @divyeshvora2007...
