### ISSUE TITLE
tutorial rework

### ISSUE THREAD

**Issue by cdynak** [BelledonneCommunications/linphone-iphone#58]
i think, that with small changes, linphone-iphone hello-world's could be even more user friendly. as a example i propose: https://github.com/BelledonneCommunications/linphone-iphone/pull/55

project file could be modified a little bit, because libSKP_SILK_SDK.a reference still makes the same problem as in: https://github.com/BelledonneCommunications/linphone-iphone/pull/8

maybe it is worth to create in Objective-C LinphoneMiniManager class, like in linphone-android?

**Comment by bagage** [comment]
I'll take a look at that when I get some time - LinphoneMiniManager could be a good idea but I won't have time to do it myself. The code is actually much more straightforward in objectiveC, so there is no necessary need for it but if you'd like to do it, I'd gladly merge it.

**Comment by cdynak** [comment]
Of course, linphone-iphone code is very nice, but if iphone and android samples will have more in common they will be more attractive.

if i will have possibility to write LinphoneMiniManager for sure i will make pull request, but for now i just want to knew your opinion about that and https://github.com/BelledonneCommunications/linphone-iphone/pull/55.

**Comment by bagage** [comment]
Yes, I just wanted to pinpoint that I agree with you but I won't be able to do it in the short-term, so if you or anyone wants to implement it, I will probably review and merge it 👍

**Comment by cdynak** [comment]
hello;
i just saw, that you closed that issue, but what about tutorial anyway?
still there is nothing about it in `README.md`
but there is also a little mess around:
https://github.com/BelledonneCommunications/linphone-iphone/blob/5da8a2812070227070f332d959f6685275eaf29c/.gitignore#L18
https://github.com/BelledonneCommunications/linphone-iphone/blob/7696fe9d8f0dc77bf0641b90bff7160a876aaef0/prepare.py#L349

**Comment by ReisBenjamin** [comment]
Hello,

There's no plan currently to rework the tutorial for now.
