### ISSUE TITLE
IOS 13, xcode 11: error: conflicting parameter types in implementation of 'application:handleActionWithIdentifier:forLocalNotification:completionHandler'

### ISSUE THREAD

**Issue by wirelessmundi** [BelledonneCommunications/linphone-iphone#580]
logs:
[error2.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/3657814/error2.txt)

Hope someone great soul will help

**Comment by astuter** [comment]
`- (void)application:(UIApplication *)application
	handleActionWithIdentifier:(NSString *)identifier
		  forLocalNotification:(UILocalNotification *)notification
			  withResponseInfo:(NSDictionary *)responseInfo
			 completionHandler:(void (^)())completionHandler;`

is deprecated, it should be replaced by following method: 

`- (void)userNotificationCenter:(UNUserNotificationCenter *)center 
didReceiveNotificationResponse:(UNNotificationResponse *)response 
         withCompletionHandler:(void (^)(void))completionHandler;`

As a workaround you can change `completionHandler:(void (^)())completionHandler` to `completionHandler:(void (^)(void))completionHandler` to solve your error.
