### ISSUE TITLE
Unable to use G729 codec With latest Version 4.1.1 and 4.2

### ISSUE THREAD

**Issue by Rushabh5** [BelledonneCommunications/linphone-iphone#585]
I herewith a problem of enabling G729 codec.

Currently, I am using linphone libraries for making sip calls from iPhone. I need to work with g729 codec.

Can anyone have an idea on how do i do that?

**Comment by RaviChavada** [comment]
Hey,
we are successfully building G729 codec in iPhone as well as android.
