### ISSUE TITLE
Android Samsung tablet incoming video is pixelated and render only to one line

### ISSUE THREAD

**Issue by ericeche** [BelledonneCommunications/linphone-iphone#59]
Downloaded the latest version from this link https://github.com/BelledonneCommunications/linphone-android.

I was able to run the application in the same tablet in older versions of linphone android without any issues. In recent upgrades though, the remote video piece does not seem to work properly. This only happens in the incoming video -- see attached image --.  Please see also the android device OS parameters

![samsung_tablet](https://cloud.githubusercontent.com/assets/4226151/14915693/ebf53714-0de2-11e6-9ea1-94281c155b2c.png)

![device-2016-04-29-080652](https://cloud.githubusercontent.com/assets/4226151/14915671/b52ea2e2-0de2-11e6-9d3d-aee63e4e9697.png)

Any help will be appreciated

**Comment by ericeche** [comment]
And here is how I install the apk on the device using 

<img width="584" alt="screen shot 2016-04-29 at 8 20 03 am" src="https://cloud.githubusercontent.com/assets/4226151/14915755/4bc077d0-0de3-11e6-92fe-03ee51e3213e.png">



BUILD SUCCESSFUL
Total time: 5 seconds
Dildorf:linphone-android ericecheverri$ make install
ant installd
Buildfile: /Users/ericecheverri/android-linphone/linphone-android/build.xml
[getbuildtools] Using latest Build Tools: 23.0.2

-set-mode-check:

-set-debug-files:

install:
     [echo] Installing /Users/ericecheverri/android-linphone/linphone-android/bin/Linphone-debug.apk onto default emulator or device...
     [exec] 4583 KB/s (25695692 bytes in 5.475s)
     [exec] 	pkg: /data/local/tmp/Linphone-debug.apk
     [exec] Success

installd:

BUILD SUCCESSFUL
Total time: 21 seconds
ant run
Buildfile: /Users/ericecheverri/android-linphone/linphone-android/build.xml
[getbuildtools] Using latest Build Tools: 23.0.2

run:
     [exec] Starting: Intent { act=android.intent.action.MAIN cmp=org.linphone/.LinphoneLauncherActivity }

BUILD SUCCESSFUL
Total time: 1 second

**Comment by bagage** [comment]
Wrong repository - this repository is linphone-iphone, not android. Please use the mailing list instead.

**Comment by ericeche** [comment]
Could you send me the link please for linphone-android issues please ?
