### ISSUE TITLE
Call rejected with 603 while answering from CallKit view 

### ISSUE THREAD

**Issue by uniruddh** [BelledonneCommunications/linphone-iphone#590]
While answering incoming call from call kit screen, linphone is rejecting call with 603. Also, To and From fields are reversed in the SIP message. Attached the logs for the same. 

[603-error.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/3760547/603-error.txt)

**Comment by ZStatements** [comment]
@uniruddh did you ever fix this?

**Comment by bnsy** [comment]
Any update on this?

**Comment by jvarruda** [comment]
I'm hitting the same issue. Was this ever fixed?
