### ISSUE TITLE
Build liblinphone error on target EP_decaf

### ISSUE THREAD

**Issue by SarunyuPrasert** [BelledonneCommunications/linphone-iphone#591]
I cloned a project using this command 
"git clone https://gitlab.linphone.org/BC/public/linphone-sdk.git --recursive"
and running build command but i received this error.

====================================================================

Scanning dependencies of target EP_decaf
[ 12%] Creating directories for 'EP_decaf'
[ 12%] No download step for 'EP_decaf'
[ 13%] No patch step for 'EP_decaf'
[ 13%] No update step for 'EP_decaf'
[ 13%] Performing configure step for 'EP_decaf'
loading initial cache file /Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7//tmp/EP_decaf/EP_decaf-cache-RelWithDebInfo.cmake
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk
-- Using sdk version: 13.1
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk
-- Using sdk version: 13.1
-- The C compiler identification is AppleClang 11.0.0.11000033
-- The CXX compiler identification is AppleClang 11.0.0.11000033
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.16", minimum required is "2.7") 
Generated source code in /Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.15") found components:  doxygen dot 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf
[ 14%] Forcing build for 'EP_decaf'
[ 14%] Performing build step for 'EP_decaf'
Scanning dependencies of target generatorCommonCode
[  1%] Generating code for include/decaf.h
[  3%] Generating code for include/decaf/eddsa.hxx
[  5%] Generating code for include/decaf.hxx
[  7%] Generating code for decaf/crypto.hxx
[  9%] Generating ../GENERATED/include/decaf/common.h
[ 11%] Generating ../GENERATED/include/decaf/sha512.hxx
[ 13%] Generating ../GENERATED/include/decaf/sha512.h
[ 15%] Generating ../GENERATED/include/decaf/shake.hxx
[ 16%] Generating ../GENERATED/include/decaf/shake.h
[ 18%] Generating ../GENERATED/include/decaf/spongerng.hxx
[ 20%] Generating ../GENERATED/include/decaf/spongerng.h
[ 22%] Generating ../GENERATED/include/decaf/secure_buffer.hxx
[ 24%] Generating code for decaf/point_255.h
[ 26%] Generating code for decaf/point_448.h
[ 28%] Generating code for decaf/ed255.h
[ 30%] Generating code for decaf/ed448.h
[ 30%] Built target generatorCommonCode
Scanning dependencies of target generatorP448
[ 32%] Generating code for p448/f_field.h
[ 33%] Generating code for p448/f_generic.c
[ 33%] Built target generatorP448
Scanning dependencies of target generatorEd448goldilocks
[ 35%] Generating code for ed448goldilocks/scalar.c
[ 37%] Generating code for ed448goldilocks/decaf.c
[ 39%] Generating code for ed448goldilocks/elligator.c
[ 41%] Generating code for ed448goldilocks/eddsa.c
[ 43%] Generating code for include/decaf/point_448.hxx
[ 45%] Generating code for include/decaf/ed448.hxx
[ 45%] Built target generatorEd448goldilocks
Scanning dependencies of target generatorP25519
[ 47%] Generating code for p25519/f_field.h
[ 49%] Generating code for p25519/f_generic.c
[ 49%] Built target generatorP25519
Scanning dependencies of target generatorCurve25519
[ 50%] Generating code for curve25519/scalar.c
[ 52%] Generating code for curve25519/decaf.c
[ 54%] Generating code for curve25519/elligator.c
[ 56%] Generating code for curve25519/eddsa.c
[ 58%] Generating code for include/decaf/point_255.hxx
[ 60%] Generating code for include/decaf/ed255.hxx
[ 60%] Built target generatorCurve25519
Scanning dependencies of target generatedCode
[ 60%] Built target generatedCode
Scanning dependencies of target p25519
[ 62%] Building C object src/p25519/CMakeFiles/p25519.dir/arch_32/f_impl.c.o
[ 64%] Building C object src/p25519/CMakeFiles/p25519.dir/f_arithmetic.c.o
[ 66%] Building C object src/p25519/CMakeFiles/p25519.dir/__/GENERATED/c/p25519/f_generic.c.o
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
        UNROLL while (fill < (unsigned int)(LIMB_PLACE_VALUE(LIMBPERM(i))) && j < nbytes) {
               ^
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Build/decaf/src/GENERATED/c/p25519/f_generic.c:70:16: error: loop not unrolled: the optimizer was unable to
      perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
8 errors generated.
make[8]: *** [src/p25519/CMakeFiles/p25519.dir/__/GENERATED/c/p25519/f_generic.c.o] Error 1
make[7]: *** [src/p25519/CMakeFiles/p25519.dir/all] Error 2
make[6]: *** [all] Error 2
make[5]: *** [/Users/sarunyuprasert/Documents/Git_Linphone_SDK_iOS_new/linphone-sdk/build/WORK/ios-armv7/Stamp/EP_decaf/EP_decaf-build] Error 2
make[4]: *** [CMakeFiles/EP_decaf.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ios-armv7-prefix/src/ios-armv7-stamp/ios-armv7-build] Error 2
make[1]: *** [CMakeFiles/ios-armv7.dir/all] Error 2
make: *** [all] Error 2

====================================================================

What is EP_decaf ? Is there a option in "ccmake .." to disable it?  so i can build successfully.

Thank you.

**Comment by SarunyuPrasert** [comment]
@Viish Did you get this issue when you build it?

**Comment by Viish** [comment]
No we aren't aware of any build issue on iOS SDK.
Decaf is used for LIME end to end encryption. You can disable it with -DENABLE_LIME_X3DH=NO
Please stop notifying me of your iOS tickets.

**Comment by SarunyuPrasert** [comment]
Sorry to bother you. it won't happen again.

Thank you
