### ISSUE TITLE
ERROR: Compiling linphone-iphone project in XCODE 11.1

### ISSUE THREAD

**Issue by shadowwalkersteam** [BelledonneCommunications/linphone-iphone#592]
I have cloned linphone-iphone into my xcode. I configure it with cocoapods as you described, ran pod install and then opened **linphone.xcworkspace** but when i build the project it is giving me this error.
`/Users/abc/Library/Developer/Xcode/DerivedData/linphone-diiyckxoivqcotdtmjwckxpfbiqe/Build/Intermediates.noindex/linphone.build/Debug-iphoneos/linphone.build/Script-63DCC71D1A07B08E00916627.sh: line 2: /Users/abc/iOS: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code`
I am using latest Xcode: version is 11.1
Please help me

**Comment by benedictcontawe** [comment]
Hi I have the same problem as well do you have any suggestions on this. I Used the master branch for this and pod install and pod update as well then build also failed same error in this issue as well. any suggestions how to fix this?

**Comment by shadowwalkersteam** [comment]
> Hi I have the same problem as well do you have any suggestions on this. I Used the master branch for this and pod install and pod update as well then build also failed same error in this issue as well. any suggestions how to fix this?

I resolved it by going to Build Phases and Disable the scripts from Run Script.
Those scripts were causing issue.

**Comment by benedictcontawe** [comment]
how to disable the scripts?

**Comment by irfanismaya20** [comment]
please help

**Comment by shadowwalkersteam** [comment]
Hi, Sorry for late reply.
Just go to your project settings -> build phases. there you will have few lines of scripts in Run Script section. Delete those script. For more information check the below image links
[https://imgur.com/cpkbxAR](url)
[https://imgur.com/Xa2JWWn](url)
