### ISSUE TITLE
Build Error With Xocde 6.2

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#6]
Hi,

I try to launch Linphone for iPhone, I have download the last master branch version.
During the build process I get an error:

Install Xcode 6.4
Install HomeBrew, a package manager for OS X.
Build SDK : ./prepare.py -c && ./prepare.py && make An error occurred.

/Users/XXX/Documents/linphone-iphone/WORK/ios-x86_64/cmake/EP_vpx_configure.sh: line 32: /Users/XXX/Documents/linphone-iphone/submodules/externals/libvpx/configure: No such file or directory
make[3]: *** [/Users/XXX/Documents/linphone-iphone/WORK/ios-x86_64/Stamp/EP_vpx/EP_vpx-configure] Error 127
make[2]: *** [CMakeFiles/EP_vpx.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all-x86_64] Error 2

Then from suggestion based on this link:
http://lists.nongnu.org/archive/html/linphone-developers/2015-09/msg00029.html
I downgraded to Xcode 6.2 

Build SDK : ./prepare.py -c && ./prepare.py && make 
./prepare.py -c && ./prepare.py all --enable-non-free-codecs  --disable-gpl-third-parties -DENABLE_VPX=OFF

Response was:
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/XXX/Documents/linphone-iphone/WORK/ios-x86_64/cmake
WARNING: 
***************************************************************************
***************************************************************************
***** Linphone SDK without 3rd party GPL software                     *****
***** If you acquired a proprietary license from Belledonne           *****
***** Communications, this SDK can be used to create                  *****
***** a proprietary linphone-based application.                       *****
***************************************************************************
***************************************************************************

Then
Open linphone.xcodeproj in Xcode: open linphone.xcodeproj

Try to Run: Thje following is the error:

pResource liblinphone-sdk/apple-darwin/share/linphone/rootca.pem /Users/XXX/Library/Developer/Xcode/DerivedData/linphone-binsaljywoiqbkgqyhcxaaicznoc/Build/Products/Debug-iphonesimulator/linphone.app/rootca.pem
    cd /Users/XXX/Documents/linphone-iphone
    export PATH="/Applications/Xcode6.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:(null)/Users/XXX/.gem/ruby/2.0.0(null):(null)/Library/Ruby/Gems/2.0.0(null):(null)/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0(null):/Applications/Xcode6.2.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/XXX/Documents/linphone-iphone/liblinphone-sdk/apple-darwin/share/linphone/rootca.pem /Users/XXX/Library/Developer/Xcode/DerivedData/linphone-binsaljywoiqbkgqyhcxaaicznoc/Build/Products/Debug-iphonesimulator/linphone.app

error: /Users/XXX/Documents/linphone-iphone/liblinphone-sdk/apple-darwin/share/linphone/rootca.pem: No such file or directory

**Comment by bagage** [comment]
Please update your repository and try again, a few changes happened here.

**Comment by uditbatra** [comment]
Thanks, let me try once. Will it work with Xcode 7 also.

Shall we follow complete process 
Or just after pull start with Build step.

**Comment by uditbatra** [comment]
Hi I am getting the issue now on building:

ld: warning: ARM function not 4-byte aligned: __b_evaluation from /Users/uditbatra/Documents/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __a_evaluation from /Users/uditbatra/Documents/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __end_b_evaluation2 from /Users/uditbatra/Documents/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __a_evaluation2 from /Users/uditbatra/Documents/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
ld: warning: ARM function not 4-byte aligned: __end_simple_idct_arm from /Users/uditbatra/Documents/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libavcodec.a(simple_idct_arm.o)
Undefined symbols for architecture armv7:
  "_libmsx264_init", referenced from:
      -[LinphoneManager createLinphoneCore] in LinphoneManager.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by uditbatra** [comment]
I have updated the repository.

Then
Again Builded it using 
./prepare.py -c && ./prepare.py && make

Then 
Open linphone.xcodeproj in Xcode: open linphone.xcodeproj

Following files are still missing. Please see the images for missing files. 

Thanks
![screen shot 2015-09-24 at 3 48 26 pm](https://cloud.githubusercontent.com/assets/3806195/10071013/13267cd6-62d4-11e5-83ee-def77ce70aea.png)
![screen shot 2015-09-24 at 3 48 33 pm](https://cloud.githubusercontent.com/assets/3806195/10071014/132ab346-62d4-11e5-8675-6cadc5cc06e8.png)

**Comment by bagage** [comment]
I do not know what you are trying to do but it is working fine here.

**Comment by bagage** [comment]
OK, I actually found your issue - it should be fixed now.

**Comment by uditbatra** [comment]
ok,Thanks
