### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by uniruddh** [BelledonneCommunications/linphone-iphone#601]
Getting following warning when submitting app to App store.

> Apple will stop accepting submissions of apps that use UIWebView APIs . 

See [here for more information](https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by hamzaozturk** [comment]
I created a [PR](https://github.com/BelledonneCommunications/linphone-iphone/pull/603) to remove the deprecated API.
