### ISSUE TITLE
linphone_factory_create_core_with_config_3 error

### ISSUE THREAD

**Issue by Spyspyspy** [BelledonneCommunications/linphone-iphone#607]
Hello. I've implemented my iOS app with linphone sdk, but when I change display name of the app to the Cyrillic name it crashes in linphone_factory_create_core_with_config_3. But when it is in latin - all is ok. What's wrong?

**Comment by alexxpert** [comment]
I get the same problem. Are You find a solution?

**Comment by hamzaozturk** [comment]
When you initialize linphone core with linphone_factory_create_core_with_config_3, you need to give factory and config file path parameters as pointer. If you use Cyrillic name as display name of the app, it will be included in the path and the path will be not resolvable.

**Comment by showgoodjiang** [comment]
Change "Bundle display name" in Info.plist, do not change Target Display Name.

**Comment by Weijiaxiang** [comment]
I tried the above method, but I didn't solve the problem. Has anyone found a solution to this problem
