### ISSUE TITLE
Pod install doesn't work for new clone of project

### ISSUE THREAD

**Issue by DroidPulkit** [BelledonneCommunications/linphone-iphone#613]
If we git clone this project, and follow along to do pod install, I am getting the following errros

```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "linphone-sdk/basic-frameworks":
  In Podfile:
    linphone-sdk/basic-frameworks (= 4.3.1)

None of your spec sources contain a spec satisfying the dependency: `linphone-sdk/basic-frameworks (= 4.3.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I even tried updating the pod file to use other version of SDK but it dosen't help
Tried installing cocoapods again, tried pod update, pod outdated or pod install --repo-update
All lead to this error

**Comment by DroidPulkit** [comment]
Fixed this, with following podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source "https://gitlab.linphone.org/BC/public/podspec.git"
source "https://github.com/CocoaPods/Specs.git"

def basic_pods
	pod 'linphone-sdk', '4.3.1'
	crashlythics
end

def crashlythics
	if not ENV['USE_CRASHLYTHICS'].nil?
		# activate crashlythics
		pod 'Firebase/Core'
		pod 'Fabric', '~> 1.9.0'
		pod 'Crashlytics', '~> 3.12.0'
		pod 'Firebase/Performance'
	end
end

target 'linphone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for linphone
  basic_pods
	pod 'SVProgressHUD'

end

post_install do |installer|
	# Get the version of linphone-sdk
	installer.pod_targets.each do |target|
		if target.pod_name == 'linphone-sdk'
			target.specs.each do |spec|
				$linphone_sdk_version = spec.version
			end
		end
	end
			
	app_project = Xcodeproj::Project.open(Dir.glob("*.xcodeproj")[0])
	app_project.native_targets.each do |target|
		if target.name == 'linphone'
			target.build_configurations.each do |config|
				if ENV['USE_CRASHLYTHICS'].nil?
					if config.name == "Debug" then
						config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) DEBUG=1'
					else
						config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited)'
					end
				else
					# activate crashlythics
					if config.name == "Debug" then
						config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) DEBUG=1 USE_CRASHLYTHICSS=1'
						else
						config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) USE_CRASHLYTHICSS=1'
					end
				end

				config.build_settings['OTHER_CFLAGS'] = '-DBCTBX_LOG_DOMAIN=\"ios\"',
																								'-DCHECK_VERSION_UPDATE=FALSE',
																								'-DENABLE_QRCODE=TRUE',
																								'-DENABLE_SMS_INVITE=TRUE',
																								'$(inherited)',
																								"-DLINPHONE_SDK_VERSION=\\\"#{$linphone_sdk_version}\\\""
				
				app_project.save
			end
		end
	end
end


```

**Comment by chetan1406** [comment]
@DroidPulkit Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler: linphone-iphone-master/Pods/linphone-sdk/linphone-sdk/apple-darwin/Frameworks/linphonesw.framework/Modules/linphonesw.swiftmodule/arm64.swiftmodule



any resolution regarding this error after updating pod.

**Comment by DroidPulkit** [comment]
Don't use latest xcode11, it only works in xcode 10

**Comment by DroidPulkit** [comment]
Also need couple of more changes like delete the extra targets, and change the bundle is to some random com.example.linphone and choose a team and then remove the app group from the compatibility tab

**Comment by DroidPulkit** [comment]
Run the code on actual device, as the native library wasn't compiled for intel CPU architecture

**Comment by chetan1406** [comment]
@DroidPulkit thanks brother working fine with xcode 10 but need to do with xcode 11 :(

**Comment by S0U1SB4N3** [comment]
Apple Inc wont allow us to run things in the store that arent xcode 11, 4.2.2 loads on xcode 11, why did this not get updated for 4.3.1 release

**Comment by S0U1SB4N3** [comment]
v4.2.2 release doesnt wake from background and now v 4.3.1 cant be compiled in xcode 11 ? why are we stepping backwards in development ?

**Comment by becklo** [comment]
Hello, 

I get the same issue but with the following 

```
[!] CocoaPods could not find compatible versions for pod "linphone-sdk/app-extension-swift":
  In Podfile:
    linphone-sdk/app-extension-swift (= 4.4)

None of your spec sources contain a spec satisfying the dependency: `linphone-sdk/app-extension-swift (= 4.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

I checked [](https://gitlab.linphone.org/BC/public/podspec/tree/master) and see that 4.4 is still in alpha, is it why it doesn't work ?

**Comment by tjramoliya** [comment]
@DroidPulkit i have configure all with developer account and bundle identifier.
It's all good working fine. 

but when i am try to run i am getting same error

**Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler: linphone-iphone-master/Pods/linphone-sdk/linphone-sdk/apple-darwin/Frameworks/linphonesw.framework/Modules/linphonesw.swiftmodule/arm64.swiftmodule**

this same error got @chetan1406 
So is there any solution for that how to solve this ?

Because this linphonesw.framwork not able to compile in Xcode 11.4 or any other Xcode 11 version.
