### ISSUE TITLE
How to handle incoming cell calls putting linphone on hold.

### ISSUE THREAD

**Issue by S0U1SB4N3** [BelledonneCommunications/linphone-iphone#617]
How do i stop the linphone app from putting a connected sip call on hold when my cellular phone receives an incoming call. 

I only want it on hold if the incoming cellular call is accepted, not while the incoming cell call  is just ringing though.

**Comment by chetan1406** [comment]
@S0U1SB4N3 you can use this method (func provider(_ provider: CXProvider, perform action: CXSetHeldCallAction) ).

**Comment by S0U1SB4N3** [comment]
I will try this , im looking at the ProviderDelegate.m 
trying to trace down why it Down why it does this. 
I only want a call to be put on hold if I select to do so
Im getting this screen 
![Screen Shot 2020-04-13 at 12 52 48 PM](https://user-images.githubusercontent.com/22788570/79141087-17b4c000-7d87-11ea-8d41-029e75199497.png)

I need this one at all times. 
![Screen Shot 2020-04-13 at 12 53 04 PM](https://user-images.githubusercontent.com/22788570/79141099-1d120a80-7d87-11ea-9916-588275f17a4e.png)

**Comment by S0U1SB4N3** [comment]
@chetan1406 I only want to put a call on hold if I push the pause button in the UI < I do not want a paused call automatically upon incoming cellular call while I have an outgoing sip call, 

can you tell me which file this is done within, and ill modify it, can you show me an example 

![Screen Shot 2020-04-13 at 1 07 45 PM](https://user-images.githubusercontent.com/22788570/79141458-d244c280-7d87-11ea-9cc2-888b9e9648ee.png)
![Screen Shot 2020-04-13 at 1 07 12 PM](https://user-images.githubusercontent.com/22788570/79141462-d4a71c80-7d87-11ea-8bb3-c60d3b69f89e.png)
