### ISSUE TITLE
How to set order for audio codec with latest source?

### ISSUE THREAD

**Issue by astuter** [BelledonneCommunications/linphone-iphone#62]
Earlier we had a list to set order/priority of audio codecs in **linphonecore.c** as following: 

`static const char *codec_pref_order[]= { "speex", "gsm", "pcmu", "pcma", "H264", "MP4V-ES", "theora", "H263-1998", "H263", "x-snow", NULL, };`

I am not able to find **codec_pref_order** or anything similar in the latest source. Can someone help me to know how I can change codec priority/order? 

Thanks.

**Comment by bagage** [comment]
You have to enter them in your linphonerc in the desired order. For instance in [linphonerc-factory](https://github.com/BelledonneCommunications/linphone-iphone/blob/master/Resources/linphonerc-factory), you can do:
```
[audio_codec_0]
... opus or anything else

[audio_codec_1]
... something else etc.
```

**Comment by astuter** [comment]
Okay thanks. Got it.

**Comment by shraddha-patel-1891** [comment]
@astuter @bagage 
how to change the codec priority programmatically?
I tried **linphone_core_get_audio_payload_types** and **linphone_core_set_audio_payload_types** the method but not working.
so can you please help me to resolve this issue?

Thanks

**Comment by bercursor** [comment]
Hi, i have the same issue that you have posted above. Have you figured out any solutions. If so, could you please help me @shraddha-patel-1891

**Comment by UrocToutou** [comment]
Hello,
I also have this same problem. Does anyone know the solution?
