### ISSUE TITLE
How to seprate incoming,outgoing and missed call from history screen.

### ISSUE THREAD

**Issue by Nipagohel** [BelledonneCommunications/linphone-iphone#622]
anyone can please assist on How to seprate incoming,outgoing and missed call from history screen.

**Comment by victorbarskov** [comment]
+ (LinphoneCallStatus)statusOfCall:(LinphoneCall *)call{
    LinphoneCallLog *log = linphone_call_get_call_log(call);
    return linphone_call_log_get_status(log);
}

**Comment by victorbarskov** [comment]
typedef enum _LinphoneCallStatus {
	LinphoneCallSuccess, /**< The call was sucessful */
	LinphoneCallAborted, /**< The call was aborted */
	LinphoneCallMissed, /**< The call was missed (unanswered) */
	LinphoneCallDeclined, /**< The call was declined, either locally or by remote end */
	LinphoneCallEarlyAborted, /**<The call was aborted before being advertised to the application - for protocol reasons*/
	LinphoneCallAcceptedElsewhere, /**<The call was answered on another device*/
	LinphoneCallDeclinedElsewhere /**<The call was declined on another device*/
} LinphoneCallStatus;

**Comment by victorbarskov** [comment]
+ (LinphoneCallDir)directionOfCall:(LinphoneCall *)call{
    if (!call) {
        return 0;
    }
    return linphone_call_get_dir(call);
}

This is for direction of the call

**Comment by Nipagohel** [comment]
Only getting outgoing calllist
- (void)loadDataIncoming {
  for (id day in self.sections.allKeys) {
    for (id log in self.sections[day]) {
      linphone_call_log_unref([log pointerValue]);
    }
  }
  
  const bctbx_list_t *logs = linphone_core_get_call_logs(LC);
  self.sections = [NSMutableDictionary dictionary];
  while (logs != NULL) {
    LinphoneCallLog *log = (LinphoneCallLog *)logs->data;
    
    if (  linphone_call_log_get_status(log) == LinphoneCallIncoming) {

      NSDate *startDate = [self
                           dateAtBeginningOfDayForDate:[NSDate
                                                        dateWithTimeIntervalSince1970:linphone_call_log_get_start_date(log)]];
      NSMutableArray *eventsOnThisDay = [self.sections objectForKey:startDate];
      if (eventsOnThisDay == nil) {
        eventsOnThisDay = [NSMutableArray array];
        [self.sections setObject:eventsOnThisDay forKey:startDate];
      }
      
      linphone_call_log_set_user_data(log, NULL);
      
        // if this contact was already the previous entry, do not add it twice
      LinphoneCallLog *prev = [eventsOnThisDay lastObject] ? [[eventsOnThisDay lastObject] pointerValue] : NULL;
      if (prev && linphone_address_weak_equal(linphone_call_log_get_remote_address(prev),
                                              linphone_call_log_get_remote_address(log))) {
        bctbx_list_t *list = linphone_call_log_get_user_data(prev);
        list = bctbx_list_append(list, log);
        linphone_call_log_set_user_data(prev, list);
      } else {
        [eventsOnThisDay addObject:[NSValue valueWithPointer:linphone_call_log_ref(log)]];
      }
    }
    logs = bctbx_list_next(logs);
  }
  
  [self computeSections];
  
  [super loadData];
  
  if (IPAD) {
    if (![self selectFirstRow]) {
      HistoryDetailsView *view = VIEW(HistoryDetailsView);
      [view setCallLogId:nil];
    }
  }
}

**Comment by victorbarskov** [comment]
If you need to store and get call history somewhere I would recommend you have your own local DB where you can save/get each incoming or outgoing calls. Then subscribe for states of the call and save or update your calls object in you db by call id.

**Comment by Nipagohel** [comment]
can we change in existing code ?

**Comment by Nipagohel** [comment]
HistoryListTableView - > loadData method 

Can we change from existing code in above class and method
