### ISSUE TITLE
linphone Build error

### ISSUE THREAD

**Issue by Darshan-Sonigara** [BelledonneCommunications/linphone-iphone#624]
I have tried to build linphone but I am getting error "No URL found for submodule path 'Classes/KIF' in .gitmodules"

I have installed homebrew and JDK

**This steps I follow:**

step-1: git clone https://github.com/BelledonneCommunications/linphone-iphone.git
step-2: sudo ./prepare.py
step-3: git submodule sync && git submodule update --init --recursive

error "No URL found for submodule path 'Classes/KIF' in .gitmodules" 

Thanks in advance

**Comment by krishnastvSMSC** [comment]
Hello Team,
we also got the same issue, how to resolve this.

**Comment by AhmedShmmala** [comment]
+1

**Comment by AhmedShmmala** [comment]
@Darshan-Sonigara  did you able to solve it ?
