### ISSUE TITLE
iOS VoIP calls not working when app in terminated state.. where was mistake in my code ..please suggestion or solution ....would be any help really more appreciated 

### ISSUE THREAD

**Issue by pasha4uu** [BelledonneCommunications/linphone-iphone#625]
`-(void)pushRegistry:(PKPushRegistry *)registry 
             didReceiveIncomingPushWithPayload:(PKPushPayload *)payload 
            forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {
                     NSString * nameA = [NSBundle.mainBundle 
                            objectForInfoDictionaryKey:@"CFBundleDisplayName"]
                     CXProviderConfiguration *config = [[CXProviderConfiguration 
                     alloc]initWithLocalizedName:nameA];
                    config.supportsVideo = FALSE;
                      config.iconTemplateImageData = UIImagePNGRepresentation([UIImage 
                  imageNamed:@"callkit_logo"]);   
            NSArray *ar = @[ [NSNumber numberWithInt:(int)CXHandleTypeGeneric] ];
            NSSet *handleTypes = [[NSSet alloc] initWithArray:ar];
            [config setSupportedHandleTypes:handleTypes];
            [config setMaximumCallGroups:2];
            [config setMaximumCallsPerCallGroup:1];
        
            self.cxProvider = [[CXProvider alloc] initWithConfiguration:config];
        
            NSDictionary *dict = [payload.dictionaryPayload objectForKey:@"aps"];
            NSString * callm = [dict objectForKey:@"callfrom"];
            if (callm.length ==0) {
                callm = @"CALL BB";
            }
                 CXHandle *callHandle = [[CXHandle alloc] initWithType:CXHandleTypeGeneric value:callm];
                 CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
                 callUpdate.remoteHandle = callHandle;
                 callUpdate.supportsDTMF = YES;
                 callUpdate.supportsHolding = YES;
                 callUpdate.supportsGrouping = NO;
                 callUpdate.supportsUngrouping = NO;
                 callUpdate.hasVideo = NO;
        
                 self.uuid = [NSUUID UUID];
        
                 [self.cxProvider reportNewIncomingCallWithUUID:self.uuid update:callUpdate completion:^(NSError *error) {
                     NSLog(@"error1 ----> %@",error);
                     if (error) {
                         if (@available(iOS 13.0, *)) {
                             [self.cxProvider reportCallWithUUID:self.uuid endedAtDate:[NSDate now] reason:CXCallEndedReasonFailed];
                         } else {
                         }
                     }
                 }];
         CXCallController *callController = [[CXCallController alloc] initWithQueue:dispatch_get_main_queue()]; 
                 dispatch_async(dispatch_get_main_queue(), ^{
        
                     CXEndCallAction *endCallAction = [[CXEndCallAction alloc] initWithCallUUID:self.uuid];
                     CXTransaction *transaction = [[CXTransaction alloc] initWithAction:endCallAction];
        
                     [callController requestTransaction:transaction completion:^(NSError *error) {
                         NSLog(@"error2 ----> %@",error);
                         if (@available(iOS 13.0, *)) {
                             [self.cxProvider reportCallWithUUID:self.uuid endedAtDate:[NSDate now] reason:CXCallEndedReasonRemoteEnded];
                         } else {
                         }
                     }];
        
                 });
        
                [self processPush:payload.dictionaryPayload];
                dispatch_async(dispatch_get_main_queue(), ^{completion();});
            }

`

**Comment by chetan1406** [comment]
```
source "https://github.com/CocoaPods/Specs.git"
source "https://gitlab.linphone.org/BC/public/podspec.git"

target 'YourTarget' do
  pod 'linphone-sdk/basic-frameworks', '~> 4.4.0-alpha'
  pod 'linphone-sdk/app-extension-swift', '~> 4.4.0-alpha'
end
```

**Comment by pasha4uu** [comment]
if i proceed above the POD is it will work ? any other thing have to  implement ?

**Comment by pasha4uu** [comment]
IM GETTING POD ERROR...

> ```
> source "https://github.com/CocoaPods/Specs.git"
> source "https://gitlab.linphone.org/BC/public/podspec.git"
> 
> target 'YourTarget' do
>   pod 'linphone-sdk/basic-frameworks', '~> 4.4.0-alpha'
>   pod 'linphone-sdk/app-extension-swift', '~> 4.4.0-alpha'
> end
> ```

GETTING THIS ERROR
![Screenshot 2020-05-04 at 11 17 41 PM](https://user-images.githubusercontent.com/38080760/81040247-90abc100-8ec8-11ea-8af7-9614332c216b.png)

**Comment by pasha4uu** [comment]
> ```
> source "https://github.com/CocoaPods/Specs.git"
> source "https://gitlab.linphone.org/BC/public/podspec.git"
> 
> target 'YourTarget' do
>   pod 'linphone-sdk/basic-frameworks', '~> 4.4.0-alpha'
>   pod 'linphone-sdk/app-extension-swift', '~> 4.4.0-alpha'
> end
> ```
IM GETTING THIS ERROR :
![Screenshot 2020-05-04 at 11 17 41 PM](https://user-images.githubusercontent.com/38080760/81040797-d0bf7380-8ec9-11ea-851a-f83fd41b0456.png)

**Comment by pasha4uu** [comment]
> ```
> source "https://github.com/CocoaPods/Specs.git"
> source "https://gitlab.linphone.org/BC/public/podspec.git"
> 
> target 'YourTarget' do
>   pod 'linphone-sdk/basic-frameworks', '~> 4.4.0-alpha'
>   pod 'linphone-sdk/app-extension-swift', '~> 4.4.0-alpha'
> end
> ```

IM GETTING THIS ERROR
![Screenshot 2020-05-04 at 11 17 41 PM](https://user-images.githubusercontent.com/38080760/81040984-3c094580-8eca-11ea-9a19-d985f449d3ec.png)

**Comment by S0U1SB4N3** [comment]
Im having same issue unresolved at this time
