### ISSUE TITLE
How to stop incoming call notification based on permission

### ISSUE THREAD

**Issue by Nipagohel** [BelledonneCommunications/linphone-iphone#626]
How to stop incoming call notification based on permission while app in background, foreground and kill state.

**Comment by pasha4uu** [comment]
> How to stop incoming call notification based on permission while app in background, foreground and kill state.

are you getting call when app kill state ?

**Comment by Nipagohel** [comment]
Nop, I just want to stop incoming call whie app in background, foreground based on permission
