### ISSUE TITLE
I Implemented below code for getting calls when app in kill state. below code is working some times and some times not working .. please help me.. any mistake in the code ? and or any implementation backend server for full working without drop calls?

### ISSUE THREAD

**Issue by pasha4uu** [BelledonneCommunications/linphone-iphone#627]
```
- (void)pushRegistry:(PKPushRegistry *)registry didReceiveIncomingPushWithPayload:(PKPushPayload *)payload forType:(PKPushType)type withCompletionHandler:(void (^)(void))completion {    
       CXProviderConfiguration *config = [[CXProviderConfiguration alloc]
        initWithLocalizedName:[NSBundle.mainBundle objectForInfoDictionaryKey:@"CFBundleDisplayName"]];
    config.ringtoneSound = @"notes_of_the_optimistic.caf";
    config.supportsVideo = FALSE;
    config.iconTemplateImageData = UIImagePNGRepresentation([UIImage imageNamed:@"callkit_logo"]);

    NSArray *ar = @[ [NSNumber numberWithInt:(int)CXHandleTypeGeneric] ];
    NSSet *handleTypes = [[NSSet alloc] initWithArray:ar];
    [config setSupportedHandleTypes:handleTypes];
    [config setMaximumCallGroups:2];
    [config setMaximumCallsPerCallGroup:1];
    
    self.cxProvider = [[CXProvider alloc] initWithConfiguration:config];

    NSDictionary *dict = [payload.dictionaryPayload objectForKey:@"aps"];
    NSString *callfm= [dict objectForKey:@"callfrom"];
    if (callfm.length==0) {
        callfm = @"ab";
    }
    
         CXHandle *callHandle = [[CXHandle alloc] initWithType:CXHandleTypeGeneric value:callfm];

         CXCallUpdate *callUpdate = [[CXCallUpdate alloc] init];
         callUpdate.remoteHandle = callHandle;
         callUpdate.supportsDTMF = YES;
         callUpdate.supportsHolding = YES;
         callUpdate.supportsGrouping = NO;
         callUpdate.supportsUngrouping = NO;
         callUpdate.hasVideo = NO;

         self.uuid = [NSUUID UUID];
         [self.cxProvider reportNewIncomingCallWithUUID:self.uuid update:callUpdate completion:^(NSError *error) {
             NSLog(@"error1 ----> %@",error);
             if (error) {
                 if (@available(iOS 13.0, *)) {
                     [self.cxProvider reportCallWithUUID:self.uuid endedAtDate:[NSDate now] reason:CXCallEndedReasonRemoteEnded];
                 } else {
                     // Fallback on earlier versions
                 }
                 
             }
         }]; 
     CXCallController *callController = [[CXCallController alloc] initWithQueue:dispatch_get_main_queue()];

         dispatch_async(dispatch_get_main_queue(), ^{

             CXEndCallAction *endCallAction = [[CXEndCallAction alloc] initWithCallUUID:self.uuid];
             CXTransaction *transaction = [[CXTransaction alloc] initWithAction:endCallAction];

             [callController requestTransaction:transaction completion:^(NSError *error) {
                 NSLog(@"error2 ----> %@",error);
                 if (@available(iOS 13.0, *)) {
                     [self.cxProvider reportCallWithUUID:self.uuid endedAtDate:[NSDate now] reason:CXCallEndedReasonFailed];
                 } else {
                     // Fallback on earlier versions
                 }

             }];

         });

    [self processPush:payload.dictionaryPayload];
    completion();
}
```

**Comment by 0x41mmarVM** [comment]
I haven't read your code yet, but I just wanted to tell you that branch master of this repo is currently getting calls in kill state just fine. There are still problems to messages, though.

**Comment by S0U1SB4N3** [comment]
i have not been able to compile 4.3 for xcode 11.4.1 the latest xcode, when compiled on 10.3 it gives and exit error 0 but no fail point.

**Comment by 0x41mmarVM** [comment]
@S0U1SB4N3 I met with the same failure, but there were many fail points, so I'm not sure if it's the same problem, but the solution was to update sdk to 4.4.0-beta, see branch fix/crash_and_bugs.
Basically replace 'alpha' in Podfile with 'beta', do a `pod repo update` then a` pod install.` and restart xcode.

**Comment by S0U1SB4N3** [comment]
I did this and have not been able to produce a build for release 4.3 xcode 10.3 using pod install with the 4.4 alpha sdk build. 


I have xcode 10.3 , 11.0, 11.1, 11.3,11.4, and 11.4.1 installed and none have worked i downloaded your release 4.3 branch , ran the pod install, then opened workspace project and it fails to build.

**Comment by S0U1SB4N3** [comment]
Ill try the beta as you described and download the bug fix branch and try again

**Comment by S0U1SB4N3** [comment]
@0x41mmarVM 

curernt build error with xcode 10.3 and fixes_ bugs branch with beta sdk as instructed 

/Users/developer/Downloads/linphone-iphone-fix-crash_and_bugs/Classes/Utils/FastAddressBook.h:23:10: error: 'linphone/linphonecore.h' file not found
#include "linphone/linphonecore.h"
         ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/developer/Library/Developer/Xcode/DerivedData/linphone-euodjwwkigdbaugcclffjcnvartu/Build/Intermediates.noindex/PrecompiledHeaders/linphone-Bridging-Header-swift_BPS22OLZ2RWW-clang_2IVFOAP8X15GN.pch' for bridging header '/Users/developer/Downloads/linphone-iphone-fix-crash_and_bugs/Classes/linphone-Bridging-Header.h'

![Screen Shot 2020-05-21 at 1 59 34 PM](https://user-images.githubusercontent.com/22788570/82590232-5cdcc680-9b6b-11ea-9d99-dd13509095be.png)

![Screen Shot 2020-05-21 at 1 55 52 PM](https://user-images.githubusercontent.com/22788570/82590249-6403d480-9b6b-11ea-8008-6edc8cd2337e.png)
