### ISSUE TITLE
Successfully Build the Local SDK, Couldn't Integrate to Build

### ISSUE THREAD

**Issue by mrkerusi** [BelledonneCommunications/linphone-iphone#629]
Hi, I manage to Build the SDK to have fixed Domain (for Chatting) but when i follow the instructions:

"Create or edit the gradle.properties file in $GRADLE_USER_HOME (usually ~/.gradle) file and add the absolute path to your linphone-sdk build directory, for example:

LinphoneSdkBuildDir=/home/<username>/linphone-sdk/build/"

I created a cradle.properties file in $GRADLE_USER_HOME (~/.gradle) and amended the line with eate or edit the gradle.properties file in $GRADLE_USER_HOME (usually ~/.gradle) file and add the absolute path to your linphone-sdk build directory, for example:

"LinphoneSdkBuildDir=/home/<username>/linphone-sdk/build/"

but it seems like it doesn't have any changes to the behavior of the Chatting.

I'm Building the SDK on 
-macOS Catalina 10.5.4
-Android Studio 3.6.3
- Target SDk: is Android

maybe i was missing a step in the instruction, kindly advise if i missed anything.

**Comment by DroidPulkit** [comment]
Maybe post it in https://github.com/BelledonneCommunications/linphone-android
And include, what is the behavior(changes) you are looking for in it?
