### ISSUE TITLE
Licence for H264

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#63]
Hi,
As per the Description:
"The liblinphone SDK is compiled with third parties code that are subject to patent license, specially: AMR, SILK G729 and **H264 codecs**. Linphone controls the embedding of these codecs by generating dummy libraries when there are not available. You can enable them using prepare.py script (see -DENABLE_NON_FREE_CODECS=OFF option). Before embedding these 4 codecs in the final application, make sure to have the right to do so."

I want to enable H264 and H263+. Whats the process to gets rights for this.

Thanks

**Comment by bagage** [comment]
You've [3 choices](http://www.streaminglearningcenter.com/articles/h264-royalties-what-you-need-to-know.html):

* use H264 hardwared accelerated codec - free to use and enabled by default
* use openH264 implementation - see MPEG LA for pricing
* use x264 implementation - [see x264 licensing](http://www.x264licensing.com/)

**Comment by uditbatra** [comment]
Thanks
