### ISSUE TITLE
theLinphoneCore - BAD ACCES error

### ISSUE THREAD

**Issue by czaviar** [BelledonneCommunications/linphone-iphone#631]
Hi,

I managed to compile liblinphone-sdk from scratch and then build Linphone 4.0.2 in Xcode10, however I get the following error once I run the simulator:

theLinphoneCore = linphone_factory_create_core_with_config_3(factory, _configDb, NULL);Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

I haven't changed the Display Name (found that someone has similar problem after name change). Any other thoughts what may be the other reason of the problem above ?

**Comment by Weijiaxiang** [comment]
Hello, I met the same problem. Have you found a solution to the problem

**Comment by Peter-iOS** [comment]
Hello, I met the same problem too. Anyone can help me?
