### ISSUE TITLE
Linphone Iphone Push Notification [How to]

### ISSUE THREAD

**Issue by brightson93** [BelledonneCommunications/linphone-iphone#638]
Good Day,

I've tested the source code on xcode, it seems like it can receive call and text when only the app is active and device is awake. from what i read, linphone ios still require push notification in order to receive these notifications 

I'm still relatively new with VOIP software, may i know step by step what do i need to achieve these
1. Linphone IOS can receive incoming call from Sleep
2. Linphone IOS can receive chat

i'm using,
Client: linphone-iphone version 4.3,
PBX: FusionPBX

Hope you can help me with these, Thank You Very Much!

**Comment by 0x41mmarVM** [comment]
Linphone iOS is already equipped to get push notifications, but it's the SIP server that needs to send them. You can add a module to your existing PBX setup to hande it, if something is available, or you can place an entirely different gateway in front of it to act as a Push Gateway.
Example of 1: https://github.com/sem32/freeswitch-ApplePushNotification
Example of 2: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Push%20Gateway/

**Comment by brightson93** [comment]
thanks 

> Linphone iOS is already equipped to get push notifications, but it's the SIP server that needs to send them. You can add a module to your existing PBX setup to hande it, if something is available, or you can place an entirely different gateway in front of it to act as a Push Gateway.
> Example of 1: https://github.com/sem32/freeswitch-ApplePushNotification
> Example of 2: https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Push%20Gateway/

Thanks.. i will try to do this..

**Comment by brightson93** [comment]
Hi I've tried doing the above, to no success didn't work on my part. but however, i saw there is Firebase options for push notifications. i've done it on Android its working but, didn't work on IOS.

**Comment by brightson93** [comment]
Hi You can Close this Thread Now, It took me awhile to Learn the [How-to] for Linphone IOS Push Notification, which i think is worth to share with everyone. there are two method i found so far, and i have tested working, at least in my case.

I'm using Freeswitch with the Client, i'm using python apns packages, there's a lot of options out there. for these I'm using gobiko.apns or kalyke-apns.

both solution can send either normal push notification or voip notification, note that voip notification in my understanding was sent silently in the background as long pushkit pre-requisite exist in your codes.

The Objective is to have the the Linphone IOS to be able to receive call, and wake up even in sleep mode.   

First with kalyke-apns, using the voip client, there will be requirements, refer to these
https://pypi.org/project/kalyke-apns/

Note: you will need to get voip cert from your apple dev account, and convert it to .pem.your python must be 3.5 or later. the payload expected by pushkit is the call-id. i've tested in my local machine, the push worked, but unfortunately doesn't work when pushed from the Freeswitch. (there is some certificate issue that will take more time to troubleshoot)

Secondly with gobiko-apns, using the apns client, previously i've tested this package and it worked on both my local machine and the Freeswitch. but only sending the push notification message. there is also requirements, please refer here
https://pypi.org/project/gobiko.apns/
https://gobiko.com/blog/token-based-authentication-http2-example-apns/

Note: for this solution, you need to get apns key from your apple dev account. with this key. you will need to include kwargs argument for the call-id payload for the pushkit to receive the push notification. there is also you will require to append .voip on your bundle id, for the package to see it as voip push.

I hope these helps, thanks.
