### ISSUE TITLE
Not work with ios 9.3

### ISSUE THREAD

**Issue by xscconan** [BelledonneCommunications/linphone-iphone#64]
Audio is not work with IOS 9.3 (xcode 7.3).   But same code can be works  with IOS 8.x (xcode 6.4).

Sip server is asterisk.

Any suggestion?

Thanks

**Comment by xscconan** [comment]
Error in log:

2016-05-11 13:46:43.338 linphone[13622:128133] 13:46:43.338 ERROR:    >aurioc> 1503: AURemoteIO@0x7fd11189d840: IOThread exiting with 

ERROR:    1233: AUIOClient_StartIO failed (-66637)

**Comment by bagage** [comment]
Do you have any audio when using a linphone.org account?

**Comment by bagage** [comment]
Cannot replicate - please reopen with additional info.
