### ISSUE TITLE
Merge hu (Hungarian - magyar) translations from Transifex

### ISSUE THREAD

**Issue by ovari** [BelledonneCommunications/linphone-iphone#641]
Please merge hu (Hungarian - magyar) translations from Transifex. Thank you

**Comment by ovari** [comment]
@Viish can you merge the hu translations for iOS too?

Unfortunately, don't know the @ symbol for `Danmei Chen` from https://github.com/BelledonneCommunications/linphone-iphone/tree/release/4.3

Thank you

**Comment by Viish** [comment]
Don't worry it will be done when we will publish the release.

**Comment by ovari** [comment]
Have just corrected a few errors in the hu translation for iOS on Transifex. Can the strings please be updated before the release of Linphone 4.3 for iPhone/iPad? Thank you

**Comment by ChenDanmei** [comment]
We have already finished the work for Linphone 4.3 For IOS. But we will update it for Linphone 4.3.1 soon.

**Comment by ovari** [comment]
Thanks @ChenDanmei.

1. Do you know when Linphone 4.3 should be showing on the [App Store](https://apps.apple.com/us/app/linphone/id360065638)? Currently version 4.2.2 is showing.
2. Is there an ETA for Linphone 4.3.1?
3. Is there a Linphone release plan?
4. Should this issue be closed?

Thank you

**Comment by ChenDanmei** [comment]
Hello,

Linphone 4.3 is now on the store. Over the next few months, we will be working on 4.3.1, which will fix some issues with Linphone 4.3.

**Comment by ovari** [comment]
Thank you for advising, and congratulations on, the release of Linphone 4.3 in [Google Play](https://play.google.com/store/apps/details?id=org.linphone&hl=hu) and [App Store](https://apps.apple.com/us/app/linphone/id360065638).

> Languages English, Arabic, Dutch, French, German, Japanese, Russian
https://apps.apple.com/us/app/linphone/id360065638

Can you please add `Hungarian` to the list of languages?

What do you think?

Thank you once again.
