### ISSUE TITLE
Not receive VoIP PushKit in TestFlight mode

### ISSUE THREAD

**Issue by Binman1** [BelledonneCommunications/linphone-iphone#642]
Hi everyone,
I'm working on linphone iOS repository and I made some UI changes and added some new features to it for customization! Now, I wanna add VoIP PushKit capability to this project for receive incoming calls when app is in background mode or force closed by user!
I created all necessary certificates for it from the apple developer account and everything is ok in development mode ( when run the app in my iPhone by usb cable ) but when I build the app for production mode and send it to AppStore connect and release it to TestFlight, The app can not receive pushes from APNS! PushKit Token is registered and I save it in my server db successfully but when I send a VoIP push to app, is not received! I try to get log of installed app ( TestFlight mode ) and I've found out push receive to OS but the OS not awake the app and delivered the push to my app! 
Please help me to fix this problem! TNX all!

**Comment by pasha4uu** [comment]
Hi @Binman1 same issue mine too. if you have any solution or gathered any information about that please share to me.

**Comment by fractalysid** [comment]
Hi, same problem here. The app responds to alert notifications but not to background and voip one.
Does anyone has a solution for this?

**Comment by iOS-38** [comment]
Change SandBox Env. to Prod. env on the backend side
