### ISSUE TITLE
Incoming Call and Push calls and Background calls Not working

### ISSUE THREAD

**Issue by pasha4uu** [BelledonneCommunications/linphone-iphone#643]
Hi 
I cloned project from master branch recently .  and build succeed also. but in this Build we are  able get the incoming call (issue --> not going to incoming call screen in the any screen when getting the incoming call) and also TestFlight beta app also same issue.. and also not working Background and push calls... 

 when I'm getting the incoming call  the issues screens some like below :---

![IMG_0212](https://user-images.githubusercontent.com/38080760/85140626-21651300-b263-11ea-83f0-f7faf106fdaf.PNG)

![IMG_0211](https://user-images.githubusercontent.com/38080760/85140635-24600380-b263-11ea-939e-984d69925355.PNG)

**Comment by deepak2503** [comment]
I am experiencing the same. Anyone solution?

**Comment by btea2020** [comment]
I am experiencing the same too.

I can make calls, but I can't receive calls.
How do I change the repository clone?

**Comment by Raviojha62** [comment]
any one got the solution please help . i am not getting any call notification when app is in background or suspended state. i am using latest source code and compile it on real device it work fine when app in foreground.

**Comment by Raviojha62** [comment]
@benoit-martins is this a good way ? 
That without provide any solution you marking as closed for all issue

**Comment by benoit-martins** [comment]
Hi,

We have closed all open tickets as the upcoming release of Linphone 6.0 is a complete redesign of the app. 
This new version will address existing issues with a fresh approach, so we encourage you to explore the updated app when it's available.

Thank you for your understanding and support!

Best regards
