### ISSUE TITLE
Read on device CA Certificates.

### ISSUE THREAD

**Issue by ipodtouchdude** [BelledonneCommunications/linphone-iphone#645]
On iOS you can install a CA certificate to the device, this would be useful if linphone could read that on too. So we could verify self-signed certificate for TLS support for servers. I know you can compile it into the app but then you would have to build and sign the app for everyone that uses the TLS and keep doing so every time there is an update. But if this feature was in the app all they would have to do is download the updated app from the App Store.

**Comment by Attiv** [comment]
hope too
