### ISSUE TITLE
Failed to compile: No known class method for selector currentTraitCollection in UIInterfaceStyleToggleButton.m

### ISSUE THREAD

**Issue by fractalysid** [BelledonneCommunications/linphone-iphone#647]
Hi, I've been trying to compile linphone-iphone on a MacOS High Sierra (XCode 10.1, Swift 4.2) without success. I first got a compile error because of a wrong import, and then I got this error:
- ARC Semantic Issue : No known class method for selector currentTraitCollection in file UIInterfaceStyleToggleButton.m

Does anyone have any idea on how to fix this?
Thank you

![immagine](https://user-images.githubusercontent.com/8359330/85831381-83a3a380-b78e-11ea-9bd7-7a71b89de74e.png)

**Comment by ChenDanmei** [comment]
please update your Xcode

**Comment by fractalysid** [comment]
Thank you very much for your answer! 
I will see if I can and update you on this.

**Comment by fractalysid** [comment]
Thank you very much, it worked by using a MacOS Catalina system and XCode 11.5
