### ISSUE TITLE
Run with Error on step3 

### ISSUE THREAD

**Issue by LiangyongFShen** [BelledonneCommunications/linphone-iphone#65]
When I first run "./prepare.py" on the command line , and output ：
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:git submodule sync && git submodule update --init --recursive

And then I try running:git submodule sync && git submodule update --init --recursive
It began to download somethings
When it downloaded finishing, I rerun ：./prepare.py 
However, there was shown something on the command line:
ERROR: strings binary missing, please run:
	sudo ln -s /usr/bin/strings /Developer/usr/bin/strings

Therefore, I try running the command as the error output ： sudo ln -s /usr/bin/strings /Developer/usr/bin/strings
ERROR: strings binary missing, please run:
	sudo ln -s /usr/bin/strings /Developer/usr/bin/strings
yesdeMBP-2:linphone-iphone hanzimacbook-pro$ sudo ln -s /usr/bin/strings /Developer/usr/bin/strings
Password:
ln: /Developer/usr/bin/strings: No such file or directory

What should I do  next ? It there any error happen to me ?

**Comment by bagage** [comment]
What is your Xcode version? Can you pull and try again please, I tried a fix in 4d9cd80. Thanks!

**Comment by LiangyongFShen** [comment]
The current Xcode version is Xcode6.4 . I had saw the fix , it means i should try with a Xcode version > 7 ?
And I had tried git clone With the The Xcode7.3 also, and there was some error too , like this : your cmake version is 3.2.2 but it needs  > 3.2.215xxx. 
What should i do?

**Comment by bagage** [comment]
No, please keep your Xcode6.4 it's fine. You should be able to compile.

**Comment by LiangyongFShen** [comment]
Now my Xcode version kept with Xcode6.4.

The fix : 
 if not find_executable("strings"):
 +                sdk_strings_path = Popen("xcrun --find strings".split(" "), stdout=PIPE).stdout.read().split("\n")[0]
 +                error("strings binary missing, please run:\n\tsudo ln -s {} {}".format(sdk_strings_path, package_manager_info[detect_package_manager() + "-binary-path"]))
                  reterr = 1

What does it mean ? Is there telling me should split strings with " " at a path ? Can you tell me the detail?

**Comment by bagage** [comment]
Just launch `prepare.py` and see what it tells you.

**Comment by LiangyongFShen** [comment]
It means success ?

yesdeMacBook-Pro-2:linphone-iphone hanzimacbook-pro$ ./prepare.py
 cmake /Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/Users/hanzimacbook-pro/linphone-iphone/liblinphone-sdk/x86_64-apple-darwin.ios -DCMAKE_INSTALL_PREFIX=/Users/hanzimacbook-pro/linphone-iphone/liblinphone-sdk/x86_64-apple-darwin.ios -DLINPHONE_BUILDER_WORK_DIR=/Users/hanzimacbook-pro/linphone-iphone/WORK/ios-x86_64 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-ios-x86_64.cmake -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-ios-x86_64.cmake -DCMAKE_INSTALL_MESSAGE=LAZY -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/Users/hanzimacbook-pro/linphone-iphone/submodules -G "Unix Makefiles" -DLINPHONE_IOS_DEPLOYMENT_TARGET=6.0 "-DLINPHONE_BUILDER_DUMMY_LIBRARIES=libopenh264 libcunit libavcodec libspeex libbelr libpolarssl libswresample libmediastreamer_voip libopus libmbedtls libbellesip libopencore-amrwb libsrtp libvo-amrwbenc libmbedx509 libbzrtp libgsm libtunnel libmsbcg729 liblinphonetester libswscale libvpx libmsamr libbcg729 libspeexdsp liblinphone libx264 libortp libmsopenh264 libebml2 libmediastreamer_base libbelcard libmbedcrypto libavutil libmssilk libbctoolbox-tester libopencore-amrnb libmatroska2 libmswebrtc libantlr3c libmsx264 libcorec libbctoolbox"
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
-- Using sdk version: 8.4
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
-- Using sdk version: 8.4
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Using toolchain file '/Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder/toolchains/toolchain-ios-x86_64.cmake'
-- Using configuration file '/Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder/configs/config-ios-x86_64.cmake'
-- Including builder mbedtls
-- Including builder cunit
-- Including builder bctoolbox
-- Including builder antlr3c
-- Including builder bellesip
-- ENABLING ANTLR3C BUILDER
-- Including builder ortp
-- Including builder speex
-- Including builder gsm
-- Including builder opus
-- Including builder ffmpeg
-- Including builder vpx
-- Including builder matroska2
-- Including builder srtp
-- Including builder bzrtp
-- Including builder ms2
-- Including builder mswebrtc
-- Including builder mssilk
-- Including builder linphone
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
-- Using sdk version: 8.4
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
-- Using sdk version: 8.4
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hanzimacbook-pro/linphone-iphone/WORK/ios-x86_64/cmake/Autotools
-- Enabled features:
 * Unit tests , Build unit tests programs for belle-sip, mediastreamer2 and linphone.
 * Documentation , Enable documentation generation with Doxygen.
 * Mbedtls , Crypto stack implementation based on mbeddtls
 * GPL third parties , Usage of GPL third-party code (FFmpeg and x264).
 * SRTP , SRTP media encryption support.
 * ZRTP , ZRTP media encryption support.
 * DTLS , DTLS media encryption support.
 * GSM , GSM audio encoding/decoding support.
 * iLBC , iLBC audio encoding/decoding support.
 * ISAC , ISAC audio encoding/decoding support.
 * OPUS , OPUS audio encoding/decoding support.
 * Silk , Silk audio encoding/decoding support.
 * Speex , Speex audio encoding/decoding support.
 * Video , Ability to capture and display video.
 * FFmpeg , Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * MKV , MKV playing and recording support.
 * VPX , VPX (VP8) video encoding/decoding support.
 * NLS , Enable internationalization of Linphone and Liblinphone. (Only for the desktop target)

-- Disabled features:
 * Polarssl , Crypto stack implementation based on polarssl
 * Tunnel , Secure tunnel for SIP/RTP (require license).
 * RTP MAP , Always include rtpmap in SDP.
 * Belledonne Antlr , Do not build the Belledonne version of Antlr3c
 * Non free codecs , Allow inclusion of non-free codecs in the build.
 * WebRTC AEC , WebRTC echo canceller support.
 * WASAPI , Windows Audio Session API (WASAPI) sound card support.
 * AMRNB , AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB , AMR wide-band audio encoding/decoding support (require license).
 * Codec2 , Codec2 audio encoding/decoding support.
 * G729 , G.729 audio encoding/decoding support (require license).
 * BV16 , BroadVoice 16 audio encoding/decoding support.
 * H263 , H263 video encoding/decoding support (require license).
 * H263p , H263+ video encoding/decoding support (require license).
 * MPEG4 , MPEG4 video encoding/decoding support (require license).
 * OpenH264 , H.264 video encoding/decoding support with the openh264 library (require license).
 * V4L , V4L camera driver.
 * X264 , H.264 video encoding support with the x264 library (require license).
 * PCAP , PCAP support.
 * VCARD , Enable vCard 4 support Linphone and Liblinphone.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hanzimacbook-pro/linphone-iphone/WORK/ios-x86_64/cmake
 cmake /Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/Users/hanzimacbook-pro/linphone-iphone/liblinphone-sdk/arm64-apple-darwin.ios -DCMAKE_INSTALL_PREFIX=/Users/hanzimacbook-pro/linphone-iphone/liblinphone-sdk/arm64-apple-darwin.ios -DLINPHONE_BUILDER_WORK_DIR=/Users/hanzimacbook-pro/linphone-iphone/WORK/ios-arm64 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-ios-arm64.cmake -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-ios-arm64.cmake -DCMAKE_INSTALL_MESSAGE=LAZY -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/Users/hanzimacbook-pro/linphone-iphone/submodules -G "Unix Makefiles" -DLINPHONE_IOS_DEPLOYMENT_TARGET=6.0 "-DLINPHONE_BUILDER_DUMMY_LIBRARIES=libopenh264 libcunit libavcodec libspeex libbelr libpolarssl libswresample libmediastreamer_voip libopus libmbedtls libbellesip libopencore-amrwb libsrtp libvo-amrwbenc libmbedx509 libbzrtp libgsm libtunnel libmsbcg729 liblinphonetester libswscale libvpx libmsamr libbcg729 libspeexdsp liblinphone libx264 libortp libmsopenh264 libebml2 libmediastreamer_base libbelcard libmbedcrypto libavutil libmssilk libbctoolbox-tester libopencore-amrnb libmatroska2 libmswebrtc libantlr3c libmsx264 libcorec libbctoolbox"
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Using toolchain file '/Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder/toolchains/toolchain-ios-arm64.cmake'
-- Using configuration file '/Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder/configs/config-ios-arm64.cmake'
-- Including builder mbedtls
-- Including builder cunit
-- Including builder bctoolbox
-- Including builder antlr3c
-- Including builder bellesip
-- ENABLING ANTLR3C BUILDER
-- Including builder ortp
-- Including builder speex
-- Including builder gsm
-- Including builder opus
-- Including builder ffmpeg
-- Including builder vpx
-- Including builder matroska2
-- Including builder srtp
-- Including builder bzrtp
-- Including builder ms2
-- Including builder mswebrtc
-- Including builder mssilk
-- Including builder linphone
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hanzimacbook-pro/linphone-iphone/WORK/ios-arm64/cmake/Autotools
-- Enabled features:
 * Unit tests , Build unit tests programs for belle-sip, mediastreamer2 and linphone.
 * Documentation , Enable documentation generation with Doxygen.
 * Mbedtls , Crypto stack implementation based on mbeddtls
 * GPL third parties , Usage of GPL third-party code (FFmpeg and x264).
 * SRTP , SRTP media encryption support.
 * ZRTP , ZRTP media encryption support.
 * DTLS , DTLS media encryption support.
 * GSM , GSM audio encoding/decoding support.
 * iLBC , iLBC audio encoding/decoding support.
 * ISAC , ISAC audio encoding/decoding support.
 * OPUS , OPUS audio encoding/decoding support.
 * Silk , Silk audio encoding/decoding support.
 * Speex , Speex audio encoding/decoding support.
 * Video , Ability to capture and display video.
 * FFmpeg , Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * MKV , MKV playing and recording support.
 * VPX , VPX (VP8) video encoding/decoding support.
 * NLS , Enable internationalization of Linphone and Liblinphone. (Only for the desktop target)

-- Disabled features:
 * Polarssl , Crypto stack implementation based on polarssl
 * Tunnel , Secure tunnel for SIP/RTP (require license).
 * RTP MAP , Always include rtpmap in SDP.
 * Belledonne Antlr , Do not build the Belledonne version of Antlr3c
 * Non free codecs , Allow inclusion of non-free codecs in the build.
 * WebRTC AEC , WebRTC echo canceller support.
 * WASAPI , Windows Audio Session API (WASAPI) sound card support.
 * AMRNB , AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB , AMR wide-band audio encoding/decoding support (require license).
 * Codec2 , Codec2 audio encoding/decoding support.
 * G729 , G.729 audio encoding/decoding support (require license).
 * BV16 , BroadVoice 16 audio encoding/decoding support.
 * H263 , H263 video encoding/decoding support (require license).
 * H263p , H263+ video encoding/decoding support (require license).
 * MPEG4 , MPEG4 video encoding/decoding support (require license).
 * OpenH264 , H.264 video encoding/decoding support with the openh264 library (require license).
 * V4L , V4L camera driver.
 * X264 , H.264 video encoding support with the x264 library (require license).
 * PCAP , PCAP support.
 * VCARD , Enable vCard 4 support Linphone and Liblinphone.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hanzimacbook-pro/linphone-iphone/WORK/ios-arm64/cmake
 cmake /Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/Users/hanzimacbook-pro/linphone-iphone/liblinphone-sdk/armv7-apple-darwin.ios -DCMAKE_INSTALL_PREFIX=/Users/hanzimacbook-pro/linphone-iphone/liblinphone-sdk/armv7-apple-darwin.ios -DLINPHONE_BUILDER_WORK_DIR=/Users/hanzimacbook-pro/linphone-iphone/WORK/ios-armv7 -DCMAKE_TOOLCHAIN_FILE=toolchains/toolchain-ios-armv7.cmake -DLINPHONE_BUILDER_CONFIG_FILE=configs/config-ios-armv7.cmake -DCMAKE_INSTALL_MESSAGE=LAZY -DLINPHONE_BUILDER_EXTERNAL_SOURCE_PATH=/Users/hanzimacbook-pro/linphone-iphone/submodules -G "Unix Makefiles" -DLINPHONE_IOS_DEPLOYMENT_TARGET=6.0 "-DLINPHONE_BUILDER_DUMMY_LIBRARIES=libopenh264 libcunit libavcodec libspeex libbelr libpolarssl libswresample libmediastreamer_voip libopus libmbedtls libbellesip libopencore-amrwb libsrtp libvo-amrwbenc libmbedx509 libbzrtp libgsm libtunnel libmsbcg729 liblinphonetester libswscale libvpx libmsamr libbcg729 libspeexdsp liblinphone libx264 libortp libmsopenh264 libebml2 libmediastreamer_base libbelcard libmbedcrypto libavutil libmssilk libbctoolbox-tester libopencore-amrnb libmatroska2 libmswebrtc libantlr3c libmsx264 libcorec libbctoolbox"
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Using toolchain file '/Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder/toolchains/toolchain-ios-armv7.cmake'
-- Using configuration file '/Users/hanzimacbook-pro/linphone-iphone/submodules/cmake-builder/configs/config-ios-armv7.cmake'
-- Including builder mbedtls
-- Including builder cunit
-- Including builder bctoolbox
-- Including builder antlr3c
-- Including builder bellesip
-- ENABLING ANTLR3C BUILDER
-- Including builder ortp
-- Including builder speex
-- Including builder gsm
-- Including builder opus
-- Including builder ffmpeg
-- Including builder vpx
-- Including builder matroska2
-- Including builder srtp
-- Including builder bzrtp
-- Including builder ms2
-- Including builder mswebrtc
-- Including builder mssilk
-- Including builder linphone
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Using sysroot path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk
-- Using sdk version: 8.4
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hanzimacbook-pro/linphone-iphone/WORK/ios-armv7/cmake/Autotools
-- Enabled features:
 * Unit tests , Build unit tests programs for belle-sip, mediastreamer2 and linphone.
 * Documentation , Enable documentation generation with Doxygen.
 * Mbedtls , Crypto stack implementation based on mbeddtls
 * GPL third parties , Usage of GPL third-party code (FFmpeg and x264).
 * SRTP , SRTP media encryption support.
 * ZRTP , ZRTP media encryption support.
 * DTLS , DTLS media encryption support.
 * GSM , GSM audio encoding/decoding support.
 * iLBC , iLBC audio encoding/decoding support.
 * ISAC , ISAC audio encoding/decoding support.
 * OPUS , OPUS audio encoding/decoding support.
 * Silk , Silk audio encoding/decoding support.
 * Speex , Speex audio encoding/decoding support.
 * Video , Ability to capture and display video.
 * FFmpeg , Some video processing features via FFmpeg: JPEG encoding/decoding, video scaling, H264 decoding...
 * MKV , MKV playing and recording support.
 * VPX , VPX (VP8) video encoding/decoding support.
 * NLS , Enable internationalization of Linphone and Liblinphone. (Only for the desktop target)

-- Disabled features:
 * Polarssl , Crypto stack implementation based on polarssl
 * Tunnel , Secure tunnel for SIP/RTP (require license).
 * RTP MAP , Always include rtpmap in SDP.
 * Belledonne Antlr , Do not build the Belledonne version of Antlr3c
 * Non free codecs , Allow inclusion of non-free codecs in the build.
 * WebRTC AEC , WebRTC echo canceller support.
 * WASAPI , Windows Audio Session API (WASAPI) sound card support.
 * AMRNB , AMR narrow-band audio encoding/decoding support (require license).
 * AMRWB , AMR wide-band audio encoding/decoding support (require license).
 * Codec2 , Codec2 audio encoding/decoding support.
 * G729 , G.729 audio encoding/decoding support (require license).
 * BV16 , BroadVoice 16 audio encoding/decoding support.
 * H263 , H263 video encoding/decoding support (require license).
 * H263p , H263+ video encoding/decoding support (require license).
 * MPEG4 , MPEG4 video encoding/decoding support (require license).
 * OpenH264 , H.264 video encoding/decoding support with the openh264 library (require license).
 * V4L , V4L camera driver.
 * X264 , H.264 video encoding support with the x264 library (require license).
 * PCAP , PCAP support.
 * VCARD , Enable vCard 4 support Linphone and Liblinphone.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hanzimacbook-pro/linphone-iphone/WORK/ios-armv7/cmake
INFO: Installing Git pre-commit hook
WARNING: 
***************************************************************************
***************************************************************************
***** CAUTION, this liblinphone SDK is built using 3rd party GPL code *****
***** Even if you acquired a proprietary license from Belledonne      *****
***** Communications, this SDK is GPL and GPL only.                   *****
***** To disable 3rd party gpl code, please use:                      *****
***** $ ./prepare.py -DENABLE_GPL_THIRD_PARTIES=NO                    *****
***************************************************************************
***************************************************************************
yesdeMacBook-Pro-2:linphone-iphone hanzimacbook-pro$

**Comment by bagage** [comment]
Yes, check the README.

**Comment by LiangyongFShen** [comment]
Thanks a lot , checking the README now .
