### ISSUE TITLE
Pod update/install after merge release 4.3 branch

### ISSUE THREAD

**Issue by Daniele-Tentoni** [BelledonneCommunications/linphone-iphone#650]
Hi all @Viish . I've merged branch release 4.3 from belledonne repo to my org repo resolving some conflicts. Now the pod update command return me this:
Update all pods
Updating local specs repositories
  $ /usr/bin/git -C /Users/administrator/.cocoapods/repos/linphone-bc-public-podspec fetch origin
  --progress
  $ /usr/bin/git -C /Users/administrator/.cocoapods/repos/linphone-bc-public-podspec rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/administrator/.cocoapods/repos/linphone-bc-public-podspec reset --hard
  origin/master
  HEAD is now at a3462ed [Update] linphone-sdk (4.4.1-pre.10+160da85)
  $ /usr/bin/git -C /Users/administrator/.cocoapods/repos/master fetch origin --progress
  remote: Enumerating objects: 41, done.        
  remote: Counting objects: 100% (41/41), done.        
  remote: Compressing objects: 100% (27/27), done.        
  remote: Total 27 (delta 18), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     a9ecfebbb847..1b3ff4c8df55  master     -> origin/master
  $ /usr/bin/git -C /Users/administrator/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/administrator/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 1b3ff4c8df55 [Add] AtomSDKBySecure 4.0.0-beta-5
Analyzing dependencies
[!] Unable to find host target(s) for msgNotificationService, msgNotificationContent. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target. A host target is a "parent" target which embeds a "child" target. These are example types of targets that need a host target:
- Framework
- App Extension
- Watch OS 1 Extension
- Messages Extension (except when used with a Messages Application)

[!] `<PBXGroup name=`Frameworks` UUID=`29B97323FDCFA39411CA2CEA`>` attempted to initialize an object with an unknown UUID. `D252FEC7DD06DD5695A320A1` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXGroup name=`Frameworks` UUID=`29B97323FDCFA39411CA2CEA`>` attempted to initialize an object with an unknown UUID. `65CEDD144CABFAA70A29AF27` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`NethCTI` UUID=`1D6058900D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `63DCC71D1A07B08E00916627` for attribute: `build_phases`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`NethCTI` UUID=`1D6058900D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `EA8CB83A239F9A3000C330CC` for attribute: `dependencies`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`NethCTI` UUID=`1D6058900D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `EA8CB83C239F9A3000C330CC` for attribute: `dependencies`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXProject name=`linphone` UUID=`29B97313FDCFA39411CA2CEA`>` attempted to initialize an object with an unknown UUID. `F0F951FF1A6AEB1000254160` for attribute: `targets`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXProject name=`linphone` UUID=`29B97313FDCFA39411CA2CEA`>` attempted to initialize an object with an unknown UUID. `F0BB8BD41936208100974404` for attribute: `targets`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXProject name=`linphone` UUID=`29B97313FDCFA39411CA2CEA`>` attempted to initialize an object with an unknown UUID. `F08F118319C09C6A007D70C2` for attribute: `targets`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`msgNotificationService` UUID=`EA5F25D8232BD3E200475F2E`>` attempted to initialize an object with an unknown UUID. `CD5CF0B3FE8B6052CD8219CE` for attribute: `build_phases`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`msgNotificationService` UUID=`EA5F25D8232BD3E200475F2E`>` attempted to initialize an object with an unknown UUID. `6112A01A243B2CCF00DBD5F5` for attribute: `build_phases`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`msgNotificationContent` UUID=`EA8CB826239F96CA00C330CC`>` attempted to initialize an object with an unknown UUID. `B0A561F0290F0342EACE9005` for attribute: `build_phases`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`msgNotificationContent` UUID=`EA8CB826239F96CA00C330CC`>` attempted to initialize an object with an unknown UUID. `EA8CB823239F96CA00C330CC` for attribute: `build_phases`. This can be the result of a merge and  the unknown UUID is being discarded.

[!] `<PBXNativeTarget name=`msgNotificationContent` UUID=`EA8CB826239F96CA00C330CC`>` attempted to initialize an object with an unknown UUID. `6112A019243B2C8400DBD5F5` for attribute: `build_phases`. This can be the result of a merge and  the unknown UUID is being discarded.

I'll attach my current project file.
[Archivio.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/4879902/Archivio.zip)

pod install command say me the same error
[!] Unable to find host target(s) for msgNotificationService, msgNotificationContent. Please add the host targets for the embedded targets to the Podfile.
Certain kinds of targets require a host target. A host target is a "parent" target which embeds a "child" target. These are example types of targets that need a host target:
- Framework
- App Extension
- Watch OS 1 Extension
- Messages Extension (except when used with a Messages Application)

**Comment by ChenDanmei** [comment]
Something is missing in your project file, like linphone-Info.plist ...
You keep targets for msgNotification without the msgNotification file.
