### ISSUE TITLE
[Q] CallKit implementation

### ISSUE THREAD

**Issue by simoneraffaelli** [BelledonneCommunications/linphone-iphone#654]
Hi,I have some question regarding how linphone handle incoming call and push notifications with CallKit.
First of all we based our app implementation on Linphone [4.3.1](https://github.com/BelledonneCommunications/linphone-iphone/releases/tag/4.3.1) and we use Asterisk as PBX. We know that with iOS13 as soon as we receive the push notification we need to notify CallKit with an incoming call that might not exist. I saw that in your code you use as call identifier the SIP Call-ID, but with our Aterisk implementation we cannot pass SIP Call-ID to the notification because the notification is sent before the "SIP connection". So, can we use different identifier for call? I saw that you check the call Id present in the linphone CallLog ([link](https://github.com/BelledonneCommunications/linphone-iphone/blob/master/Classes/CallManager.swift#L107)), can we edit the callId valorization?
(becuase without the correct callid we need to answer to 2 call screen the first spawned with call=nil and the second that is the correct one)

As an extra point can you explain how linphone handle notification and incoming calls?
From what I saw form the code:
You receive the notification and call _displayIncomingcall(callId)_ which, not finding any uuids or calls already set, will call displayIncomingCall(call: nil, handle: "Calling", hasVideo: true, callId: callId) which spawns the _Calling.._ screen unsure if there is a call or not. Then in the app will be triggered the _onStatecallChanged_ with _IncomingReceived_ as state. Here if there if there is an uuid linked to the _SIP_ CallId in UUIDS list (meaning the call is already managed) it will go ahead and accept or decline the call, and if there isn't ant uuid matching the _SIP_ CallID then it will update the Calling.. screen with the _SIP_ data. Doing this it will of course also update the nil call spawned with callkit with the SIP call present in linphone callList. And so, after having done all this stuff, we can finally say that the first screen (spawned with) and the real SIP call are connected.
Am I right?

thank you :)

**Comment by karthikk2020** [comment]
@raffaa what is the payload you are passing in push notification from asterisk  ?. Yes linphone checks for call-id.  We keep trying invite till app register after push notification sent . we can not send call id in PN as call id is not generated until unless actual call is made .   Are you passing PN type voip ?.  What payload you are sending  ?.

**Comment by Raffaa** [comment]
> @Raffaa what is the payload you are passing in push notification from asterisk ?. Yes linphone checks for call-id. We keep trying invite till app register after push notification sent . we can not send call id in PN as call id is not generated until unless actual call is made . Are you passing PN type voip ?. What payload you are sending ?.

Yep PN type is VoIP. In the paylod I also pass currenttimemills as secondary callid, then when the SIP calls arrives i replace my secondary callid in uuids dictionary with the sip one. In this way the problem seems solved.

**Comment by diomerc** [comment]
Hello, I have same problem in the first time I receive an incoming push but with nill in call-id than there is second push with call-id how did you replaced the uuid with the sip one?

**Comment by Raffaa** [comment]
> In the paylod I also pass currenttimemills as secondary callid, then when the SIP calls arrives i replace my secondary callid in uuids dictionary with the sip one.

**Comment by Raffaa** [comment]
> In the paylod I also pass currenttimemills as secondary callid, then when the SIP calls arrives i replace my secondary callid in uuids dictionary with the sip one.

**Comment by ravi6880** [comment]
@Raffaa @diomerc @karthikk2020, Please explain how can I achieve this, I am using the latest source code and able to run the app, but still not getting any VOIP notification in the app while testflight build which provide by linphone, its working fine, but the code is not working. Please help

**Comment by E2-Mohamed** [comment]
Can someone send me the sample of VOIP APNs payload which linphone app receives?

**Comment by asadcr** [comment]
```
{
aps : {
"call-id": "Call-id of the SIP INVITE Packet"
},
}
```

This is the packet that is getting used @E2-Mohamed

**Comment by E2-Mohamed** [comment]
@asadcr I'm having a hard time getting the right call-id before I send a VOIP notification, once I send the VOIP notification then app wakes up and gets registered with the server after that the SIP Invite is generated, without Trigerring VOIP if I trigger the Dial() from asterisk that instantly gets terminated saying the other party is unavailable. 

So, it's hard to set the Dial plan in an asterisk to make it work, some advice would be helpful.
