### ISSUE TITLE
App Store reject App due to CallKit active

### ISSUE THREAD

**Issue by showgoodjiang** [BelledonneCommunications/linphone-iphone#655]
We use linphone ios sdk 4.3  in our app as following: 

pod 'linphone-sdk' , '4.3'

After submit to App Store, App Store rejected the App.
How can we do to use linphone ios sdk without CallKit? 
Or how to set CallKit to be deactivated with linphone sdk, while linphone can make calls?

Tips: We wrap linphone with EasySip:
https://github.com/WellerZhao/EasySip/tree/master/EasySip/liblinphone

----------------App Store Rejection Information-----------------

Guideline 5.0 - Legal

Recently, the Chinese Ministry of Industry and Information Technology (MIIT) requested that CallKit functionality be deactivated in all apps available on the China App Store.

During our review, we found that your app currently includes CallKit functionality and has China listed as an available territory in App Store Connect.

Next Steps

This app cannot be approved with CallKit functionality active in China. Please make the appropriate changes and resubmit this app for review.

If you have already ensured that CallKit functionality is not active in China, you may reply to this message in Resolution Center to confirm.

Voice over Internet Protocol (VoIP) call functionality continues to be allowed but can no longer take advantage of CallKit’s intuitive look and feel. CallKit can continue to be used in apps outside of China.

**Comment by karthikk2020** [comment]
So you want to distribute your app in china ?.  Why can not just remove call kit and build linphone ..

**Comment by showgoodjiang** [comment]
Yes, we removed ProviderDelegate, CallKit from App, set use_callkit=0 in linphone config file, then passed App Store review.
