### ISSUE TITLE
Callback issue

### ISSUE THREAD

**Issue by Nipagohel** [BelledonneCommunications/linphone-iphone#659]
We are  facing issue  when we initiate call from call log\history\from dialing call Panel at that time also we are getting Call Acceptance screen which practically supposed to display at the time receiving call not at the time of dialing call, We noticed that this issue comes only after receiving first VOIP call. Are you facing similar issue with current Meet Me app too?

Here is the  video link for callback.

https://tinyurl.com/y5uuw9rb

**Comment by balusreekanth** [comment]
Hello , It seems you are calling from a SIP account to  registered sip account on app . It is normal right  to receive incoming call alert as soon as you dial .  Can you elaborate more what is the issue .

**Comment by Nipagohel** [comment]
when we callbck from history screen or dialpad at that also voip screen appear

Here is the video link for callback.

https://tinyurl.com/y5uuw9rb
