### ISSUE TITLE
[QUESTION] listening to a rtp stream

### ISSUE THREAD

**Issue by kampfgnu** [BelledonneCommunications/linphone-iphone#66]
i was able to successfully start a call to our local asterisk server by registering a call with the identity:
"sip:101@192.168.1.251" and destination "1001" from my iPhone.
this enables me to listen to the mic-input of my phone from VLC by entering "rtp://@239.0.0.1:1234".

i was able to listen on other devices via MobileVLCKit, but it is a pain to include it in my xcode project and it is very huge in filesize too.
my question: is it possible to use your lib to listen to this rtp stream from other iDevices?

cheers

**Comment by bagage** [comment]
Please use the mailing list for questions instead, this is a more appropriate place where other users might be able to help as well ;).

**Comment by kampfgnu** [comment]
ok, thanks

**Comment by sree127** [comment]
hey @kampfgnu, were you able to achieve this? Any idea how to stream rtp from an IP camera? Any help would be much appreciated.

**Comment by kampfgnu** [comment]
no, i gave up using this library and rolled my own audio streaming library.
basically i encode the audio signal with AAC-ELD and send it through local network via UDP packets...
