### ISSUE TITLE
Cannot find protocol declaration for 'CXProviderDelegate'

### ISSUE THREAD

**Issue by Nipagohel** [BelledonneCommunications/linphone-iphone#661]
Cannot find protocol declaration for 'CXProviderDelegate'

The errors are showing in my projects 

-swift.h
(the project mixes Swift and Objective-c).
Any idea why this is happening? Unless I'm missing something I can't see any basic mistakes (typo etc.) that could cause this.

-Cleaned project, remove derived data , do all the possible scenario
<img width="1658" alt="Screenshot 2020-07-29 at 7 32 52 PM" src="https://user-images.githubusercontent.com/49637108/88810022-6cfbcc80-d1d2-11ea-89e0-8020c7c5e0a8.png">

**Comment by Nipagohel** [comment]
Hello Team,

Can anyone have idea about above error ?

**Comment by ravi6880** [comment]
@Nipagohel  . I am getting the same error, have you got any solution, if yes, please share here

**Comment by ofiron** [comment]
In the -Bridging-Header.h file, add 
`#import <CallKit/CallKit.h>`
Strange but it seem to work.

**Comment by ravi6880** [comment]
@ofiron  thanks, i have got the solution right now i am getting a different problem no body was help me , could you please do something 
[](https://github.com/BelledonneCommunications/linphone-iphone/issues/684)

**Comment by ofiron** [comment]
@ravi6880 I am not using this repo (or I used it 10 years ago), I was searching for solution for the problem.
What exactly the problem?
* Do you get push notifications [even of a text  push]?
* What exactly the problem?
* Did you review the sample app and your app?
* Is the sample app is working (sometimes I see crashes in sample apps?

**Comment by ravi6880** [comment]
Thanks for reply @ofiron 
Do you get push notifications [even of a text push]?
Yes i got the notification 
What exactly the problem?
Problem is voip notification when app is in background or terminated it never work , i am not sure how to achieve this , in the github repo its not working. but the app on appstore (Linphone app) its working fine 
Did you review the sample app and your app?
Sample is also not working 
Is the sample app is working (sometimes I see crashes in sample apps?
No
