### ISSUE TITLE
Implicit declaration of function 'linphone_core_did_register_for_remote_push' is invalid in C99

### ISSUE THREAD

**Issue by Nipagohel** [BelledonneCommunications/linphone-iphone#671]
Implicit declaration of function 'linphone_core_did_register_for_remote_push' is invalid in C99
<img width="1362" alt="Screenshot 2020-08-10 at 10 40 31 AM" src="https://user-images.githubusercontent.com/49637108/89753456-fa55ef80-daf5-11ea-8cce-8b58c37d7c18.png">

**Comment by ChenDanmei** [comment]
This api is not yet integrated with linphone-sdk. Please use the branch master or release.

**Comment by zxpgo** [comment]
> This api is not yet integrated with linphone-sdk. Please use the branch master or release.
Is the following problem also because linphone-sdk is not integrated? Thanks for your answer.

![image](https://user-images.githubusercontent.com/37869997/100360726-4e003080-3034-11eb-89c6-24ec0310b66d.png)

**Comment by zxpgo** [comment]
can you build success?

**Comment by zxpgo** [comment]
> This api is not yet integrated with linphone-sdk. Please use the branch master or release.

![image](https://user-images.githubusercontent.com/37869997/100361233-dd0d4880-3034-11eb-8213-231e5f2c4295.png)
