### ISSUE TITLE
Call does not start when app is terminated

### ISSUE THREAD

**Issue by simonepauro** [BelledonneCommunications/linphone-iphone#673]
I implemented Linphone for domotic purpose, so I'm relying on simple Push Notification for incoming calls.

If the app is completely terminated it still receives the push notification, but when the user opens the app, it won't receive the invite and the call won't start ringing.
I precise that the app successfully registers at startup.

Any idea? thank you

**Comment by ravi6880** [comment]
Did you find any solution?

**Comment by simonepauro** [comment]
i was missing the core destruction part

**Comment by KhairulRijl** [comment]
@simonepauro can you explain how to solve that? if use swift wrapper
