### ISSUE TITLE
Set Path Fail

### ISSUE THREAD

**Issue by huanghun-666** [BelledonneCommunications/linphone-iphone#675]
![image](https://user-images.githubusercontent.com/14903407/91247532-0d6aef80-e785-11ea-8b0b-23bcb46204e1.png)

In Linphone demo, the path setting failed, what should I do?

const char *linphone_factory_get_config_dir(LinphoneFactory *factory, void *context);
const char *linphone_factory_get_data_dir(LinphoneFactory *factory, void *context);

**Comment by TusharSharma651** [comment]
Change kLinphoneMsgNotificationAppGroupId value to your group identifier, replace in all project.
