### ISSUE TITLE
ortp-warning-Fail 

### ISSUE THREAD

**Issue by huanghun-666** [BelledonneCommunications/linphone-iphone#676]
ortp-warning-Fail to set IPv4 packet info on RTP socket: Invalid argument

When the program is running, the above reminder always appears, what is the configuration caused

**Comment by 123sunxiaolin** [comment]
Hello, I face the same issues, how do you solve it ? Thanks very much. Wechat:401788217

**Comment by Nallo** [comment]
Same happen to me: linphone-sdk v4.4.2 iOS only
