### ISSUE TITLE
Mute conference call 

### ISSUE THREAD

**Issue by TusharSharma651** [BelledonneCommunications/linphone-iphone#679]
I have started a conference call using SDK method **conference.inviteParticipants(addresses: addressesValues, params: callParams)**

I am looking for a way to mute, pause, hold a conference call just like we do for normal Call in linphone.

Is there any solution?

**Comment by Raviojha62** [comment]
@TusharSharma651  are you using the latest sdk and giving support to callkit , if yes , please guide me  how can i resolve it .I am using the latest code but it not working in background or terminated state

**Comment by TusharSharma651** [comment]
> @TusharSharma651 are you using the latest sdk and giving support to callkit , if yes , please guide me how can i resolve it .I am using the latest code but it not working in background or terminated state

Not able to calls in background/killed state. I think you need to implement push notifications separately.
