### ISSUE TITLE
ios 13, stops to react on coming VoIP pushes

### ISSUE THREAD

**Issue by KolyanVM** [BelledonneCommunications/linphone-iphone#680]
Hi!
There is a problem on IOS 13 only, build linphone build 4.2.2, SDK release 4.3.1.
On devices with other IOS  versions, all work fine.
Linphone version above 4.2.2 does not work at all on all ios versions.

A device gets VoIP pushes to wake up linphone when it is sleeping and we see SIP REGISTER messages on our SIP server. All works fine.
Then, after several pushes and incoming not responding sip calls, run linphone several times getting it to sleep. Linphone stops to react on coming VoIP pushes, so do not wake up and we not see the SIP REGISTER messages on our SIP server.
Restart device does not solve this problem. It resolves when I reinstall linphone on the device.

I will be grateful if you can tell me how to fix this problem in the code

**Comment by AhmedShammala** [comment]
Hey,
in iOS 13 you should show call kit immediately after you got voip push or after 3 attempts your app will blocked and will not receive the voip push unless your reinstall the app.
search about iOS 13 linphone changes.

**Comment by Raviojha62** [comment]
@AhmedShammala  @KolyanVM  I am using the same code which is working fine when app is in foreground , but when app in killed or in background . notification not work .
While it mention that it support to the callkit and ios 13. 
On appstore linphone app it working fine but this source code something wrong or i need to make some changes dont know .
Please let me know if you can guide me

**Comment by ndapost** [comment]
Before IOS 13, the code works well if you send two push messages with a 4-second wait. This is a bug. Since the app doesn't send SIP REGISTER during the first push, linphone sends SIP REGISTER after the second push, and it may already receive an incoming call.

**Comment by Raviojha62** [comment]
> Before IOS 13, the code works well if you send two push messages with a 4-second wait. This is a bug. Since the app doesn't send SIP REGISTER during the first push, linphone sends SIP REGISTER after the second push, and it may ready to receive an incoming call.

but when i download the linphone app from appstore it working fine, i want to know if any one using the same code from github, is there anything need to change for the callkit , because its not working in this code on my side

**Comment by bnsy** [comment]
I am also facing the same issue, please let us know did anyone found the solution @Raviojha62 @ndapost @AhmedShammala @KolyanVM
