### ISSUE TITLE
It takes 6 seconds to answer

### ISSUE THREAD

**Issue by simonepauro** [BelledonneCommunications/linphone-iphone#687]
I noticed that when I receive a call and the app is closed or in background, it takes about 6 seconds for the call to start.
Do you experience the same delay? 
Is there a way to improve this?

**Comment by ravi6880** [comment]
@simonepauro Can you please guide me, i am using the latest source code, able to run it on a real device but still i am not getting calls in the background or suspended state, please help

**Comment by simonepauro** [comment]
I think you should destroy the core in the applicationWillTerminate method.
The documentation is poor, you should check the linphone-iphone source code and check what's they are doing when the app goes to background or is terminated.

**Comment by ravi6880** [comment]
- (void)applicationWillTerminate:(UIApplication *)application {
	LOGI(@"%@", NSStringFromSelector(_cmd));
	LinphoneManager.instance.conf = TRUE;
	linphone_core_terminate_all_calls(LC);
	[CallManager.instance removeAllCallInfos];
	[LinphoneManager.instance destroyLinphoneCore];
}

In the Code I think it happens , In terminate method destroyLinphoneCore is being called.

**Comment by simonepauro** [comment]
make sure you're registering / resuming the registration at startup

**Comment by ravi6880** [comment]
Thanks, I will check it
