### ISSUE TITLE
Can't enable/disable video during call

### ISSUE THREAD

**Issue by simoneraffaelli** [BelledonneCommunications/linphone-iphone#689]
I have a strange problem, during a call the video button doesn't work and if clicked it freezes all the bottom bar and the only thing I can do is end the call. After some digging I found that this problem happen only on devices with iOS version prior to 14.0 and only on the caller side (the callee has no problem at all). I found that when the problem occur the call remain in state Updating, it never switch back to StreamsRunning. I'll attach the log of the two different usecase, I can spoiler you that in the working case is sent an INVITE message, in the non-working case no message is sent.

If I remember well before the introduction of callkit it was all working well, then with the big update (4.3.0) the video button has stopped working (on caller side). All I can assume is that maybe there are some Call-Id not perfectly linked/matched that prevent the INVITE to be sent?

I'm using a personalization of linphone 4.3.1, and asterisk as PBX (without a sip proxy as per linphone official app)

Working Case log: https://pastebin.com/Qn90XpTE
Non-Working Case log: https://pastebin.com/cHjEpiNx

**Comment by ravi6880** [comment]
@Raffaa Can you help me how to achieve the call kit because I am using the same code and it's not working when the app is in the background or killed state. Linphone said its supports to call kit and its testflight build is working fine, but when I am using this code on a real device I am not getting any call notification, please let me know

**Comment by Raffaa** [comment]
> @Raffaa Can you help me how to achieve the call kit because I am using the same code and it's not working when the app is in the background or killed state. Linphone said its supports to call kit and its testflight build is working fine, but when I am using this code on a real device I am not getting any call notification, please let me know

Well actually I can't help much, your problem can depends on so many factors...
And also this is not the way to search for solutions, open a new issue instead of writing response completely off-topic
