### ISSUE TITLE
UI flaw

### ISSUE THREAD

**Issue by ivylee1108** [BelledonneCommunications/linphone-iphone#69]
Hi
I get the latest code and build the linphone project.
Install the linphone app to iphone6, I found the position of SideMenuView should be just under the StatusBarView, but it is not. 
The UI on linphone app installed from app store is normal.
Can you help to resolve this UI flew, thank you.

**Comment by LiangyongFShen** [comment]
Whether your project is not include the iPhone6 launch images ?

By the way, Can you tell me what is your OS X version and your Xcode version which you built successfully , what is more can you send me your project which was built successfully to my email 2387584231@qq.com, thanks?

**Comment by bagage** [comment]
Fixed in 6e7f9b6, thanks.
