### ISSUE TITLE
Add Password to auth

### ISSUE THREAD

**Issue by piyush-ebizz** [BelledonneCommunications/linphone-iphone#690]
- How can I set a password to the authentication while registering?. I have set it but it always showing the wrong param and getting "linphone_core_add_proxy_config(LC, config) = -1".
 Here is my registration code:

func SIPAccountRegistration() {

        phoneNumber = self.usernameTF.text!
        extensionNumber = String(phoneNumber!.suffix(5))        
        let displayName = phoneNumber
        let config = linphone_core_create_proxy_config(LC)
        let addr = linphone_address_new(nil)
        let tmpAddr = linphone_address_new("sip:\(domain)")
        if tmpAddr == nil {
            // displayAssistantConfigurationError()
            CRNotifications.showNotification(type: CRNotifications.error, title: "Error!", message: "Login credentials are not correct", dismissDelay: 3)
            return
        }
        linphone_address_set_password(addr, passwordTF.text!)
        linphone_address_set_username(addr, usernameTF.text!)
        linphone_address_set_port(addr, linphone_address_get_port(tmpAddr))
        linphone_address_set_domain(addr, linphone_address_get_domain(tmpAddr))
        if displayName != "" && !(displayName == "") {
            linphone_address_set_display_name(addr, displayName)
        }
        linphone_proxy_config_set_identity_address(config, addr)
        // set transport
        
        let type = "UDP"
        let UTF8String = type.lowercased()
        linphone_proxy_config_set_route(
            config,
            "\(domain.utf8CString);transport=\(UTF8String)")
        linphone_proxy_config_set_server_addr(
            config,
            "\(domain.utf8CString);transport=\(UTF8String)")
   
        linphone_proxy_config_enable_publish(config, 0)
        linphone_proxy_config_enable_register(config, 1)
        let info = linphone_auth_info_new(
            linphone_address_get_username(addr), // username
            nil, // user id
            linphone_address_get_password(addr), // passwd
            nil, // ha1
            linphone_address_get_domain(addr), // realm - assumed to be domain
            linphone_address_get_domain(addr) /* domain */)
        linphone_core_add_auth_info(LC, info)
        linphone_address_unref(addr)
        linphone_address_unref(tmpAddr)
        if (config != nil) {
            LinphoneManager.instance().configurePushToken(for: config)
            if linphone_core_add_proxy_config(LC, config) != -1 {
                linphone_core_set_default_proxy_config(LC, config)
                CRNotifications.showNotification(type: CRNotifications.success, title: "Success!", message: "You are successfully Logged In", dismissDelay: 3)
                self.performSegue(withIdentifier: "toMain", sender: nil)
            } else {
                CRNotifications.showNotification(type: CRNotifications.error, title: "Error!", message: "Login credentials are not correct", dismissDelay: 3)
                            }
        } else {
            CRNotifications.showNotification(type: CRNotifications.error, title: "Error!", message: "Login credentials are not correct", dismissDelay: 3)
                    }
    }

**Comment by Raviojha62** [comment]
Can you help me how to achieve the call kit because I am using the same code and it's not working when the app is in the background or killed state. Linphone said its supports to call kit and its testflight build is working fine, but when I am using this code on a real device I am not getting any call notification, please let me know

**Comment by Adnan-addi** [comment]
having same issue regarding the password, no idea why its not working from assistant screen ,
i have to goto settings and re enter in account to update the password , but that is completely out of flow , 

password should work on the first Assistant Login Screen
