### ISSUE TITLE
dark theme issues

### ISSUE THREAD

**Issue by 532910** [BelledonneCommunications/linphone-iphone#694]
Some parts are completely invisible:

![image](https://user-images.githubusercontent.com/14617699/97047130-26273400-1581-11eb-8e99-9114e3210640.png)
![image](https://user-images.githubusercontent.com/14617699/97047173-363f1380-1581-11eb-99a1-e0f94355e2fa.png)

**Comment by haseebjaved1** [comment]
You need to add a new entry in "linphone-Info.plist" file
 "Appearance" -> "Light"
