### ISSUE TITLE
Linker Failure - Exit Code 1

### ISSUE THREAD

**Issue by Ccook67357** [BelledonneCommunications/linphone-iphone#7]
Hi,

Immediately prior to upgrading to Xcode 7 I was having no problem compiling the application for both my physical iPad mini and the various simulators I use for testing purposes.  Since upgrading to Xcode 7 it seems the build is failing because of a problem reported by the linker.  I see that the linker is a little more particular about the target particular object files were built for but I don't understand how to go about resolving this issue so that I can resume testing this application on my simulator.  

Here is the error I am receiving:

d /Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Products/Debug-iphonesimulator/linphone.app/linphone normal x86_64
    cd /Users/chriscook/Desktop/LINPHONE/linphone-iphone
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Products/Debug-iphonesimulator -L/Users/chriscook/Desktop/LINPHONE/linphone-iphone/liblinphone-sdk/apple-darwin/lib -L/Users/chriscook/Desktop/LINPHONE/linphone-iphone/liblinphone-sdk/apple-darwin/lib/mediastreamer/plugins -F/Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Products/Debug-iphonesimulator -filelist /Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Intermediates/linphone.build/Debug-iphonesimulator/linphone.build/Objects-normal/x86_64/linphone.LinkFileList -mios-simulator-version-min=6.0 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime -lSKP_SILK_SDK -lxml2 -lilbcrfc3951 -liconv -lz -lmsopenh264 -lopenh264 -lopus -lpolarssl -lantlr3c -lbellesip -lbzrtp /Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Products/Debug-iphonesimulator/libNinePatch.a /Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Products/Debug-iphonesimulator/libXMLRPC.a -framework AddressBook -framework AddressBookUI -framework AssetsLibrary -framework AudioToolbox -weak_framework AVFoundation -weak_framework CFNetwork -framework CoreAudio -framework CoreGraphics -weak_framework CoreMedia -framework CoreTelephony -weak_framework CoreVideo -framework Foundation -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -weak_framework UIKit -weak-lc++.1 -lsqlite3 -weak-lstdc++.6 -lresolv -lavcodec -lavutil -lgsm -llinphone -lmediastreamer_base -lmediastreamer_voip -lmsamr -lmsilbc -lmssilk -lortp -lopencore-amrnb -lopencore-amrwb -lmsbcg729 -lspeex -lspeexdsp -lsrtp -lswscale -lvpx -Xlinker -dependency_info -Xlinker /Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Intermediates/linphone.build/Debug-iphonesimulator/linphone.build/Objects-normal/x86_64/linphone_dependency_info.dat -o /Users/chriscook/Library/Developer/Xcode/DerivedData/linphone-dwnxacodktdgiodbnwvyahdziadp/Build/Products/Debug-iphonesimulator/linphone.app/linphone

ld: building for iOS simulator, but linking in object file built for OSX, file '/Users/chriscook/Desktop/LINPHONE/linphone-iphone/liblinphone-sdk/apple-darwin/lib/libSKP_SILK_SDK.a' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I assume this is an issue that would need to be overcome for anyone attempting to build this project using the new IDE?  I haven't seen it reported anywhere else with regards to linphone in particular.

Any information or instruction would be greatly appreciated.  Let me know if there is any additional information that might be useful.

**Comment by Ccook67357** [comment]
It might be worth mentioning that the project continues to build and deploy with no issues to my iPad mini, which I have yet to upgrade to iOS 9.  The above error is encountered whenever I try to build and deploy to a simulator, be it iOS 8.4 or 9.

**Comment by bagage** [comment]
Can you try latest master version (`git pull && ./prepare.py -c` before anything else)?

**Comment by bagage** [comment]
It should be fixed now.
