### ISSUE TITLE
iOS 14 App crash when call rejected

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-iphone#701]
hi , 
i have been working on ios version and fixed most of the things , but only one thing is prompting me , 
when i reject incoming call my apps crash on iOS 14 . works well on other iOS versions.

what could be the issue , or where i have to fix this issue.

**Comment by Kellendros007** [comment]
@Adnan-addi, hi, can you tell more info about your exception, and scenario to reproduce error?

**Comment by Adnan-addi** [comment]
[testflight_feedback (3).zip](https://github.com/BelledonneCommunications/linphone-iphone/files/5451050/testflight_feedback.3.zip)

Hi,

here is the log i can fetch from testflight.
if this helps for you attaching more file in new comment

**Comment by Adnan-addi** [comment]
![image](https://user-images.githubusercontent.com/25033749/97422193-4d8a5200-192f-11eb-976a-3a3cfb8993c0.png)

here is the screen shot on which crash occurs on iOS 14.

**Comment by Adnan-addi** [comment]
[testflight_feedback.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/5451384/testflight_feedback.zip)
also check this feedback .

**Comment by Adnan-addi** [comment]
<img width="778" alt="Screenshot 2020-10-28 at 10 57 49 PM" src="https://user-images.githubusercontent.com/25033749/97477170-15a3fe80-1971-11eb-8d7e-81a088a988f5.png">

Crash occurs after rejecting from red cross button.

**Comment by ravi6880** [comment]
@Adnan-addi can you please help me to support callkit.
Basically I am using complete source code from GitHub and it working fine when the app is in the foreground, but it never works when the app is in the background or terminated, while the test flight build of linphone is working fine in every case
Please let me know how can I achieve this
