### ISSUE TITLE
App crashes when sharing a recording

### ISSUE THREAD

**Issue by simoneraffaelli** [BelledonneCommunications/linphone-iphone#706]
The app on App Store (Linphone) crashes as soon as I click the share button on a recording. The reason might be

> Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<UIPopoverPresentationController: 0x136de8ae0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.'

**Comment by jonasongithub** [comment]
I just came across the same issue with the most recent app store version. Is there any way to access the recording through the files app?
