### ISSUE TITLE
(linphone_factory_create_core_with_config_3(factory, _configDb, NULL)) An error has occurred

### ISSUE THREAD

**Issue by Weijiaxiang** [BelledonneCommunications/linphone-iphone#708]
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

I hope someone can help solve this problem. I have been troubled by this problem for half a month. Thank you

**Comment by Peter-iOS** [comment]
Hi,bro.How did you solve this problem later?

**Comment by nguyenhuynhdeveloper** [comment]
me too
