### ISSUE TITLE
how to build linphone-sdk for iphone

### ISSUE THREAD

**Issue by zxpgo** [BelledonneCommunications/linphone-iphone#710]
The linphone-sdk building command is :
cmake .. -G Xcode -DLINPHONESDK_PLATFORM=IOS
cmake --build . 

When i am build a linphone-sdk for ios project, the wrong is as follow:

![image](https://user-images.githubusercontent.com/37869997/100236502-b97ccc00-2f68-11eb-9a41-1ae1f2b13d0d.png)
![image](https://user-images.githubusercontent.com/37869997/100236598-d6190400-2f68-11eb-9080-43d8879d5938.png)
![image](https://user-images.githubusercontent.com/37869997/100236538-c7325180-2f68-11eb-8daf-b420b7a52df8.png)

Thanks for your answer.

**Comment by Kellendros007** [comment]
After build linphone-sdk, you need to do some additional steps.

> Rebuild the project:
>    PODFILE_PATH=\<path to linphone-sdk-ios\> pod install
> where is your build directory of the linphone-sdk project, containing the linphone-sdk.podspec file and a linphone-sdk ouptut directory comprising built frameworks and resources.
> 
> Then open linphone.xcworkspace with Xcode to build and run the app.
