### ISSUE TITLE
App failure after uploading to app store - code EXC_BAD_ACCESS (SIGSEGV)

### ISSUE THREAD

**Issue by samuelrochati** [BelledonneCommunications/linphone-iphone#713]
Hello friends, how are you?

I made some modifications, and the app works normal on the simulator and even on the physical device when installed by the cable.

However, when I upload it to appsore it does not log in via SIP Exception Type: EXC_BAD_ACCESS (SIGSEGV).

link image: https://drive.google.com/file/d/10Ll6ko6CnKSkJLCqgF0xuUa9_l8Av2st/view?usp=sharing
link crashlog.txt: https://drive.google.com/drive/folders/1jIFbf_1WbZ22kK8UutSjg-gidsBknVQg?usp=sharing

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000000
VM Region Info: 0 is not in any region.  Bytes before following region: 4330192896
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                   102198000-1021a0000 [   32K] r-x/r-x SM=COW  ...ex.app/virtex

Can someone help me? has some special configuration for the release version. Because it works normal in the simulator

Thanks

**Comment by Economog98** [comment]
Solved this if still interested, I missed some bundle identifiers which were hardcoded. Hope it helps.
