### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by zxpgo** [BelledonneCommunications/linphone-iphone#718]
![29981609597070_ pic](https://user-images.githubusercontent.com/37869997/103459202-5ee54580-4d48-11eb-9966-65a73177acc9.jpg)

Sending messages and receiving messages are in two different windows. Does anyone know why this is?

**Comment by basncy** [comment]
Are these message send from asterisk server? This is known issue since Linphone 4.2.2, and my personal fix pasted below, you might re-compile asterisk from source code to solve this problem. 

patches are in the history tab.
https://issues.asterisk.org/jira/browse/ASTERISK-28928

**Comment by zxpgo** [comment]
> Are these message send from asterisk server? This is known issue since Linphone 4.2.2, and my personal fix pasted below, you might re-compile asterisk from source code to solve this problem.
> 
> patches are in the history tab.
> https://issues.asterisk.org/jira/browse/ASTERISK-28928

Thank you, i solve the problem!

**Comment by zxpgo** [comment]
https://user-images.githubusercontent.com/37869997/103472564-f5a61680-4dc9-11eb-90ba-2fd5a22fe7f5.mp4

Linphone cannot send Chinese messages. What is the problem? What should I do?

**Comment by basncy** [comment]
> 
> 
> Are these message send from asterisk server? This is known issue since Linphone 4.2.2, and my personal fix pasted below, you might re-compile asterisk from source code to solve this problem.
> 
> patches are in the history tab.
> https://issues.asterisk.org/jira/browse/ASTERISK-28928

Now asterisk officially fixed this issue in the version of 16 and 18, pls check out the latest source code then re-compile.
The patch title is "res_pjsip_messaging: Refactor outgoing URI processing", and the commit id is 8e2672d2a47eccc406ee7080d110cd0237eeb8c5

BTW, you need to add the third parameter(e.g. sip:${EXTEN}@sip.example.com) to MessageSend to enabled this feature.
