### ISSUE TITLE
 App crash while making outgoing call using G729 codec

### ISSUE THREAD

**Issue by FabCoder** [BelledonneCommunications/linphone-iphone#72]
Hi,

I have enabled G729 codec and use as default codec for making calls. When I make outgoing call application crashes.

When i debug app it comes in LinphoneCoreListenerBase listener with OutgoingEarlyMedia state before application crashes

The error is Fatal signal 11 (SIGSEGV), code 2, fault addr 0xbe33efec in tid 6067

App is working fine with other audio codecs.

Is there any issues with G729 codec in linphone?

**Comment by bagage** [comment]
It seems I do not reproduce it... can you tell me:
* what options did you use for `prepare.py` invocation?
* what are the 2 devices used
* is that reproducible if you reverse caller/callee
* can you grab full stacktrace with debug symbols (`./prepare.py --debug`)?

**Comment by FabCoder** [comment]
Hi,

I have solved this issue using  Latest linphone.

Thanks.

**Comment by bagage** [comment]
A new release should come soon anyway. Thanks @FabCoder.
