### ISSUE TITLE
Contacts are not being displayed

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#73]
I am not able to see any contacts in contact list in this version 3.13. If I add a new contact, it also doesn't display in list. 
Although, in earlier version 3.12, it is working fine.

I am using Xcode 7.3.1 and Simulator iOS 9.3.

**Comment by bagage** [comment]
Yes, contacts are broken on master - I am working on it.

**Comment by nitesh-borad** [comment]
I also found two other issues. Should I comment out it here or create separate issues?

**Comment by bagage** [comment]
Please create separate issues, I'll close them if irrelevant/duplicate of existing ones. Thanks!

**Comment by bagage** [comment]
Fixed in 9feeeee
