### ISSUE TITLE
User profile image (in sidebar menu) is not updating

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#74]
Updating user profile image, from side bar menu, is not working:

1. Setting new image with camera does nothing.
2. Setting new image with photo library crashes the app.

In earlier version 3.12, it is working fine.
I am using Xcode 7.3.1 and Simulator iOS 9.3 and linphone sip user account.

**Comment by bagage** [comment]
This is indeed the second issue: every access to photo (including in chat) will crash the app. Not sure what's happening here, but it seems related to something very recent in iOS and somewhat related to #72. Under investigation too... thanks @nitesh-borad 👍

**Comment by bagage** [comment]
Fixed in 9feeeee
