### ISSUE TITLE
iOS - Linphone registration issue

### ISSUE THREAD

**Issue by Jiunnan** [BelledonneCommunications/linphone-iphone#753]
Dear Linphone Team:
  I am facing an issue with registration, while i am trying to register with sip details, it's working fine.When Apple reviewer trying to register with sip details, it shows registration state always as in progress.
  Please tell me the reason.
  Thank you in advance.

iOS version: 14.6
linphone SDK: 4.4.3
communication protocol of sip server: UDP

**Comment by TonyTaoLiang** [comment]
Did you solved this problem? I had the same issues.
