### ISSUE TITLE
No ringing notifications when app is in Background

### ISSUE THREAD

**Issue by HollaTheWoodFairy** [BelledonneCommunications/linphone-iphone#759]
Linphone does not ring when the app is in background or iOS is in sleepmode. I've tested this on different devices.
When the App is on screen - everything works fine.

iOS: 14.6
Linphone App: 4.5.0

**Comment by leelai** [comment]
I encounter this issue many times, and i don't know how to solve the problem.

**Comment by leelai** [comment]
linphone was getting invite from server, but after 6 sec it send 111 bye back to server. I don't know why.

**Comment by haseebjaved1** [comment]
use production build to make it work :)

**Comment by HollaTheWoodFairy** [comment]
> use production build to make it work :)

It’s the iOS Version from the AppStore. I think this is the production version.

**Comment by haseebjaved1** [comment]
Ok i thought you're building it from XCode. 
I built it from Xcode and its working fine ....

**Comment by mhisham** [comment]
I have the same issue and many issues with push notifications also v5 of liblinphone now give us a chance to change anything in the push notification header

**Comment by dilawer** [comment]
@bagage @benjamries any update on this issue? Can you guide how to fix this problem? Thanks

**Comment by dilawer** [comment]
@haseebjaved1 can you show a demo where it's working fine in the background? thanks
