### ISSUE TITLE
 Could not load grammar sdp_grammar because the file could not be located.

### ISSUE THREAD

**Issue by Attiv** [BelledonneCommunications/linphone-iphone#762]
app crashed with message:  Could not load grammar sdp_grammar because the file could not be located.

**Comment by RussellGee** [comment]
> app crashed with message: Could not load grammar sdp_grammar because the file could not be located.

HI, Attiv. I have same problem, Do you have any ideas? Thank you in advance :D

**Comment by Attiv** [comment]
> :
I'm very sorry I forgot how to fix this, probably by changing the source code

**Comment by RussellGee** [comment]
You gave me confidence

**Comment by jfalexvijay** [comment]
Any solution for this issue?
