### ISSUE TITLE
Push notification variables/team ID on Linphone-iPhone

### ISSUE THREAD

**Issue by hasanr68** [BelledonneCommunications/linphone-iphone#763]
Gents/ladies.

Been trying to implement push notifications on iPhone via this project:
https://github.com/AGProjects/sylk-pushserver

It seems to work great with Linphone Android. 

I have already changed the variables to the new specs (pn-param etc) for saving the device parameters. I understand that most people wouldn't have used the project for push notifications, but your insights may help nevertheless.

Initially the app was sending ABCD1234 as the team ID, which we changed in the Linphone code to our team ID on the dev account. The device token is passed as:

6F2AFC22BBCFE21B4C9AF024671DCE9C3BD561BAF8FF04FB3AE6D54B86XXXXXX:remote&65FE30F9C97874C9C8C22681C629BD7527122E096F882EE1555AA80ECXXXX:voip

However, the push doesn't seem to go through. I removed the parameters after the colon (voip & remote) and the push was going through. But it was a short notification (a second or so) and the phone went off again and didn't keep ringing.

The questions are:

1. Are there any other variables (in addition to ABCD1234) to be changed in the Linphone iPhone code for push notifications?
2. Is it normal for Linphone to append :remote or :voip? Have we done something wrong?
3. I would have expected the phone to stay awake and not go back to sleep within a second or so - something we doing wrong?

Apologies if this is very basic, I did do a search and didn't find much.

Thanks in advance.

**Comment by Economog98** [comment]
Any luck with this? Can't seem to find where to change the "ABCD1234"
