### ISSUE TITLE
PUSH notification. APNS-Firebase->application

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linphone-iphone#765]
Good afternoon! I am working on implementing PUSH Notifications. Create a bunch of Firebase and APNS, downloaded the GoogleService-Info.plist file from Firebase. I wanted to know what needs to be done next for push notifications to work? How can I get the identifier, device token in my Asterisk? I am working with xcode 12 in simulator mode.

**Comment by alex-eri** [comment]
duplicate #768
