### ISSUE TITLE
SIP account bug

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linphone-iphone#766]
Good afternoon! I downloaded your application from the appstore, but it doesn't work correctly. When registering using a SIP account, registration does not occur. But the bug is that if I first create an account with udp then tcp then registration occurs.

**Comment by alex-eri** [comment]
tls is default. If you using tcp - you need to switch setting.

**Comment by arm-computech** [comment]
No, I use UDP, I choose UDP when registering. Please check the app. Since there is no registration at the moment. That is, the application does not send anything to the server at all. Before 2-3 months ago, everything was fine.
