### ISSUE TITLE
Push!

### ISSUE THREAD

**Issue by arm-computech** [BelledonneCommunications/linphone-iphone#768]
Good afternoon! I am working on implementing PUSH Notifications. Create a bunch of Firebase and APNS, downloaded the GoogleService-Info.plist file from Firebase. I wanted to know what needs to be done next for push notifications to work? How can I get the identifier, device token in my Asterisk? I am working with xcode 12 in simulator mode.

**Comment by mhisham** [comment]
I'm working on the samething, 
But I think linphone v5 not give us to control the header of push notification in the packet which is fixed in the liblinphone

**Comment by alex-eri** [comment]
@arm-computech if using pjsip you can get it with AMI 

Python code works with android version

```
import panoramisk

m = panoramisk.Manager(
        host=cfg['host'],
        username=cfg['username'],
        secret=cfg['secret'])

await m.connect()

def on_uri(uri):
    return dict((p.split('=') for p in uri.split(';')[1:]))

def register_cb(manager, message):
    ep = message['EndpointName']
    params = on_uri(message['URI'])
    logging.info(pformat(params))

m.register_event('ContactStatus', register_cb)
```

**Comment by arm-computech** [comment]
Thanks, but initially I'm still interested in implementing Firebase into a project. That is, where to drop the GoogleService-Info.plist file in the project. Whether it is necessary, somewhere to register, what exactly I use Firebase.

**Comment by arm-computech** [comment]
> @ arm-computech, если вы используете pjsip, вы можете получить его с помощью AMI
> 
> Код Python работает с версией Android
> 
> ```
> import panoramisk
> 
> m = panoramisk.Manager(
>         host=cfg['host'],
>         username=cfg['username'],
>         secret=cfg['secret'])
> 
> await m.connect()
> 
> def on_uri(uri):
>     return dict((p.split('=') for p in uri.split(';')[1:]))
> 
> def register_cb(manager, message):
>     ep = message['EndpointName']
>     params = on_uri(message['URI'])
>     logging.info(pformat(params))
> 
> m.register_event('ContactStatus', register_cb)
> ```
> 
> вам нужно разветвить и пересобрать linphone, чтобы использовать его.

И  как вы говорите, код работает с версией Android. Вот только в Android можно и  без всего этого токен получить. Там все настроено хорошо.
