### ISSUE TITLE
Linphone_iterate crash after enabling video [master]

### ISSUE THREAD

**Issue by reste85** [BelledonneCommunications/linphone-iphone#77]
Hi,
i'm using the 3.11.8 version of liblinphone-iphone. Registration and receive call (only audio) worked well. If i enable the video via these lines of code:

let current_call = linphone_core_get_current_call(LinphoneManager.getLc())
let call_params = linphone_call_params_copy(linphone_call_get_current_params(current_call));
linphone_call_params_enable_video(call_params, 1);
linphone_core_update_call(LinphoneManager.getLc(), current_call, call_params);

the lib crashes on linphone_core_iterate. 
Here more details of the iteration:
1) I Register to SIP server correctly
2) I receive a call, and accept immediately
3) When i press a button on my GUI i execute the lines of code i've written before

See attached .zip for debug logs.

thank you!

[Logs_Linphone.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/293839/Logs_Linphone.zip)

PS: I've already set the UIView via the command: 
linphone_core_set_native_video_window_id(LinphoneManager.getLc(), &displayView);

**Comment by reste85** [comment]
Tried today with the current version (master) and the problem is the same... is that a bug or a problem of my configuration file?

Thank you very much...

**Comment by bagage** [comment]
Can you try Linphone official version? Do you reproduce the version with the same account(s)? If yes, can you also try with linphone.org accounts and check if the problem is still there?
I'll investigate this further when having some time for it.

**Comment by reste85** [comment]
Hi,
i've tried with linphone official version and it works. I'm searching for something that i've missed, maybe in the configuration. When i accept the call with (acceptCall method of the LinphoneManager) with eventWithVideo = true --> it comes the crash on the linphone accept ...

**Comment by reste85** [comment]
Ok was my mistake,
I'm using linphone sdk in Swift, the error was related to how i pass the UIView to the linphone sdk.

Here the code examples, assuming that displayView is an instance of UIView

**Bugged Version:**
linphone_core_set_native_video_window_id(LinphoneManager.getLc(), &displayView)

**Correct Version:**
linphone_core_set_native_video_window_id(LinphoneManager.getLc(),  UnsafeMutablePointer<Void>(bridge(displayView)));

i've to declare these support functions: 
func bridge<T : AnyObject>(obj : T) -> UnsafePointer<Void> {
        return UnsafePointer(Unmanaged.passUnretained(obj).toOpaque())
        // return unsafeAddressOf(obj) // ***
    }
    
    func bridge<T : AnyObject>(ptr : UnsafePointer<Void>) -> T {
        return Unmanaged<T>.fromOpaque(COpaquePointer(ptr)).takeUnretainedValue()
        // return unsafeBitCast(ptr, T.self) // ***
    }


i wasn't passing what linphone was expecting, i was passing an UnsafeMutablePointer<UIView> instead of UnsafeMutablePointer<void> (i'm new to iOS so correct me if i'm wrong). 

You can close the issue, it was my mistake.

**Comment by bagage** [comment]
Great to see that you have fixed your issue!

**Comment by E2-Pavithran** [comment]
> Ok was my mistake,
> I'm using linphone sdk in Swift, the error was related to how i pass the UIView to the linphone sdk.
> 
> Here the code examples, assuming that displayView is an instance of UIView
> 
> **Bugged Version:**
> linphone_core_set_native_video_window_id(LinphoneManager.getLc(), &displayView)
> 
> **Correct Version:**
> linphone_core_set_native_video_window_id(LinphoneManager.getLc(), UnsafeMutablePointer< Void >(bridge(displayView)));
> 
> i've to declare these support functions:
> func bridge(obj : T) -> UnsafePointer< Void > {
> return UnsafePointer(Unmanaged.passUnretained(obj).toOpaque())
> // return unsafeAddressOf(obj) // ***
> }
> 
> ```
> func bridge<T : AnyObject>(ptr : UnsafePointer< Void >) -> T {
>     return Unmanaged<T>.fromOpaque(COpaquePointer(ptr)).takeUnretainedValue()
>     // return unsafeBitCast(ptr, T.self) // ***
> }
> ```
> 
> i wasn't passing what linphone was expecting, i was passing an UnsafeMutablePointer< UIView > instead of UnsafeMutablePointer< void > (i'm new to iOS so correct me if i'm wrong).
> 
> You can close the issue, it was my mistake.

Hi, 
I too facing this issue with version 4.3.1
And I am setting my view in objective c as below,

linphone_core_set_native_video_window_id([LinphoneManager getLc], (__bridge void *)(self->myVideoview));

Should I change anything on this notation?
