### ISSUE TITLE
IOS client breaks dialplan

### ISSUE THREAD

**Issue by alex-eri** [BelledonneCommunications/linphone-iphone#774]
`exten = _X.,n,Dial(${PJSIP_DIAL_CONTACTS(${EXTEN})})`  macro

makes string like 

```
PJSIP/0007/sip:0007@93.81.46.13:51663;transport=udp;pn-provider=apns;pn-prid=D737567DE2713CF36AE4939B94FB74E452CFF63DF07925423F5C19FE6DABFBF6:remote&614D0D116860C606F6025300F58C59D854019F687F2A9BDCFB76AD7E23418033:voip;pn-param=ABCD1234.org.linphone.phone.remote&voip;pn-msg-str=IM_MSG;pn-call-str=IC_MSG;pn-groupchat-str=GC_MSG;pn-call-snd=notes_of_the_optimistic.caf;pn-msg-snd=msg.caf;pn-timeout=0;pn-silent=1
```

So Dial cant call it because of **&** in contact.

**Comment by chillcollex** [comment]
hey, 
@alex-eri Could you let me know if you've resolved it?
@Viish any idea of this issue? only happens on linphone-iphone

**Comment by alex-eri** [comment]
> hey, 
> @alex-eri Could you let me know if you've resolved it?

I abandoned project because of no working sip ua, available in play store. 

If  issue of `&` resolved I will return to my sip project
