### ISSUE TITLE
When sending sip MESSAGE, the request URI is incomplete: the port number is missing.

### ISSUE THREAD

**Issue by paruyrs** [BelledonneCommunications/linphone-iphone#775]
The issue is related when chat room is create.
case when using linphone_core_get_chat_room: LinphoneChatRoom *basicRoom = linphone_core_get_chat_room(LC, addresses->data);
 - we pass address with correct URI when port is included however when we get peer or participant and get address the port is missing (after creation of chat Room).
 case when using linphone_core_create_chat_room (any number) - LinphoneChatRoom *room = linphone_core_create_chat_room_2(LC, param, subject ?: LINPHONE_DUMMY_SUBJECT, addresses);
 - in this case peer address and participant is null when we try to get them, so it doesn't work at all. 
 -
How to add port to ip in sip message? 
example: 
expected: 
2021-08-11 17:07:24:436 [linphone/belle-sip] MESSAGE channel [0x1092dc000]: message sent to [UDP://proxy.sip.company.com:5060], size: [690] bytes
MESSAGE sip:102@212.77.222.222:**7200** SIP/2.0
Via: SIP/2.0/UDP 192.168.4.56:57538;branch=z9hG4bK.vf8ij~fdT;rport
From: <sip:locext103@212.34.248.234>;tag=qyuKKpGJn
To: sip:102@212.34.248.234
CSeq: 20 MESSAGE
....

but we get this:  
2021-08-11 17:07:24:436 [linphone/belle-sip] MESSAGE channel [0x1092dc000]: message sent to [UDP://proxy.sip.company.com:5060], size: [690] bytes
MESSAGE **sip:102@212.77.222.222** SIP/2.0
Via: SIP/2.0/UDP 192.168.4.56:57538;branch=z9hG4bK.vf8ij~fdT;rport
From: <sip:locext103@212.34.248.234>;tag=qyuKKpGJn
To: sip:102@212.34.248.234
CSeq: 20 MESSAGE
....

**Comment by alex-eri** [comment]
where are chat rooms in Linhome app?

**Comment by paruyrs** [comment]
What you mean? Could you please clarify?
