### ISSUE TITLE
Getting Error No such module 'linphonesw'

### ISSUE THREAD

**Issue by safranashereen** [BelledonneCommunications/linphone-iphone#777]
when I do the Archive I'm getting Getting Error No such module 'linphonesw' error in linphone-sdk
<img width="468" alt="Screenshot 2021-08-26 at 9 47 50 AM" src="https://user-images.githubusercontent.com/6188530/130899775-0a6febc2-b1a7-4180-9b45-0511907b4dc2.png">

I tried the following things to fix this issue. But I couldn’t 😒.

- Quit Xcode.
- Delete project's temp files located at ~/Library/Developer/Xcode/DerivedData
- Delete ProjectName.xcworkspace
- Delete Podfile.lock file and Pods folder
- Run pod install.
- Open the newly created ProjectName.xcworkspace file and build.

It does not work out.

Anyone, please help me to fix this issue.

**Comment by siavashnamiranian** [comment]
same issue!!
any update?

**Comment by DanilAlbutov** [comment]
Go to Product > Schemes > New Scheme...
Select the name of your Cocoapod then click OK.
After you do this, build the project (click cmd + B)

**Comment by DanilAlbutov** [comment]
> > Go to Product > Schemes > New Scheme... Select the name of your Cocoapod then click OK. After you do this, build the project (click cmd + B)
> 
> by changing schema to pod name(pods-test2 or linphone-sdk) only that pod will be build instead of main project

You can launch xcode with rosetta. Its work for me.

**Comment by golditdev** [comment]
that's not working. selected new scheme and built the pod scheme, but I got same error

**Comment by iosmoon38** [comment]
I am facing the same issue. Does anyone have a solution?

![265387264-8f7abe2e-4693-414f-b60c-3216f134698e](https://github.com/BelledonneCommunications/linphone-iphone/assets/114209530/1a6dff23-0a89-47b8-81ba-1b7cb2894d4c)

**Comment by jingluoguo** [comment]
> I am facing the same issue. Does anyone have a solution?
> 
> ![265387264-8f7abe2e-4693-414f-b60c-3216f134698e](https://private-user-images.githubusercontent.com/114209530/265396923-1a6dff23-0a89-47b8-81ba-1b7cb2894d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODYzNDgsIm5iZiI6MTcxNzQ4NjA0OCwicGF0aCI6Ii8xMTQyMDk1MzAvMjY1Mzk2OTIzLTFhNmRmZjIzLTBhODktNDdiOC04MWJhLTFiN2NiMjg5NGQ0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNzI3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDViYjdjZTIxODI5YzdhMmRmYjA3MzJkNzZjYWNjZTQwMTUyNjYyODM4YWNmZjFhNmJhYWMwMmMxYTQ3OGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0hrwt2hlFg4WnIUwUKp30TzJmYv6VoD116gMObAawYo)

hi, did you resolved this?
