### ISSUE TITLE
Password not working from assistant login screen

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-iphone#778]
Hi , i compiled linphone code and entering the credentials and when i hit login it says credentials missing and when go to setting re enter password than it works , 

what can i do to make it work on the first go. why password field is not setting up in proxy configs from assistant screen.

i even downloaded the app from appstore, i am facing the same issue on the store app also , 
Testing on iphone 12 pro.

when i upload on test flight 

it says 
<img width="223" alt="Screenshot 2021-09-03 at 10 58 17 AM" src="https://user-images.githubusercontent.com/25033749/131957598-0d659f01-d296-41f0-982f-9fad4738a344.png">

what could be the issue with password ? please help .

Thank You

**Comment by divyeshvora2007** [comment]
Any answer you can get @Adnan-addi

**Comment by Adnan-addi** [comment]
yes in assistant class there are debug values hardcoded you need put your default values in else part than it should pickup all the fields .
