### ISSUE TITLE
about ios ipv6 problem

### ISSUE THREAD

**Issue by zhangyushneg** [BelledonneCommunications/linphone-iphone#78]
i want to use nat64 connect sip server, but i can't connect, Use nat64 provided by Apple， please help me， what should I do？

**Comment by bagage** [comment]
Please wait for next release which would have full ipv6 support.

**Comment by zhangyushneg** [comment]
When to submit it，and  my linphone version is 3.7.5, Now how can I do to Apple's audit？only-ipv6

**Comment by bagage** [comment]
Linphone 3.13.9 has been released!

**Comment by uditbatra** [comment]
Hi,

I am using an older Line phone SDK version which was before June 16, 2016. Can you please tell me how can I enable iPV6 on that SDK without upgrading to the latest release.
