### ISSUE TITLE
Pod install error with sample app

### ISSUE THREAD

**Issue by mathist** [BelledonneCommunications/linphone-iphone#784]
I'm not sure if this right place to post this issue, but... when I use this sample: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Getting%20started/iOS/ - I get an error when I run pod install

[!] Couldn't determine repo type for URL: https://gitlab.linphone.org/BC/public/podspec.git: (): mapping values are not allowed in this context at line 3 column 17

Here's my podfile:

platform :ios, '13.0'

source "https://gitlab.linphone.org/BC/public/podspec.git"

target 'LinphoneTest' do
  use_frameworks!

  pod 'linphone-sdk' , '4.5'
end

**Comment by guofengtd** [comment]
same issue

**Comment by kemalbalaban** [comment]
Hi,
same issue

**Comment by guofengtd** [comment]
anyone can help?
this is urgent

thanks.

**Comment by kemalbalaban** [comment]
Hi,
i'm solved to issue. the steps i followed.
`cd linphone-iphone`
`pod setup`
`pod install`
