### ISSUE TITLE
sip to sips problem

### ISSUE THREAD

**Issue by Gari77** [BelledonneCommunications/linphone-iphone#785]
I want to share the next problem ...
When, in the assistant, I select the item to use a sip account, enter all the data, then the account is registered on my flexisip server and at first glance everything is fine.  (I use transport TLS)

![InkedSimulator Screen Shot - iPhone 11 - 2021-10-11 at 17 08 03_LI](https://user-images.githubusercontent.com/91553597/136811144-36b1a6c1-0c35-4e47-96eb-7b57fae6dca8.jpg)

registration for flexisip looks like this:
Mon Oct 11 16:08:08 2021: Registered <sip: 210 @ xxx .xxxxxxx .com> (sip: 210@99.222.250.80: 49874; transport = tls; fs-conn-id = eadf15c1429e8460) LinphoneiOS / 4.4.0 (iPhone 11) LinphoneSDK / 5.1.0-alpha.89 + e58e96f

But if I re-enter the account settings, the following "problem" appears( sip changes to sips) :

![InkedInked20211011_172800_LI](https://user-images.githubusercontent.com/91553597/136811312-066c30d5-caf2-418e-ab08-64d57cf6319a.jpg)

registration for flexisip looks like this:
Mon Oct 11 16:09:10 2021: Registered <sips: 210 @ xxx .xxxxxxx .com> (sips: 210@99.222.250.80: 52559; fs-conn-id = 17c623bd1cef3781) LinphoneiOS / 4.4.0 (iPhone 11) LinphoneSDK / 5.1.0-alpha.89 + e58e96f

when trying to make a call i am getting the following error:

![Inked20211011_172826_LI](https://user-images.githubusercontent.com/91553597/136811415-3e244327-b97f-4c00-abcb-ac2e5c59bb0a.jpg)

From the side of flexisip in logs:
flexisip [5286]: Not dispatching request because SIPS not allowed for sips: 0193 @ XXX .XXXXXXX .com

**Comment by Er-hgy** [comment]
I have the same problem, I also use a third party SIP server, but the difference is that I choose the UDP in the login page.
Can you make outgoing calls using UDP？
![ios-sip to ios-sip_3_副本](https://user-images.githubusercontent.com/74401896/167765290-57f3d126-32fc-4f86-bfb2-2b0bc0ef6f8d.png)
