### ISSUE TITLE
Incoming call being answered even after caller has disconnected

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#79]
Steps to produce issue:

**1. User A calls to User B.** 
- User A's app shows outgoing call to User B.
- User B's app shows incoming call from User A.

**2. User A turns off Wifi / Data Connection.** 
- User A's app disconnects outgoing call to User B as internet connection is disconnected. This is okay.
- _But, User B's app doesn't dismiss incoming call screen for minutes. Even User B can accept call from User A. And it shows active call for more than 30 seconds. This is an issue._

**Comment by bagage** [comment]
I do not reproduce it. Are you using linphone.org accounts? Are you connected only on 2 devices, or another devices may interfere too?

**Comment by gled-rs** [comment]
Probably no CANCEL received on the User B's app...

**Comment by nitesh-borad** [comment]
**Yes**. I am using linphone.org accounts and connected to 2 devices only.

**Comment by bagage** [comment]
Then would you mind attaching logs from both end please?

**Comment by nitesh-borad** [comment]
**Logs:**
Caller: nitesh.borad (iPhone 5 Device)-
[Caller.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/320534/Caller.txt)

Receiver: krupanshu (iPhone 6 Simulator)-
[Call Receiver.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/320536/Call.Receiver.txt)

**Comment by ReisBenjamin** [comment]
Please update to latest commit and re open if it's still happening
