### ISSUE TITLE
Update on Push Notifications

### ISSUE THREAD

**Issue by guillaumesoucy94** [BelledonneCommunications/linphone-iphone#791]
Hello, 

I know there already peoples here with a Push Notification problem but is that issue will be fixed? Is a updated version will be pushed to the App Store soon? This is just a issue update request.

I use the Linphone version 4.5.0 from the Apple App Store:

![IMG_4447](https://user-images.githubusercontent.com/22561876/140908991-d3a4bda2-663c-4513-aafb-e2caa25de2dd.PNG)

Because of the Push notification issue, the app is almost useless for now as it will not rang the phone if it is in the background.

Thank-you

Guillaume

**Comment by Economog98** [comment]
Yes, the app is useless at the current state, pending for an update.

**Comment by guillaumesoucy94** [comment]
Any update? Please?

**Comment by Economog98** [comment]
From what I learned searching about this issue:

Actually is not an issue with the linphone app. If you use linphone's free sip service you'll received push notification as you should because they use flexisip which is correctly setup to send push. 
Linphone has the ability to send push notification but the user,if he is using his own pbx/proxy, must setup the server to send them.

**Comment by lenhatminh0528** [comment]
> From what I learned searching about this issue:
> 
> Actually is not an issue with the linphone app. If you use linphone's free sip service you'll received push notification as you should because they use flexisip which is correctly setup to send push. Linphone has the ability to send push notification but the user,if he is using his own pbx/proxy, must setup the server to send them.

can you pls be more specific about how to set up the server correctly? im using flexsip but still not receive notifications.

**Comment by Economog98** [comment]
Have created the required certificates through appleconnect?Also in the xcode simulator I think that the push notification won't work so you have to be on the physical device.

**Comment by dcowan-london** [comment]
As confirmed [here](https://github.com/BelledonneCommunications/linphone-android/issues/1561#issuecomment-983689986), there is no way to get push notifications with the stock Linphone app from the app server with a custom SIP server. You can only use push notifications with the Linphone SIP service.

To get push notifications with any other SIP service, you will need to build the app yourself.
