### ISSUE TITLE
Need VOIP APNS payload of Linphone iOS app, to know what value we are getting for the "call-id" key.

### ISSUE THREAD

**Issue by E2-Mohamed** [BelledonneCommunications/linphone-iphone#794]
More info:

https://stackoverflow.com/questions/69989575/how-to-get-call-id-not-callerid-from-asterisk-before-we-do-the-dial-process-in

**Comment by tyleryeh** [comment]
Hi~ @E2-Mohamed , you could reference the tutorials of 8.RemoteNotification it works for me.

tutorials: https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/ios/swift

**Comment by E2-Mohamed** [comment]
Thanks @tyleryeh, i will check that out.
