### ISSUE TITLE
Application Crash on call resume within 10 seconds of call pause

### ISSUE THREAD

**Issue by NaveenKhannaBM** [BelledonneCommunications/linphone-iphone#795]
Greetings,

I am facing an application crash if a call is resumed within 10 seconds of pause. 
A Fatal error is generated  **Trying to create a new au_write filter when there is already one existing**

In case pause duration exceeds 10 seconds and call resume is done after that then application continues to work gracefully.

Regards,

Naveen Khanna

**Comment by sodaDreamer** [comment]
I'm also seeing the same error on multiple iOS devices. Pausing and resuming the same call seems fine, but if I pause the call (to initiate a transfer) and then make a new call it crashes shortly after the OutgoingEarlyMedia event. Same as Naveen, it seems ok if I wait 10 seconds before making the new call.
