### ISSUE TITLE
When user calls himself it gives busy tone and doesn't disconnect automatically

### ISSUE THREAD

**Issue by nitesh-borad** [BelledonneCommunications/linphone-iphone#80]
I am registered on domain sip.linphone.org with username: nitesh.borad.
Now, when I call to myself (nitesh.borad), it gives me busy tone. And it continues giving busy tone for more than minute (probably even more).

**In my opinion, it should have some alert when user calls himself or should not allow to call himself.**

**Comment by bagage** [comment]
It should not happen - if you are registered only once, you should get after ~3 sec a "nitesh.borad is busy" popup error. Are you sure that you are not using your account somewhere else? 
Can you attach some debug logs from the application to see what's going on please?

**Comment by nitesh-borad** [comment]
PFA log and image.
![screen shot 2016-06-06 at 1 52 43 pm](https://cloud.githubusercontent.com/assets/17453543/15818627/18b6ad96-2bfc-11e6-953d-6eb011172d73.png)

[Linphone_3.13_Log.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/300139/Linphone_3.13_Log.txt)

**Comment by nitesh-borad** [comment]
**You are right.**
It seems that account 'nitesh.borad' is being used in other device too.
 
After using different account, I got "acount-name is busy" popup error after ~3 sec.
So, this was not an issue actually.
