### ISSUE TITLE
CallKit crashes in the background iOS

### ISSUE THREAD

**Issue by sianami** [BelledonneCommunications/linphone-iphone#805]
Hi
I am using the linphone sdk on iOS
I used PushKit to receive incoming calls and used CallKit to display calls

Callkit works properly when the app is in the foreground
But when the app is completely closed, the app crashes when it receives the incoming push.

In the didReceiveIncomingPushWith method, when the push is received, I immediately call reportNewIncomingCall
But it crashes in the background.

**Comment by asadcr** [comment]
Same issue, is there anyone looking at it ?

**Comment by thipoo24** [comment]
Is there any solution for the above issue

**Comment by asadcr** [comment]
Just FYI, i updated to `release/5.0` and crashing disappeared.
