### ISSUE TITLE
Callkit notification is broken when receiving 2 invitations from the server

### ISSUE THREAD

**Issue by hieujames** [BelledonneCommunications/linphone-iphone#807]
Hello,
We are making a call. The call from the server that initiates a direct invitation, everything is very stable, but when the server creates 2 invitations, from a station A wants to go to station C of B, the first invitation from A to B, B creates add an invitation to C and have a total of 2 invitations, the application displays an incoming call notification for about 4 seconds, then disconnects and the notification is still running in the background. How to make the application work comfortably and neatly. Please help me

**Comment by thipoo24** [comment]
Hi, Did you find any solution to your issue
