### ISSUE TITLE
'pod install' on iOS, failing for podspec with source https://www.linphone.org/releases

### ISSUE THREAD

**Issue by gabe4coding** [BelledonneCommunications/linphone-iphone#814]
The podspecs for older version of the library are not updated to the baseURL: **https://download.linphone.org/releases/**
This is causing the failure of the download of the package.

The downloaded file is the HTML of the root page under releases.

-> Installing linphone-sdk (4.4.4)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip
   https://www.linphone.org/releases/ios/linphone-sdk-ios-4.4.4.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.4.0'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100   222  100   222    0     0   1609      0 --:--:-- --:--:-- --:--:--  1720
   100   247  100   247    0     0    462      0 --:--:-- --:--:-- --:--:--  1506
   100  3043  100  3043    0     0   5333      0 --:--:-- --:--:-- --:--:--  5333
   $ /usr/bin/unzip /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip -d
   /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3
   Archive:  /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip
     End-of-central-directory signature not found.  Either this file is not
     a zipfile, or it constitutes one disk of a multi-part archive.  In the
     latter case the central directory and zipfile comment will be found on
     the last disk(s) of this archive.
   unzip:  cannot find zipfile directory in one of /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip or
           /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip.zip, and cannot find /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip.ZIP, period.

[!] Error installing linphone-sdk
[!] /usr/bin/unzip /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip -d /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3

Archive:  /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip or
        /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip.zip, and cannot find /var/folders/k6/v5k3gd856vq527b95blyxy6h0000gn/T/d20220309-40272-1ep3hc3/file.zip.ZIP, period.

**Comment by ninholli** [comment]
> 

Where can I update this source?

**Comment by arjenfvellinga** [comment]
For older versions of the sdk the url to the source is incorrect, for instance:
```
cat ~/.cocoapods/repos/linphone-bc-public-podspec/linphone-sdk/5.0.50/linphone-sdk.podspec | grep "s.source  "
  s.source       = { :http => "https://www.linphone.org/releases/ios/linphone-sdk-ios-5.0.50.zip" }
```

Newer podspecs point to the correct source, for example:
```
cat ~/.cocoapods/repos/linphone-bc-public-podspec/linphone-sdk/5.0.69/linphone-sdk.podspec | grep "s.source  "
  s.source       = { :http => "https://download.linphone.org/releases/ios/linphone-sdk-ios-5.0.69.zip" }
```

So change the one you use to the correct url
