### ISSUE TITLE
pushNotificationEnabled issue with push notifications and PushRegistry

### ISSUE THREAD

**Issue by eliasalzaghrini** [BelledonneCommunications/linphone-iphone#817]
I am on Linphone SDK > 5.0 on iOS
I want to manage locally both Push Notifications and PushKit (Without Linphone). 
When pushNotificationEnabled = true, notifications are working, but PushRegistry is managed by Linphone.
And when pushNotificationEnabled = false, notifications are no longer working, but PushRegistry is corrrectly managed locally.

Can anyone help me?

**Comment by mhisham** [comment]
+1

**Comment by eliasalzaghrini** [comment]
I found a solution by doing a turnaround, 
set pushNotificationEnabled = false, then all you have to do, is to add 
`UIApplication.shared.registerForRemoteNotifications()`
In the didUpdate method for PushKit after receiving the PushKit token, so it will manually call the registerForRemoteNotifications method
