### ISSUE TITLE
Disable SMS delivery-notification

### ISSUE THREAD

**Issue by udy786** [BelledonneCommunications/linphone-iphone#822]
Hi,

Whenever receiving any SMS on extension, extension sending delivery-notification back to number with status that its delivered and read. So I would like to know how to disable this functionality. 

`<?xml version="1.0" encoding="UTF-8" standalone="no" ?><imdn xmlns="urn:ietf:params:xml:ns:imdn"><message-id>af89ee34-c23f-4324-b3b9-ba672cfaa114</message-id><datetime>2022-04-14T18:02:23Z</datetime><delivery-notification><status><delivered/></status></delivery-notification></imdn>`

Please let me know. 

Thanks
Uday.

**Comment by sysfu** [comment]
I posted a similar issue for the desktop app. Apparently there's an undocumented configuaration file setting that allows status messages such as these to be disable.

https://github.com/BelledonneCommunications/linphone-desktop/issues/785#issuecomment-1702425340

Maybe there is something in the iOS app that can be configured similarly.

I'm going to open a separate feature request issue for adding a SIP account configuration option to disable [Message Composition Indication (RFC 3994)](https://github.com/BelledonneCommunications/linphone-desktop/issues/785#top)

[RFC 3994
](https://datatracker.ietf.org/doc/html/rfc3994)

Message Composition Indication (RFC 3994)
[Event and Presence Framework](https://www.pjsip.org/pjsip/docs/html/group__PJSIP__SIMPLE.htm)
