### ISSUE TITLE
DTMF is causing audio stream to stop

### ISSUE THREAD

**Issue by tevas8** [BelledonneCommunications/linphone-iphone#824]
Linphone SDK Version: 5.1.28

During outgoing calls we can't use DTMF tones because they break the audio stream.

This is pretty disrupting as people are calling an IVR (Interactive Voice Response), choosing an option in a menu by sending a DTMF tone that sends their call to a support technician but then they are unable to talk to support because sending the DTMF tone killed the audio stream.
In fact it kills it only in one way, as the caller can hear the other side of the line but they can't be heard.

This did not use to be the case in previous Linphone versions so it has been introduced relatively recently.
Latest version where the bug was NOT present: 5.0.70

**Steps to reproduce**
1. Call a number that uses an IVR menu
2. Choose an option that will direct you to an agent
3. When your call is put through notice how you can hear the agent but the agent can't hear you

**Comment by roman-yerin** [comment]
@tevas8 any luck with the issue?
