### ISSUE TITLE
Issue : linphone-doesnt-work-well-on-wi-fi 

### ISSUE THREAD

**Issue by Jeel2210** [BelledonneCommunications/linphone-iphone#835]
I am facing some issues regarding status from flexisip .

Scenario : 1 ( Wifi connectivity )
User A calls user B and then call is being cut by User A, Then it will not giving the release status. (Note : in cellular network it works fine. )

Scenario : 2 ( Wifi connectivity )
There are some status missing while connecting wifi network .

please suggest any solution.

**Comment by Arnav-arw** [comment]
You can try setting up a VPN. This might help as it replaces multiple hoops the coonection has to go through by one single tunnnel.
