### ISSUE TITLE
App Crashed on iOS 16 version

### ISSUE THREAD

**Issue by deepak2503** [BelledonneCommunications/linphone-iphone#839]
libsp.dylib: spd_checkin_socket.cold.1 + 16

[BgqdzbHLcS6RkJ3yHAG2vn.xccrashpoint.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/9695915/BgqdzbHLcS6RkJ3yHAG2vn.xccrashpoint.zip)

<img width="1512" alt="Screenshot 2022-10-03 at 2 11 16 PM" src="https://user-images.githubusercontent.com/16147783/193535698-9f3454f1-5340-438b-8449-a3715e13a856.png">

**Comment by vishnunair43** [comment]
Hi, 
May i know what version of linphone sdk are you using for building the project?

**Comment by golditdev** [comment]
I have same issue, line-phone sdk crashed on iOS 16, Xcode 14.0.1

**Comment by deepak2503** [comment]
> Hi,
> May i know what version of linphone sdk are you using for building the project?

Version 5.1.64

**Comment by guofengtd** [comment]
<img width="1378" alt="2022-12-01 21 30 27" src="https://user-images.githubusercontent.com/13635167/205070598-99c5d467-eabe-4307-988c-aa10820dbee9.png">

iPhone 11 Pro Max + iOS 16.0.2 + tls
Using linphone-sdk (5.2.0-alpha.172+ec269c19)

crashes every time!
anyone can help?

**Comment by hieultse03355** [comment]
![Screen Shot 2022-12-26 at 15 12 28](https://user-images.githubusercontent.com/14196282/209523390-595ead86-e18d-4249-af77-7b9e05532dd2.png)
I am using Linphone too, so am i facing to the same issue with you right? So do you find out some solution for this issue? @guofengtd

**Comment by oenama** [comment]
any update? were you able to fix it?

**Comment by comebabymiss** [comment]
Have you repaired it

**Comment by Viish** [comment]
Yes it has been fixed a while ago, simply use latest 5.2 release.
