### ISSUE TITLE
no background for udp sip registration?

### ISSUE THREAD

**Issue by zj299792458** [BelledonneCommunications/linphone-iphone#84]
Hi there. I just found I'm not able to receive any call notification during background with udp sip registration (didn't test tcp). 

I dig into the code and I can only find 'setKeepAliveTimeout' is called during the background for maintaining sip registration for every 600 secs. I don't see any wake-up callbacks during background for incoming call. 

But strangely in 'linphonecore.h' line 3013 it's well commented that we can config udp sip socket as persistent by retrieving the socket from 'ortp_socket_t linphone_core_get_sip_socket(LinphoneCore *lc);' and setting kCFStreamNetworkServiceType to kCFStreamNetworkServiceTypeVoIP somehow. So why don't do it? Is there a technical barriers?

Thank you.

**Comment by juiced** [comment]
Apple/iOS doesn't support keeping UDP sockets open when backgrounding VoIP apps, because UDP needs keepalives every few seconds and therefore drains the batteries. Using TCP/TLS you will be able to receive incoming calls while the app is in the background.

**Comment by bagage** [comment]
Yes, thanks @juiced.
