### ISSUE TITLE
Build error when using gRPC-ProtoRPC

### ISSUE THREAD

**Issue by ninholli** [BelledonneCommunications/linphone-iphone#840]
I can not build my iOS project if using gRPC-ProtoRPC framework when upgrade to 5.1.64
I use cocoapods: pod 'gRPC-ProtoRPC' and get issues when build:
 - Could not build Objective-C module 'linphone'
 - 'chrono' file not found in the time.h

**Comment by ChandlerBinGuo** [comment]
same question.
