### ISSUE TITLE
Audio Message Issue in iOS 16.0.2

### ISSUE THREAD

**Issue by merry37** [BelledonneCommunications/linphone-iphone#841]
Audio message voice not coming in iOS 16.0.2 while it's working on iOS 15 version. Anyone have solution ? I am using LinphonePlayer

**Comment by Viish** [comment]
Hi,

This issue has been fixed in SDK release 5.1.66.

**Comment by zeshanbaig786** [comment]
5.2 beta version for audio fix please?

**Comment by Viish** [comment]
@zeshanbaig786 the current public testflight is using latest 5.2 that has the fix.
