### ISSUE TITLE
turn, ice, stun enabled + mediastreamer/ice: Retransmit (7) binding request for pair

### ISSUE THREAD

**Issue by OulaGaddour** [BelledonneCommunications/linphone-iphone#849]
`'linphone-sdk', '5.0.63'` but reproductible in new versions too.

hi,
in the app im setting turn + ice + stun configs, when i kill the app and receive a new incoming call:
the app is able to register with success , however there is no media.
in linphone logs, i noticed this kind of logs:
`mediastreamer/ice: Retransmit (7) binding request for pair.`

so after 7 retries , i got this log, then linphone send a bye packet:

`07/12/2022 à 00:05:15 [Notice] belle-sip/Changing [server] [INVITE] transaction [0x281834000], from state [ACCEPTED] to [TERMINATED]

﻿07/12/2022 à 00:05:15 [Notice] belle-sip/Server INVITE transaction [0x281834000] terminated
﻿07/12/2022 à 00:05:15 [Notice] belle-sip/transaction [0x281834000]: ending transaction background task with id=[2d].
﻿07/12/2022 à 00:05:15 [Notice] liblinphone/Call [0x11fd62d20]: Media connectivity with "New contact" <sip:+335999999999@185.63.XX.XX> is lost, call is going to be terminated
`
here is the full log:
[incoming+turn+copie.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/10171445/incoming%2Bturn%2Bcopie.txt)

if the app is on foreground and i make a new call, this later is working fine and i can hear my callee, here is the log:
[outgoing+turn - copie.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/10171483/outgoing%2Bturn.-.copie.txt)

**Comment by Viish** [comment]
Hi,

5.0.63 is a very old SDK release, please update to latest one (5.2.0 at this time).
If you still have the issue, please attach new logs.

**Comment by OulaGaddour** [comment]
thanks @Viish for your quick reply,
here are the full log for each scenario, linphone 5.1.73 :

incomingCall + without Turn,ice,stun: OK
[incomingCall+withoutTurn.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/10175551/incomingCall%2BwithoutTurn.txt)

incomingCall  with Turn,ice,stun: NOK
[incomingCall+withTurn.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/10175552/incomingCall%2BwithTurn.txt)

outgoingCall + without Turn,ice,stun: OK
[outgoingCall+withoutTurn.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/10175553/outgoingCall%2BwithoutTurn.txt)

outgoingCall + with Turn,ice,stun: OK
[outgoingCall+withTurn.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/10175555/outgoingCall%2BwithTurn.txt)

Thanks

**Comment by OulaGaddour** [comment]
i see that this ticket is closed , should i create a new one? @Viish
