### ISSUE TITLE
./prepare.py can't run

### ISSUE THREAD

**Issue by zddawn** [BelledonneCommunications/linphone-iphone#85]
ERROR:root:Could not find prepare module: 'module' object has no attribute 'Target', probably missing submodules/cmake-builder? Try running:
git submodule sync && git submodule update --init --recursive

Two months ago, I can also compile
Maybe the problem is that antlr can not download now?

**Comment by bagage** [comment]
Did you ran ` git submodule sync && git submodule update --init --recursive`? Can you show output of `find submodules/ -maxdepth 2`?

**Comment by zddawn** [comment]
No,not anything output

**Comment by zddawn** [comment]
It output : `fatal: Not a git repository (or any of the parent directories): .git`
Then run git init  output :`Initialized empty Git repository in /Users/tianming/Downloads/linphone-iphone-master/.git/`
Then input `git submodule sync && git submodule update --init --recursive`  havn't anything output

**Comment by bagage** [comment]
Don't download a ZIP copy of this repository, but clone it otherwise nothing will work:

`git clone https://github.com/BelledonneCommunications/linphone-iphone.git --recursive`

**Comment by bagage** [comment]
Closing since no response for a long time. Please reopen if needed.

**Comment by gabrielvincent** [comment]
I'm having this problem.
I did run `git submodule sync && git submodule update --init --recursive` but I keep getting the error.

The output I get when I run `find submodules/ -maxdepth 2` is:

`
submodules/
submodules//bcg729
submodules//bctoolbox
submodules//bcunit
submodules//belcard
submodules//belle-sip
submodules//belr
submodules//bzrtp
submodules//cmake-builder
submodules//externals
submodules//externals/antlr3
submodules//externals/bv16-floatingpoint
submodules//externals/codec2
submodules//externals/ffmpeg
submodules//externals/gsm
submodules//externals/libjpeg-turbo
submodules//externals/libmatroska-c
submodules//externals/libvpx
submodules//externals/libxml2
submodules//externals/mbedtls
submodules//externals/opencore-amr
submodules//externals/openh264
submodules//externals/opus
submodules//externals/speex
submodules//externals/srtp
submodules//externals/vo-amrwbenc
submodules//externals/x264
submodules//linphone
submodules//mediastreamer2
submodules//msamr
submodules//mscodec2
submodules//msopenh264
submodules//mssilk
submodules//mswebrtc
submodules//msx264
submodules//ortp
`

**Comment by tahirjilani** [comment]
Faced same issue couple of times. I was cloning by using SourceTree by enabling recursive submodules option which was not cloning complete source code. I tried in terminal git clone https://github.com/BelledonneCommunications/linphone-android.git --recursive and it worked. ./prepare.py works fine now.

**Comment by andresheredia777** [comment]
hello I have this problem when I try to run make:
andres@andres ~/Desktop/linphone-android $ sudo make
./gradlew clean

FAILURE: Build failed with an exception.

* Where:
Build file '/home/andres/Desktop/linphone-android/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating root project 'linphone-android'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
make: *** [java-clean] Error 1

**Comment by a2t2** [comment]
@andresheredia777  Was your problem resolved ?
