### ISSUE TITLE
multiple accounts on iOS client not working

### ISSUE THREAD

**Issue by ajay-gh** [BelledonneCommunications/linphone-iphone#852]
When trying to "use" two separate accounts (for example one linphone account, one separate sip account from another provider) using the assistant under version 4, the second account does first seem to be accepted. But it turns out both accounts (visible in the UIs  sidebar) do not work. Strange enough, the client does even show 2x2 accounts in the side bar where one expect 2 only. Trying exactly the same setup in the Linphone desktop version works just fine with both accounts, which proves that this is not a problem with the accounts, their parameters, etc. Setting up only one of the two accounts (or deleting the second) does not cause any issues.
Conclusion: this (current) iOS version can only handle one (sip) account properly. It seems intended to allow more accounts (and switch between them inside the client), but this does not work.
If I can help further please respond and I will try to provide further information about the bug

iOS 12.5.6 (my device cannot be upgraded further), but this seems unrelated to this issue.
Linphone for iOS, v4.6.8

**Comment by eric-brechemier** [comment]
I confirm the issue, which I experienced with two SIP accounts from the same VOIP provider as well. Using either SIP account alone works. Once a second account is added, authentication is reported to fail systematically. Deleting either of the two accounts makes the single account active and working again.

I also noticed that if the different SIP accounts are configured with the same user name for different SIP domains, Linphone Settings get confused about which is which, and display a list in which all accounts have the same name (the common user name) and give access to the settings of one of the accounts, always the same, making the settings of the other accounts for different domains unreachable.

Linphone iOS version 5.0.2
Linphone SDK 5.2.32
on iPadOS 16.5
