### ISSUE TITLE
How to fix Linked against modern SDK, VOIP socket will not wake. Use Local Push Connectivity instead with pod pod  'linphone-sdk', '5.2.20' not install

### ISSUE THREAD

**Issue by jamesdevmt** [BelledonneCommunications/linphone-iphone#859]
hi @Viish  I tried to use the new sdk as vish said there was a fix in an xcode 14 issue but I can't download or update the new sdk. Hope for a help

<img width="548" alt="Screenshot 2023-02-06 at 1 59 03 PM" src="https://user-images.githubusercontent.com/81943697/216904174-812b6570-89b0-4901-8c3d-f0cdc13656eb.png">

**Comment by yudhisthira123** [comment]
@jamesdevmt @Viish  any update on this issue?
