### ISSUE TITLE
nasm is missing

### ISSUE THREAD

**Issue by ghost** [BelledonneCommunications/linphone-iphone#86]
I keep getting this error when it's already installed
ERROR: The following binaries are missing: nasm. Please install them using:
brew install nasm

**Comment by bagage** [comment]
`which nasm`?
`narm -v`?
`echo $PATH`?

**Comment by bagage** [comment]
Can you show me output of `nasm -f elf32` please?

**Comment by baixiangguobing** [comment]
it says
nasm: error: no input file specified
type `nasm -h' for help

**Comment by baixiangguobing** [comment]
but if I do nasm -f ELF32 or nasm -f elf, it'll work

**Comment by bagage** [comment]
Is it still not working?

**Comment by ReisBenjamin** [comment]
not answered.
Please update to latest commit and re-open if still happening

Thanks

**Comment by rajivudayan** [comment]
Check this answer
https://github.com/BelledonneCommunications/linphone-iphone/issues/25
