### ISSUE TITLE
How to receive incoming calls when app is closed? (I integrated Pushkit and Callkit)

### ISSUE THREAD

**Issue by SmartSystemElectronics** [BelledonneCommunications/linphone-iphone#865]
I really need to receive incoming calls when app is closed. Actually I researched for this issue from many documentations but couldn't find any solution. Actually I integrated Pushkit and Callkit and when I write below command, test call coming to me in background but I don't know how to know incoming calls coming to app when app is closed? how to trigger? I know it should be some settings on sip server but I use local sip server. Can you help me for this issue? How can I do that?

To test call, I used this command;
`curl -v -d '{"aps":{"alert":"hello"}}' --http2 --cert YeniCallKit.pem:202148 https://api.development.push.apple.com/3/device/177e7861396ad0256886673d1efb3c82d5adb54e86dc5cfd781356c1672cfa07`

For you my local sip server should support Pushkit to integrate it? Or any development be able to do on sip server?

**Comment by mhisham** [comment]
Check this https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/IOS%20push%20notification%20management/

I tried it too and call received and the number get registered but it ends the call after that
