### ISSUE TITLE
Unable to build the Linphone-iphone project

### ISSUE THREAD

**Issue by Saikumar3002** [BelledonneCommunications/linphone-iphone#868]
While building the Linphone-iphone project, getting the below error:

**<img width="1440" alt="Screenshot 2023-03-07 at 2 40 49 PM" src="https://user-images.githubusercontent.com/29062614/224227932-68927397-87d5-4bcc-b528-8eb2e1ea881f.png">**

**Comment by khancom1988** [comment]
@Saikumar3002 Did you find any solutions to this issue.

**Comment by liudehuaGithub** [comment]
Have you found a solution to this problem? I have the same problem now

**Comment by liudehuaGithub** [comment]
I have tested it, the version of pod 'linphone-sdk', '5.2.28' is ok, but it will report an error starting from version 5.2.30, causing the linphone program to fail to run

**Comment by Saikumar3002** [comment]
@khancom1988 Not yet. I didn't get any solution.

**Comment by Saikumar3002** [comment]
@liudehuaGithub how to change the pod 'linphone-sdk' to 5.2.28?

**Comment by liudehuaGithub** [comment]
pod 'linphone-sdk', '5.2.28'    That should do it

**Comment by liudehuaGithub** [comment]
> @liudehuaGithub如何将 pod 'linphone-sdk' 更改为 5.2.28？

pod 'linphone-sdk', '5.2.28' That should do it

**Comment by Ali3bdelhady** [comment]
> > @liudehuaGithub如何将 pod 'linphone-sdk' 更改为 5.2.28？
> 
> pod 'linphone-sdk', '5.2.28' That should do it ，In the Podfile。

I have added pod 'linphone-sdk', '5.2.28'  to Podfile but when I run pod install it gives me another version,
When trying to add a newer version installed it successfully but got the same error No such module 'linphone'.

**Comment by robertcoroianu** [comment]
> > > @liudehuaGithub如何将 pod 'linphone-sdk' 更改为 5.2.28？
> > 
> > 
> > pod 'linphone-sdk', '5.2.28' That should do it ，In the Podfile。
> 
> I have added pod 'linphone-sdk', '5.2.28' to Podfile but when I run pod install it gives me another version, When trying to add a newer version installed it successfully but got the same error No such module 'linphone'.

I have the same issue when I'm trying with a new version "No such module 'linphone'. Did you find it a solution to this?
