### ISSUE TITLE
About Login

### ISSUE THREAD

**Issue by cache0928** [BelledonneCommunications/linphone-iphone#87]
I have to Input Proxy & enable outbound proxy to login my sip server
![2016-06-22 at 5 06](https://cloud.githubusercontent.com/assets/7350995/16260914/f14fed9c-389b-11e6-9540-26ca05a5254a.png)
But I can't find these two field in the login VC
<img width="351" alt="2016-06-22 5 07 05" src="https://cloud.githubusercontent.com/assets/7350995/16260925/feea7012-389b-11e6-8481-08b471ed052f.png">
Can you tell me how to coding about it ? I have set these four parameter, but if don't have proxy & enable outbound proxy, I can't login success.
<img width="805" alt="2016-06-22 5 09 32" src="https://cloud.githubusercontent.com/assets/7350995/16260987/44cd51c6-389c-11e6-896d-b0937063f415.png">

**Comment by bagage** [comment]
Just configure login / password / domain (soc1000.com here), then a popup will appear, click on "Continue" and go to settings to add outbound proxy. 
We do not support outbound proxy in assistant to avoid having too many fields.

**Comment by cache0928** [comment]
I want to login success to avoid the popup，how I can coding with it?

**Comment by cache0928** [comment]
Can I set proxy & enable out bound proxy via coding ?

**Comment by bagage** [comment]
Yes, cf [this](https://github.com/BelledonneCommunications/linphone-iphone/blob/master/Classes/LinphoneCoreSettingsStore.m#L508-L517)

**Comment by cache0928** [comment]
what about enable outbound proxy via coding?

**Comment by ReisBenjamin** [comment]
You can change the default value in assistant_external_sip.rc
re-open if issue still occurs.

Thanks
