### ISSUE TITLE
Chat notification integration

### ISSUE THREAD

**Issue by Raviojha62** [BelledonneCommunications/linphone-iphone#873]
Hi Everyone,
I have made setup on server side for chat notification and i am able to get the notification , 
As per linphone documentation i am getting the call-id paramter in apns payload but when i am trying to fetch the message from call-id 
linphone_core_get_new_message_from_callid which returning nil .
So its not working can any body tell me how can i fix it .
Thanks

**Comment by Raviojha62** [comment]
@Viish please help me

**Comment by Viish** [comment]
Hi @Raviojha62,

If this is urgent, I recommend you to contact our company by sending an email to sales@belledonne-communications.com for a dev-assist or support contract.

The help we give here is on a best effort basis, and I don't have enough knowledge of iOS specifics to help anyway.

Cheers,

**Comment by Raviojha62** [comment]
Thanks @Viish . if you can let me like stepwise configure push notification for chat . it will be helpful

**Comment by Viish** [comment]
You should find everything on our wiki: https://wiki.linphone.org/xwiki/wiki/public/view/Main/
