### ISSUE TITLE
 Auto switching to bluetooth hangs linphone sdk

### ISSUE THREAD

**Issue by nikhil-appventurez** [BelledonneCommunications/linphone-iphone#874]
The problem occurs when there is an automatic switch to Bluetooth during a Linphone call, which causes the application to hang or become unresponsive.
Linphone sdk: 5.2.55
iOS version: 16.4.1
@Gui13 @jehandelalune @smorlat @bagage @Viish

**Comment by Ali3bdelhady** [comment]
Could you please tell me how to run it when building the project I got the error No such module 'linphone'
