### ISSUE TITLE
Build failed xcode 14 apple silicon

### ISSUE THREAD

**Issue by Skyle974** [BelledonneCommunications/linphone-iphone#879]
Hello,
I tried to build master banch in xcode 14 on apple silicon.
but I got this error:
Undefined symbols for architecture arm64:
  "_libmsx264_init", referenced from:
      -[LinphoneManager createLinphoneCore] in LinphoneManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried change depency ios version and nothing work.

**Comment by Arguillq** [comment]
Hi, 

this issue should be fixed if you base yourself on the release/5.1 branch, the fix has not yet been merged into master.
You can fix it yourself by removing the two mentions of libmsx264 in the linphonemanager.m file, which is no longer used by the SDK
