### ISSUE TITLE
Linker error duplicate symbol on Simulator

### ISSUE THREAD

**Issue by reste85** [BelledonneCommunications/linphone-iphone#88]
Hi,
my application is using Linphone iPhone and all is going right when i test it on a real device. Unfortunately when i build for the simulator i'm getting this error:

duplicate symbol _Levinson in:
    Linphone/lib/libbv16.a(levdur.c.o)
    Linphone/lib/libopencore-amrnb.a(levinson.cpp.o)
ld: 1 duplicate symbol for architecture x86_64

is that a bug? 

Thank you very much

**Comment by bagage** [comment]
Indeed, there is a method conflicts between these 2 plugins. Do you need both bv16 and amr codecs? 

Confirming the bug, I'll fix it later.

**Comment by bagage** [comment]
Fixed in 1c78556
