### ISSUE TITLE
Linphone iphone build error

### ISSUE THREAD

**Issue by Ali3bdelhady** [BelledonneCommunications/linphone-iphone#882]
I'm trying to build linphone iPhone, 
I've followed the guide here https://github.com/BelledonneCommunications/linphone-iphone 
I have cocoapods 1.8.4 
Then run pod install in the project directory and everything works fine 
Then open linphone.xcworkspace file 
But, I got the error No such module 'linphone' when trying to build it.
![Screenshot 2023-07-22 232137](https://github.com/BelledonneCommunications/linphone-iphone/assets/105130773/68dfdabd-d54b-48fb-bebe-aba6aa8bcaf7)

 So, please any help?

**Comment by ceobitch** [comment]
Having same issue

**Comment by Ali3bdelhady** [comment]
anyone could help ??

**Comment by robertcoroianu** [comment]
Same Issue

**Comment by iosmoon38** [comment]
I am facing the same issue. Does anyone have a solution?

![Screenshot 2023-09-04 at 1 00 53 PM](https://github.com/BelledonneCommunications/linphone-iphone/assets/114209530/8f7abe2e-4693-414f-b60c-3216f134698e)

**Comment by robertcoroianu** [comment]
> I am facing the same issue. Does anyone have a solution?
> 
> ![Screenshot 2023-09-04 at 1 00 53 PM](https://user-images.githubusercontent.com/114209530/265387264-8f7abe2e-4693-414f-b60c-3216f134698e.png)

When I received this error, I removed include folly from the config file, and it worked perfect.
I hope it help you.
```
#ifndef FOLLY_NO_CONFIG
#include <folly/folly-config.h>
#endif
```

**Comment by iosmoon38** [comment]
@robertcoroianu, Thanks for the response. I can't find folly in the whole project. Can you please guide me?

```
#ifndef FOLLY_NO_CONFIG
#include <folly/folly-config.h>
#endif
```

**Comment by robertcoroianu** [comment]
> 
Sorry, I forgot, I'm using react-native.
The package was from the react-native, and because of it, I've got the same error as you.
Maybe you have another conflict with another pod.
