### ISSUE TITLE
SRV resolution isn't working like on android

### ISSUE THREAD

**Issue by davidcsi** [BelledonneCommunications/linphone-iphone#885]
Hello,

I created an SRV for my test sip server like this:

```
% dig -t SRV _sip._tcp.mydomain.com.

; <<>> DiG 9.10.6 <<>> -t SRV _sip._tcp.mydomain.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59445
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_sip._tcp.mydomain.com.	IN	SRV

;; ANSWER SECTION:
_sip._tcp.mydomain.com. 300 IN	SRV	10 10 5067 sip.mydomain.com.

;; Query time: 47 msec
;; SERVER: 4.2.2.1#53(4.2.2.1)
;; WHEN: Sat Aug 19 02:19:51 CEST 2023
;; MSG SIZE  rcvd: 99
```

This is the case for TCP, but for TLS it is the same (_sips._tcp.mydomain.com).
This works perfectly on Android, but it doesn't work on iPhone... It complaints:

`
[linphone/belle-sip] MESSAGE dns_service_query_record_cb : resolving _sip._tcp.mydomain.com. : no such record
`

Any ideas why? the DNS i configured on the phone is the same as where i did the "dig".

Thanks!

David

**Comment by Viish** [comment]
Hi,

Check linphone SDK debug logs to make sure it used the DNS server you expect.

Cheers,

**Comment by davidcsi** [comment]
Thanks for replying! i've checked the logs many times. And on Android i do see the DNS it's using in the logs, (4.2.2.1). But on iphone there's nothing saying which servers it's using. And the app sometimes just doesn't connect when on Android it connects perfectly... i'm stumped on what the reason could be.
