### ISSUE TITLE
Unable to send push notifications

### ISSUE THREAD

**Issue by devs-bg** [BelledonneCommunications/linphone-iphone#890]
flexisip-error-Could not create push notification: %sInvalid RFC8599 push parameters: pn-param declares 1 service(s), whereas there is/are 2 token(s) in pn-prid

I have all setup the dev and prod certificates in /etc/flexisip/apn
But for some reason the flexisip return only pn-param=ABCD1234.com.app.com.voip instead of pn-param=ABCD1234.com.app.com.voip&remote

**Comment by devs-bg** [comment]
Hello anyone can help on this?

**Comment by juliancorrea** [comment]
Same here!

**Comment by Viish** [comment]
Take a look at https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications#iOS, it might help you.

**Comment by juliancorrea** [comment]
Hey @Viish , is there a way to simulate a call by just sending a push notification? Can it be done?
