### ISSUE TITLE
Ldap contacts | Magic Search Crash

### ISSUE THREAD

**Issue by Economog98** [BelledonneCommunications/linphone-iphone#894]
Added an ldap configuration and everything works okay except the magic search functionality. 
During the search it randomly crashes, noticed this happens more when you type fast or with small intervals between some letters. Tried to changes delay, timeout, and various other settings both on ldap server and on the app, but the crashes persist.

**Comment by Viish** [comment]
@Economog98,

Please provide the SDK debug logs from the start of the app to the moment it crashes along with the symbolized crash stack trace.

**Comment by Economog98** [comment]
Crash :
[2023-10-16_12-56-03.7475_+0300-6712acbb17d5d23200c877f3c152554a2e033672.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/13004528/2023-10-16_12-56-03.7475_%2B0300-6712acbb17d5d23200c877f3c152554a2e033672.txt)

Log from app from start of the to cr
[linphone_log1.txt](https://github.com/BelledonneCommunications/linphone-iphone/files/13018093/linphone_log1.txt)
ash:

**Comment by Economog98** [comment]
Any update on this?

**Comment by Economog98** [comment]
Accidentally closed the issue, any update on this?
