### ISSUE TITLE
Can I make the two recorded files separated by speaker?

### ISSUE THREAD

**Issue by yh97yhyh** [BelledonneCommunications/linphone-iphone#896]
Can I make the two recorded files separated by speaker?

I recorded the entire voice of a call. but I want to record two files for each speaker-separated call. Is it possible?

**Comment by Viish** [comment]
Hi,

No this isn't currently possible, the recording filter in https://github.com/BelledonneCommunications/mediastreamer2 being instantiated after the mixer.

Cheers,
