### ISSUE TITLE
Calls drop on iPhone

### ISSUE THREAD

**Issue by BEEBZER** [BelledonneCommunications/linphone-iphone#897]
Hi there,

We use Linphone for iOS in our company and we didn't have any issues until last week. All of a sudden (no update on FreePBX 16, no update on the app itself), we are unable to make outgoing calls, they just drop and the other parties receive a miscall. We rebooted FreePBX, deleted and installed the Linphone app, no use, we still face the same problem.

Any idea?

Best,

Savas

**Comment by Viish** [comment]
Hi @BEEBZER,

Could you please turn on debug logs, restart the app, reproduce the issue and then attach logs here ? This way we could tell you what's happening.

Cheers,
