### ISSUE TITLE
HA1 password and plain password bug

### ISSUE THREAD

**Issue by AdilSoomro** [BelledonneCommunications/linphone-iphone#9]
There's a bug in writing plain text password if ha1 is not provided while writing auth info
File: linphone-iphone/submodules/linphone/coreapi/authentication.c
Function: linphone_auth_info_write_config

We read the `store_ha1_passwd` config defaulting to 1

    bool_t store_ha1_passwd = lp_config_get_int(config, "sip", "store_ha1_passwd", 1);

and then we're checking if `store_ha1_passwd` is true, and then we're checking if `obj - > ha1` isn't `NULL`. Then save the `ha1` password.

But if `ha1` was `NULL` then the plain password isn't being saved. Since the else is for `store_ha1_passwd` which is true always:

    if (obj - > passwd != NULL) {
        if (store_ha1_passwd) {
            if (obj - > ha1) { /*if we have our ha1 and store_ha1_passwd set to TRUE,
    then drop the clear text password for security*/
                linphone_auth_info_set_passwd(obj, NULL);
            }
        } else { /*we store clear text password only if store_ha1_passwd is FALSE*/
            lp_config_set_string(config, key, "passwd", obj - > passwd);
        }
    }

Is there specific reason for such condition? In my point of view, it should've been like this:

    if (store_ha1_passwd && obj - > ha1) {
    /*if we have our ha1 and store_ha1_passwd set to TRUE,
        then drop the clear text password for security*/
            linphone_auth_info_set_passwd(obj, NULL);
    } else { /*we store clear text password only if there's no ha1*/
        lp_config_set_string(config, key, "passwd", obj - > passwd);
    }

**Comment by bagage** [comment]
Well, the purpose of this is to avoid storing clear password. If we want to use ha1 password, we do not expect the application to store clear password at any time.
The ha1 can be computed only when registering the first time to the server, so until there we cannot compute it - hence the possible time where the application would be dropped.

**Comment by AdilSoomro** [comment]
Yes, correct, but in the case, if there's a chance if application doesn't provide `ha1`. We should read the default config for ha1 with `0` as default value.

    lp_config_get_int(config, "sip", "store_ha1_passwd", 0);

**Comment by bagage** [comment]
Well, by default it's better to always use ha1. If someone really wants to store clear passwords, he/she can change it.
This is application task to query user's password just before registering to server in order to minimize the chance of dropping the password - it will be kept in memory the whole time application is running and password will be dropped only if no connection to the server was successful AND the password was asked.

**Comment by AdilSoomro** [comment]
Providing the `0` for `store_ha1_passwd`  in `sip` section from objective c avoids the default value of `store_ha1_passwd` from being 1 always.

    LinphoneManager *lm = [LinphoneManager instance];
    [lm lpConfigSetInt:0 forKey:@"store_ha1_passwd" forSection:@"sip"];

The linphone iOS app, compiled from source takes the plain password only in Settings tab against `password_preferences` and saves to core settings, since we want to use plain password, there's no way, the app can save the plain password, and it keeps failing the registration in iOS app.

**Comment by bagage** [comment]
I cannot find this portion of code. Can you provide me filename/line number please?

**Comment by AdilSoomro** [comment]
It didn't exist. I added myself to the `LinphoneCoreSettingsStore.m` while adding the auth info to proxy config as follow:

    // mandatory parameters
    NSString * username = [self stringForKey: @"username_preference"];
    NSString * userID = [self stringForKey: @"userid_preference"];
    NSString * domain = [self stringForKey: @"domain_preference"];
    NSString * transport = [self stringForKey: @"transport_preference"];
    NSString * accountHa1 = [self stringForKey: @"ha1_preference"];
    NSString * accountPassword = [self stringForKey: @"password_preference"];
    bool isOutboundProxy = [self boolForKey: @"outbound_proxy_preference"];
    BOOL use_avpf = [self boolForKey: @"avpf_preference"];
    
    if (!accountHa1 || [accountHa1 length] <= 0) {
        //there's no ha1, save the preference as 0
        [lm lpConfigSetInt: 0 forKey: @"store_ha1_passwd" forSection: @"sip"];
    }

**Comment by bagage** [comment]
Well, it cannot work like this (anymore). Either you want to always store clear text password, or you do not want them at all.

**Comment by AdilSoomro** [comment]
If we want to use HA1 password, then we've to provide a HA1 username, password.
linphone ios app will work fine. It won't store plain password.

If we want to use plain password, then we're not providing an HA1 username, password, rather a plain password. But in that case, linphone should save the plain password, since  we're providing a plain password, and not the HA1 password.

The current source doesn't reflect that. I pulled the latest, compile and gave my plain username password, my domain, into Settings tab, and it worked the first time and didn't REGISTER second time after coming from background. The reason was linphone core isn't storing the plain password and it always expect to have a HA1 password as follow:

    bool_t store_ha1_passwd = lp_config_get_int(config, "sip", "store_ha1_passwd", 1);

The actual bug over here in my point of view is, there should be a way to tell linphone that we want to provide an HA1 password or a plain password. I worked around this by saving the config to 0 from Objective C as follow 

    LinphoneManager *lm = [LinphoneManager instance];
    [lm lpConfigSetInt:0 forKey:@"store_ha1_passwd" forSection:@"sip"];

In this way, I've told linphone config to not look for HA1 password, because I'm not providing it, and it should store my plain password.

and the bug is introduced here when saving:

    if (obj - > passwd != NULL) {
        if (store_ha1_passwd) { //ADIL: Since it's always true, it won't goto else part EVERRRR...!!!!!!**
            if (obj - > ha1) {
                /*if we have our ha1 and store_ha1_passwd set to TRUE,
                then drop the clear text password for security*/
                linphone_auth_info_set_passwd(obj, NULL);
            }
        } else {    
            /*we store clear text password only if store_ha1_passwd is FALSE*/
            lp_config_set_string(config, key, "passwd", obj - > passwd);
        }
    }

In the above scenario, if you want to use plain password,  `store_ha1_passwd` is never `FALSE` until you store `0` to the config in the first place.

**Comment by bagage** [comment]
There is no bug here: this is totally intentional. You have 2 choices:

- store password in plain text: simply set store_ha1_passwd=0 in linphonerc-factory, and everywhere linphone will use clear password.
- store hashed password: see linphone-iphone master. When you configure your account, password is clear text and linphone stores it in memory. It registers to the server, which returns the realm, and from that we compute the ha1 (see digest authentication rfc for reference) as username:realm:password. Then this ha1 is stored in config and password is not used anymore. When you come back from background, linphone uses the auth info with ha1 and everything should work. If not, this is a bug.

**Comment by AdilSoomro** [comment]
Agree. Now its clear.
