### ISSUE TITLE
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value in freshly compiled Linphone 5.2

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/linphone-iphone#900]
Hi everyone,

I just tried compiling the latest 5.2 branch with Xcode 15.0.1 and the first error was Xcode complaining that 
"VFSUtil.swift:24:8 Compiling for iOS 12.0, but module 'linphonesw' has a minimum deployment target of iOS 13.0:"

![xcode_error](https://github.com/BelledonneCommunications/linphone-iphone/assets/6282595/d24d8623-f19e-49d0-89a7-e391f315f307)

Ok, so I then set the linphoneExtension,  msgNotificationService and  msgNotificationContent targets to iOS Deployment Target 13.0 (instead of 12.0).

After that it compiles without issues but as soon as it starts running in the simulator (iPhone 15 with iOS 17.0) it starts running into problems:

```
Unable to simultaneously satisfy constraints.
 Probably at least one of the constraints in the following list is one you don't want. 
 Try this: 
  (1) look at each constraint and try to figure out which you don't expect; 
  (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000239d0e0 'accessoryView.bottom' _UIRemoteKeyboardPlaceholderView:0x11ed0ee00.bottom == _UIKBCompatInputView:0x106bbff40.top   (active)>",
    "<NSLayoutConstraint:0x60000239d630 'assistantHeight' SystemInputAssistantView.height == 45   (active, names: SystemInputAssistantView:0x106bbb8a0 )>",
    "<NSLayoutConstraint:0x600002290050 'assistantView.bottom' SystemInputAssistantView.bottom == _UIKBCompatInputView:0x106bbff40.top   (active, names: SystemInputAssistantView:0x106bbb8a0 )>",
    "<NSLayoutConstraint:0x60000239cfa0 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x11ed0ee00]-(0)-[SystemInputAssistantView]   (active, names: SystemInputAssistantView:0x106bbb8a0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000239cfa0 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x11ed0ee00]-(0)-[SystemInputAssistantView]   (active, names: SystemInputAssistantView:0x106bbb8a0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful. 
Type: Error | Timestamp: 2023-12-07 16:19:00.749424Z | Library: UIKitCore | Subsystem: com.apple.UIKit | Category: LayoutConstraints | TID: 0xfc221
```

This is all happening with linphone defaults and the problem starts as soon as I try to login to my linphone account in the wizard.

Hope this bug report is useful.

Cheers,
Peter

**Comment by petervnv** [comment]
It's not just a problem with constraints apparently, as soon as I try to call another linphone user I see the following crash in Xcode 15.

```
linphoneapp/SingleCallView.swift:133: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
Dec 12 16:47:11  linphone[73960] <Error>: linphoneapp/SingleCallView.swift:133: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
```

![photo_2023-12-12_16-49-01](https://github.com/BelledonneCommunications/linphone-iphone/assets/6282595/f32340e7-fb76-4eff-be1b-d9f069eec82b)

Anyone else experiencing this or is it just me?

Cheers

**Comment by petervnv** [comment]
Hi again,

I have just tried compiling release/5.2 with SDK 5.3.4 and the exact same problem occurs as soon as I try to answer a call from another linphone user. I also found what seems to be a new bug with lime chat but not sure if I should spend more time detailing these bug reports if they are not useful at all to the linphone team.

**Comment by petervnv** [comment]
Same exact error with SDKs 5.3.7 and 5.4.0-alpha.10+482eb27b

Does anyone even care about these bug reports or am I just wasting my precious time here?

**Comment by asterix999** [comment]
Hi Peter,

Even though no one ever replied to you it seems you were indeed correct in identifying this bug since it has just been fixed today https://github.com/BelledonneCommunications/linphone-iphone/commit/9094c9cea8104f57d00b76f1dbebebc895fd30ad

I know it is frustrating to contribute bug reports when no one seems to acknowledge them but please continue to do so. At the very least it helps others like myself not waste hours investigating something which has already been reported months ago!

It would be nice if someone from the team actually confirmed the bug reports from the community but this iOS repo seems to get little attention. It looks like the most responsive and proactive repo here is the linphone-android one.

**Comment by petervnv** [comment]
Hi Asterix,
Thanks for your kind words. You are correct. This bug was never acknowledged by the linphone team but it has been recently fixed.
