### ISSUE TITLE
Abnormal usage of iOS17.1.2 system ！！

### ISSUE THREAD

**Issue by SanYeCJS** [BelledonneCommunications/linphone-iphone#902]
Under the iOS 17.1.2 version, linphone cannot be used. I wonder if anyone has paid attention to this problem?

**Comment by Viish** [comment]
Hi @SanYeCJS,

Please describe the problem and attach matching debug logs from app.
As far as we know there is no issue with iOS 17.1.2.

Cheers,

**Comment by SanYeCJS** [comment]
Sorry, something has been delayed these days. We found here that Linphone will fail to log in to the SIP account for the first time on iPhone 11. I have tried the same iOS system version, such as iOS17.1.2, on iPhone12pro max The above is running well, but on iPhone11, it cannot log in successfully for the first time and will return a no network problem. When I click to refresh the status, the following error will be reported:

[Warning] Refresh register operation not available (network unreachable)
[Warning] Refresh register operation not available (network unreachable)
[Warning] Refresh register operation not available (network unreachable)



But when I exit the APP to the background and re-enter the APP, the SIP account will show that the login is successful. I looked at the code and found that the core object was restarted, but I don’t know why I can’t log in for the first time? My network permissions have been assigned. I also tried the linphone version in the Appstore. The situation is the same as above. I wonder if you can troubleshoot this error?

**Comment by SanYeCJS** [comment]
Looking forward to your reply, I will reply as soon as I see it

**Comment by Arguillq** [comment]
Hi, 
could you please upload the full logs of your issue ? 
I tried downloading the Linphone App from the store on older devices : 
- iPhone 6s, iOS 14.6
- iPhone 6 plus, iOS 12.5.7

and I couldn't reproduce it, and neither could I on an iPhone 13 using iOS 17.3

**Comment by SanYeCJS** [comment]
I have tried using the system version you mentioned above and other models, and everything runs normally. I wonder if there is something wrong with the iPhone 11. The iPhone 11 worked normally before I upgraded it to iOS 17, but it stopped working after I upgraded it to iOS 17. , the iPhone system version number in question is iOS17.1.2. The same iOS17.1.2 runs fine on my iPhone 12 promax. I will pull a copy of the log and send it to you today, or do you have an email address? Can I send it directly to you via email?

**Comment by SanYeCJS** [comment]
This is the log that has just been executed. You can take a look at it.

[Log.zip](https://github.com/BelledonneCommunications/linphone-iphone/files/13710157/Log.zip)

**Comment by Arguillq** [comment]
Hi,

my apologies but I cannot begin to find an explanation for your specific issue. Running linphone on iOS Simulator for iPhone 11 (ios version 17.0.1 being the only one I had available on XCode), or even a physical iPhone 11 running on iOS 17.1.2, did not reproduce your issue.

I couldn't find any clue of what is going wrong in the logs you uploaded either. I digged into the SDK code, and the warning you're receiving is theoretically caused by... network being unavailable, as you'd expect. So nothing that would explain what you're encountering

**Comment by SanYeCJS** [comment]
Or I can send you a video of the demonstration? Including using the version in the Appstore to show you? I only tested it on this iPhone 11, because I couldn’t explain why, so I asked the official to help troubleshoot the problem?

**Comment by SanYeCJS** [comment]
If possible, can you provide your email address? I'll record a video for you to watch tomorro

**Comment by SanYeCJS** [comment]
ok
