### ISSUE TITLE
Parsing of SIP Cancel

### ISSUE THREAD

**Issue by jakubprusa** [BelledonneCommunications/linphone-iphone#91]
Hi,

I’ve been developing iOS VOIP application. When I calling from one device to multiple devices and one device accept the call. Then this device (which accepted call) send to others this message:

```
CANCEL sip:pokus1@10.0.32.127 SIP/2.0
Via: SIP/2.0/UDP 10.0.32.139:5062;rport;branch=z9hG4bK816857796
From: "Name" <sip:688686502@192.168.65.4>;tag=1889760655
To: <sip:pokus1@10.0.32.127>
Call-ID: 150232022
CSeq: 20 CANCEL
Max-Forwards: 70
User-Agent: IP 2.16.0.25.2
Reason: SIP;cause=200;text="Call completed elsewhere"
Content-Length: 0

```

Important for me is this reason: **Call completed elsewhere.** I properly get notification about call and, and reason is **LinphoneReasonNotAnswered**. But I need know if call is completed somewhere else or not.

**Comment by jakubprusa** [comment]
I tried to read from

`linphone_call_get_error_info` but i didn't get the text "Call completed elsewhere"

**Comment by jakubprusa** [comment]
This is according this RFC: https://tools.ietf.org/html/rfc3326

**Comment by bagage** [comment]
Please check `linphone_call_get_reason`, which code is:

```
LinphoneReason linphone_call_get_reason(const LinphoneCall *call){
	return linphone_error_info_get_reason(linphone_call_get_error_info(call));
}
```

Hopefully that'll help!
