### ISSUE TITLE
 I am getting the following errors when trying to push application to TestFlight . 

### ISSUE THREAD

**Issue by NavinVr** [BelledonneCommunications/linphone-iphone#914]
Hi,
I use linphone ios sdk SDK 5.3.5 version.

 I am getting the following errors when trying to push application to TestFlight . 

Asset validation failed
Invalid MinimumOSVersion. The value for the Info.plist key MinimumOSVersion could not be parsed . (ID: 914f9917-d79a-45d6-ac07-d914916fcf2c)

Asset validation failed
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle linphone.app/Frameworks/exampleplugin.framework is required. (ID: 967106cc-0038-46fd-9bd0-94bbc87543a7)

**Comment by Viish** [comment]
Hi @NavinVr,

Please stop opening the same tickets here and on our clients bugtracker.

Thanks in advance.

**Comment by NavinVr** [comment]
Could you please advise how to resolve this issue.

**Comment by E2-Mohamed** [comment]
Facing the same issue, @NavinVr Did you figure anything out on how to resolve this?

@NavinVr Please add a link to the issue that is currently open, thanks.

**Comment by NavinVr** [comment]
@E2-Mohamed  Thanks , I have solving this problem.
 its minimum os version issue for exampleplugin.framework .

**Comment by E2-Mohamed** [comment]
@NavinVr Yes, i'm aware of that but how do it fix it?
