### ISSUE TITLE
XMLRPC or FlexiAPI?

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/linphone-iphone#916]
Hi guys,

Does linphone-iphone not support FlexiAPI (REST) like linphone-android does?

I see that FirstLogin in iOS still uses XMLRPC but FlexiAPI  has removed all support for XMLRPC and the android version is already using the REST API so there seems to be 2 incompatible versions currently available which is somewhat confusing.

Cheers

**Comment by petervnv** [comment]
Hi @Viish 

Thanks for your reply! Hmm, that's weird because I am on 5.2.0 release and have in linphonerc-factory the correct params for FlexiAPI:

[account_creator]
backend=1
url=https://my.domain.com/panel/api/

Works fine on Android but on iOS it seems it tries to use XMLRPC when starting with the FirstLogin view (perhaps that's the issue? ie. that FirstLogin view is deprecated or always uses XMLRPC?)

<img width="1420" alt="Screenshot 2024-02-20 at 13 52 26" src="https://github.com/BelledonneCommunications/linphone-iphone/assets/6282595/ccdbdd96-cf3c-42e9-97df-6abc3561bfe4">

Cheers,
Peter

**Comment by Arguillq** [comment]
Hi, 

the FirstLoginView has indeed not been used or maintained for a long time (5-9 years) and was missed during the transition from XMLRPC to FlexiAPI. 

Is there a specific reason why you are not using the AssistantView and you require the FirstLoginView ? The display of this view should be set depending on the "enable_first_login_view_preference" config variable, which is not set and hidden from advanced parameters by default on release/5.2 of linphone-iphone
