### ISSUE TITLE
SDK require Privacy manifest

### ISSUE THREAD

**Issue by yeuem141289** [BelledonneCommunications/linphone-iphone#918]
Since Spring 2024 Apple require SDK have Signed and Manifest file
https://developer.apple.com/news/?id=r1henawx
https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/videos/play/wwdc2023/10060/ 
https://developer.apple.com/videos/play/wwdc2023/10061/
![Screenshot 2024-02-27 at 7 32 51 AM](https://github.com/BelledonneCommunications/linphone-iphone/assets/5528861/d4d056af-887c-4924-8a8d-9bfd2f9ed849)

Does linphone SDK need do this?

**Comment by yeuem141289** [comment]
![Uploading Screenshot 2024-02-27 at 7.32.51 AM.png…]()

**Comment by nexxvoip** [comment]
hello , any update on this ? 
thanks

**Comment by Arguillq** [comment]
Hi, sorry for the delay on this issue, I will investigate and keep you updated
