### ISSUE TITLE
Not able to compile the iOS Build

### ISSUE THREAD

**Issue by disolaterX** [BelledonneCommunications/linphone-iphone#921]
Podfile:

source "https://gitlab.linphone.org/BC/public/podspec.git"
pod 'linphone-sdk' , '~>5.3.4'

But I am getting 

❌  (ios/Pods/RCT-Folly/folly/portability/Time.h:22:10)

  20 | #include <time.h>
  21 | 
> 22 | #include <folly/portability/Config.h>
     |          ^ 'folly/portability/Config.h' file not found
  23 | 
  24 | // OSX is a pain. The XCode 8 SDK always declares clock_gettime
  25 | // even if the target OS version doesn't support it, so you get

❌  (ios/Pods/linphone-sdk/linphone-sdk/apple-darwin/share/linphonesw/LinphoneWrapper.swift:21:8)

  19 | */
  20 | import Foundation
> 21 | import linphone
     |        ^ could not build Objective-C module 'linphone'
  22 | #if canImport(SwiftUI)
  23 | import SwiftUI
  24 | #endif

**Comment by mingeee** [comment]
@disolaterX I am getting the same issue. Did you end up finding a solution? 😭 
Do you mind sharing the solution if you have one?

**Comment by disolaterX** [comment]
> @disolaterX I am getting the same issue. Did you end up finding a solution? 😭 
> 
> Do you mind sharing the solution if you have one?

no luck till now

**Comment by lchenfox** [comment]
The same issue.

**Comment by lchenfox** [comment]
As a workaround:

- 1.  **ios/Pods/RCT-Folly/folly/portability/Time.h**

Change

```
#include <folly/portability/Config.h>
```

into

```
#import "Config.h"
```

- 2.  **ios/Pods/linphone-sdk/linphone-sdk/apple-darwin/share/linphonesw/LinphoneWrapper.swift**

**Comment out** or **remove** the following line

```
#include <folly/folly-config.h> // **Comment out** or **remove** this line.
```

Then clean `Xcode` and build again. It should work well.

**Comment by disolaterX** [comment]
![image](https://github.com/BelledonneCommunications/linphone-iphone/assets/42447408/dc4f18e6-aaad-4395-9ddb-f737f17eaaba)

What you did for this ?

**Comment by lchenfox** [comment]
> ![image](https://private-user-images.githubusercontent.com/42447408/320290123-dc4f18e6-aaad-4395-9ddb-f737f17eaaba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDc1MDUsIm5iZiI6MTcxMjUwNzIwNSwicGF0aCI6Ii80MjQ0NzQwOC8zMjAyOTAxMjMtZGM0ZjE4ZTYtYWFhZC00Mzk1LTlkZGItZjczN2YxN2VhYWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE2MjY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4OTA2ODI1NzZlY2E2OWIzNmVkZDMyZjliYTg1OTU5YjYwZjE2MWQyZDY0OWRlZjg4NDMxZTllMTBiMDg5Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f0zYZxhgdpXTFyVG6uTSjZ8dMC2l8kkx2frgTbVdNbE)
> 
> What you did for this ?

Firstly, make sure that you have already added `PushKit` framework to `Link Binary with Libraries` in `Build Phases`. Then, you have to import `CallKit` framework before importing `linphone` and import your project swift bridging header file. It looks like in `AppDelegate.m`

```
#import <CallKit/CallKit.h>
#import "YOUR-PROJECT-NAME-Swift.h"
#import <PushKit/PushKit.h> 
#import <linphone/linphonecore.h>
```

**Comment by mingeee** [comment]
> As a workaround:
> 
> * 1. **ios/Pods/RCT-Folly/folly/portability/Time.h**
> 
> Change
> 
> ```
> #include <folly/portability/Config.h>
> ```
> 
> into
> 
> ```
> #import "Config.h"
> ```
> 
> * 2. **Pods/RCT-Folly/folly/portability/Config.h**
> 
> **Comment out** or **remove** the following line
> 
> ```
> #ifndef FOLLY_NO_CONFIG
> //#include <folly/folly-config.h> // **Comment out** or **remove** this line.
> #endif
> ```
> 
> Then clean `Xcode` and build again. It should work well.

You are the man! Thanks!

**Comment by vukan-m** [comment]
I have worked out what seems to be the problem for me, but still didn't find a solution since im not that experienced with iOS development.

The problem seems to be that `#include "time.h"` doesn't include the system time header, but instead RCT-Folly/probability/Time.h (in my case).

If you can somehow override this or tell it specifically which header file to import, that would solve the issue.
