### ISSUE TITLE
Incoming call issue for accepting

### ISSUE THREAD

**Issue by bidawaptg2023** [BelledonneCommunications/linphone-iphone#924]
I am facing issues when accepting new incoming calls. I received a VoIP push from the server. When I receive a VoIP push notification then loged in to the linphone after that make a reset API call to the server to resume incoming call and send an invite to the iPhone user. but before the API process completion the user accepts the incoming call through the call kit and a new call invite is received after the incoming call is accepted by the user then incoming call will never accepted by the user but call kit shows call is started. How can I fix it in linphone IOS. On server side we are using the Kamailio server.

**Comment by chillcollex** [comment]
Hi @bidawaptg2023 ,

I noticed that you've managed to resolve the VoIP push issue with Linphone on iOS. That's fantastic news!

I'm currently facing a similar challenge. I've configured the VoIP push payload to trigger CallKit, and the incoming call UI appears as expected. However, when I answer the call, it doesn't connect—there's no audio, and the call doesn't seem to establish properly.

Could you please share how you managed to solve this issue? Any insights, tips, or advice would be greatly appreciated. I'd love to learn from your experience.

Thank you in advance for your time and assistance!
