### ISSUE TITLE
Unable to build linphone-ios with local sdk 

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-iphone#929]
Hi @Viish 

I tried building local sdk and compiled it with Ninja technique sdk build was successful

than i ran the command PODFILE_PATH=/Users/ABC/Desktop/linphone_ios_sdk/linphone-sdk pod install

but i am getting this error :
[!] No podspec found for `linphone-sdk` in `/Users/ABC/Desktop/linphone_ios_sdk/linphone-sdk`

I could not build folder generated in sdk directory previously with old cmake build folder was generated but that technique takes lot of time i used Ninja Technique which was mentioned in Readme.md file but build folder not generated only ios-build folder generated .

How to make it work if local sdk compiled using Ninja command.

Could you please tell me what is the correct way to use local sdk i am trying use local sdk to work with flexisip.

Thanks

**Comment by Adnan-addi** [comment]
@all

Please help me with this issue 
There is no extra documentation i could find to move further with development.

Thanks

**Comment by Adnan-addi** [comment]
Thank you for this

**Comment by waseemkhanyes** [comment]
![image](https://github.com/BelledonneCommunications/linphone-iphone/assets/59431339/86cb2a38-1c8c-4505-b8e2-032f971e137f)

Facing this issue after installing the above command

![image](https://github.com/BelledonneCommunications/linphone-iphone/assets/59431339/a6c9c02f-6d63-4fc0-b1ad-adf2488386cb)

**Comment by aostano** [comment]
probably you use -DENABLE_SWIFT_WRAPPER=OFF
set this at ON or remove from cmake --prepare command

Bye   ;-)
