### ISSUE TITLE
Logout Functionality

### ISSUE THREAD

**Issue by uditbatra** [BelledonneCommunications/linphone-iphone#93]
I want to implement logout functionality. 
I can se currently there is only remove account functionality which is using the below function which deleted all configuration:
/**
 * Removes a proxy configuration.
 *
 * LinphoneCore will then automatically unregister and place the proxy configuration
 * on a deleted list. For that reason, a removed proxy does NOT need to be freed.
**/

`LINPHONE_PUBLIC void linphone_core_remove_proxy_config(LinphoneCore *lc, LinphoneProxyConfig *config);
`

I only want to implement logout. 
And want that the Proxy and other settings be intact on logout.

Thanks in Advance.

**Comment by bagage** [comment]
This is already implemented, check "Disable/Enable" setting in account management; it turs on/off registrations for the given proxy config.
