### ISSUE TITLE
register account bug

### ISSUE THREAD

**Issue by gaoruiqing187** [BelledonneCommunications/linphone-iphone#930]
![image](https://github.com/BelledonneCommunications/linphone-iphone/assets/14845602/687a54a9-9a62-4d60-a94a-c705338a9daa)

When I register my account, I don't get the result. I call refreshRegisters() and the log is printed as shown in the figure above. My network is fine, neither Wi-Fi nor 5G. The problem only occurs when you install the app for the first time.
Sometimes waiting 5 minutes will return the result。how to solve it.

![image](https://github.com/BelledonneCommunications/linphone-iphone/assets/14845602/d24af34b-e6c5-405b-a282-3a9ee8bc28a8)
This is the code I registered

**Comment by Viish** [comment]
Hi @gaoruiqing187,

Please attach SDK debug logs from the start of the app to the moment the issue happens.

Cheers,

**Comment by gaoruiqing187** [comment]
<img width="755" alt="image" src="https://github.com/BelledonneCommunications/linphone-iphone/assets/14845602/84b26123-f44a-4678-b66e-e25f08d94972">
Twenty seconds after calling the registration method, I call the refreshRegisters method, and the log displays the contents in the red box

**Comment by Viish** [comment]
@gaoruiqing187 That's not what I asked you.
