### ISSUE TITLE
iphone 15pro linphone, doesnt stay connected in background.

### ISSUE THREAD

**Issue by niyon-x** [BelledonneCommunications/linphone-iphone#931]
Hey guys, is linphone unusable in iphone? When I close the linphone app or have it in background, it disconnects, doesnt stays connected, so I have to keep it open all the time? I am using sip of twilio. Please let me know If there is any way around it. Thanks.

**Comment by petervnv** [comment]
Hi,

That's expected. iOS doesn't allow backgound apps to keep an open channel to the server.
You probably need to setup a push notification server to work with twilio so it can wake up your app and have it register on twilio when there's an incoming call or message. https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/HOWTOs/Push%20Gateway/

Cheers

**Comment by jay98760** [comment]
Other iOS 18 voip apps with push notifications disabled can run fine in the background and will ring as normal.
