### ISSUE TITLE
terminating the app after incoming call is not working

### ISSUE THREAD

**Issue by shubhamparekh2000** [BelledonneCommunications/linphone-iphone#932]
I'm using the push kit,
when my app is terminated state incoming call notification time my app will not awake can you please explain to me how to resolve this issue?

**Comment by Viish** [comment]
Hi @shubhamparekh2000,

Read this: https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Push%20notifications/IOS%20push%20notification%20management/

Cheers,

**Comment by shubhamparekh2000** [comment]
thanks for replying me but I want to know how to register in the sip when my app is terminated & incoming call notification will be come.

note: my code will be written in **objective C**
