### ISSUE TITLE
Remote address is as "sip:anonymous@anonymous.invalid" for Incoming call with Callkit push notification.

### ISSUE THREAD

**Issue by mingeee** [BelledonneCommunications/linphone-iphone#935]
<img width="591" alt="image" src="https://github.com/BelledonneCommunications/linphone-iphone/assets/48815262/5a6132e4-e1ac-41d1-9c38-30181d76b1a6">

I was thinking about listening to onPushNotificationReceived to update the remote address with 
"from-uri" : "sip:pusher@sip.example.org"

But the callback is only being triggered after the call. 

Hmm... Does anyone have any ideas on how can I show the correct caller when using push notifications?

**Comment by darmaheev** [comment]
We have the same problem, did you find a solution?

**Comment by mingeee** [comment]
> We have the same problem, did you find a solution?

@darmaheev Hmm... I don't think there is a way show the SIP address immediately from my research.

The workaround for this is update the callkit once you have got the SIP address. 

`self.mProviderDelegate.updateCall(uuid: uuid!, displayAddress: prettifyAddress(self.remoteAddress))`

The function inside the mProviderDelegate
`func updateCall(uuid: UUID, displayAddress: String) {
      let update = CXCallUpdate()
      update.remoteHandle = CXHandle(type:.generic, value: displayAddress)
      
      provider.reportCall(with:uuid, updated:update);
   }`

Not the best but it is the same as how linphone native does it. Eg, showing "Incoming" ---> then update with the sip address once you got the info.
