### ISSUE TITLE
Apple App Store Rejections - Guideline 4.3(a) - Design - Spam

### ISSUE THREAD

**Issue by arron-tamar** [BelledonneCommunications/linphone-iphone#936]
Hi All,
 
Just reaching out to you to see if anyone has recently come across issues regarding submission of a customized linphone iPhone app to the Apple App Store.
 
We have modified functionality to bring it inline with our product and colour scheme.
 
However, when submitting the app to Apple for review, we have received the following rejection from them:
 
"Regarding Guideline 4.3(a) - Design - Spam, your app shares a similar binary, metadata, and/or concept as apps submitted to the App Store by other developers, with only minor differences."
 
This is not an issue/rejection we have come across before (we have submitted a Linphone iPhone app before with adjustments).
 
Has anyone else come across this or have a workaround for it?
 
Any help/information would be greatly appreciated.
 
Thanks,
Arron

**Comment by ludovicsto** [comment]
Hi, did you find a solution. for your submission?
thank!

**Comment by arron-tamar** [comment]
Hi,

We didn't unfortunately. We tried changing key parts of the app such as using a new icon set, colour scheme etc but still received a rejection from Apple. The base code was highly modified too (compared to our other app / Linphone app).

The rejection seems to be linked to us running another Linphone based app from the same Apple account. In the end we decided to make the updates to our current active app on the app store which passed the checks almost straight away.

Annoying but got us to where we needed. I would imagine, you would need to review what other apps you have active on your account which could be causing the conflict.

Thanks,
A

**Comment by HanGuoxiang** [comment]
Quickly launch Appstore, professional fee solution for 4.3design: spam rejection issue
WhatsApp:+86 18953671207 
Facebook: https://www.facebook.com/profile.php?id=61560004032174&mibextid=LQQJ4d
Telegram：@approvetoappstore
WeChat：+86 18953671207
We have responded promptly to WeChat and Telegram's messages
