### ISSUE TITLE
contact filter memory access crash

### ISSUE THREAD

**Issue by petervnv** [BelledonneCommunications/linphone-iphone#938]
Hi again,

Just compiled release/5.2 with latest SDK 5.3.x
All works fine until I uncomment in linphone-factory #contact_filter_on_default_domain=1

As soon as the app gets contacts permission it raises an exception because it is trying to access memory it supposedly isn't allowed to access (running in xcode simulator with iOS 17.4)

exc_bad_access (code=1 address=0x0)

Is this a known bug (thus why it is commented out in your linphone-factory)?

Any ideas how to fix this?

Cheers,
Peter

<img width="1496" alt="Screenshot 2024-06-06 at 17 14 33" src="https://github.com/BelledonneCommunications/linphone-iphone/assets/6282595/a8e4c6e2-261c-4975-aac5-5c3ec9524843">

**Comment by cdeschambc** [comment]
Hello, 
thank you for your feedback
this will be fixed in upcoming version (5.3.4).
