### ISSUE TITLE
Linphone dont ring when in background . i have bought Zoiper app , then it rings in background

### ISSUE THREAD

**Issue by Aramousa** [BelledonneCommunications/linphone-iphone#940]
I have purchsed zoiper and the problem solved. our freeswitch server dont has push notification server and my iphone is updated with ios 17.5.1 . it recives the calls when it's in background or when it closed. what really happend ?

**Comment by lucaszhang99** [comment]
Same here, Zoiper works in background & closed (version 3.47)

**Comment by martinsben** [comment]
Hi,

I think Zoiper uses its own push notification server. This is not the case for Linphone if you use your sip domain.

![IMG_2478](https://github.com/user-attachments/assets/56f04402-665b-4de5-ae44-3963c583059d)

Best regards.
