### ISSUE TITLE
Can't find Early Media option in Linphone iphone Settings.

### ISSUE THREAD

**Issue by Adnan-addi** [BelledonneCommunications/linphone-iphone#945]
@all 

Hi , 
I need to know where I can find or enable Early Media option. As its its not appearing in iphone app settings but available in android app ?

Please help or let me know how to enable early media in iPhone linphone app?

**Comment by Viish** [comment]
Hi @Adnan-addi, 

You can easily take a look at how the setting is implemented on Android and do the same on iOS.

Cheers,
