### ISSUE TITLE
EarlyMedia option not works

### ISSUE THREAD

**Issue by waseemkhanyes** [BelledonneCommunications/linphone-iphone#947]
https://github.com/ALL

Hi ,
In Linphone code early media option  by default is hidden, I unhide Early Media option from the code 
and enable the early media flags from call settings
but when I receive a call early media functionality not work
Please help or let me know how early media works in the iPhone linphone app?

<img width="482" alt="image" src="https://github.com/user-attachments/assets/e05344e9-90d4-4cfd-9434-1364a0945efc">

**Comment by Adnan-addi** [comment]
@Viish please help in this regard , as i am also facing this, however Early media works fine in Android.

**Comment by Viish** [comment]
Sorry I can't help on iOS, but take a look at linhome-ios (https://gitlab.linphone.org/BC/public/linhome-ios) source code, I know that early media works well on it.

**Comment by Adnan-addi** [comment]
Thanks :-)

**Comment by Adnan-addi** [comment]
![thumb_IMG_3069](https://github.com/user-attachments/assets/f7c2bdde-d5a1-43c3-bfd3-80ccf6d8e5ee)

I have Accept Early Media On , in IOS Linphone App , When i dial a call early media is sent and can be viewed on Android App.

but when i recieve a call on ios than early media is not shown on a pop up box as Android .

I want to know how IOS shows or displays early media ?

@Viish 
@jehandelalune 
@Gui13
