### ISSUE TITLE
Integrate EarlyMedia

### ISSUE THREAD

**Issue by waseemkhanyes** [BelledonneCommunications/linphone-iphone#949]
https://github.com/ALL

Hi ,
In Linphone on call incoming view i add a view in which a want to play earlymedia video streaming
can i get earlymedia video streaming data from call notification payload?

on red point i want to show earlyMedia view

<img width="451" alt="SCR-20240829-iihd" src="https://github.com/user-attachments/assets/69f1bfdc-9aee-406a-9101-b35961911aee">

**Comment by Adnan-addi** [comment]
@Viish 
@Gui13 
@jehandelalune 
@bagage 
I am having the same issue. please help in this regard. 

Thank you .
