### ISSUE TITLE
Implementing CoS marking with DSCP field

### ISSUE THREAD

**Issue by lboue** [BelledonneCommunications/linphone-iphone#95]
Hello,

I am trying to apply CoS marking with DSCP to the linphone-iphone application with those setting:
- sip_dscp=24
- video_dscp=34
- audio_dscp=46

So I added entry name="dscp" to the XML config file but it seems to be not applied according to my network trace:
```
config xmlns="http://www.linphone.org/xsds/lpconfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.linphone.org/xsds/lpconfig.xsd lpconfig.xsd">
    <section name="app">
        <entry name="show_login_view" overwrite="true">0</entry>
        <entry name="pushnotification_preference" overwrite="true">0</entry>
    </section>
    <section name="sip">
        <entry name="sip_port" overwrite="true">5060</entry>
        <entry name="dscp">0x28</entry>
        <entry name="guess_hostname" overwrite="true">1</entry>
        <entry name="inc_timeout" overwrite="true">15</entry>
        <entry name="use_ipv6" overwrite="true">0</entry>
        <entry name="register_only_when_network_is_up" overwrite="true">1</entry>
        <entry name="default_proxy" overwrite="true">0</entry>
        <entry name="keepalive_period" overwrite="true">10000</entry>
        <entry name="only_one_codec" overwrite="true">0</entry>
        <entry name="ping_with_options" overwrite="true">1</entry>
        <entry name="auto_net_state_mon" overwrite="true">1</entry>
    </section>
```

I also find this article ["Linphone remote provisioning"]( https://linphone.org/dokuwiki/doku.php/remoteprovisioning:start?s[]=video)
```
[sip]
sip_tcp_port=5070
ping_with_options=0
media_encryption=none
dscp=0x0
```
Could you tell me how to apply DSCP marking for linphone-iphone application?
I notice this behaviour is already allowed for [desktop linphone
](https://github.com/BelledonneCommunications/linphone/blob/c946d7064e9afcae27ad147f5840d4f3bac0786a/gtk/dscp_settings.ui)
Regards,

**Comment by bagage** [comment]
Please use overwrite="true" in your XML config file:

>         <entry name="dscp" overwrite="true">0x28</entry>

**Comment by afone-lboue** [comment]
Thanks for you help
