### ISSUE TITLE
Failed to upload the app to the AppStore, cause the bitcode contains.

### ISSUE THREAD

**Issue by PacoPacoPakitor** [BelledonneCommunications/linphone-iphone#952]
Description:
I tried to upload a new version from Xcode16 to the App Store but failed due to bitcode issues, it's works when running. I tried disabling bitcode from the project also framework. but didn't work at all. Any solution for this? thanks

A few ways to try to resolve the issue, but it still happens.
 - In Pods:   config.build_settings['ENABLE_BITCODE'] = 'NO'
 - In Project: ENABLE_BITCODE = NO
 - In Pods: ENABLE_BITCODE = NO 
 
Environment:
- Xcode: 16
- linphone-sdk-novideo: 5.3.84

Issue screenshots:
<img width="458" alt="image" src="https://github.com/user-attachments/assets/a1c66d50-13e7-492c-80f5-e26aca422f99">
<img width="428" alt="image" src="https://github.com/user-attachments/assets/a29c7ac3-ee40-402e-b1e7-c53a18f8ad71">

**Comment by eliasalzaghrini** [comment]
Same issue. Any solution?

**Comment by husbycodereis** [comment]
Hey, after Xcode 16 update, Apple now does not accept builds with bit-code. The packages used in lincode has to be bit stripped.  

Under podfile copy and paste the code under the post_install section. 

`
bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end

  framework_paths = [
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/bctoolbox-ios.xcframework/ios-arm64/bctoolbox-ios.framework/bctoolbox-ios",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/bctoolbox-tester.xcframework/ios-arm64/bctoolbox-tester.framework/bctoolbox-tester",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/bctoolbox.xcframework/ios-arm64/bctoolbox.framework/bctoolbox",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/belcard.xcframework/ios-arm64/belcard.framework/belcard",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/belle-sip.xcframework/ios-arm64/belle-sip.framework/belle-sip",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/belr.xcframework/ios-arm64/belr.framework/belr",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/lime.xcframework/ios-arm64/lime.framework/lime",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/limetester.xcframework/ios-arm64/limetester.framework/limetester",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/linphone.xcframework/ios-arm64/linphone.framework/linphone",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/linphonetester.xcframework/ios-arm64/linphonetester.framework/linphonetester",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/mediastreamer2.xcframework/ios-arm64/mediastreamer2.framework/mediastreamer2",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/msamr.xcframework/ios-arm64/msamr.framework/msamr",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/mscodec2.xcframework/ios-arm64/mscodec2.framework/mscodec2",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/msopenh264.xcframework/ios-arm64/msopenh264.framework/msopenh264",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/mssilk.xcframework/ios-arm64/mssilk.framework/mssilk",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/mswebrtc.xcframework/ios-arm64/mswebrtc.framework/mswebrtc",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/ortp.xcframework/ios-arm64/ortp.framework/ortp",
    "Pods/linphone-sdk/linphone-sdk/apple-darwin/XCFrameworks/ZXing.xcframework/ios-arm64/ZXing.framework/ZXing",
  ]

  framework_paths.each do |framework_relative_path|
    strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
  end
`
 
It is modified for linphone from this (original post)[https://stackoverflow.com/questions/79022303/asset-validation-failed-nslocalizedrecoverysuggestion-invalid-executable-the-e]

**Comment by Viish** [comment]
This is already fixed in master & latest 5.3 releases of our SDK.
