### ISSUE TITLE
Version SDK build issues

### ISSUE THREAD

**Issue by 13866109020** [BelledonneCommunications/linphone-iphone#956]
I want to build version 5.1.72 SDK, but the code error is prompted, do I need to modify the build code, how should I modify it?

**Comment by 13866109020** [comment]
![Uploading 截屏2024-09-26 19.30.23.png…]()

**Comment by 13866109020** [comment]
<img width="564" alt="截屏2024-09-26 19 30 23" src="https://github.com/user-attachments/assets/997c751d-8187-43e4-9381-86bb2fb3ac12">

**Comment by Viish** [comment]
We don't support 5.1 SDK, please update to current release (5.3).

**Comment by 13866109020** [comment]
那为什么macOS，下载你们客户端，界面语言是日语就奔溃呢，我现在使用5.3和5.1都是这个情况，即使你们最新的桌面端也有这个问题，而且是一只存在的，能不能修复呢？




傲
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "BelledonneCommunications/linphone-iphone"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月2日(星期三) 晚上8:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BelledonneCommunications/linphone-iphone] Version SDK build issues (Issue #956)





 
We don't support 5.1 SDK, please update to current release (5.3).
