### ISSUE TITLE
The call is displayed twice

### ISSUE THREAD

**Issue by and7ey** [BelledonneCommunications/linphone-iphone#957]
Why do I have the incoming call displayed twice on iOs 18?

![IMG_20241004_200627_512](https://github.com/user-attachments/assets/37aceaad-117b-46ac-a7e8-5701c673909a)
![IMG_20241004_200632_315](https://github.com/user-attachments/assets/0358d646-a855-41f4-979e-8d3a2e31df93)

**Comment by and7ey** [comment]
@benoit-martins what does "completed" mean? there is no single comment

**Comment by benoit-martins** [comment]
Hi,

We have closed all open tickets as the upcoming release of Linphone 6.0 is a complete redesign of the app. 
This new version will address existing issues with a fresh approach, so we encourage you to explore the updated app when it's available.

Thank you for your understanding and support!

Best regards
