### ISSUE TITLE
doesn't include the com.apple.developer.usernotifications.filtering entitlement

### ISSUE THREAD

**Issue by alexunderboots** [BelledonneCommunications/linphone-iphone#958]
please help? can't build? got error with Provisioning profile:
Provisioning profile "iOS Team Provisioning Profile: org.ab.phone.msgNotificationService" doesn't include the com.apple.developer.usernotifications.filtering entitlement.

**Comment by alexunderboots** [comment]
Please help me answer the questions from apple
1. Explain why existing APIs are not adequate for your app.
2. Explain why your app doesn’t show a visible notification each time a push notification is received.
3. When your extension runs, what system and network resources does it need?
4. How often does your extension run? What can trigger it to run?

**Comment by alexunderboots** [comment]
https://developer.apple.com/contact/request/notification-service

**Comment by Arguillq** [comment]
Hi,

The com.apple.developer.usernotifications.filtering entitlement allows your app extension to hide incoming remote push notification if you call  the content handler with an empty notification content ("contentHandler(UNNotificationContent())") .

Obtaining this entitlmeent require you to complete the steps you mentioned in the form and send it to Apple, where they will decide wether they want to allow you app to filter notifications or not. You may want to explain, for example, that your app allows the user to join several group chatrooms which may cause a spam of messages and want to be allowed to selectively mute some of them, while still receiving important notifications from other parts of your application.

**Comment by Arguillq** [comment]
You can also just remove the com.apple.developer.usernotifications.filtering  key from your info.plist file. In which case, when calling "contentHandler(UNNotificationContent())", a default message of the form "you have received a notification" will be displayed to the user

**Comment by GuruPrasath1012** [comment]
[Message] Unable to find chat room in RAM: ConferenceId(peer=sip:6382937255@103.16.202.169, local=sip:6382937124@192.168.1.71). Still its not working while receivng the new message for new user i am getting the crash for the first message after that its working properly Please help me out it from here
