### ISSUE TITLE
New Message app crashing in linphone

### ISSUE THREAD

**Issue by GuruPrasath1012** [BelledonneCommunications/linphone-iphone#959]
[Warning] Unable to get event from invalid storage ID -1
[Message] Unable to find chat room in RAM: ConferenceId(peer=sip:6382937011@192.168.1.71, local=sip:6382937023@192.168.1.71).
[Error] Unable to find chat room: ConferenceId(peer=sip:6382937011@192.168.1.71, local=sip:6382937023@192.168.1.71).
[Error] cannot find eventLog for storage ID [7] associated to message [0x6000022da580]
[Message] Unable to find chat room in RAM: ConferenceId(peer=sip:6382937011@192.168.1.71, local=sip:6382937023@192.168.1.71). 

its not working while receivng the new message for a new user i am getting the crash for the first message after that its working properly, Help me out it

**Comment by GuruPrasath1012** [comment]
[Warning] Unable to get event from invalid storage ID -1
[Message] Unable to find chat room in RAM: ConferenceId(peer=sip:6382937011@192.168.1.71, local=sip:6382937023@192.168.1.71).
[Error] Unable to find chat room: ConferenceId(peer=sip:6382937011@192.168.1.71, local=sip:6382937023@192.168.1.71).
[Error] cannot find eventLog for storage ID [7] associated to message [0x6000022da580]
[Message] Unable to find chat room in RAM: ConferenceId(peer=sip:6382937011@192.168.1.71, local=sip:6382937023@192.168.1.71).

**Comment by Viish** [comment]
@GuruPrasath1012 please stop copying/pasting your message into every issue, I'll delete them.

**Comment by GuruPrasath1012** [comment]
No actually both are same issue only

**Comment by GuruPrasath1012** [comment]
> @GuruPrasath1012 please stop copying/pasting your message into every issue, I'll delete them.

Both are same log i have merged into single comment
