### ISSUE TITLE
No rule to make target `vpx/src/vpx_decoder.c.o' , needed by `libvpx_g.a'.  Stop.

### ISSUE THREAD

**Issue by smking111222** [BelledonneCommunications/linphone-iphone#96]
Hi guys,

I checked the latest code this afternoon, by git clone command, not download the zip file directly.
and then 
1. run the ./prepary.py in iTerm.
2. Reorder path by "export PATH=/usr/local/bin:$PATH"
3. build sdk by ./prepare.py -c && ./prepare.py && make

But Error happen, see attached belows.

[ 41%] Forcing build for 'EP_vpx'
[ 42%] Performing build step for 'EP_vpx'
make[5]: **\* No rule to make target `vpx/src/vpx_decoder.c.o', needed by`libvpx_g.a'.  Stop.
make[4]: **\* [.DEFAULT] Error 2
make[3]: **\* [/Users/heqin/Downloads/linphone/linphone_iphone_latest/linphone-iphone/WORK/ios-x86_64/Stamp/EP_vpx/EP_vpx-build] Error 2
make[2]: **\* [CMakeFiles/EP_vpx.dir/all] Error 2
make[1]: **\* [all] Error 2
make: **\* [x86_64-build] Error 2
# Any ideas are appreciated.

**Comment by bagage** [comment]
Strange. What's your xcode version? Do you reproduce it with current master version?
