### ISSUE TITLE
app doesnt stay connected in background

### ISSUE THREAD

**Issue by jay98760** [BelledonneCommunications/linphone-iphone#964]
The latest linphone on my iOS 18 / iphone 15 pro doesnt stay connected on TLS port 5061 to the sip-server when in background
Other voip apps work fine (push notifications disabled)
Does Linphone have plans to support backgrounding?

Note that I do not want push notifications, but backgrounding.

**Comment by jay98760** [comment]
i am guessing this is done with background app refresh

**Comment by benoit-martins** [comment]
Hi,

Thanks for pointing this out! Currently, Linphone relies on Apple’s VoIP framework, which pushes for the use of PushKit notifications to keep apps connected and handle incoming calls in the background. Unfortunately, maintaining a persistent connection on TLS 5061 without push notifications isn’t supported natively at the moment.

Background App Refresh, as you mentioned, isn’t really designed for this kind of real-time SIP communication—it’s more for periodic updates, so it wouldn’t fully solve the issue either.

Additionally, methods that bypass Apple's guidelines can lead to higher battery consumption, inefficient resource management, and a risk of being rejected by the App Store.

Best regards

**Comment by jay98760** [comment]
Thank you for responding.

Supporting incoming calls, text and presence without interference from third parties/Apple is a requirement in order for us to use a voip app. SLA, GDPR and security is a problem otherwise. I really hope that support for backgrounding will be prioritised in near future.

Thanks
