### ISSUE TITLE
Could some guys tell me, linphone sdk start to surpport ipv6 from which version? 3.7.0, or 3.9.1

### ISSUE THREAD

**Issue by shenheqin** [BelledonneCommunications/linphone-iphone#97]
Hello guys, 

I need to imbed the linphone SDK to my app, which need to supoort ipv6, but I don't know linphone support ipv6 from which version? 3.7.0, or 3.9.1, or some later version?

Thanks in advance.

**Comment by bagage** [comment]
Please read the changelog, thanks!

**Comment by shenheqin** [comment]
Hello bagage, could you tell me where I can find the changelog? 

I try to find it in releases, 3.13.9 "...",  when I click the "...", then it shows "apple store version 3.13 build 9". I guess this is not the changelog due to so short words. 

Please tell me where I can find the changelog. 

Thanks a lot. @bagage
