### ISSUE TITLE
Retrieve Call-ID from chat message

### ISSUE THREAD

**Issue by reste85** [BelledonneCommunications/linphone-iphone#99]
Is it possible to retrieve the Call-ID associated with a LinphoneChatMessage? I've seen from logs that there is the field Call-ID. 

Linphone logs:

MESSAGE sip:55001@192.168.1.101 SIP/2.0
Via: SIP/2.0/TCP 192.168.254.117:49506;branch=z9hG4bK.~8YNFOwZ9;rport
From: <sip:60992@192.168.1.101>;tag=RjHv1N9FC
To: sip:55001@192.168.1.101
CSeq: 20 MESSAGE
Call-ID: iS4EDGG5km
Max-Forwards: 70
Route: <sip:192.168.254.1;lr>
Supported: replaces, outbound
Content-Type: text/plain
Content-Length: 4
Date: Mon, 18 Jul 2016 07:52:19 GMT
Panda: command
Mobile-IMEI: BBCAAEEE-1AC7-4845-877F-C00BDF9CA3BC
MyName: Matteo
ActuationId: E8936018-4217-44C6-B3B3-9FE6E455F76A
User-Agent: (null)_iPhone.6_iOS9.3.2/3.12.1-113-g7e116b2 (belle-sip/1.4.2)

AUX2

How can i retrieve the Call-ID field?

**Comment by bagage** [comment]
You should run the following:

```
	NSString *callID = [NSString stringWithUTF8String:linphone_chat_message_get_custom_header(msg, "Call-ID")];
```
